namespace SwiftlyS2.Core.GameHooks;

internal enum DatamapHookListener
{
    CAmbientGenericRampThink,
    CBarnLightThink_ApplyLightStylesToTargets,
    CBarnLightThink_LightStyleEvent,
    CBarnLightThink_SetNextQueuedLightStyle,
    CBaseAnimGraphChoreoServicesThink,
    CBaseButtonActivateTouch,
    CBaseButtonButtonBackHome,
    CBaseButtonButtonReturn,
    CBaseButtonButtonSpark,
    CBaseButtonButtonTouch,
    CBaseButtonButtonUse,
    CBaseButtonTriggerAndWait,
    CBaseCSGrenadeProjectileDangerSoundThink,
    CBaseDoorCloseAreaPortalsThink,
    CBaseDoorDoorGoDown,
    CBaseDoorDoorGoUp,
    CBaseDoorDoorHitBottom,
    CBaseDoorDoorHitTop,
    CBaseDoorDoorTouch,
    CBaseDoorMovingSoundThink,
    CBaseEntityClearNavIgnoreContentsThink,
    CBaseEntityFakeScriptThinkFunc,
    CBaseEntitySUB_CallUseToggle,
    CBaseEntitySUB_DoNothing,
    CBaseEntitySUB_KillSelf,
    CBaseEntitySUB_Remove,
    CBaseGrenadeBounceTouch,
    CBaseGrenadeDangerSoundThink,
    CBaseGrenadeDetonate,
    CBaseGrenadeDetonateUse,
    CBaseGrenadeExplodeTouch,
    CBaseGrenadePreDetonate,
    CBaseGrenadeSlideTouch,
    CBaseGrenadeSmoke,
    CBaseGrenadeTumbleThink,
    CBaseModelEntityProcessSceneEventsThink,
    CBaseModelEntitySUB_DissolveIfUncarried,
    CBaseModelEntitySUB_FadeOut,
    CBaseModelEntitySUB_PerformShadowFadeIn,
    CBaseModelEntitySUB_PerformShadowFadeOut,
    CBaseModelEntitySUB_StartFadeOut,
    CBaseModelEntitySUB_StartFadeOutInstant,
    CBaseModelEntitySUB_StartShadowFadeIn,
    CBaseModelEntitySUB_StartShadowFadeOut,
    CBaseModelEntitySUB_StopShadowFade,
    CBasePropDoorDisableAreaPortalThink,
    CBasePropDoorDoorAutoCloseThink,
    CBasePropDoorDoorCloseMoveDone,
    CBasePropDoorDoorOpenMoveDone,
    CBombTargetBombTargetTouch,
    CBombTargetBombTargetUse,
    CBreakableDie,
    CBreakablePropBreakThink,
    CBreakablePropRampToDefaultFadeScale,
    CCSPlayerControllerInventoryUpdateThink,
    CCSPlayerControllerPlayerForceTeamThink,
    CCSPlayerControllerResetForceTeamThink,
    CCSPlayerControllerResourceDataThink,
    CCSPlayerPawnCheckStuffThink,
    CCSPlayerPawnPushawayThink,
    CCSPlayerResourceResourceThink,
    CCSWeaponBaseDefaultTouch,
    CCSWeaponBaseRemoveUnownedWeaponThink,
    CChickenChickenThink,
    CChickenChickenTouch,
    CChickenChickenUse,
    CColorCorrectionFadeInThink,
    CColorCorrectionFadeOutThink,
    CColorCorrectionVolumeThinkFunc,
    CDecoyProjectileGunfireThink,
    CDecoyProjectileThink_Detonate,
    CDynamicLightDynamicLightThink,
    CDynamicPropAnimThink,
    CEntityDissolveDissolveThink,
    CEntityDissolveElectrocuteThink,
    CEnvBeamStrikeThink,
    CEnvBeamUpdateThink,
    CEnvEntityMakerCheckSpawnThink,
    CEnvLaserStrikeThink,
    CEnvSparkSparkThink,
    CEnvWindControllerWindThink,
    CEnvWindWindThink,
    CFishPoolUpdate,
    CFogControllerSetLerpValues,
    CFuncMoveLinearNavMovableThink,
    CFuncMoveLinearNavObstacleThink,
    CFuncMoveLinearStopMoveSound,
    CFuncPlatCallGoDown,
    CFuncPlatCallHitBottom,
    CFuncPlatCallHitTop,
    CFuncPlatPlatUse,
    CFuncRotatingHurtTouch,
    CFuncRotatingReverseMove,
    CFuncRotatingRotateMove,
    CFuncRotatingRotatingUse,
    CFuncRotatingSpinDownMove,
    CFuncRotatingSpinUpMove,
    CFuncShatterglassGlassThink,
    CFuncTrackChangeFind,
    CFuncTrackTrainDeadEnd,
    CFuncTrackTrainFind,
    CFuncTrackTrainNearestPath,
    CFuncTrackTrainNext,
    CFuncTrainNext,
    CFuncTrainWait,
    CGenericConstraintUpdateThink,
    CGunTargetNext,
    CGunTargetStart,
    CGunTargetWait,
    CHostageHostageThink,
    CHostageHostageUse,
    CHostageRescueZoneHostageRescueTouch,
    CInfernoInfernoThink,
    CInfoSpawnGroupLoadUnloadSpawnGroupLoadingThink,
    CInfoSpawnGroupLoadUnloadSpawnGroupUnloadingThink,
    CItemComeToRest,
    CItemDefuserActivateThink,
    CItemDefuserDefuserTouch,
    CItemGenericItemGenericTouch,
    CItemItemTouch,
    CItemMaterialize,
    CLogicActiveAutosaveSaveThink,
    CLogicDistanceAutosaveSaveThink,
    CLogicGameStateReportSetGameStateReportThink,
    CLogicMeasureMovementMeasureThink,
    CLogicNPCCounterSetNPCCounterThink,
    CMapVetoPickControllerVoteControllerThink,
    CMomentaryRotButtonReturnMoveDone,
    CMomentaryRotButtonSetPositionMoveDone,
    CMomentaryRotButtonUpdateThink,
    CMomentaryRotButtonUseMoveDone,
    CMultiLightProxyApproachBrightnessThink,
    CMultiLightProxyRestoreFlashlightThink,
    CMultiSourceRegister,
    CParticleSystemStartParticleSystemThink,
    CPathMoverEntitySpawnerSpawnThink,
    CPathNodeParentedMoveThink,
    CPhysForceForceOff,
    CPhysForceInitialThink,
    CPhysHingeLimitThink,
    CPhysHingeMoveThink,
    CPhysHingeSoundThink,
    CPhysImpactPointAtEntity,
    CPhysSlideConstraintSoundThink,
    CPhysicsPropClearFlagsThink,
    CPhysicsPropClearThrownByPlayerThink,
    CPhysicsPropRespawnableMaterialize,
    CPlantedC4C4Think,
    CPointCommentaryNodeAcculumatePlayTimeThink,
    CPointCommentaryNodeSpinThink,
    CPointCommentaryNodeUpdateViewPostThink,
    CPointCommentaryNodeUpdateViewThink,
    CPointHurtHurtThink,
    CPointOrientReorientThink,
    CPointPushPushThink,
    CPointValueRemapperUpdateThink,
    CRagdollPropAttachedItemsThink,
    CRagdollPropClearFlagsThink,
    CRagdollPropFadeOutThink,
    CRagdollPropSetDebrisThink,
    CRagdollPropSettleThink,
    CRevertSavedLoadThink,
    CScriptedSequenceScriptThink,
    CSmokeGrenadeProjectileThink_BuildingSmokeVolume,
    CSmokeGrenadeProjectileThink_Detonate,
    CSmokeGrenadeProjectileThink_Remove,
    CSmokeGrenadeProjectileThink_Update,
    CSoundEventConeEntitySoundEventConeThink,
    CSoundEventEntitySoundFinishedThink,
    CSoundEventOBBEntitySoundEventOBBThink,
    CSoundEventPathCornerEntitySoundEventPathCornerThink,
    CSoundEventSphereEntitySoundEventSphereThink,
    CSoundOpvarSetAutoRoomEntitySetOpvarThink,
    CSoundOpvarSetBoxEntitySetOpvarThink,
    CSoundOpvarSetOBBWindEntitySetOpvarThink,
    CSoundOpvarSetPathCornerEntitySetOpvarThink,
    CSoundOpvarSetPointBaseSetOpvarThink,
    CSoundOpvarSetPointEntitySetOpvarThink,
    CSplineConstraintTransitionThink,
    CSpriteAnimateThink,
    CSpriteAnimateUntilDead,
    CSpriteBeginFadeOutThink,
    CSpriteExpandThink,
    CTriggerActiveWeaponDetectActiveWeaponThink,
    CTriggerFanPushThink,
    CTriggerHurtHurtThink,
    CTriggerHurtNavThink,
    CTriggerHurtRadiationThink,
    CTriggerImpactDisableThink,
    CTriggerLerpObjectAttachedEntityThink,
    CTriggerLerpObjectLerpThink,
    CTriggerLerpObjectUnsetWaitForEntity,
    CTriggerLookTimeoutThink,
    CTriggerMultipleMultiTouch,
    CTriggerMultipleMultiWaitOver,
    CTriggerProximityMeasureThink,
    CTriggerSaveRetriggerWaitOver,
    CTriggerSndSosOpvarSndSosTriggerOpvarWaitOver,
    CTriggerSoundscapePlayerUpdateThink,
    CVoteControllerVoteControllerThink,
    CWaterBulletBulletThink,
}

internal static partial class DatamapHooksPublisher
{
    internal static Guid HookFunction(DatamapHookListener hookName)
    {
        return hookName switch
        {
            DatamapHookListener.CAmbientGenericRampThink => HookCAmbientGenericRampThink(),
            DatamapHookListener.CBarnLightThink_ApplyLightStylesToTargets => HookCBarnLightThink_ApplyLightStylesToTargets(),
            DatamapHookListener.CBarnLightThink_LightStyleEvent => HookCBarnLightThink_LightStyleEvent(),
            DatamapHookListener.CBarnLightThink_SetNextQueuedLightStyle => HookCBarnLightThink_SetNextQueuedLightStyle(),
            DatamapHookListener.CBaseAnimGraphChoreoServicesThink => HookCBaseAnimGraphChoreoServicesThink(),
            DatamapHookListener.CBaseButtonActivateTouch => HookCBaseButtonActivateTouch(),
            DatamapHookListener.CBaseButtonButtonBackHome => HookCBaseButtonButtonBackHome(),
            DatamapHookListener.CBaseButtonButtonReturn => HookCBaseButtonButtonReturn(),
            DatamapHookListener.CBaseButtonButtonSpark => HookCBaseButtonButtonSpark(),
            DatamapHookListener.CBaseButtonButtonTouch => HookCBaseButtonButtonTouch(),
            DatamapHookListener.CBaseButtonButtonUse => HookCBaseButtonButtonUse(),
            DatamapHookListener.CBaseButtonTriggerAndWait => HookCBaseButtonTriggerAndWait(),
            DatamapHookListener.CBaseCSGrenadeProjectileDangerSoundThink => HookCBaseCSGrenadeProjectileDangerSoundThink(),
            DatamapHookListener.CBaseDoorCloseAreaPortalsThink => HookCBaseDoorCloseAreaPortalsThink(),
            DatamapHookListener.CBaseDoorDoorGoDown => HookCBaseDoorDoorGoDown(),
            DatamapHookListener.CBaseDoorDoorGoUp => HookCBaseDoorDoorGoUp(),
            DatamapHookListener.CBaseDoorDoorHitBottom => HookCBaseDoorDoorHitBottom(),
            DatamapHookListener.CBaseDoorDoorHitTop => HookCBaseDoorDoorHitTop(),
            DatamapHookListener.CBaseDoorDoorTouch => HookCBaseDoorDoorTouch(),
            DatamapHookListener.CBaseDoorMovingSoundThink => HookCBaseDoorMovingSoundThink(),
            DatamapHookListener.CBaseEntityClearNavIgnoreContentsThink => HookCBaseEntityClearNavIgnoreContentsThink(),
            DatamapHookListener.CBaseEntityFakeScriptThinkFunc => HookCBaseEntityFakeScriptThinkFunc(),
            DatamapHookListener.CBaseEntitySUB_CallUseToggle => HookCBaseEntitySUB_CallUseToggle(),
            DatamapHookListener.CBaseEntitySUB_DoNothing => HookCBaseEntitySUB_DoNothing(),
            DatamapHookListener.CBaseEntitySUB_KillSelf => HookCBaseEntitySUB_KillSelf(),
            DatamapHookListener.CBaseEntitySUB_Remove => HookCBaseEntitySUB_Remove(),
            DatamapHookListener.CBaseGrenadeBounceTouch => HookCBaseGrenadeBounceTouch(),
            DatamapHookListener.CBaseGrenadeDangerSoundThink => HookCBaseGrenadeDangerSoundThink(),
            DatamapHookListener.CBaseGrenadeDetonate => HookCBaseGrenadeDetonate(),
            DatamapHookListener.CBaseGrenadeDetonateUse => HookCBaseGrenadeDetonateUse(),
            DatamapHookListener.CBaseGrenadeExplodeTouch => HookCBaseGrenadeExplodeTouch(),
            DatamapHookListener.CBaseGrenadePreDetonate => HookCBaseGrenadePreDetonate(),
            DatamapHookListener.CBaseGrenadeSlideTouch => HookCBaseGrenadeSlideTouch(),
            DatamapHookListener.CBaseGrenadeSmoke => HookCBaseGrenadeSmoke(),
            DatamapHookListener.CBaseGrenadeTumbleThink => HookCBaseGrenadeTumbleThink(),
            DatamapHookListener.CBaseModelEntityProcessSceneEventsThink => HookCBaseModelEntityProcessSceneEventsThink(),
            DatamapHookListener.CBaseModelEntitySUB_DissolveIfUncarried => HookCBaseModelEntitySUB_DissolveIfUncarried(),
            DatamapHookListener.CBaseModelEntitySUB_FadeOut => HookCBaseModelEntitySUB_FadeOut(),
            DatamapHookListener.CBaseModelEntitySUB_PerformShadowFadeIn => HookCBaseModelEntitySUB_PerformShadowFadeIn(),
            DatamapHookListener.CBaseModelEntitySUB_PerformShadowFadeOut => HookCBaseModelEntitySUB_PerformShadowFadeOut(),
            DatamapHookListener.CBaseModelEntitySUB_StartFadeOut => HookCBaseModelEntitySUB_StartFadeOut(),
            DatamapHookListener.CBaseModelEntitySUB_StartFadeOutInstant => HookCBaseModelEntitySUB_StartFadeOutInstant(),
            DatamapHookListener.CBaseModelEntitySUB_StartShadowFadeIn => HookCBaseModelEntitySUB_StartShadowFadeIn(),
            DatamapHookListener.CBaseModelEntitySUB_StartShadowFadeOut => HookCBaseModelEntitySUB_StartShadowFadeOut(),
            DatamapHookListener.CBaseModelEntitySUB_StopShadowFade => HookCBaseModelEntitySUB_StopShadowFade(),
            DatamapHookListener.CBasePropDoorDisableAreaPortalThink => HookCBasePropDoorDisableAreaPortalThink(),
            DatamapHookListener.CBasePropDoorDoorAutoCloseThink => HookCBasePropDoorDoorAutoCloseThink(),
            DatamapHookListener.CBasePropDoorDoorCloseMoveDone => HookCBasePropDoorDoorCloseMoveDone(),
            DatamapHookListener.CBasePropDoorDoorOpenMoveDone => HookCBasePropDoorDoorOpenMoveDone(),
            DatamapHookListener.CBombTargetBombTargetTouch => HookCBombTargetBombTargetTouch(),
            DatamapHookListener.CBombTargetBombTargetUse => HookCBombTargetBombTargetUse(),
            DatamapHookListener.CBreakableDie => HookCBreakableDie(),
            DatamapHookListener.CBreakablePropBreakThink => HookCBreakablePropBreakThink(),
            DatamapHookListener.CBreakablePropRampToDefaultFadeScale => HookCBreakablePropRampToDefaultFadeScale(),
            DatamapHookListener.CCSPlayerControllerInventoryUpdateThink => HookCCSPlayerControllerInventoryUpdateThink(),
            DatamapHookListener.CCSPlayerControllerPlayerForceTeamThink => HookCCSPlayerControllerPlayerForceTeamThink(),
            DatamapHookListener.CCSPlayerControllerResetForceTeamThink => HookCCSPlayerControllerResetForceTeamThink(),
            DatamapHookListener.CCSPlayerControllerResourceDataThink => HookCCSPlayerControllerResourceDataThink(),
            DatamapHookListener.CCSPlayerPawnCheckStuffThink => HookCCSPlayerPawnCheckStuffThink(),
            DatamapHookListener.CCSPlayerPawnPushawayThink => HookCCSPlayerPawnPushawayThink(),
            DatamapHookListener.CCSPlayerResourceResourceThink => HookCCSPlayerResourceResourceThink(),
            DatamapHookListener.CCSWeaponBaseDefaultTouch => HookCCSWeaponBaseDefaultTouch(),
            DatamapHookListener.CCSWeaponBaseRemoveUnownedWeaponThink => HookCCSWeaponBaseRemoveUnownedWeaponThink(),
            DatamapHookListener.CChickenChickenThink => HookCChickenChickenThink(),
            DatamapHookListener.CChickenChickenTouch => HookCChickenChickenTouch(),
            DatamapHookListener.CChickenChickenUse => HookCChickenChickenUse(),
            DatamapHookListener.CColorCorrectionFadeInThink => HookCColorCorrectionFadeInThink(),
            DatamapHookListener.CColorCorrectionFadeOutThink => HookCColorCorrectionFadeOutThink(),
            DatamapHookListener.CColorCorrectionVolumeThinkFunc => HookCColorCorrectionVolumeThinkFunc(),
            DatamapHookListener.CDecoyProjectileGunfireThink => HookCDecoyProjectileGunfireThink(),
            DatamapHookListener.CDecoyProjectileThink_Detonate => HookCDecoyProjectileThink_Detonate(),
            DatamapHookListener.CDynamicLightDynamicLightThink => HookCDynamicLightDynamicLightThink(),
            DatamapHookListener.CDynamicPropAnimThink => HookCDynamicPropAnimThink(),
            DatamapHookListener.CEntityDissolveDissolveThink => HookCEntityDissolveDissolveThink(),
            DatamapHookListener.CEntityDissolveElectrocuteThink => HookCEntityDissolveElectrocuteThink(),
            DatamapHookListener.CEnvBeamStrikeThink => HookCEnvBeamStrikeThink(),
            DatamapHookListener.CEnvBeamUpdateThink => HookCEnvBeamUpdateThink(),
            DatamapHookListener.CEnvEntityMakerCheckSpawnThink => HookCEnvEntityMakerCheckSpawnThink(),
            DatamapHookListener.CEnvLaserStrikeThink => HookCEnvLaserStrikeThink(),
            DatamapHookListener.CEnvSparkSparkThink => HookCEnvSparkSparkThink(),
            DatamapHookListener.CEnvWindControllerWindThink => HookCEnvWindControllerWindThink(),
            DatamapHookListener.CEnvWindWindThink => HookCEnvWindWindThink(),
            DatamapHookListener.CFishPoolUpdate => HookCFishPoolUpdate(),
            DatamapHookListener.CFogControllerSetLerpValues => HookCFogControllerSetLerpValues(),
            DatamapHookListener.CFuncMoveLinearNavMovableThink => HookCFuncMoveLinearNavMovableThink(),
            DatamapHookListener.CFuncMoveLinearNavObstacleThink => HookCFuncMoveLinearNavObstacleThink(),
            DatamapHookListener.CFuncMoveLinearStopMoveSound => HookCFuncMoveLinearStopMoveSound(),
            DatamapHookListener.CFuncPlatCallGoDown => HookCFuncPlatCallGoDown(),
            DatamapHookListener.CFuncPlatCallHitBottom => HookCFuncPlatCallHitBottom(),
            DatamapHookListener.CFuncPlatCallHitTop => HookCFuncPlatCallHitTop(),
            DatamapHookListener.CFuncPlatPlatUse => HookCFuncPlatPlatUse(),
            DatamapHookListener.CFuncRotatingHurtTouch => HookCFuncRotatingHurtTouch(),
            DatamapHookListener.CFuncRotatingReverseMove => HookCFuncRotatingReverseMove(),
            DatamapHookListener.CFuncRotatingRotateMove => HookCFuncRotatingRotateMove(),
            DatamapHookListener.CFuncRotatingRotatingUse => HookCFuncRotatingRotatingUse(),
            DatamapHookListener.CFuncRotatingSpinDownMove => HookCFuncRotatingSpinDownMove(),
            DatamapHookListener.CFuncRotatingSpinUpMove => HookCFuncRotatingSpinUpMove(),
            DatamapHookListener.CFuncShatterglassGlassThink => HookCFuncShatterglassGlassThink(),
            DatamapHookListener.CFuncTrackChangeFind => HookCFuncTrackChangeFind(),
            DatamapHookListener.CFuncTrackTrainDeadEnd => HookCFuncTrackTrainDeadEnd(),
            DatamapHookListener.CFuncTrackTrainFind => HookCFuncTrackTrainFind(),
            DatamapHookListener.CFuncTrackTrainNearestPath => HookCFuncTrackTrainNearestPath(),
            DatamapHookListener.CFuncTrackTrainNext => HookCFuncTrackTrainNext(),
            DatamapHookListener.CFuncTrainNext => HookCFuncTrainNext(),
            DatamapHookListener.CFuncTrainWait => HookCFuncTrainWait(),
            DatamapHookListener.CGenericConstraintUpdateThink => HookCGenericConstraintUpdateThink(),
            DatamapHookListener.CGunTargetNext => HookCGunTargetNext(),
            DatamapHookListener.CGunTargetStart => HookCGunTargetStart(),
            DatamapHookListener.CGunTargetWait => HookCGunTargetWait(),
            DatamapHookListener.CHostageHostageThink => HookCHostageHostageThink(),
            DatamapHookListener.CHostageHostageUse => HookCHostageHostageUse(),
            DatamapHookListener.CHostageRescueZoneHostageRescueTouch => HookCHostageRescueZoneHostageRescueTouch(),
            DatamapHookListener.CInfernoInfernoThink => HookCInfernoInfernoThink(),
            DatamapHookListener.CInfoSpawnGroupLoadUnloadSpawnGroupLoadingThink => HookCInfoSpawnGroupLoadUnloadSpawnGroupLoadingThink(),
            DatamapHookListener.CInfoSpawnGroupLoadUnloadSpawnGroupUnloadingThink => HookCInfoSpawnGroupLoadUnloadSpawnGroupUnloadingThink(),
            DatamapHookListener.CItemComeToRest => HookCItemComeToRest(),
            DatamapHookListener.CItemDefuserActivateThink => HookCItemDefuserActivateThink(),
            DatamapHookListener.CItemDefuserDefuserTouch => HookCItemDefuserDefuserTouch(),
            DatamapHookListener.CItemGenericItemGenericTouch => HookCItemGenericItemGenericTouch(),
            DatamapHookListener.CItemItemTouch => HookCItemItemTouch(),
            DatamapHookListener.CItemMaterialize => HookCItemMaterialize(),
            DatamapHookListener.CLogicActiveAutosaveSaveThink => HookCLogicActiveAutosaveSaveThink(),
            DatamapHookListener.CLogicDistanceAutosaveSaveThink => HookCLogicDistanceAutosaveSaveThink(),
            DatamapHookListener.CLogicGameStateReportSetGameStateReportThink => HookCLogicGameStateReportSetGameStateReportThink(),
            DatamapHookListener.CLogicMeasureMovementMeasureThink => HookCLogicMeasureMovementMeasureThink(),
            DatamapHookListener.CLogicNPCCounterSetNPCCounterThink => HookCLogicNPCCounterSetNPCCounterThink(),
            DatamapHookListener.CMapVetoPickControllerVoteControllerThink => HookCMapVetoPickControllerVoteControllerThink(),
            DatamapHookListener.CMomentaryRotButtonReturnMoveDone => HookCMomentaryRotButtonReturnMoveDone(),
            DatamapHookListener.CMomentaryRotButtonSetPositionMoveDone => HookCMomentaryRotButtonSetPositionMoveDone(),
            DatamapHookListener.CMomentaryRotButtonUpdateThink => HookCMomentaryRotButtonUpdateThink(),
            DatamapHookListener.CMomentaryRotButtonUseMoveDone => HookCMomentaryRotButtonUseMoveDone(),
            DatamapHookListener.CMultiLightProxyApproachBrightnessThink => HookCMultiLightProxyApproachBrightnessThink(),
            DatamapHookListener.CMultiLightProxyRestoreFlashlightThink => HookCMultiLightProxyRestoreFlashlightThink(),
            DatamapHookListener.CMultiSourceRegister => HookCMultiSourceRegister(),
            DatamapHookListener.CParticleSystemStartParticleSystemThink => HookCParticleSystemStartParticleSystemThink(),
            DatamapHookListener.CPathMoverEntitySpawnerSpawnThink => HookCPathMoverEntitySpawnerSpawnThink(),
            DatamapHookListener.CPathNodeParentedMoveThink => HookCPathNodeParentedMoveThink(),
            DatamapHookListener.CPhysForceForceOff => HookCPhysForceForceOff(),
            DatamapHookListener.CPhysForceInitialThink => HookCPhysForceInitialThink(),
            DatamapHookListener.CPhysHingeLimitThink => HookCPhysHingeLimitThink(),
            DatamapHookListener.CPhysHingeMoveThink => HookCPhysHingeMoveThink(),
            DatamapHookListener.CPhysHingeSoundThink => HookCPhysHingeSoundThink(),
            DatamapHookListener.CPhysImpactPointAtEntity => HookCPhysImpactPointAtEntity(),
            DatamapHookListener.CPhysSlideConstraintSoundThink => HookCPhysSlideConstraintSoundThink(),
            DatamapHookListener.CPhysicsPropClearFlagsThink => HookCPhysicsPropClearFlagsThink(),
            DatamapHookListener.CPhysicsPropClearThrownByPlayerThink => HookCPhysicsPropClearThrownByPlayerThink(),
            DatamapHookListener.CPhysicsPropRespawnableMaterialize => HookCPhysicsPropRespawnableMaterialize(),
            DatamapHookListener.CPlantedC4C4Think => HookCPlantedC4C4Think(),
            DatamapHookListener.CPointCommentaryNodeAcculumatePlayTimeThink => HookCPointCommentaryNodeAcculumatePlayTimeThink(),
            DatamapHookListener.CPointCommentaryNodeSpinThink => HookCPointCommentaryNodeSpinThink(),
            DatamapHookListener.CPointCommentaryNodeUpdateViewPostThink => HookCPointCommentaryNodeUpdateViewPostThink(),
            DatamapHookListener.CPointCommentaryNodeUpdateViewThink => HookCPointCommentaryNodeUpdateViewThink(),
            DatamapHookListener.CPointHurtHurtThink => HookCPointHurtHurtThink(),
            DatamapHookListener.CPointOrientReorientThink => HookCPointOrientReorientThink(),
            DatamapHookListener.CPointPushPushThink => HookCPointPushPushThink(),
            DatamapHookListener.CPointValueRemapperUpdateThink => HookCPointValueRemapperUpdateThink(),
            DatamapHookListener.CRagdollPropAttachedItemsThink => HookCRagdollPropAttachedItemsThink(),
            DatamapHookListener.CRagdollPropClearFlagsThink => HookCRagdollPropClearFlagsThink(),
            DatamapHookListener.CRagdollPropFadeOutThink => HookCRagdollPropFadeOutThink(),
            DatamapHookListener.CRagdollPropSetDebrisThink => HookCRagdollPropSetDebrisThink(),
            DatamapHookListener.CRagdollPropSettleThink => HookCRagdollPropSettleThink(),
            DatamapHookListener.CRevertSavedLoadThink => HookCRevertSavedLoadThink(),
            DatamapHookListener.CScriptedSequenceScriptThink => HookCScriptedSequenceScriptThink(),
            DatamapHookListener.CSmokeGrenadeProjectileThink_BuildingSmokeVolume => HookCSmokeGrenadeProjectileThink_BuildingSmokeVolume(),
            DatamapHookListener.CSmokeGrenadeProjectileThink_Detonate => HookCSmokeGrenadeProjectileThink_Detonate(),
            DatamapHookListener.CSmokeGrenadeProjectileThink_Remove => HookCSmokeGrenadeProjectileThink_Remove(),
            DatamapHookListener.CSmokeGrenadeProjectileThink_Update => HookCSmokeGrenadeProjectileThink_Update(),
            DatamapHookListener.CSoundEventConeEntitySoundEventConeThink => HookCSoundEventConeEntitySoundEventConeThink(),
            DatamapHookListener.CSoundEventEntitySoundFinishedThink => HookCSoundEventEntitySoundFinishedThink(),
            DatamapHookListener.CSoundEventOBBEntitySoundEventOBBThink => HookCSoundEventOBBEntitySoundEventOBBThink(),
            DatamapHookListener.CSoundEventPathCornerEntitySoundEventPathCornerThink => HookCSoundEventPathCornerEntitySoundEventPathCornerThink(),
            DatamapHookListener.CSoundEventSphereEntitySoundEventSphereThink => HookCSoundEventSphereEntitySoundEventSphereThink(),
            DatamapHookListener.CSoundOpvarSetAutoRoomEntitySetOpvarThink => HookCSoundOpvarSetAutoRoomEntitySetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetBoxEntitySetOpvarThink => HookCSoundOpvarSetBoxEntitySetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetOBBWindEntitySetOpvarThink => HookCSoundOpvarSetOBBWindEntitySetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetPathCornerEntitySetOpvarThink => HookCSoundOpvarSetPathCornerEntitySetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetPointBaseSetOpvarThink => HookCSoundOpvarSetPointBaseSetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetPointEntitySetOpvarThink => HookCSoundOpvarSetPointEntitySetOpvarThink(),
            DatamapHookListener.CSplineConstraintTransitionThink => HookCSplineConstraintTransitionThink(),
            DatamapHookListener.CSpriteAnimateThink => HookCSpriteAnimateThink(),
            DatamapHookListener.CSpriteAnimateUntilDead => HookCSpriteAnimateUntilDead(),
            DatamapHookListener.CSpriteBeginFadeOutThink => HookCSpriteBeginFadeOutThink(),
            DatamapHookListener.CSpriteExpandThink => HookCSpriteExpandThink(),
            DatamapHookListener.CTriggerActiveWeaponDetectActiveWeaponThink => HookCTriggerActiveWeaponDetectActiveWeaponThink(),
            DatamapHookListener.CTriggerFanPushThink => HookCTriggerFanPushThink(),
            DatamapHookListener.CTriggerHurtHurtThink => HookCTriggerHurtHurtThink(),
            DatamapHookListener.CTriggerHurtNavThink => HookCTriggerHurtNavThink(),
            DatamapHookListener.CTriggerHurtRadiationThink => HookCTriggerHurtRadiationThink(),
            DatamapHookListener.CTriggerImpactDisableThink => HookCTriggerImpactDisableThink(),
            DatamapHookListener.CTriggerLerpObjectAttachedEntityThink => HookCTriggerLerpObjectAttachedEntityThink(),
            DatamapHookListener.CTriggerLerpObjectLerpThink => HookCTriggerLerpObjectLerpThink(),
            DatamapHookListener.CTriggerLerpObjectUnsetWaitForEntity => HookCTriggerLerpObjectUnsetWaitForEntity(),
            DatamapHookListener.CTriggerLookTimeoutThink => HookCTriggerLookTimeoutThink(),
            DatamapHookListener.CTriggerMultipleMultiTouch => HookCTriggerMultipleMultiTouch(),
            DatamapHookListener.CTriggerMultipleMultiWaitOver => HookCTriggerMultipleMultiWaitOver(),
            DatamapHookListener.CTriggerProximityMeasureThink => HookCTriggerProximityMeasureThink(),
            DatamapHookListener.CTriggerSaveRetriggerWaitOver => HookCTriggerSaveRetriggerWaitOver(),
            DatamapHookListener.CTriggerSndSosOpvarSndSosTriggerOpvarWaitOver => HookCTriggerSndSosOpvarSndSosTriggerOpvarWaitOver(),
            DatamapHookListener.CTriggerSoundscapePlayerUpdateThink => HookCTriggerSoundscapePlayerUpdateThink(),
            DatamapHookListener.CVoteControllerVoteControllerThink => HookCVoteControllerVoteControllerThink(),
            DatamapHookListener.CWaterBulletBulletThink => HookCWaterBulletBulletThink(),
            _ => throw new ArgumentOutOfRangeException(nameof(hookName), $"No hook found for {hookName}"),
        };
    }

    internal static Guid UnhookFunction(DatamapHookListener hookName)
    {
        return hookName switch
        {
            DatamapHookListener.CAmbientGenericRampThink => UnhookCAmbientGenericRampThink(),
            DatamapHookListener.CBarnLightThink_ApplyLightStylesToTargets => UnhookCBarnLightThink_ApplyLightStylesToTargets(),
            DatamapHookListener.CBarnLightThink_LightStyleEvent => UnhookCBarnLightThink_LightStyleEvent(),
            DatamapHookListener.CBarnLightThink_SetNextQueuedLightStyle => UnhookCBarnLightThink_SetNextQueuedLightStyle(),
            DatamapHookListener.CBaseAnimGraphChoreoServicesThink => UnhookCBaseAnimGraphChoreoServicesThink(),
            DatamapHookListener.CBaseButtonActivateTouch => UnhookCBaseButtonActivateTouch(),
            DatamapHookListener.CBaseButtonButtonBackHome => UnhookCBaseButtonButtonBackHome(),
            DatamapHookListener.CBaseButtonButtonReturn => UnhookCBaseButtonButtonReturn(),
            DatamapHookListener.CBaseButtonButtonSpark => UnhookCBaseButtonButtonSpark(),
            DatamapHookListener.CBaseButtonButtonTouch => UnhookCBaseButtonButtonTouch(),
            DatamapHookListener.CBaseButtonButtonUse => UnhookCBaseButtonButtonUse(),
            DatamapHookListener.CBaseButtonTriggerAndWait => UnhookCBaseButtonTriggerAndWait(),
            DatamapHookListener.CBaseCSGrenadeProjectileDangerSoundThink => UnhookCBaseCSGrenadeProjectileDangerSoundThink(),
            DatamapHookListener.CBaseDoorCloseAreaPortalsThink => UnhookCBaseDoorCloseAreaPortalsThink(),
            DatamapHookListener.CBaseDoorDoorGoDown => UnhookCBaseDoorDoorGoDown(),
            DatamapHookListener.CBaseDoorDoorGoUp => UnhookCBaseDoorDoorGoUp(),
            DatamapHookListener.CBaseDoorDoorHitBottom => UnhookCBaseDoorDoorHitBottom(),
            DatamapHookListener.CBaseDoorDoorHitTop => UnhookCBaseDoorDoorHitTop(),
            DatamapHookListener.CBaseDoorDoorTouch => UnhookCBaseDoorDoorTouch(),
            DatamapHookListener.CBaseDoorMovingSoundThink => UnhookCBaseDoorMovingSoundThink(),
            DatamapHookListener.CBaseEntityClearNavIgnoreContentsThink => UnhookCBaseEntityClearNavIgnoreContentsThink(),
            DatamapHookListener.CBaseEntityFakeScriptThinkFunc => UnhookCBaseEntityFakeScriptThinkFunc(),
            DatamapHookListener.CBaseEntitySUB_CallUseToggle => UnhookCBaseEntitySUB_CallUseToggle(),
            DatamapHookListener.CBaseEntitySUB_DoNothing => UnhookCBaseEntitySUB_DoNothing(),
            DatamapHookListener.CBaseEntitySUB_KillSelf => UnhookCBaseEntitySUB_KillSelf(),
            DatamapHookListener.CBaseEntitySUB_Remove => UnhookCBaseEntitySUB_Remove(),
            DatamapHookListener.CBaseGrenadeBounceTouch => UnhookCBaseGrenadeBounceTouch(),
            DatamapHookListener.CBaseGrenadeDangerSoundThink => UnhookCBaseGrenadeDangerSoundThink(),
            DatamapHookListener.CBaseGrenadeDetonate => UnhookCBaseGrenadeDetonate(),
            DatamapHookListener.CBaseGrenadeDetonateUse => UnhookCBaseGrenadeDetonateUse(),
            DatamapHookListener.CBaseGrenadeExplodeTouch => UnhookCBaseGrenadeExplodeTouch(),
            DatamapHookListener.CBaseGrenadePreDetonate => UnhookCBaseGrenadePreDetonate(),
            DatamapHookListener.CBaseGrenadeSlideTouch => UnhookCBaseGrenadeSlideTouch(),
            DatamapHookListener.CBaseGrenadeSmoke => UnhookCBaseGrenadeSmoke(),
            DatamapHookListener.CBaseGrenadeTumbleThink => UnhookCBaseGrenadeTumbleThink(),
            DatamapHookListener.CBaseModelEntityProcessSceneEventsThink => UnhookCBaseModelEntityProcessSceneEventsThink(),
            DatamapHookListener.CBaseModelEntitySUB_DissolveIfUncarried => UnhookCBaseModelEntitySUB_DissolveIfUncarried(),
            DatamapHookListener.CBaseModelEntitySUB_FadeOut => UnhookCBaseModelEntitySUB_FadeOut(),
            DatamapHookListener.CBaseModelEntitySUB_PerformShadowFadeIn => UnhookCBaseModelEntitySUB_PerformShadowFadeIn(),
            DatamapHookListener.CBaseModelEntitySUB_PerformShadowFadeOut => UnhookCBaseModelEntitySUB_PerformShadowFadeOut(),
            DatamapHookListener.CBaseModelEntitySUB_StartFadeOut => UnhookCBaseModelEntitySUB_StartFadeOut(),
            DatamapHookListener.CBaseModelEntitySUB_StartFadeOutInstant => UnhookCBaseModelEntitySUB_StartFadeOutInstant(),
            DatamapHookListener.CBaseModelEntitySUB_StartShadowFadeIn => UnhookCBaseModelEntitySUB_StartShadowFadeIn(),
            DatamapHookListener.CBaseModelEntitySUB_StartShadowFadeOut => UnhookCBaseModelEntitySUB_StartShadowFadeOut(),
            DatamapHookListener.CBaseModelEntitySUB_StopShadowFade => UnhookCBaseModelEntitySUB_StopShadowFade(),
            DatamapHookListener.CBasePropDoorDisableAreaPortalThink => UnhookCBasePropDoorDisableAreaPortalThink(),
            DatamapHookListener.CBasePropDoorDoorAutoCloseThink => UnhookCBasePropDoorDoorAutoCloseThink(),
            DatamapHookListener.CBasePropDoorDoorCloseMoveDone => UnhookCBasePropDoorDoorCloseMoveDone(),
            DatamapHookListener.CBasePropDoorDoorOpenMoveDone => UnhookCBasePropDoorDoorOpenMoveDone(),
            DatamapHookListener.CBombTargetBombTargetTouch => UnhookCBombTargetBombTargetTouch(),
            DatamapHookListener.CBombTargetBombTargetUse => UnhookCBombTargetBombTargetUse(),
            DatamapHookListener.CBreakableDie => UnhookCBreakableDie(),
            DatamapHookListener.CBreakablePropBreakThink => UnhookCBreakablePropBreakThink(),
            DatamapHookListener.CBreakablePropRampToDefaultFadeScale => UnhookCBreakablePropRampToDefaultFadeScale(),
            DatamapHookListener.CCSPlayerControllerInventoryUpdateThink => UnhookCCSPlayerControllerInventoryUpdateThink(),
            DatamapHookListener.CCSPlayerControllerPlayerForceTeamThink => UnhookCCSPlayerControllerPlayerForceTeamThink(),
            DatamapHookListener.CCSPlayerControllerResetForceTeamThink => UnhookCCSPlayerControllerResetForceTeamThink(),
            DatamapHookListener.CCSPlayerControllerResourceDataThink => UnhookCCSPlayerControllerResourceDataThink(),
            DatamapHookListener.CCSPlayerPawnCheckStuffThink => UnhookCCSPlayerPawnCheckStuffThink(),
            DatamapHookListener.CCSPlayerPawnPushawayThink => UnhookCCSPlayerPawnPushawayThink(),
            DatamapHookListener.CCSPlayerResourceResourceThink => UnhookCCSPlayerResourceResourceThink(),
            DatamapHookListener.CCSWeaponBaseDefaultTouch => UnhookCCSWeaponBaseDefaultTouch(),
            DatamapHookListener.CCSWeaponBaseRemoveUnownedWeaponThink => UnhookCCSWeaponBaseRemoveUnownedWeaponThink(),
            DatamapHookListener.CChickenChickenThink => UnhookCChickenChickenThink(),
            DatamapHookListener.CChickenChickenTouch => UnhookCChickenChickenTouch(),
            DatamapHookListener.CChickenChickenUse => UnhookCChickenChickenUse(),
            DatamapHookListener.CColorCorrectionFadeInThink => UnhookCColorCorrectionFadeInThink(),
            DatamapHookListener.CColorCorrectionFadeOutThink => UnhookCColorCorrectionFadeOutThink(),
            DatamapHookListener.CColorCorrectionVolumeThinkFunc => UnhookCColorCorrectionVolumeThinkFunc(),
            DatamapHookListener.CDecoyProjectileGunfireThink => UnhookCDecoyProjectileGunfireThink(),
            DatamapHookListener.CDecoyProjectileThink_Detonate => UnhookCDecoyProjectileThink_Detonate(),
            DatamapHookListener.CDynamicLightDynamicLightThink => UnhookCDynamicLightDynamicLightThink(),
            DatamapHookListener.CDynamicPropAnimThink => UnhookCDynamicPropAnimThink(),
            DatamapHookListener.CEntityDissolveDissolveThink => UnhookCEntityDissolveDissolveThink(),
            DatamapHookListener.CEntityDissolveElectrocuteThink => UnhookCEntityDissolveElectrocuteThink(),
            DatamapHookListener.CEnvBeamStrikeThink => UnhookCEnvBeamStrikeThink(),
            DatamapHookListener.CEnvBeamUpdateThink => UnhookCEnvBeamUpdateThink(),
            DatamapHookListener.CEnvEntityMakerCheckSpawnThink => UnhookCEnvEntityMakerCheckSpawnThink(),
            DatamapHookListener.CEnvLaserStrikeThink => UnhookCEnvLaserStrikeThink(),
            DatamapHookListener.CEnvSparkSparkThink => UnhookCEnvSparkSparkThink(),
            DatamapHookListener.CEnvWindControllerWindThink => UnhookCEnvWindControllerWindThink(),
            DatamapHookListener.CEnvWindWindThink => UnhookCEnvWindWindThink(),
            DatamapHookListener.CFishPoolUpdate => UnhookCFishPoolUpdate(),
            DatamapHookListener.CFogControllerSetLerpValues => UnhookCFogControllerSetLerpValues(),
            DatamapHookListener.CFuncMoveLinearNavMovableThink => UnhookCFuncMoveLinearNavMovableThink(),
            DatamapHookListener.CFuncMoveLinearNavObstacleThink => UnhookCFuncMoveLinearNavObstacleThink(),
            DatamapHookListener.CFuncMoveLinearStopMoveSound => UnhookCFuncMoveLinearStopMoveSound(),
            DatamapHookListener.CFuncPlatCallGoDown => UnhookCFuncPlatCallGoDown(),
            DatamapHookListener.CFuncPlatCallHitBottom => UnhookCFuncPlatCallHitBottom(),
            DatamapHookListener.CFuncPlatCallHitTop => UnhookCFuncPlatCallHitTop(),
            DatamapHookListener.CFuncPlatPlatUse => UnhookCFuncPlatPlatUse(),
            DatamapHookListener.CFuncRotatingHurtTouch => UnhookCFuncRotatingHurtTouch(),
            DatamapHookListener.CFuncRotatingReverseMove => UnhookCFuncRotatingReverseMove(),
            DatamapHookListener.CFuncRotatingRotateMove => UnhookCFuncRotatingRotateMove(),
            DatamapHookListener.CFuncRotatingRotatingUse => UnhookCFuncRotatingRotatingUse(),
            DatamapHookListener.CFuncRotatingSpinDownMove => UnhookCFuncRotatingSpinDownMove(),
            DatamapHookListener.CFuncRotatingSpinUpMove => UnhookCFuncRotatingSpinUpMove(),
            DatamapHookListener.CFuncShatterglassGlassThink => UnhookCFuncShatterglassGlassThink(),
            DatamapHookListener.CFuncTrackChangeFind => UnhookCFuncTrackChangeFind(),
            DatamapHookListener.CFuncTrackTrainDeadEnd => UnhookCFuncTrackTrainDeadEnd(),
            DatamapHookListener.CFuncTrackTrainFind => UnhookCFuncTrackTrainFind(),
            DatamapHookListener.CFuncTrackTrainNearestPath => UnhookCFuncTrackTrainNearestPath(),
            DatamapHookListener.CFuncTrackTrainNext => UnhookCFuncTrackTrainNext(),
            DatamapHookListener.CFuncTrainNext => UnhookCFuncTrainNext(),
            DatamapHookListener.CFuncTrainWait => UnhookCFuncTrainWait(),
            DatamapHookListener.CGenericConstraintUpdateThink => UnhookCGenericConstraintUpdateThink(),
            DatamapHookListener.CGunTargetNext => UnhookCGunTargetNext(),
            DatamapHookListener.CGunTargetStart => UnhookCGunTargetStart(),
            DatamapHookListener.CGunTargetWait => UnhookCGunTargetWait(),
            DatamapHookListener.CHostageHostageThink => UnhookCHostageHostageThink(),
            DatamapHookListener.CHostageHostageUse => UnhookCHostageHostageUse(),
            DatamapHookListener.CHostageRescueZoneHostageRescueTouch => UnhookCHostageRescueZoneHostageRescueTouch(),
            DatamapHookListener.CInfernoInfernoThink => UnhookCInfernoInfernoThink(),
            DatamapHookListener.CInfoSpawnGroupLoadUnloadSpawnGroupLoadingThink => UnhookCInfoSpawnGroupLoadUnloadSpawnGroupLoadingThink(),
            DatamapHookListener.CInfoSpawnGroupLoadUnloadSpawnGroupUnloadingThink => UnhookCInfoSpawnGroupLoadUnloadSpawnGroupUnloadingThink(),
            DatamapHookListener.CItemComeToRest => UnhookCItemComeToRest(),
            DatamapHookListener.CItemDefuserActivateThink => UnhookCItemDefuserActivateThink(),
            DatamapHookListener.CItemDefuserDefuserTouch => UnhookCItemDefuserDefuserTouch(),
            DatamapHookListener.CItemGenericItemGenericTouch => UnhookCItemGenericItemGenericTouch(),
            DatamapHookListener.CItemItemTouch => UnhookCItemItemTouch(),
            DatamapHookListener.CItemMaterialize => UnhookCItemMaterialize(),
            DatamapHookListener.CLogicActiveAutosaveSaveThink => UnhookCLogicActiveAutosaveSaveThink(),
            DatamapHookListener.CLogicDistanceAutosaveSaveThink => UnhookCLogicDistanceAutosaveSaveThink(),
            DatamapHookListener.CLogicGameStateReportSetGameStateReportThink => UnhookCLogicGameStateReportSetGameStateReportThink(),
            DatamapHookListener.CLogicMeasureMovementMeasureThink => UnhookCLogicMeasureMovementMeasureThink(),
            DatamapHookListener.CLogicNPCCounterSetNPCCounterThink => UnhookCLogicNPCCounterSetNPCCounterThink(),
            DatamapHookListener.CMapVetoPickControllerVoteControllerThink => UnhookCMapVetoPickControllerVoteControllerThink(),
            DatamapHookListener.CMomentaryRotButtonReturnMoveDone => UnhookCMomentaryRotButtonReturnMoveDone(),
            DatamapHookListener.CMomentaryRotButtonSetPositionMoveDone => UnhookCMomentaryRotButtonSetPositionMoveDone(),
            DatamapHookListener.CMomentaryRotButtonUpdateThink => UnhookCMomentaryRotButtonUpdateThink(),
            DatamapHookListener.CMomentaryRotButtonUseMoveDone => UnhookCMomentaryRotButtonUseMoveDone(),
            DatamapHookListener.CMultiLightProxyApproachBrightnessThink => UnhookCMultiLightProxyApproachBrightnessThink(),
            DatamapHookListener.CMultiLightProxyRestoreFlashlightThink => UnhookCMultiLightProxyRestoreFlashlightThink(),
            DatamapHookListener.CMultiSourceRegister => UnhookCMultiSourceRegister(),
            DatamapHookListener.CParticleSystemStartParticleSystemThink => UnhookCParticleSystemStartParticleSystemThink(),
            DatamapHookListener.CPathMoverEntitySpawnerSpawnThink => UnhookCPathMoverEntitySpawnerSpawnThink(),
            DatamapHookListener.CPathNodeParentedMoveThink => UnhookCPathNodeParentedMoveThink(),
            DatamapHookListener.CPhysForceForceOff => UnhookCPhysForceForceOff(),
            DatamapHookListener.CPhysForceInitialThink => UnhookCPhysForceInitialThink(),
            DatamapHookListener.CPhysHingeLimitThink => UnhookCPhysHingeLimitThink(),
            DatamapHookListener.CPhysHingeMoveThink => UnhookCPhysHingeMoveThink(),
            DatamapHookListener.CPhysHingeSoundThink => UnhookCPhysHingeSoundThink(),
            DatamapHookListener.CPhysImpactPointAtEntity => UnhookCPhysImpactPointAtEntity(),
            DatamapHookListener.CPhysSlideConstraintSoundThink => UnhookCPhysSlideConstraintSoundThink(),
            DatamapHookListener.CPhysicsPropClearFlagsThink => UnhookCPhysicsPropClearFlagsThink(),
            DatamapHookListener.CPhysicsPropClearThrownByPlayerThink => UnhookCPhysicsPropClearThrownByPlayerThink(),
            DatamapHookListener.CPhysicsPropRespawnableMaterialize => UnhookCPhysicsPropRespawnableMaterialize(),
            DatamapHookListener.CPlantedC4C4Think => UnhookCPlantedC4C4Think(),
            DatamapHookListener.CPointCommentaryNodeAcculumatePlayTimeThink => UnhookCPointCommentaryNodeAcculumatePlayTimeThink(),
            DatamapHookListener.CPointCommentaryNodeSpinThink => UnhookCPointCommentaryNodeSpinThink(),
            DatamapHookListener.CPointCommentaryNodeUpdateViewPostThink => UnhookCPointCommentaryNodeUpdateViewPostThink(),
            DatamapHookListener.CPointCommentaryNodeUpdateViewThink => UnhookCPointCommentaryNodeUpdateViewThink(),
            DatamapHookListener.CPointHurtHurtThink => UnhookCPointHurtHurtThink(),
            DatamapHookListener.CPointOrientReorientThink => UnhookCPointOrientReorientThink(),
            DatamapHookListener.CPointPushPushThink => UnhookCPointPushPushThink(),
            DatamapHookListener.CPointValueRemapperUpdateThink => UnhookCPointValueRemapperUpdateThink(),
            DatamapHookListener.CRagdollPropAttachedItemsThink => UnhookCRagdollPropAttachedItemsThink(),
            DatamapHookListener.CRagdollPropClearFlagsThink => UnhookCRagdollPropClearFlagsThink(),
            DatamapHookListener.CRagdollPropFadeOutThink => UnhookCRagdollPropFadeOutThink(),
            DatamapHookListener.CRagdollPropSetDebrisThink => UnhookCRagdollPropSetDebrisThink(),
            DatamapHookListener.CRagdollPropSettleThink => UnhookCRagdollPropSettleThink(),
            DatamapHookListener.CRevertSavedLoadThink => UnhookCRevertSavedLoadThink(),
            DatamapHookListener.CScriptedSequenceScriptThink => UnhookCScriptedSequenceScriptThink(),
            DatamapHookListener.CSmokeGrenadeProjectileThink_BuildingSmokeVolume => UnhookCSmokeGrenadeProjectileThink_BuildingSmokeVolume(),
            DatamapHookListener.CSmokeGrenadeProjectileThink_Detonate => UnhookCSmokeGrenadeProjectileThink_Detonate(),
            DatamapHookListener.CSmokeGrenadeProjectileThink_Remove => UnhookCSmokeGrenadeProjectileThink_Remove(),
            DatamapHookListener.CSmokeGrenadeProjectileThink_Update => UnhookCSmokeGrenadeProjectileThink_Update(),
            DatamapHookListener.CSoundEventConeEntitySoundEventConeThink => UnhookCSoundEventConeEntitySoundEventConeThink(),
            DatamapHookListener.CSoundEventEntitySoundFinishedThink => UnhookCSoundEventEntitySoundFinishedThink(),
            DatamapHookListener.CSoundEventOBBEntitySoundEventOBBThink => UnhookCSoundEventOBBEntitySoundEventOBBThink(),
            DatamapHookListener.CSoundEventPathCornerEntitySoundEventPathCornerThink => UnhookCSoundEventPathCornerEntitySoundEventPathCornerThink(),
            DatamapHookListener.CSoundEventSphereEntitySoundEventSphereThink => UnhookCSoundEventSphereEntitySoundEventSphereThink(),
            DatamapHookListener.CSoundOpvarSetAutoRoomEntitySetOpvarThink => UnhookCSoundOpvarSetAutoRoomEntitySetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetBoxEntitySetOpvarThink => UnhookCSoundOpvarSetBoxEntitySetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetOBBWindEntitySetOpvarThink => UnhookCSoundOpvarSetOBBWindEntitySetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetPathCornerEntitySetOpvarThink => UnhookCSoundOpvarSetPathCornerEntitySetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetPointBaseSetOpvarThink => UnhookCSoundOpvarSetPointBaseSetOpvarThink(),
            DatamapHookListener.CSoundOpvarSetPointEntitySetOpvarThink => UnhookCSoundOpvarSetPointEntitySetOpvarThink(),
            DatamapHookListener.CSplineConstraintTransitionThink => UnhookCSplineConstraintTransitionThink(),
            DatamapHookListener.CSpriteAnimateThink => UnhookCSpriteAnimateThink(),
            DatamapHookListener.CSpriteAnimateUntilDead => UnhookCSpriteAnimateUntilDead(),
            DatamapHookListener.CSpriteBeginFadeOutThink => UnhookCSpriteBeginFadeOutThink(),
            DatamapHookListener.CSpriteExpandThink => UnhookCSpriteExpandThink(),
            DatamapHookListener.CTriggerActiveWeaponDetectActiveWeaponThink => UnhookCTriggerActiveWeaponDetectActiveWeaponThink(),
            DatamapHookListener.CTriggerFanPushThink => UnhookCTriggerFanPushThink(),
            DatamapHookListener.CTriggerHurtHurtThink => UnhookCTriggerHurtHurtThink(),
            DatamapHookListener.CTriggerHurtNavThink => UnhookCTriggerHurtNavThink(),
            DatamapHookListener.CTriggerHurtRadiationThink => UnhookCTriggerHurtRadiationThink(),
            DatamapHookListener.CTriggerImpactDisableThink => UnhookCTriggerImpactDisableThink(),
            DatamapHookListener.CTriggerLerpObjectAttachedEntityThink => UnhookCTriggerLerpObjectAttachedEntityThink(),
            DatamapHookListener.CTriggerLerpObjectLerpThink => UnhookCTriggerLerpObjectLerpThink(),
            DatamapHookListener.CTriggerLerpObjectUnsetWaitForEntity => UnhookCTriggerLerpObjectUnsetWaitForEntity(),
            DatamapHookListener.CTriggerLookTimeoutThink => UnhookCTriggerLookTimeoutThink(),
            DatamapHookListener.CTriggerMultipleMultiTouch => UnhookCTriggerMultipleMultiTouch(),
            DatamapHookListener.CTriggerMultipleMultiWaitOver => UnhookCTriggerMultipleMultiWaitOver(),
            DatamapHookListener.CTriggerProximityMeasureThink => UnhookCTriggerProximityMeasureThink(),
            DatamapHookListener.CTriggerSaveRetriggerWaitOver => UnhookCTriggerSaveRetriggerWaitOver(),
            DatamapHookListener.CTriggerSndSosOpvarSndSosTriggerOpvarWaitOver => UnhookCTriggerSndSosOpvarSndSosTriggerOpvarWaitOver(),
            DatamapHookListener.CTriggerSoundscapePlayerUpdateThink => UnhookCTriggerSoundscapePlayerUpdateThink(),
            DatamapHookListener.CVoteControllerVoteControllerThink => UnhookCVoteControllerVoteControllerThink(),
            DatamapHookListener.CWaterBulletBulletThink => UnhookCWaterBulletBulletThink(),
            _ => throw new ArgumentOutOfRangeException(nameof(hookName), $"No hook found for {hookName}"),
        };
    }
}