using SwiftlyS2.Shared.GameHooks;

namespace SwiftlyS2.Core.GameHooks;

internal sealed class GameHookDatamaps : IGameHookDatamaps
{
    internal readonly GameHookDatamapCAmbientGeneric CAmbientGenericHook = new();
    internal readonly GameHookDatamapCBarnLight CBarnLightHook = new();
    internal readonly GameHookDatamapCBaseAnimGraph CBaseAnimGraphHook = new();
    internal readonly GameHookDatamapCBaseButton CBaseButtonHook = new();
    internal readonly GameHookDatamapCBaseCSGrenadeProjectile CBaseCSGrenadeProjectileHook = new();
    internal readonly GameHookDatamapCBaseDoor CBaseDoorHook = new();
    internal readonly GameHookDatamapCBaseEntity CBaseEntityHook = new();
    internal readonly GameHookDatamapCBaseGrenade CBaseGrenadeHook = new();
    internal readonly GameHookDatamapCBaseModelEntity CBaseModelEntityHook = new();
    internal readonly GameHookDatamapCBasePropDoor CBasePropDoorHook = new();
    internal readonly GameHookDatamapCBombTarget CBombTargetHook = new();
    internal readonly GameHookDatamapCBreakable CBreakableHook = new();
    internal readonly GameHookDatamapCBreakableProp CBreakablePropHook = new();
    internal readonly GameHookDatamapCCSPlayerController CCSPlayerControllerHook = new();
    internal readonly GameHookDatamapCCSPlayerPawn CCSPlayerPawnHook = new();
    internal readonly GameHookDatamapCCSPlayerResource CCSPlayerResourceHook = new();
    internal readonly GameHookDatamapCCSWeaponBase CCSWeaponBaseHook = new();
    internal readonly GameHookDatamapCChicken CChickenHook = new();
    internal readonly GameHookDatamapCColorCorrection CColorCorrectionHook = new();
    internal readonly GameHookDatamapCColorCorrectionVolume CColorCorrectionVolumeHook = new();
    internal readonly GameHookDatamapCDecoyProjectile CDecoyProjectileHook = new();
    internal readonly GameHookDatamapCDynamicLight CDynamicLightHook = new();
    internal readonly GameHookDatamapCDynamicProp CDynamicPropHook = new();
    internal readonly GameHookDatamapCEntityDissolve CEntityDissolveHook = new();
    internal readonly GameHookDatamapCEnvBeam CEnvBeamHook = new();
    internal readonly GameHookDatamapCEnvEntityMaker CEnvEntityMakerHook = new();
    internal readonly GameHookDatamapCEnvLaser CEnvLaserHook = new();
    internal readonly GameHookDatamapCEnvSpark CEnvSparkHook = new();
    internal readonly GameHookDatamapCEnvWind CEnvWindHook = new();
    internal readonly GameHookDatamapCEnvWindController CEnvWindControllerHook = new();
    internal readonly GameHookDatamapCFishPool CFishPoolHook = new();
    internal readonly GameHookDatamapCFogController CFogControllerHook = new();
    internal readonly GameHookDatamapCFuncMoveLinear CFuncMoveLinearHook = new();
    internal readonly GameHookDatamapCFuncPlat CFuncPlatHook = new();
    internal readonly GameHookDatamapCFuncRotating CFuncRotatingHook = new();
    internal readonly GameHookDatamapCFuncShatterglass CFuncShatterglassHook = new();
    internal readonly GameHookDatamapCFuncTrackChange CFuncTrackChangeHook = new();
    internal readonly GameHookDatamapCFuncTrackTrain CFuncTrackTrainHook = new();
    internal readonly GameHookDatamapCFuncTrain CFuncTrainHook = new();
    internal readonly GameHookDatamapCGenericConstraint CGenericConstraintHook = new();
    internal readonly GameHookDatamapCGunTarget CGunTargetHook = new();
    internal readonly GameHookDatamapCHostage CHostageHook = new();
    internal readonly GameHookDatamapCHostageRescueZone CHostageRescueZoneHook = new();
    internal readonly GameHookDatamapCInferno CInfernoHook = new();
    internal readonly GameHookDatamapCInfoSpawnGroupLoadUnload CInfoSpawnGroupLoadUnloadHook = new();
    internal readonly GameHookDatamapCItem CItemHook = new();
    internal readonly GameHookDatamapCItemDefuser CItemDefuserHook = new();
    internal readonly GameHookDatamapCItemGeneric CItemGenericHook = new();
    internal readonly GameHookDatamapCLogicActiveAutosave CLogicActiveAutosaveHook = new();
    internal readonly GameHookDatamapCLogicDistanceAutosave CLogicDistanceAutosaveHook = new();
    internal readonly GameHookDatamapCLogicGameStateReport CLogicGameStateReportHook = new();
    internal readonly GameHookDatamapCLogicMeasureMovement CLogicMeasureMovementHook = new();
    internal readonly GameHookDatamapCLogicNPCCounter CLogicNPCCounterHook = new();
    internal readonly GameHookDatamapCMapVetoPickController CMapVetoPickControllerHook = new();
    internal readonly GameHookDatamapCMomentaryRotButton CMomentaryRotButtonHook = new();
    internal readonly GameHookDatamapCMultiLightProxy CMultiLightProxyHook = new();
    internal readonly GameHookDatamapCMultiSource CMultiSourceHook = new();
    internal readonly GameHookDatamapCParticleSystem CParticleSystemHook = new();
    internal readonly GameHookDatamapCPathMoverEntitySpawner CPathMoverEntitySpawnerHook = new();
    internal readonly GameHookDatamapCPathNode CPathNodeHook = new();
    internal readonly GameHookDatamapCPhysForce CPhysForceHook = new();
    internal readonly GameHookDatamapCPhysHinge CPhysHingeHook = new();
    internal readonly GameHookDatamapCPhysImpact CPhysImpactHook = new();
    internal readonly GameHookDatamapCPhysSlideConstraint CPhysSlideConstraintHook = new();
    internal readonly GameHookDatamapCPhysicsProp CPhysicsPropHook = new();
    internal readonly GameHookDatamapCPhysicsPropRespawnable CPhysicsPropRespawnableHook = new();
    internal readonly GameHookDatamapCPlantedC4 CPlantedC4Hook = new();
    internal readonly GameHookDatamapCPointCommentaryNode CPointCommentaryNodeHook = new();
    internal readonly GameHookDatamapCPointHurt CPointHurtHook = new();
    internal readonly GameHookDatamapCPointOrient CPointOrientHook = new();
    internal readonly GameHookDatamapCPointPush CPointPushHook = new();
    internal readonly GameHookDatamapCPointValueRemapper CPointValueRemapperHook = new();
    internal readonly GameHookDatamapCRagdollProp CRagdollPropHook = new();
    internal readonly GameHookDatamapCRevertSaved CRevertSavedHook = new();
    internal readonly GameHookDatamapCScriptedSequence CScriptedSequenceHook = new();
    internal readonly GameHookDatamapCSmokeGrenadeProjectile CSmokeGrenadeProjectileHook = new();
    internal readonly GameHookDatamapCSoundEventConeEntity CSoundEventConeEntityHook = new();
    internal readonly GameHookDatamapCSoundEventEntity CSoundEventEntityHook = new();
    internal readonly GameHookDatamapCSoundEventOBBEntity CSoundEventOBBEntityHook = new();
    internal readonly GameHookDatamapCSoundEventPathCornerEntity CSoundEventPathCornerEntityHook = new();
    internal readonly GameHookDatamapCSoundEventSphereEntity CSoundEventSphereEntityHook = new();
    internal readonly GameHookDatamapCSoundOpvarSetAutoRoomEntity CSoundOpvarSetAutoRoomEntityHook = new();
    internal readonly GameHookDatamapCSoundOpvarSetBoxEntity CSoundOpvarSetBoxEntityHook = new();
    internal readonly GameHookDatamapCSoundOpvarSetOBBWindEntity CSoundOpvarSetOBBWindEntityHook = new();
    internal readonly GameHookDatamapCSoundOpvarSetPathCornerEntity CSoundOpvarSetPathCornerEntityHook = new();
    internal readonly GameHookDatamapCSoundOpvarSetPointBase CSoundOpvarSetPointBaseHook = new();
    internal readonly GameHookDatamapCSoundOpvarSetPointEntity CSoundOpvarSetPointEntityHook = new();
    internal readonly GameHookDatamapCSplineConstraint CSplineConstraintHook = new();
    internal readonly GameHookDatamapCSprite CSpriteHook = new();
    internal readonly GameHookDatamapCTriggerActiveWeaponDetect CTriggerActiveWeaponDetectHook = new();
    internal readonly GameHookDatamapCTriggerFan CTriggerFanHook = new();
    internal readonly GameHookDatamapCTriggerHurt CTriggerHurtHook = new();
    internal readonly GameHookDatamapCTriggerImpact CTriggerImpactHook = new();
    internal readonly GameHookDatamapCTriggerLerpObject CTriggerLerpObjectHook = new();
    internal readonly GameHookDatamapCTriggerLook CTriggerLookHook = new();
    internal readonly GameHookDatamapCTriggerMultiple CTriggerMultipleHook = new();
    internal readonly GameHookDatamapCTriggerProximity CTriggerProximityHook = new();
    internal readonly GameHookDatamapCTriggerSave CTriggerSaveHook = new();
    internal readonly GameHookDatamapCTriggerSndSosOpvar CTriggerSndSosOpvarHook = new();
    internal readonly GameHookDatamapCTriggerSoundscape CTriggerSoundscapeHook = new();
    internal readonly GameHookDatamapCVoteController CVoteControllerHook = new();
    internal readonly GameHookDatamapCWaterBullet CWaterBulletHook = new();

    public IGameHookDatamapCAmbientGeneric CAmbientGeneric => CAmbientGenericHook;
    public IGameHookDatamapCBarnLight CBarnLight => CBarnLightHook;
    public IGameHookDatamapCBaseAnimGraph CBaseAnimGraph => CBaseAnimGraphHook;
    public IGameHookDatamapCBaseButton CBaseButton => CBaseButtonHook;
    public IGameHookDatamapCBaseCSGrenadeProjectile CBaseCSGrenadeProjectile => CBaseCSGrenadeProjectileHook;
    public IGameHookDatamapCBaseDoor CBaseDoor => CBaseDoorHook;
    public IGameHookDatamapCBaseEntity CBaseEntity => CBaseEntityHook;
    public IGameHookDatamapCBaseGrenade CBaseGrenade => CBaseGrenadeHook;
    public IGameHookDatamapCBaseModelEntity CBaseModelEntity => CBaseModelEntityHook;
    public IGameHookDatamapCBasePropDoor CBasePropDoor => CBasePropDoorHook;
    public IGameHookDatamapCBombTarget CBombTarget => CBombTargetHook;
    public IGameHookDatamapCBreakable CBreakable => CBreakableHook;
    public IGameHookDatamapCBreakableProp CBreakableProp => CBreakablePropHook;
    public IGameHookDatamapCCSPlayerController CCSPlayerController => CCSPlayerControllerHook;
    public IGameHookDatamapCCSPlayerPawn CCSPlayerPawn => CCSPlayerPawnHook;
    public IGameHookDatamapCCSPlayerResource CCSPlayerResource => CCSPlayerResourceHook;
    public IGameHookDatamapCCSWeaponBase CCSWeaponBase => CCSWeaponBaseHook;
    public IGameHookDatamapCChicken CChicken => CChickenHook;
    public IGameHookDatamapCColorCorrection CColorCorrection => CColorCorrectionHook;
    public IGameHookDatamapCColorCorrectionVolume CColorCorrectionVolume => CColorCorrectionVolumeHook;
    public IGameHookDatamapCDecoyProjectile CDecoyProjectile => CDecoyProjectileHook;
    public IGameHookDatamapCDynamicLight CDynamicLight => CDynamicLightHook;
    public IGameHookDatamapCDynamicProp CDynamicProp => CDynamicPropHook;
    public IGameHookDatamapCEntityDissolve CEntityDissolve => CEntityDissolveHook;
    public IGameHookDatamapCEnvBeam CEnvBeam => CEnvBeamHook;
    public IGameHookDatamapCEnvEntityMaker CEnvEntityMaker => CEnvEntityMakerHook;
    public IGameHookDatamapCEnvLaser CEnvLaser => CEnvLaserHook;
    public IGameHookDatamapCEnvSpark CEnvSpark => CEnvSparkHook;
    public IGameHookDatamapCEnvWind CEnvWind => CEnvWindHook;
    public IGameHookDatamapCEnvWindController CEnvWindController => CEnvWindControllerHook;
    public IGameHookDatamapCFishPool CFishPool => CFishPoolHook;
    public IGameHookDatamapCFogController CFogController => CFogControllerHook;
    public IGameHookDatamapCFuncMoveLinear CFuncMoveLinear => CFuncMoveLinearHook;
    public IGameHookDatamapCFuncPlat CFuncPlat => CFuncPlatHook;
    public IGameHookDatamapCFuncRotating CFuncRotating => CFuncRotatingHook;
    public IGameHookDatamapCFuncShatterglass CFuncShatterglass => CFuncShatterglassHook;
    public IGameHookDatamapCFuncTrackChange CFuncTrackChange => CFuncTrackChangeHook;
    public IGameHookDatamapCFuncTrackTrain CFuncTrackTrain => CFuncTrackTrainHook;
    public IGameHookDatamapCFuncTrain CFuncTrain => CFuncTrainHook;
    public IGameHookDatamapCGenericConstraint CGenericConstraint => CGenericConstraintHook;
    public IGameHookDatamapCGunTarget CGunTarget => CGunTargetHook;
    public IGameHookDatamapCHostage CHostage => CHostageHook;
    public IGameHookDatamapCHostageRescueZone CHostageRescueZone => CHostageRescueZoneHook;
    public IGameHookDatamapCInferno CInferno => CInfernoHook;
    public IGameHookDatamapCInfoSpawnGroupLoadUnload CInfoSpawnGroupLoadUnload => CInfoSpawnGroupLoadUnloadHook;
    public IGameHookDatamapCItem CItem => CItemHook;
    public IGameHookDatamapCItemDefuser CItemDefuser => CItemDefuserHook;
    public IGameHookDatamapCItemGeneric CItemGeneric => CItemGenericHook;
    public IGameHookDatamapCLogicActiveAutosave CLogicActiveAutosave => CLogicActiveAutosaveHook;
    public IGameHookDatamapCLogicDistanceAutosave CLogicDistanceAutosave => CLogicDistanceAutosaveHook;
    public IGameHookDatamapCLogicGameStateReport CLogicGameStateReport => CLogicGameStateReportHook;
    public IGameHookDatamapCLogicMeasureMovement CLogicMeasureMovement => CLogicMeasureMovementHook;
    public IGameHookDatamapCLogicNPCCounter CLogicNPCCounter => CLogicNPCCounterHook;
    public IGameHookDatamapCMapVetoPickController CMapVetoPickController => CMapVetoPickControllerHook;
    public IGameHookDatamapCMomentaryRotButton CMomentaryRotButton => CMomentaryRotButtonHook;
    public IGameHookDatamapCMultiLightProxy CMultiLightProxy => CMultiLightProxyHook;
    public IGameHookDatamapCMultiSource CMultiSource => CMultiSourceHook;
    public IGameHookDatamapCParticleSystem CParticleSystem => CParticleSystemHook;
    public IGameHookDatamapCPathMoverEntitySpawner CPathMoverEntitySpawner => CPathMoverEntitySpawnerHook;
    public IGameHookDatamapCPathNode CPathNode => CPathNodeHook;
    public IGameHookDatamapCPhysForce CPhysForce => CPhysForceHook;
    public IGameHookDatamapCPhysHinge CPhysHinge => CPhysHingeHook;
    public IGameHookDatamapCPhysImpact CPhysImpact => CPhysImpactHook;
    public IGameHookDatamapCPhysSlideConstraint CPhysSlideConstraint => CPhysSlideConstraintHook;
    public IGameHookDatamapCPhysicsProp CPhysicsProp => CPhysicsPropHook;
    public IGameHookDatamapCPhysicsPropRespawnable CPhysicsPropRespawnable => CPhysicsPropRespawnableHook;
    public IGameHookDatamapCPlantedC4 CPlantedC4 => CPlantedC4Hook;
    public IGameHookDatamapCPointCommentaryNode CPointCommentaryNode => CPointCommentaryNodeHook;
    public IGameHookDatamapCPointHurt CPointHurt => CPointHurtHook;
    public IGameHookDatamapCPointOrient CPointOrient => CPointOrientHook;
    public IGameHookDatamapCPointPush CPointPush => CPointPushHook;
    public IGameHookDatamapCPointValueRemapper CPointValueRemapper => CPointValueRemapperHook;
    public IGameHookDatamapCRagdollProp CRagdollProp => CRagdollPropHook;
    public IGameHookDatamapCRevertSaved CRevertSaved => CRevertSavedHook;
    public IGameHookDatamapCScriptedSequence CScriptedSequence => CScriptedSequenceHook;
    public IGameHookDatamapCSmokeGrenadeProjectile CSmokeGrenadeProjectile => CSmokeGrenadeProjectileHook;
    public IGameHookDatamapCSoundEventConeEntity CSoundEventConeEntity => CSoundEventConeEntityHook;
    public IGameHookDatamapCSoundEventEntity CSoundEventEntity => CSoundEventEntityHook;
    public IGameHookDatamapCSoundEventOBBEntity CSoundEventOBBEntity => CSoundEventOBBEntityHook;
    public IGameHookDatamapCSoundEventPathCornerEntity CSoundEventPathCornerEntity => CSoundEventPathCornerEntityHook;
    public IGameHookDatamapCSoundEventSphereEntity CSoundEventSphereEntity => CSoundEventSphereEntityHook;
    public IGameHookDatamapCSoundOpvarSetAutoRoomEntity CSoundOpvarSetAutoRoomEntity => CSoundOpvarSetAutoRoomEntityHook;
    public IGameHookDatamapCSoundOpvarSetBoxEntity CSoundOpvarSetBoxEntity => CSoundOpvarSetBoxEntityHook;
    public IGameHookDatamapCSoundOpvarSetOBBWindEntity CSoundOpvarSetOBBWindEntity => CSoundOpvarSetOBBWindEntityHook;
    public IGameHookDatamapCSoundOpvarSetPathCornerEntity CSoundOpvarSetPathCornerEntity => CSoundOpvarSetPathCornerEntityHook;
    public IGameHookDatamapCSoundOpvarSetPointBase CSoundOpvarSetPointBase => CSoundOpvarSetPointBaseHook;
    public IGameHookDatamapCSoundOpvarSetPointEntity CSoundOpvarSetPointEntity => CSoundOpvarSetPointEntityHook;
    public IGameHookDatamapCSplineConstraint CSplineConstraint => CSplineConstraintHook;
    public IGameHookDatamapCSprite CSprite => CSpriteHook;
    public IGameHookDatamapCTriggerActiveWeaponDetect CTriggerActiveWeaponDetect => CTriggerActiveWeaponDetectHook;
    public IGameHookDatamapCTriggerFan CTriggerFan => CTriggerFanHook;
    public IGameHookDatamapCTriggerHurt CTriggerHurt => CTriggerHurtHook;
    public IGameHookDatamapCTriggerImpact CTriggerImpact => CTriggerImpactHook;
    public IGameHookDatamapCTriggerLerpObject CTriggerLerpObject => CTriggerLerpObjectHook;
    public IGameHookDatamapCTriggerLook CTriggerLook => CTriggerLookHook;
    public IGameHookDatamapCTriggerMultiple CTriggerMultiple => CTriggerMultipleHook;
    public IGameHookDatamapCTriggerProximity CTriggerProximity => CTriggerProximityHook;
    public IGameHookDatamapCTriggerSave CTriggerSave => CTriggerSaveHook;
    public IGameHookDatamapCTriggerSndSosOpvar CTriggerSndSosOpvar => CTriggerSndSosOpvarHook;
    public IGameHookDatamapCTriggerSoundscape CTriggerSoundscape => CTriggerSoundscapeHook;
    public IGameHookDatamapCVoteController CVoteController => CVoteControllerHook;
    public IGameHookDatamapCWaterBullet CWaterBullet => CWaterBulletHook;

    internal void UnregisterAllListeners()
    {
        CAmbientGenericHook.UnregisterListeners();
        CBarnLightHook.UnregisterListeners();
        CBaseAnimGraphHook.UnregisterListeners();
        CBaseButtonHook.UnregisterListeners();
        CBaseCSGrenadeProjectileHook.UnregisterListeners();
        CBaseDoorHook.UnregisterListeners();
        CBaseEntityHook.UnregisterListeners();
        CBaseGrenadeHook.UnregisterListeners();
        CBaseModelEntityHook.UnregisterListeners();
        CBasePropDoorHook.UnregisterListeners();
        CBombTargetHook.UnregisterListeners();
        CBreakableHook.UnregisterListeners();
        CBreakablePropHook.UnregisterListeners();
        CCSPlayerControllerHook.UnregisterListeners();
        CCSPlayerPawnHook.UnregisterListeners();
        CCSPlayerResourceHook.UnregisterListeners();
        CCSWeaponBaseHook.UnregisterListeners();
        CChickenHook.UnregisterListeners();
        CColorCorrectionHook.UnregisterListeners();
        CColorCorrectionVolumeHook.UnregisterListeners();
        CDecoyProjectileHook.UnregisterListeners();
        CDynamicLightHook.UnregisterListeners();
        CDynamicPropHook.UnregisterListeners();
        CEntityDissolveHook.UnregisterListeners();
        CEnvBeamHook.UnregisterListeners();
        CEnvEntityMakerHook.UnregisterListeners();
        CEnvLaserHook.UnregisterListeners();
        CEnvSparkHook.UnregisterListeners();
        CEnvWindHook.UnregisterListeners();
        CEnvWindControllerHook.UnregisterListeners();
        CFishPoolHook.UnregisterListeners();
        CFogControllerHook.UnregisterListeners();
        CFuncMoveLinearHook.UnregisterListeners();
        CFuncPlatHook.UnregisterListeners();
        CFuncRotatingHook.UnregisterListeners();
        CFuncShatterglassHook.UnregisterListeners();
        CFuncTrackChangeHook.UnregisterListeners();
        CFuncTrackTrainHook.UnregisterListeners();
        CFuncTrainHook.UnregisterListeners();
        CGenericConstraintHook.UnregisterListeners();
        CGunTargetHook.UnregisterListeners();
        CHostageHook.UnregisterListeners();
        CHostageRescueZoneHook.UnregisterListeners();
        CInfernoHook.UnregisterListeners();
        CInfoSpawnGroupLoadUnloadHook.UnregisterListeners();
        CItemHook.UnregisterListeners();
        CItemDefuserHook.UnregisterListeners();
        CItemGenericHook.UnregisterListeners();
        CLogicActiveAutosaveHook.UnregisterListeners();
        CLogicDistanceAutosaveHook.UnregisterListeners();
        CLogicGameStateReportHook.UnregisterListeners();
        CLogicMeasureMovementHook.UnregisterListeners();
        CLogicNPCCounterHook.UnregisterListeners();
        CMapVetoPickControllerHook.UnregisterListeners();
        CMomentaryRotButtonHook.UnregisterListeners();
        CMultiLightProxyHook.UnregisterListeners();
        CMultiSourceHook.UnregisterListeners();
        CParticleSystemHook.UnregisterListeners();
        CPathMoverEntitySpawnerHook.UnregisterListeners();
        CPathNodeHook.UnregisterListeners();
        CPhysForceHook.UnregisterListeners();
        CPhysHingeHook.UnregisterListeners();
        CPhysImpactHook.UnregisterListeners();
        CPhysSlideConstraintHook.UnregisterListeners();
        CPhysicsPropHook.UnregisterListeners();
        CPhysicsPropRespawnableHook.UnregisterListeners();
        CPlantedC4Hook.UnregisterListeners();
        CPointCommentaryNodeHook.UnregisterListeners();
        CPointHurtHook.UnregisterListeners();
        CPointOrientHook.UnregisterListeners();
        CPointPushHook.UnregisterListeners();
        CPointValueRemapperHook.UnregisterListeners();
        CRagdollPropHook.UnregisterListeners();
        CRevertSavedHook.UnregisterListeners();
        CScriptedSequenceHook.UnregisterListeners();
        CSmokeGrenadeProjectileHook.UnregisterListeners();
        CSoundEventConeEntityHook.UnregisterListeners();
        CSoundEventEntityHook.UnregisterListeners();
        CSoundEventOBBEntityHook.UnregisterListeners();
        CSoundEventPathCornerEntityHook.UnregisterListeners();
        CSoundEventSphereEntityHook.UnregisterListeners();
        CSoundOpvarSetAutoRoomEntityHook.UnregisterListeners();
        CSoundOpvarSetBoxEntityHook.UnregisterListeners();
        CSoundOpvarSetOBBWindEntityHook.UnregisterListeners();
        CSoundOpvarSetPathCornerEntityHook.UnregisterListeners();
        CSoundOpvarSetPointBaseHook.UnregisterListeners();
        CSoundOpvarSetPointEntityHook.UnregisterListeners();
        CSplineConstraintHook.UnregisterListeners();
        CSpriteHook.UnregisterListeners();
        CTriggerActiveWeaponDetectHook.UnregisterListeners();
        CTriggerFanHook.UnregisterListeners();
        CTriggerHurtHook.UnregisterListeners();
        CTriggerImpactHook.UnregisterListeners();
        CTriggerLerpObjectHook.UnregisterListeners();
        CTriggerLookHook.UnregisterListeners();
        CTriggerMultipleHook.UnregisterListeners();
        CTriggerProximityHook.UnregisterListeners();
        CTriggerSaveHook.UnregisterListeners();
        CTriggerSndSosOpvarHook.UnregisterListeners();
        CTriggerSoundscapeHook.UnregisterListeners();
        CVoteControllerHook.UnregisterListeners();
        CWaterBulletHook.UnregisterListeners();
    }
}