using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal static class ClassConvertor
{
    public static readonly HashSet<string> DesignerNames =
    [
        "ai_changehintgroup",
        "ambient_generic",
        "baseanimating",
        "baseanimgraph",
        "basemodelentity",
        "baseplayerpawn",
        "beam",
        "cable_dynamic",
        "cash_stack",
        "chicken",
        "citadel_snd_opvar_set_obb",
        "color_correction",
        "color_correction_volume",
        "commentary_auto",
        "cs_gamerules",
        "cs_minimap_boundary",
        "cs_pet_placement",
        "cs_player_camera",
        "cs_player_controller",
        "cs_player_manager",
        "cs_team_manager",
        "custom_hud_layout",
        "decoy_projectile",
        "dynamic_prop",
        "end_of_match_lineup_end",
        "end_of_match_lineup_start",
        "entity_blocker",
        "entityflame",
        "env_beam",
        "env_beverage",
        "env_blood",
        "env_combined_light_probe_volume",
        "env_credits",
        "env_cs_place",
        "env_cubemap",
        "env_cubemap_box",
        "env_cubemap_fog",
        "env_debughistory",
        "env_decal",
        "env_detail_controller",
        "env_entity_dissolver",
        "env_entity_igniter",
        "env_entity_maker",
        "env_explosion",
        "env_fade",
        "env_fog_controller",
        "env_global",
        "env_glow",
        "env_gradient_fog",
        "env_hudhint",
        "env_instructor_hint",
        "env_instructor_vr_hint",
        "env_laser",
        "env_light_probe_volume",
        "env_message",
        "env_muzzleflash",
        "env_particle_glow",
        "env_physexplosion",
        "env_physimpact",
        "env_physwire",
        "env_player_visibility",
        "env_shake",
        "env_sky",
        "env_soundscape",
        "env_soundscape_proxy",
        "env_soundscape_triggerable",
        "env_spark",
        "env_splash",
        "env_sprite",
        "env_sprite_clientside",
        "env_sprite_oriented",
        "env_tilt",
        "env_tonemap_controller",
        "env_tonemap_controller2",
        "env_viewpunch",
        "env_volumetric_fog_controller",
        "env_volumetric_fog_volume",
        "env_wind",
        "env_wind_controller",
        "env_wind_volume",
        "filter_activator_attribute_int",
        "filter_activator_class",
        "filter_activator_context",
        "filter_activator_mass_greater",
        "filter_activator_model",
        "filter_activator_name",
        "filter_activator_team",
        "filter_base",
        "filter_damage_type",
        "filter_enemy",
        "filter_health",
        "filter_los",
        "filter_multi",
        "filter_proximity",
        "fish",
        "flashbang_projectile",
        "fog_volume",
        "func_bomb_target",
        "func_breakable",
        "func_brush",
        "func_button",
        "func_buyzone",
        "func_clip_interaction_layer",
        "func_clip_vphysics",
        "func_combined_light_probe_volume",
        "func_conveyor",
        "func_door",
        "func_door_rotating",
        "func_electrified_volume",
        "func_fish_pool",
        "func_footstep_control",
        "func_guntarget",
        "func_hostage_rescue",
        "func_illusionary",
        "func_ladder",
        "func_monitor",
        "func_movelinear",
        "func_mover",
        "func_mover_router",
        "func_nav_avoidance_obstacle",
        "func_nav_blocker",
        "func_nav_dynamic_connections",
        "func_nav_markup",
        "func_nav_markup_game",
        "func_physbox",
        "func_physical_button",
        "func_plat",
        "func_platrot",
        "func_precipitation",
        "func_precipitation_blocker",
        "func_proprrespawnzone",
        "func_pushable",
        "func_retakebarrier",
        "func_rot_button",
        "func_rotating",
        "func_rotator",
        "func_shatterglass",
        "func_tanktrain",
        "func_timescale",
        "func_trackautochange",
        "func_trackchange",
        "func_tracktrain",
        "func_train",
        "func_traincontrols",
        "func_useableladder",
        "func_vehicleclip",
        "func_wall",
        "func_wall_toggle",
        "func_water",
        "game_end",
        "game_gib_manager",
        "game_money",
        "game_player_equip",
        "game_ragdoll_manager",
        "game_text",
        "game_zone_player",
        "grenade",
        "handle_dummy",
        "handle_test",
        "hegrenade_projectile",
        "hl_vr_texture_based_animatable",
        "hostage_entity",
        "inferno",
        "info_bomb_target_hint_A",
        "info_bomb_target_hint_B",
        "info_choreo_anchor",
        "info_constraint_anchor",
        "info_data",
        "info_deathmatch_spawn",
        "info_dynamic_shadow_hint",
        "info_dynamic_shadow_hint_box",
        "info_game_event_proxy",
        "info_hostage_rescue_zone_hint",
        "info_hostage_spawn",
        "info_ladder_dismount",
        "info_landmark",
        "info_map_parameters",
        "info_nav_space",
        "info_null",
        "info_offscreen_panorama_texture",
        "info_particle_system",
        "info_particle_target",
        "info_player_counterterrorist",
        "info_player_deathmatch",
        "info_player_ping",
        "info_player_start",
        "info_player_terrorist",
        "info_spawngroup_landmark",
        "info_spawngroup_load_unload",
        "info_target",
        "info_target_choreo",
        "info_target_instructor_hint",
        "info_target_server_only",
        "info_teleport_destination",
        "info_trigger_fan",
        "info_visibility_box",
        "info_world_layer",
        "instanced_scripted_scene",
        "item_assaultsuit",
        "item_cutters",
        "item_defuser",
        "item_generic",
        "item_generic_trigger_helper",
        "item_kevlar",
        "item_sodacan",
        "keyframe_rope",
        "keyframe_track",
        "light_barn",
        "light_directional",
        "light_dynamic",
        "light_environment",
        "light_omni",
        "light_omni2",
        "light_ortho",
        "light_rect",
        "light_spot",
        "logic_achievement",
        "logic_active_autosave",
        "logic_activityevent",
        "logic_auto",
        "logic_autosave",
        "logic_branch",
        "logic_branch_listener",
        "logic_case",
        "logic_choreographed_scene",
        "logic_collision_pair",
        "logic_compare",
        "logic_distance_autosave",
        "logic_distance_check",
        "logic_eventlistener",
        "logic_game_event",
        "logic_gameevent_listener",
        "logic_gamestate_report",
        "logic_lineto",
        "logic_measure_movement",
        "logic_multilight_proxy",
        "logic_navigation",
        "logic_npc_counter_aabb",
        "logic_npc_counter_obb",
        "logic_npc_counter_radius",
        "logic_playerproxy",
        "logic_proximity",
        "logic_relay",
        "logic_scene_list_manager",
        "logic_script",
        "logic_timer",
        "map_shared_environment",
        "mapvetopick_controller",
        "markup_volume",
        "markup_volume_tagged",
        "markup_volume_with_ref",
        "math_colorblend",
        "math_counter",
        "math_remap",
        "molotov_projectile",
        "momentary_door",
        "momentary_rot_button",
        "move_keyframed",
        "move_rope",
        "multisource",
        "observer",
        "path_corner",
        "path_corner_crash",
        "path_mover",
        "path_mover_entity_spawner",
        "path_node",
        "path_node_mover",
        "path_particle_rope",
        "path_particle_rope_clientside",
        "path_simple",
        "path_track",
        "path_with_dynamic_nodes",
        "phys_ballsocket",
        "phys_constraint",
        "phys_genericconstraint",
        "phys_hinge",
        "phys_hinge_local",
        "phys_keepupright",
        "phys_lengthconstraint",
        "phys_magnet",
        "phys_motor",
        "phys_pulleyconstraint",
        "phys_ragdollconstraint",
        "phys_ragdollmagnet",
        "phys_slideconstraint",
        "phys_splineconstraint",
        "phys_spring",
        "phys_thruster",
        "phys_torque",
        "phys_wheelconstraint",
        "physics_entity_solver",
        "physics_prop_ragdoll",
        "planted_c4",
        "plat_trigger",
        "player",
        "player_controller",
        "player_loadsaved",
        "player_pawn_base",
        "player_spray_decal",
        "point_anglesensor",
        "point_angularvelocitysensor",
        "point_broadcastclientcommand",
        "point_camera",
        "point_camera_vertical_fov",
        "point_childmodifier",
        "point_clientcommand",
        "point_clientui_dialog",
        "point_clientui_world_panel",
        "point_clientui_world_text_panel",
        "point_commentary_node",
        "point_commentary_viewpoint",
        "point_enable_motion_fixup",
        "point_entity",
        "point_entity_finder",
        "point_gamestats_counter",
        "point_give_ammo",
        "point_hurt",
        "point_instructor_event",
        "point_message",
        "point_nav_walkable",
        "point_orient",
        "point_prefab",
        "point_proximity_sensor",
        "point_pulse",
        "point_push",
        "point_script",
        "point_servercommand",
        "point_soundevent",
        "point_teleport",
        "point_template",
        "point_value_remapper",
        "point_velocitysensor",
        "point_worldtext",
        "post_processing_volume",
        "prop_door_rotating",
        "prop_dynamic",
        "prop_dynamic_ornament",
        "prop_dynamic_override",
        "prop_physics",
        "prop_physics_multiplayer",
        "prop_physics_override",
        "prop_physics_respawnable",
        "prop_ragdoll",
        "prop_ragdoll_attached",
        "pulse_game_blackboard",
        "root",
        "rotator_target",
        "script_nav_blocker",
        "script_trigger_hurt",
        "script_trigger_multiple",
        "script_trigger_once",
        "script_trigger_push",
        "scripted_item_drop",
        "scripted_scene",
        "scripted_sequence",
        "shatterglass_shard",
        "sky_camera",
        "skybox_reference",
        "smokegrenade_projectile",
        "snd_event_alignedbox",
        "snd_event_cone",
        "snd_event_orientedbox",
        "snd_event_param",
        "snd_event_path_corner",
        "snd_event_point",
        "snd_event_sphere",
        "snd_opvar_set",
        "snd_opvar_set_aabb",
        "snd_opvar_set_auto_room",
        "snd_opvar_set_box_base",
        "snd_opvar_set_obb",
        "snd_opvar_set_path_corner",
        "snd_opvar_set_point",
        "snd_opvar_set_point_base",
        "snd_opvar_set_wind_obb",
        "snd_sound_area_base",
        "snd_sound_area_obb",
        "snd_sound_area_sphere",
        "snd_soundscape",
        "snd_soundscape_proxy",
        "snd_soundscape_triggerable",
        "snd_stack_save",
        "spark_shower",
        "spawnpoint",
        "spotlight_end",
        "tanktrain_ai",
        "tanktrain_aitarget",
        "team_intro_counterterrorist",
        "team_intro_terrorist",
        "team_manager",
        "team_preview_character_position",
        "team_select_counterterrorist",
        "team_select_terrorist",
        "test_effect",
        "test_io_combinations",
        "trigger",
        "trigger_active_weapon_detect",
        "trigger_autosave",
        "trigger_bomb_reset",
        "trigger_brush",
        "trigger_buoyancy",
        "trigger_callback",
        "trigger_changelevel",
        "trigger_detect_bullet_fire",
        "trigger_detect_explosion",
        "trigger_fan",
        "trigger_fog",
        "trigger_game_event",
        "trigger_gravity",
        "trigger_hostage_reset",
        "trigger_hurt",
        "trigger_impact",
        "trigger_lerp_object",
        "trigger_look",
        "trigger_multiple",
        "trigger_once",
        "trigger_physics",
        "trigger_proximity",
        "trigger_push",
        "trigger_remove",
        "trigger_serverragdoll",
        "trigger_snd_sos_opvar",
        "trigger_soundscape",
        "trigger_teleport",
        "trigger_tonemap",
        "trigger_transition",
        "vote_controller",
        "waterbullet",
        "weapon_ak47",
        "weapon_aug",
        "weapon_awp",
        "weapon_basecsgrenade",
        "weapon_bizon",
        "weapon_c4",
        "weapon_cs_base",
        "weapon_csbase",
        "weapon_cz75a",
        "weapon_deagle",
        "weapon_decoy",
        "weapon_elite",
        "weapon_famas",
        "weapon_fiveseven",
        "weapon_flashbang",
        "weapon_g3sg1",
        "weapon_galilar",
        "weapon_glock",
        "weapon_healthshot",
        "weapon_hegrenade",
        "weapon_hkp2000",
        "weapon_incgrenade",
        "weapon_knife",
        "weapon_m249",
        "weapon_m4a1",
        "weapon_m4a1_silencer",
        "weapon_mac10",
        "weapon_mag7",
        "weapon_molotov",
        "weapon_mp5sd",
        "weapon_mp7",
        "weapon_mp9",
        "weapon_negev",
        "weapon_nova",
        "weapon_p250",
        "weapon_p90",
        "weapon_revolver",
        "weapon_sawedoff",
        "weapon_scar20",
        "weapon_sg556",
        "weapon_smokegrenade",
        "weapon_ssg08",
        "weapon_taser",
        "weapon_tec9",
        "weapon_ump45",
        "weapon_usp_silencer",
        "weapon_xm1014",
        "wearable_item",
        "wingman_intro_counterterrorist",
        "wingman_intro_terrorist",
        "worldent",
    ];

    public static CEntityInstance ConvertEntityByDesignerName( nint address, string designerName )
    {
        return designerName switch
        {
            "ai_changehintgroup" => new CAI_ChangeHintGroupImpl(address),
            "ambient_generic" => new CAmbientGenericImpl(address),
            "baseanimating" => new CBaseAnimGraphImpl(address),
            "baseanimgraph" => new CBaseAnimGraphImpl(address),
            "basemodelentity" => new CBaseModelEntityImpl(address),
            "baseplayerpawn" => new CBasePlayerPawnImpl(address),
            "beam" => new CBeamImpl(address),
            "cable_dynamic" => new CDynamicPropImpl(address),
            "cash_stack" => new CCashStackImpl(address),
            "chicken" => new CChickenImpl(address),
            "citadel_snd_opvar_set_obb" => new CCitadelSoundOpvarSetOBBImpl(address),
            "color_correction" => new CColorCorrectionImpl(address),
            "color_correction_volume" => new CColorCorrectionVolumeImpl(address),
            "commentary_auto" => new CCommentaryAutoImpl(address),
            "cs_gamerules" => new CCSGameRulesProxyImpl(address),
            "cs_minimap_boundary" => new CCSMinimapBoundaryImpl(address),
            "cs_pet_placement" => new CCSPetPlacementImpl(address),
            "cs_player_camera" => new CCSPlayerCameraImpl(address),
            "cs_player_controller" => new CCSPlayerControllerImpl(address),
            "cs_player_manager" => new CCSPlayerResourceImpl(address),
            "cs_team_manager" => new CCSTeamImpl(address),
            "custom_hud_layout" => new CCSCustomHudLayoutImpl(address),
            "decoy_projectile" => new CDecoyProjectileImpl(address),
            "dynamic_prop" => new CDynamicPropImpl(address),
            "end_of_match_lineup_end" => new CCSGO_EndOfMatchLineupEndImpl(address),
            "end_of_match_lineup_start" => new CCSGO_EndOfMatchLineupStartImpl(address),
            "entity_blocker" => new CEntityBlockerImpl(address),
            "entityflame" => new CEntityFlameImpl(address),
            "env_beam" => new CEnvBeamImpl(address),
            "env_beverage" => new CEnvBeverageImpl(address),
            "env_blood" => new CBloodImpl(address),
            "env_combined_light_probe_volume" => new CEnvCombinedLightProbeVolumeImpl(address),
            "env_credits" => new CCreditsImpl(address),
            "env_cs_place" => new CCSPlaceImpl(address),
            "env_cubemap" => new CEnvCubemapImpl(address),
            "env_cubemap_box" => new CEnvCubemapBoxImpl(address),
            "env_cubemap_fog" => new CEnvCubemapFogImpl(address),
            "env_debughistory" => new CDebugHistoryImpl(address),
            "env_decal" => new CEnvDecalImpl(address),
            "env_detail_controller" => new CEnvDetailControllerImpl(address),
            "env_entity_dissolver" => new CEntityDissolveImpl(address),
            "env_entity_igniter" => new CEnvEntityIgniterImpl(address),
            "env_entity_maker" => new CEnvEntityMakerImpl(address),
            "env_explosion" => new CEnvExplosionImpl(address),
            "env_fade" => new CEnvFadeImpl(address),
            "env_fog_controller" => new CFogControllerImpl(address),
            "env_global" => new CEnvGlobalImpl(address),
            "env_glow" => new CSpriteImpl(address),
            "env_gradient_fog" => new CGradientFogImpl(address),
            "env_hudhint" => new CEnvHudHintImpl(address),
            "env_instructor_hint" => new CEnvInstructorHintImpl(address),
            "env_instructor_vr_hint" => new CEnvInstructorVRHintImpl(address),
            "env_laser" => new CEnvLaserImpl(address),
            "env_light_probe_volume" => new CEnvLightProbeVolumeImpl(address),
            "env_message" => new CMessageImpl(address),
            "env_muzzleflash" => new CEnvMuzzleFlashImpl(address),
            "env_particle_glow" => new CEnvParticleGlowImpl(address),
            "env_physexplosion" => new CPhysExplosionImpl(address),
            "env_physimpact" => new CPhysImpactImpl(address),
            "env_physwire" => new CPhysicsWireImpl(address),
            "env_player_visibility" => new CPlayerVisibilityImpl(address),
            "env_shake" => new CEnvShakeImpl(address),
            "env_sky" => new CEnvSkyImpl(address),
            "env_soundscape" => new CEnvSoundscapeImpl(address),
            "env_soundscape_proxy" => new CEnvSoundscapeProxyImpl(address),
            "env_soundscape_triggerable" => new CEnvSoundscapeTriggerableImpl(address),
            "env_spark" => new CEnvSparkImpl(address),
            "env_splash" => new CEnvSplashImpl(address),
            "env_sprite" => new CSpriteImpl(address),
            "env_sprite_clientside" => new CCSSpriteImpl(address),
            "env_sprite_oriented" => new CSpriteOrientedImpl(address),
            "env_tilt" => new CEnvTiltImpl(address),
            "env_tonemap_controller" => new CTonemapController2Impl(address),
            "env_tonemap_controller2" => new CTonemapController2Impl(address),
            "env_viewpunch" => new CEnvViewPunchImpl(address),
            "env_volumetric_fog_controller" => new CEnvVolumetricFogControllerImpl(address),
            "env_volumetric_fog_volume" => new CEnvVolumetricFogVolumeImpl(address),
            "env_wind" => new CEnvWindImpl(address),
            "env_wind_controller" => new CEnvWindControllerImpl(address),
            "env_wind_volume" => new CEnvWindVolumeImpl(address),
            "filter_activator_attribute_int" => new CFilterAttributeIntImpl(address),
            "filter_activator_class" => new CFilterClassImpl(address),
            "filter_activator_context" => new CFilterContextImpl(address),
            "filter_activator_mass_greater" => new CFilterMassGreaterImpl(address),
            "filter_activator_model" => new CFilterModelImpl(address),
            "filter_activator_name" => new CFilterNameImpl(address),
            "filter_activator_team" => new CFilterTeamImpl(address),
            "filter_base" => new CBaseFilterImpl(address),
            "filter_damage_type" => new FilterDamageTypeImpl(address),
            "filter_enemy" => new CFilterEnemyImpl(address),
            "filter_health" => new FilterHealthImpl(address),
            "filter_los" => new CFilterLOSImpl(address),
            "filter_multi" => new CFilterMultipleImpl(address),
            "filter_proximity" => new CFilterProximityImpl(address),
            "fish" => new CFishImpl(address),
            "flashbang_projectile" => new CFlashbangProjectileImpl(address),
            "fog_volume" => new CFogVolumeImpl(address),
            "func_bomb_target" => new CBombTargetImpl(address),
            "func_breakable" => new CBreakableImpl(address),
            "func_brush" => new CFuncBrushImpl(address),
            "func_button" => new CBaseButtonImpl(address),
            "func_buyzone" => new CBuyZoneImpl(address),
            "func_clip_interaction_layer" => new CFuncInteractionLayerClipImpl(address),
            "func_clip_vphysics" => new CFuncVPhysicsClipImpl(address),
            "func_combined_light_probe_volume" => new CEnvCombinedLightProbeVolumeImpl(address),
            "func_conveyor" => new CFuncConveyorImpl(address),
            "func_door" => new CBaseDoorImpl(address),
            "func_door_rotating" => new CRotDoorImpl(address),
            "func_electrified_volume" => new CFuncElectrifiedVolumeImpl(address),
            "func_fish_pool" => new CFishPoolImpl(address),
            "func_footstep_control" => new CFootstepControlImpl(address),
            "func_guntarget" => new CGunTargetImpl(address),
            "func_hostage_rescue" => new CHostageRescueZoneImpl(address),
            "func_illusionary" => new CFuncIllusionaryImpl(address),
            "func_ladder" => new CFuncLadderImpl(address),
            "func_monitor" => new CFuncMonitorImpl(address),
            "func_movelinear" => new CFuncMoveLinearImpl(address),
            "func_mover" => new CFuncMoverImpl(address),
            "func_mover_router" => new CFuncMoverRouterImpl(address),
            "func_nav_avoidance_obstacle" => new CFuncNavObstructionImpl(address),
            "func_nav_blocker" => new CFuncNavBlockerImpl(address),
            "func_nav_dynamic_connections" => new CDynamicNavConnectionsVolumeImpl(address),
            "func_nav_markup" => new CMarkupVolumeTagged_NavImpl(address),
            "func_nav_markup_game" => new CMarkupVolumeTagged_NavGameImpl(address),
            "func_physbox" => new CPhysBoxImpl(address),
            "func_physical_button" => new CPhysicalButtonImpl(address),
            "func_plat" => new CFuncPlatImpl(address),
            "func_platrot" => new CFuncPlatRotImpl(address),
            "func_precipitation" => new CPrecipitationImpl(address),
            "func_precipitation_blocker" => new CPrecipitationBlockerImpl(address),
            "func_proprrespawnzone" => new CFuncPropRespawnZoneImpl(address),
            "func_pushable" => new CPushableImpl(address),
            "func_retakebarrier" => new CFuncRetakeBarrierImpl(address),
            "func_rot_button" => new CRotButtonImpl(address),
            "func_rotating" => new CFuncRotatingImpl(address),
            "func_rotator" => new CFuncRotatorImpl(address),
            "func_shatterglass" => new CFuncShatterglassImpl(address),
            "func_tanktrain" => new CFuncTankTrainImpl(address),
            "func_timescale" => new CFuncTimescaleImpl(address),
            "func_trackautochange" => new CFuncTrackAutoImpl(address),
            "func_trackchange" => new CFuncTrackChangeImpl(address),
            "func_tracktrain" => new CFuncTrackTrainImpl(address),
            "func_train" => new CFuncTrainImpl(address),
            "func_traincontrols" => new CFuncTrainControlsImpl(address),
            "func_useableladder" => new CFuncLadderImpl(address),
            "func_vehicleclip" => new CFuncVehicleClipImpl(address),
            "func_wall" => new CFuncWallImpl(address),
            "func_wall_toggle" => new CFuncWallToggleImpl(address),
            "func_water" => new CFuncWaterImpl(address),
            "game_end" => new CGameEndImpl(address),
            "game_gib_manager" => new CGameGibManagerImpl(address),
            "game_money" => new CGameMoneyImpl(address),
            "game_player_equip" => new CGamePlayerEquipImpl(address),
            "game_ragdoll_manager" => new CRagdollManagerImpl(address),
            "game_text" => new CGameTextImpl(address),
            "game_zone_player" => new CGamePlayerZoneImpl(address),
            "grenade" => new CBaseGrenadeImpl(address),
            "handle_dummy" => new CHandleDummyImpl(address),
            "handle_test" => new CHandleTestImpl(address),
            "hegrenade_projectile" => new CHEGrenadeProjectileImpl(address),
            "hl_vr_texture_based_animatable" => new CTextureBasedAnimatableImpl(address),
            "hostage_entity" => new CHostageImpl(address),
            "inferno" => new CInfernoImpl(address),
            "info_bomb_target_hint_A" => new CInfoInstructorHintBombTargetAImpl(address),
            "info_bomb_target_hint_B" => new CInfoInstructorHintBombTargetBImpl(address),
            "info_choreo_anchor" => new CInfoChoreoAnchorImpl(address),
            "info_constraint_anchor" => new CConstraintAnchorImpl(address),
            "info_data" => new CInfoDataImpl(address),
            "info_deathmatch_spawn" => new CInfoDeathmatchSpawnImpl(address),
            "info_dynamic_shadow_hint" => new CInfoDynamicShadowHintImpl(address),
            "info_dynamic_shadow_hint_box" => new CInfoDynamicShadowHintBoxImpl(address),
            "info_game_event_proxy" => new CInfoGameEventProxyImpl(address),
            "info_hostage_rescue_zone_hint" => new CInfoInstructorHintHostageRescueZoneImpl(address),
            "info_hostage_spawn" => new CHostageImpl(address),
            "info_ladder_dismount" => new CInfoLadderDismountImpl(address),
            "info_landmark" => new CInfoLandmarkImpl(address),
            "info_map_parameters" => new CMapInfoImpl(address),
            "info_nav_space" => new CNavSpaceInfoImpl(address),
            "info_null" => new CNullEntityImpl(address),
            "info_offscreen_panorama_texture" => new CInfoOffscreenPanoramaTextureImpl(address),
            "info_particle_system" => new CParticleSystemImpl(address),
            "info_particle_target" => new CInfoParticleTargetImpl(address),
            "info_player_counterterrorist" => new CInfoPlayerCounterterroristImpl(address),
            "info_player_deathmatch" => new CBaseDMStartImpl(address),
            "info_player_ping" => new CPlayerPingImpl(address),
            "info_player_start" => new CInfoPlayerStartImpl(address),
            "info_player_terrorist" => new CInfoPlayerTerroristImpl(address),
            "info_spawngroup_landmark" => new CInfoSpawnGroupLandmarkImpl(address),
            "info_spawngroup_load_unload" => new CInfoSpawnGroupLoadUnloadImpl(address),
            "info_target" => new CInfoTargetImpl(address),
            "info_target_choreo" => new CChoreoInfoTargetImpl(address),
            "info_target_instructor_hint" => new CInfoInstructorHintTargetImpl(address),
            "info_target_server_only" => new CInfoTargetServerOnlyImpl(address),
            "info_teleport_destination" => new CInfoTeleportDestinationImpl(address),
            "info_trigger_fan" => new CInfoFanImpl(address),
            "info_visibility_box" => new CInfoVisibilityBoxImpl(address),
            "info_world_layer" => new CInfoWorldLayerImpl(address),
            "instanced_scripted_scene" => new CInstancedSceneEntityImpl(address),
            "item_assaultsuit" => new CItemAssaultSuitImpl(address),
            "item_cutters" => new CItemDefuserImpl(address),
            "item_defuser" => new CItemDefuserImpl(address),
            "item_generic" => new CItemGenericImpl(address),
            "item_generic_trigger_helper" => new CItemGenericTriggerHelperImpl(address),
            "item_kevlar" => new CItemKevlarImpl(address),
            "item_sodacan" => new CItemSodaImpl(address),
            "keyframe_rope" => new CRopeKeyframeImpl(address),
            "keyframe_track" => new CPathKeyFrameImpl(address),
            "light_barn" => new CBarnLightImpl(address),
            "light_directional" => new CLightDirectionalEntityImpl(address),
            "light_dynamic" => new CDynamicLightImpl(address),
            "light_environment" => new CLightEnvironmentEntityImpl(address),
            "light_omni" => new CLightEntityImpl(address),
            "light_omni2" => new COmniLightImpl(address),
            "light_ortho" => new CLightOrthoEntityImpl(address),
            "light_rect" => new CRectLightImpl(address),
            "light_spot" => new CLightSpotEntityImpl(address),
            "logic_achievement" => new CLogicAchievementImpl(address),
            "logic_active_autosave" => new CLogicActiveAutosaveImpl(address),
            "logic_activityevent" => new CLogicActivityEventImpl(address),
            "logic_auto" => new CLogicAutoImpl(address),
            "logic_autosave" => new CLogicAutosaveImpl(address),
            "logic_branch" => new CLogicBranchImpl(address),
            "logic_branch_listener" => new CLogicBranchListImpl(address),
            "logic_case" => new CLogicCaseImpl(address),
            "logic_choreographed_scene" => new CSceneEntityImpl(address),
            "logic_collision_pair" => new CLogicCollisionPairImpl(address),
            "logic_compare" => new CLogicCompareImpl(address),
            "logic_distance_autosave" => new CLogicDistanceAutosaveImpl(address),
            "logic_distance_check" => new CLogicDistanceCheckImpl(address),
            "logic_eventlistener" => new CLogicEventListenerImpl(address),
            "logic_game_event" => new CLogicGameEventImpl(address),
            "logic_gameevent_listener" => new CLogicGameEventListenerImpl(address),
            "logic_gamestate_report" => new CLogicGameStateReportImpl(address),
            "logic_lineto" => new CLogicLineToEntityImpl(address),
            "logic_measure_movement" => new CLogicMeasureMovementImpl(address),
            "logic_multilight_proxy" => new CMultiLightProxyImpl(address),
            "logic_navigation" => new CLogicNavigationImpl(address),
            "logic_npc_counter_aabb" => new CLogicNPCCounterAABBImpl(address),
            "logic_npc_counter_obb" => new CLogicNPCCounterOBBImpl(address),
            "logic_npc_counter_radius" => new CLogicNPCCounterImpl(address),
            "logic_playerproxy" => new CLogicPlayerProxyImpl(address),
            "logic_proximity" => new CLogicProximityImpl(address),
            "logic_relay" => new CLogicRelayImpl(address),
            "logic_scene_list_manager" => new CSceneListManagerImpl(address),
            "logic_script" => new CLogicScriptImpl(address),
            "logic_timer" => new CTimerEntityImpl(address),
            "map_shared_environment" => new CMapSharedEnvironmentImpl(address),
            "mapvetopick_controller" => new CMapVetoPickControllerImpl(address),
            "markup_volume" => new CMarkupVolumeImpl(address),
            "markup_volume_tagged" => new CSimpleMarkupVolumeTaggedImpl(address),
            "markup_volume_with_ref" => new CMarkupVolumeWithRefImpl(address),
            "math_colorblend" => new CMathColorBlendImpl(address),
            "math_counter" => new CMathCounterImpl(address),
            "math_remap" => new CMathRemapImpl(address),
            "molotov_projectile" => new CMolotovProjectileImpl(address),
            "momentary_door" => new CFuncMoveLinearImpl(address),
            "momentary_rot_button" => new CMomentaryRotButtonImpl(address),
            "move_keyframed" => new CBaseMoveBehaviorImpl(address),
            "move_rope" => new CRopeKeyframeImpl(address),
            "multisource" => new CMultiSourceImpl(address),
            "observer" => new CCSObserverPawnImpl(address),
            "path_corner" => new CPathCornerImpl(address),
            "path_corner_crash" => new CPathCornerCrashImpl(address),
            "path_mover" => new CPathMoverImpl(address),
            "path_mover_entity_spawner" => new CPathMoverEntitySpawnerImpl(address),
            "path_node" => new CPathNodeImpl(address),
            "path_node_mover" => new CMoverPathNodeImpl(address),
            "path_particle_rope" => new CPathParticleRopeImpl(address),
            "path_particle_rope_clientside" => new CPathParticleRopeImpl(address),
            "path_simple" => new CPathSimpleImpl(address),
            "path_track" => new CPathTrackImpl(address),
            "path_with_dynamic_nodes" => new CPathWithDynamicNodesImpl(address),
            "phys_ballsocket" => new CPhysBallSocketImpl(address),
            "phys_constraint" => new CPhysFixedImpl(address),
            "phys_genericconstraint" => new CGenericConstraintImpl(address),
            "phys_hinge" => new CPhysHingeImpl(address),
            "phys_hinge_local" => new CPhysHingeImpl(address),
            "phys_keepupright" => new CKeepUprightImpl(address),
            "phys_lengthconstraint" => new CPhysLengthImpl(address),
            "phys_magnet" => new CPhysMagnetImpl(address),
            "phys_motor" => new CPhysMotorImpl(address),
            "phys_pulleyconstraint" => new CPhysPulleyImpl(address),
            "phys_ragdollconstraint" => new CRagdollConstraintImpl(address),
            "phys_ragdollmagnet" => new CRagdollMagnetImpl(address),
            "phys_slideconstraint" => new CPhysSlideConstraintImpl(address),
            "phys_splineconstraint" => new CSplineConstraintImpl(address),
            "phys_spring" => new CPhysicsSpringImpl(address),
            "phys_thruster" => new CPhysThrusterImpl(address),
            "phys_torque" => new CPhysTorqueImpl(address),
            "phys_wheelconstraint" => new CPhysWheelConstraintImpl(address),
            "physics_entity_solver" => new CPhysicsEntitySolverImpl(address),
            "physics_prop_ragdoll" => new CRagdollPropImpl(address),
            "planted_c4" => new CPlantedC4Impl(address),
            "plat_trigger" => new CPlatTriggerImpl(address),
            "player" => new CCSPlayerPawnImpl(address),
            "player_controller" => new CBasePlayerControllerImpl(address),
            "player_loadsaved" => new CRevertSavedImpl(address),
            "player_pawn_base" => new CCSPlayerPawnBaseImpl(address),
            "player_spray_decal" => new CPlayerSprayDecalImpl(address),
            "point_anglesensor" => new CPointAngleSensorImpl(address),
            "point_angularvelocitysensor" => new CPointAngularVelocitySensorImpl(address),
            "point_broadcastclientcommand" => new CPointBroadcastClientCommandImpl(address),
            "point_camera" => new CPointCameraImpl(address),
            "point_camera_vertical_fov" => new CPointCameraVFOVImpl(address),
            "point_childmodifier" => new CPointChildModifierImpl(address),
            "point_clientcommand" => new CPointClientCommandImpl(address),
            "point_clientui_dialog" => new CPointClientUIDialogImpl(address),
            "point_clientui_world_panel" => new CPointClientUIWorldPanelImpl(address),
            "point_clientui_world_text_panel" => new CPointClientUIWorldTextPanelImpl(address),
            "point_commentary_node" => new CPointCommentaryNodeImpl(address),
            "point_commentary_viewpoint" => new CCommentaryViewPositionImpl(address),
            "point_enable_motion_fixup" => new CEnableMotionFixupImpl(address),
            "point_entity" => new CPointEntityImpl(address),
            "point_entity_finder" => new CPointEntityFinderImpl(address),
            "point_gamestats_counter" => new CPointGamestatsCounterImpl(address),
            "point_give_ammo" => new CPointGiveAmmoImpl(address),
            "point_hurt" => new CPointHurtImpl(address),
            "point_instructor_event" => new CInstructorEventEntityImpl(address),
            "point_message" => new CMessageEntityImpl(address),
            "point_nav_walkable" => new CNavWalkableImpl(address),
            "point_orient" => new CPointOrientImpl(address),
            "point_prefab" => new CPointPrefabImpl(address),
            "point_proximity_sensor" => new CPointProximitySensorImpl(address),
            "point_pulse" => new CPointPulseImpl(address),
            "point_push" => new CPointPushImpl(address),
            "point_script" => new CCSPointScriptEntityImpl(address),
            "point_servercommand" => new CPointServerCommandImpl(address),
            "point_soundevent" => new CSoundEventEntityImpl(address),
            "point_teleport" => new CPointTeleportImpl(address),
            "point_template" => new CPointTemplateImpl(address),
            "point_value_remapper" => new CPointValueRemapperImpl(address),
            "point_velocitysensor" => new CPointVelocitySensorImpl(address),
            "point_worldtext" => new CPointWorldTextImpl(address),
            "post_processing_volume" => new CPostProcessingVolumeImpl(address),
            "prop_door_rotating" => new CPropDoorRotatingBreakableImpl(address),
            "prop_dynamic" => new CDynamicPropImpl(address),
            "prop_dynamic_ornament" => new COrnamentPropImpl(address),
            "prop_dynamic_override" => new CDynamicPropImpl(address),
            "prop_physics" => new CPhysicsPropImpl(address),
            "prop_physics_multiplayer" => new CPhysicsPropMultiplayerImpl(address),
            "prop_physics_override" => new CPhysicsPropOverrideImpl(address),
            "prop_physics_respawnable" => new CPhysicsPropRespawnableImpl(address),
            "prop_ragdoll" => new CRagdollPropImpl(address),
            "prop_ragdoll_attached" => new CRagdollPropAttachedImpl(address),
            "pulse_game_blackboard" => new CPulseGameBlackboardImpl(address),
            "root" => new CEntityInstanceImpl(address),
            "rotator_target" => new CRotatorTargetImpl(address),
            "script_nav_blocker" => new CScriptNavBlockerImpl(address),
            "script_trigger_hurt" => new CScriptTriggerHurtImpl(address),
            "script_trigger_multiple" => new CScriptTriggerMultipleImpl(address),
            "script_trigger_once" => new CScriptTriggerOnceImpl(address),
            "script_trigger_push" => new CScriptTriggerPushImpl(address),
            "scripted_item_drop" => new CScriptItemImpl(address),
            "scripted_scene" => new CSceneEntityImpl(address),
            "scripted_sequence" => new CScriptedSequenceImpl(address),
            "shatterglass_shard" => new CShatterGlassShardPhysicsImpl(address),
            "sky_camera" => new CSkyCameraImpl(address),
            "skybox_reference" => new CSkyboxReferenceImpl(address),
            "smokegrenade_projectile" => new CSmokeGrenadeProjectileImpl(address),
            "snd_event_alignedbox" => new CSoundEventAABBEntityImpl(address),
            "snd_event_cone" => new CSoundEventConeEntityImpl(address),
            "snd_event_orientedbox" => new CSoundEventOBBEntityImpl(address),
            "snd_event_param" => new CSoundEventParameterImpl(address),
            "snd_event_path_corner" => new CSoundEventPathCornerEntityImpl(address),
            "snd_event_point" => new CSoundEventEntityImpl(address),
            "snd_event_sphere" => new CSoundEventSphereEntityImpl(address),
            "snd_opvar_set" => new CSoundOpvarSetEntityImpl(address),
            "snd_opvar_set_aabb" => new CSoundOpvarSetAABBEntityImpl(address),
            "snd_opvar_set_auto_room" => new CSoundOpvarSetAutoRoomEntityImpl(address),
            "snd_opvar_set_box_base" => new CSoundOpvarSetBoxEntityImpl(address),
            "snd_opvar_set_obb" => new CSoundOpvarSetOBBEntityImpl(address),
            "snd_opvar_set_path_corner" => new CSoundOpvarSetPathCornerEntityImpl(address),
            "snd_opvar_set_point" => new CSoundOpvarSetPointEntityImpl(address),
            "snd_opvar_set_point_base" => new CSoundOpvarSetPointBaseImpl(address),
            "snd_opvar_set_wind_obb" => new CSoundOpvarSetOBBWindEntityImpl(address),
            "snd_sound_area_base" => new CSoundAreaEntityBaseImpl(address),
            "snd_sound_area_obb" => new CSoundAreaEntityOrientedBoxImpl(address),
            "snd_sound_area_sphere" => new CSoundAreaEntitySphereImpl(address),
            "snd_soundscape" => new CEnvSoundscapeImpl(address),
            "snd_soundscape_proxy" => new CEnvSoundscapeProxyImpl(address),
            "snd_soundscape_triggerable" => new CEnvSoundscapeTriggerableImpl(address),
            "snd_stack_save" => new CSoundStackSaveImpl(address),
            "spark_shower" => new CShowerImpl(address),
            "spawnpoint" => new SpawnPointImpl(address),
            "spotlight_end" => new CSpotlightEndImpl(address),
            "tanktrain_ai" => new CTankTrainAIImpl(address),
            "tanktrain_aitarget" => new CTankTargetChangeImpl(address),
            "team_intro_counterterrorist" => new CCSGO_TeamIntroCounterTerroristPositionImpl(address),
            "team_intro_terrorist" => new CCSGO_TeamIntroTerroristPositionImpl(address),
            "team_manager" => new CTeamImpl(address),
            "team_preview_character_position" => new CCSGO_TeamPreviewCharacterPositionImpl(address),
            "team_select_counterterrorist" => new CCSGO_TeamSelectCounterTerroristPositionImpl(address),
            "team_select_terrorist" => new CCSGO_TeamSelectTerroristPositionImpl(address),
            "test_effect" => new CTestEffectImpl(address),
            "test_io_combinations" => new CTestPulseIOImpl(address),
            "trigger" => new CBaseTriggerImpl(address),
            "trigger_active_weapon_detect" => new CTriggerActiveWeaponDetectImpl(address),
            "trigger_autosave" => new CTriggerSaveImpl(address),
            "trigger_bomb_reset" => new CTriggerBombResetImpl(address),
            "trigger_brush" => new CTriggerBrushImpl(address),
            "trigger_buoyancy" => new CTriggerBuoyancyImpl(address),
            "trigger_callback" => new CTriggerCallbackImpl(address),
            "trigger_changelevel" => new CChangeLevelImpl(address),
            "trigger_detect_bullet_fire" => new CTriggerDetectBulletFireImpl(address),
            "trigger_detect_explosion" => new CTriggerDetectExplosionImpl(address),
            "trigger_fan" => new CTriggerFanImpl(address),
            "trigger_fog" => new CFogTriggerImpl(address),
            "trigger_game_event" => new CTriggerGameEventImpl(address),
            "trigger_gravity" => new CTriggerGravityImpl(address),
            "trigger_hostage_reset" => new CTriggerHostageResetImpl(address),
            "trigger_hurt" => new CTriggerHurtImpl(address),
            "trigger_impact" => new CTriggerImpactImpl(address),
            "trigger_lerp_object" => new CTriggerLerpObjectImpl(address),
            "trigger_look" => new CTriggerLookImpl(address),
            "trigger_multiple" => new CTriggerMultipleImpl(address),
            "trigger_once" => new CTriggerOnceImpl(address),
            "trigger_physics" => new CTriggerPhysicsImpl(address),
            "trigger_proximity" => new CTriggerProximityImpl(address),
            "trigger_push" => new CTriggerPushImpl(address),
            "trigger_remove" => new CTriggerRemoveImpl(address),
            "trigger_serverragdoll" => new CServerRagdollTriggerImpl(address),
            "trigger_snd_sos_opvar" => new CTriggerSndSosOpvarImpl(address),
            "trigger_soundscape" => new CTriggerSoundscapeImpl(address),
            "trigger_teleport" => new CTriggerTeleportImpl(address),
            "trigger_tonemap" => new CTonemapTriggerImpl(address),
            "trigger_transition" => new CTriggerVolumeImpl(address),
            "vote_controller" => new CVoteControllerImpl(address),
            "waterbullet" => new CWaterBulletImpl(address),
            "weapon_ak47" => new CAK47Impl(address),
            "weapon_aug" => new CWeaponAugImpl(address),
            "weapon_awp" => new CWeaponAWPImpl(address),
            "weapon_basecsgrenade" => new CBaseCSGrenadeImpl(address),
            "weapon_bizon" => new CWeaponBizonImpl(address),
            "weapon_c4" => new CC4Impl(address),
            "weapon_cs_base" => new CCSWeaponBaseImpl(address),
            "weapon_csbase" => new CWeaponBaseItemImpl(address),
            "weapon_cz75a" => new CWeaponCZ75aImpl(address),
            "weapon_deagle" => new CDEagleImpl(address),
            "weapon_decoy" => new CDecoyGrenadeImpl(address),
            "weapon_elite" => new CWeaponEliteImpl(address),
            "weapon_famas" => new CWeaponFamasImpl(address),
            "weapon_fiveseven" => new CWeaponFiveSevenImpl(address),
            "weapon_flashbang" => new CFlashbangImpl(address),
            "weapon_g3sg1" => new CWeaponG3SG1Impl(address),
            "weapon_galilar" => new CWeaponGalilARImpl(address),
            "weapon_glock" => new CWeaponGlockImpl(address),
            "weapon_healthshot" => new CItem_HealthshotImpl(address),
            "weapon_hegrenade" => new CHEGrenadeImpl(address),
            "weapon_hkp2000" => new CWeaponHKP2000Impl(address),
            "weapon_incgrenade" => new CIncendiaryGrenadeImpl(address),
            "weapon_knife" => new CKnifeImpl(address),
            "weapon_m249" => new CWeaponM249Impl(address),
            "weapon_m4a1" => new CWeaponM4A1Impl(address),
            "weapon_m4a1_silencer" => new CWeaponM4A1SilencerImpl(address),
            "weapon_mac10" => new CWeaponMAC10Impl(address),
            "weapon_mag7" => new CWeaponMag7Impl(address),
            "weapon_molotov" => new CMolotovGrenadeImpl(address),
            "weapon_mp5sd" => new CWeaponMP5SDImpl(address),
            "weapon_mp7" => new CWeaponMP7Impl(address),
            "weapon_mp9" => new CWeaponMP9Impl(address),
            "weapon_negev" => new CWeaponNegevImpl(address),
            "weapon_nova" => new CWeaponNOVAImpl(address),
            "weapon_p250" => new CWeaponP250Impl(address),
            "weapon_p90" => new CWeaponP90Impl(address),
            "weapon_revolver" => new CWeaponRevolverImpl(address),
            "weapon_sawedoff" => new CWeaponSawedoffImpl(address),
            "weapon_scar20" => new CWeaponSCAR20Impl(address),
            "weapon_sg556" => new CWeaponSG556Impl(address),
            "weapon_smokegrenade" => new CSmokeGrenadeImpl(address),
            "weapon_ssg08" => new CWeaponSSG08Impl(address),
            "weapon_taser" => new CWeaponTaserImpl(address),
            "weapon_tec9" => new CWeaponTec9Impl(address),
            "weapon_ump45" => new CWeaponUMP45Impl(address),
            "weapon_usp_silencer" => new CWeaponUSPSilencerImpl(address),
            "weapon_xm1014" => new CWeaponXM1014Impl(address),
            "wearable_item" => new CEconWearableImpl(address),
            "wingman_intro_counterterrorist" => new CCSGO_WingmanIntroCounterTerroristPositionImpl(address),
            "wingman_intro_terrorist" => new CCSGO_WingmanIntroTerroristPositionImpl(address),
            "worldent" => new CWorldImpl(address),
            _ => new CEntityInstanceImpl(address),
        };
    }
}