namespace SwiftlyS2.Shared.GameHooks;

public interface IGameHookDatamaps
{
    public IGameHookDatamapCAmbientGeneric CAmbientGeneric { get; }
    public IGameHookDatamapCBarnLight CBarnLight { get; }
    public IGameHookDatamapCBaseAnimGraph CBaseAnimGraph { get; }
    public IGameHookDatamapCBaseButton CBaseButton { get; }
    public IGameHookDatamapCBaseCSGrenadeProjectile CBaseCSGrenadeProjectile { get; }
    public IGameHookDatamapCBaseDoor CBaseDoor { get; }
    public IGameHookDatamapCBaseEntity CBaseEntity { get; }
    public IGameHookDatamapCBaseGrenade CBaseGrenade { get; }
    public IGameHookDatamapCBaseModelEntity CBaseModelEntity { get; }
    public IGameHookDatamapCBasePropDoor CBasePropDoor { get; }
    public IGameHookDatamapCBombTarget CBombTarget { get; }
    public IGameHookDatamapCBreakable CBreakable { get; }
    public IGameHookDatamapCBreakableProp CBreakableProp { get; }
    public IGameHookDatamapCCSPlayerController CCSPlayerController { get; }
    public IGameHookDatamapCCSPlayerPawn CCSPlayerPawn { get; }
    public IGameHookDatamapCCSPlayerResource CCSPlayerResource { get; }
    public IGameHookDatamapCCSWeaponBase CCSWeaponBase { get; }
    public IGameHookDatamapCChicken CChicken { get; }
    public IGameHookDatamapCColorCorrection CColorCorrection { get; }
    public IGameHookDatamapCColorCorrectionVolume CColorCorrectionVolume { get; }
    public IGameHookDatamapCDecoyProjectile CDecoyProjectile { get; }
    public IGameHookDatamapCDynamicLight CDynamicLight { get; }
    public IGameHookDatamapCDynamicProp CDynamicProp { get; }
    public IGameHookDatamapCEntityDissolve CEntityDissolve { get; }
    public IGameHookDatamapCEnvBeam CEnvBeam { get; }
    public IGameHookDatamapCEnvEntityMaker CEnvEntityMaker { get; }
    public IGameHookDatamapCEnvLaser CEnvLaser { get; }
    public IGameHookDatamapCEnvSpark CEnvSpark { get; }
    public IGameHookDatamapCEnvWind CEnvWind { get; }
    public IGameHookDatamapCEnvWindController CEnvWindController { get; }
    public IGameHookDatamapCFishPool CFishPool { get; }
    public IGameHookDatamapCFogController CFogController { get; }
    public IGameHookDatamapCFuncMoveLinear CFuncMoveLinear { get; }
    public IGameHookDatamapCFuncPlat CFuncPlat { get; }
    public IGameHookDatamapCFuncRotating CFuncRotating { get; }
    public IGameHookDatamapCFuncShatterglass CFuncShatterglass { get; }
    public IGameHookDatamapCFuncTrackChange CFuncTrackChange { get; }
    public IGameHookDatamapCFuncTrackTrain CFuncTrackTrain { get; }
    public IGameHookDatamapCFuncTrain CFuncTrain { get; }
    public IGameHookDatamapCGenericConstraint CGenericConstraint { get; }
    public IGameHookDatamapCGunTarget CGunTarget { get; }
    public IGameHookDatamapCHostage CHostage { get; }
    public IGameHookDatamapCHostageRescueZone CHostageRescueZone { get; }
    public IGameHookDatamapCInferno CInferno { get; }
    public IGameHookDatamapCInfoSpawnGroupLoadUnload CInfoSpawnGroupLoadUnload { get; }
    public IGameHookDatamapCItem CItem { get; }
    public IGameHookDatamapCItemDefuser CItemDefuser { get; }
    public IGameHookDatamapCItemGeneric CItemGeneric { get; }
    public IGameHookDatamapCLogicActiveAutosave CLogicActiveAutosave { get; }
    public IGameHookDatamapCLogicDistanceAutosave CLogicDistanceAutosave { get; }
    public IGameHookDatamapCLogicGameStateReport CLogicGameStateReport { get; }
    public IGameHookDatamapCLogicMeasureMovement CLogicMeasureMovement { get; }
    public IGameHookDatamapCLogicNPCCounter CLogicNPCCounter { get; }
    public IGameHookDatamapCMapVetoPickController CMapVetoPickController { get; }
    public IGameHookDatamapCMomentaryRotButton CMomentaryRotButton { get; }
    public IGameHookDatamapCMultiLightProxy CMultiLightProxy { get; }
    public IGameHookDatamapCMultiSource CMultiSource { get; }
    public IGameHookDatamapCParticleSystem CParticleSystem { get; }
    public IGameHookDatamapCPathMoverEntitySpawner CPathMoverEntitySpawner { get; }
    public IGameHookDatamapCPathNode CPathNode { get; }
    public IGameHookDatamapCPhysForce CPhysForce { get; }
    public IGameHookDatamapCPhysHinge CPhysHinge { get; }
    public IGameHookDatamapCPhysImpact CPhysImpact { get; }
    public IGameHookDatamapCPhysSlideConstraint CPhysSlideConstraint { get; }
    public IGameHookDatamapCPhysicsProp CPhysicsProp { get; }
    public IGameHookDatamapCPhysicsPropRespawnable CPhysicsPropRespawnable { get; }
    public IGameHookDatamapCPlantedC4 CPlantedC4 { get; }
    public IGameHookDatamapCPointCommentaryNode CPointCommentaryNode { get; }
    public IGameHookDatamapCPointHurt CPointHurt { get; }
    public IGameHookDatamapCPointOrient CPointOrient { get; }
    public IGameHookDatamapCPointPush CPointPush { get; }
    public IGameHookDatamapCPointValueRemapper CPointValueRemapper { get; }
    public IGameHookDatamapCRagdollProp CRagdollProp { get; }
    public IGameHookDatamapCRevertSaved CRevertSaved { get; }
    public IGameHookDatamapCScriptedSequence CScriptedSequence { get; }
    public IGameHookDatamapCSmokeGrenadeProjectile CSmokeGrenadeProjectile { get; }
    public IGameHookDatamapCSoundEventConeEntity CSoundEventConeEntity { get; }
    public IGameHookDatamapCSoundEventEntity CSoundEventEntity { get; }
    public IGameHookDatamapCSoundEventOBBEntity CSoundEventOBBEntity { get; }
    public IGameHookDatamapCSoundEventPathCornerEntity CSoundEventPathCornerEntity { get; }
    public IGameHookDatamapCSoundEventSphereEntity CSoundEventSphereEntity { get; }
    public IGameHookDatamapCSoundOpvarSetAutoRoomEntity CSoundOpvarSetAutoRoomEntity { get; }
    public IGameHookDatamapCSoundOpvarSetBoxEntity CSoundOpvarSetBoxEntity { get; }
    public IGameHookDatamapCSoundOpvarSetOBBWindEntity CSoundOpvarSetOBBWindEntity { get; }
    public IGameHookDatamapCSoundOpvarSetPathCornerEntity CSoundOpvarSetPathCornerEntity { get; }
    public IGameHookDatamapCSoundOpvarSetPointBase CSoundOpvarSetPointBase { get; }
    public IGameHookDatamapCSoundOpvarSetPointEntity CSoundOpvarSetPointEntity { get; }
    public IGameHookDatamapCSplineConstraint CSplineConstraint { get; }
    public IGameHookDatamapCSprite CSprite { get; }
    public IGameHookDatamapCTriggerActiveWeaponDetect CTriggerActiveWeaponDetect { get; }
    public IGameHookDatamapCTriggerFan CTriggerFan { get; }
    public IGameHookDatamapCTriggerHurt CTriggerHurt { get; }
    public IGameHookDatamapCTriggerImpact CTriggerImpact { get; }
    public IGameHookDatamapCTriggerLerpObject CTriggerLerpObject { get; }
    public IGameHookDatamapCTriggerLook CTriggerLook { get; }
    public IGameHookDatamapCTriggerMultiple CTriggerMultiple { get; }
    public IGameHookDatamapCTriggerProximity CTriggerProximity { get; }
    public IGameHookDatamapCTriggerSave CTriggerSave { get; }
    public IGameHookDatamapCTriggerSndSosOpvar CTriggerSndSosOpvar { get; }
    public IGameHookDatamapCTriggerSoundscape CTriggerSoundscape { get; }
    public IGameHookDatamapCVoteController CVoteController { get; }
    public IGameHookDatamapCWaterBullet CWaterBullet { get; }
}