// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_SDFLighting : CParticleFunctionOperator, ISchemaClass<C_OP_SDFLighting> {

  static C_OP_SDFLighting ISchemaClass<C_OP_SDFLighting>.From(nint handle) => new C_OP_SDFLightingImpl(handle);
  static int ISchemaClass<C_OP_SDFLighting>.Size => 488;

  
  public ref Vector LightingDir { get; }
  
  public ref Vector Tint_0 { get; }
  
  public ref Vector Tint_1 { get; }


}