// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimationGraphVisualizerPrimitiveBase : ISchemaClass<CAnimationGraphVisualizerPrimitiveBase> {

  static CAnimationGraphVisualizerPrimitiveBase ISchemaClass<CAnimationGraphVisualizerPrimitiveBase>.From(nint handle) => new CAnimationGraphVisualizerPrimitiveBaseImpl(handle);
  static int ISchemaClass<CAnimationGraphVisualizerPrimitiveBase>.Size => 64;

  
  public ref CAnimationGraphVisualizerPrimitiveType Type { get; }
  
  // AnimNodeID
  public SchemaUntypedField OwningAnimNodePaths { get; }
  
  public ref int OwningAnimNodePathCount { get; }


}