// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CChicken_GraphController : CBaseAnimGraphAnimGraphController, ISchemaClass<CChicken_GraphController> {

  static CChicken_GraphController ISchemaClass<CChicken_GraphController>.From(nint handle) => new CChicken_GraphControllerImpl(handle);
  static int ISchemaClass<CChicken_GraphController>.Size => 744;

  
  // CAnimGraphParamRef< char* >
  public SchemaUntypedField ParamActivity { get; }
  
  // CAnimGraphParamRef< bool >
  public SchemaUntypedField ParamEndActivityImmediately { get; }
  
  // CAnimGraphTagRef
  public SchemaUntypedField ActivityFinished { get; }
  
  // CAnimGraphParamRef< float32 >
  public SchemaUntypedField ParamTurnAngle { get; }


}