// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSGameModeRules : ISchemaClass<CCSGameModeRules> {

  static CCSGameModeRules ISchemaClass<CCSGameModeRules>.From(nint handle) => new CCSGameModeRulesImpl(handle);
  static int ISchemaClass<CCSGameModeRules>.Size => 48;

  
  public ref CNetworkVarChainer __m_pChainEntity { get; }


}