// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDampedValueComponentUpdater : CAnimComponentUpdater, ISchemaClass<CDampedValueComponentUpdater> {

  static CDampedValueComponentUpdater ISchemaClass<CDampedValueComponentUpdater>.From(nint handle) => new CDampedValueComponentUpdaterImpl(handle);
  static int ISchemaClass<CDampedValueComponentUpdater>.Size => 72;

  
  public ref CUtlVector<CDampedValueUpdateItem> Items { get; }


}