// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMapSharedEnvironment : CLogicalEntity, ISchemaClass<CMapSharedEnvironment> {

  static CMapSharedEnvironment ISchemaClass<CMapSharedEnvironment>.From(nint handle) => new CMapSharedEnvironmentImpl(handle);
  static int ISchemaClass<CMapSharedEnvironment>.Size => 1280;

  
  public string TargetMapName { get; set; }


}