// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMotionGraphUpdateNode : CLeafUpdateNode, ISchemaClass<CMotionGraphUpdateNode> {

  static CMotionGraphUpdateNode ISchemaClass<CMotionGraphUpdateNode>.From(nint handle) => new CMotionGraphUpdateNodeImpl(handle);
  static int ISchemaClass<CMotionGraphUpdateNode>.Size => 104;

  
  // CSmartPtr< CMotionGraph >
  public SchemaUntypedField MotionGraph { get; }


}