// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Outflow_PlayVCD : CPulseCell_Outflow_PlaySceneBase, ISchemaClass<CPulseCell_Outflow_PlayVCD> {

  static CPulseCell_Outflow_PlayVCD ISchemaClass<CPulseCell_Outflow_PlayVCD>.From(nint handle) => new CPulseCell_Outflow_PlayVCDImpl(handle);
  static int ISchemaClass<CPulseCell_Outflow_PlayVCD>.Size => 248;

  
  public ref CStrongHandle<InfoForResourceTypeCChoreoSceneResource> ChoreoScene { get; }


}