// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CStopAtGoalUpdateNode : CUnaryUpdateNode, ISchemaClass<CStopAtGoalUpdateNode> {

  static CStopAtGoalUpdateNode ISchemaClass<CStopAtGoalUpdateNode>.From(nint handle) => new CStopAtGoalUpdateNodeImpl(handle);
  static int ISchemaClass<CStopAtGoalUpdateNode>.Size => 160;

  
  public ref float OuterRadius { get; }
  
  public ref float InnerRadius { get; }
  
  public ref float MaxScale { get; }
  
  public ref float MinScale { get; }
  
  public CAnimInputDamping Damping { get; }


}