// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSymbolAnimParameter : CConcreteAnimParameter, ISchemaClass<CSymbolAnimParameter> {

  static CSymbolAnimParameter ISchemaClass<CSymbolAnimParameter>.From(nint handle) => new CSymbolAnimParameterImpl(handle);
  static int ISchemaClass<CSymbolAnimParameter>.Size => 136;

  
  public ref CGlobalSymbol DefaultValue { get; }


}