// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface ResponseParams : ISchemaClass<ResponseParams> {

  static ResponseParams ISchemaClass<ResponseParams>.From(nint handle) => new ResponseParamsImpl(handle);
  static int ISchemaClass<ResponseParams>.Size => 32;

  
  public ref short Odds { get; }
  
  public ref short Flags { get; }
  
  public ResponseFollowup? Followup { get; }


}