// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface RotatorQueueEntry_t : ISchemaClass<RotatorQueueEntry_t> {

  static RotatorQueueEntry_t ISchemaClass<RotatorQueueEntry_t>.From(nint handle) => new RotatorQueueEntry_tImpl(handle);
  static int ISchemaClass<RotatorQueueEntry_t>.Size => 32;

  
  public ref Quaternion Target { get; }
  
  public ref RotatorTargetSpace_t Space { get; }


}