// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SelectedEditItemInfo_t : ISchemaClass<SelectedEditItemInfo_t> {

  static SelectedEditItemInfo_t ISchemaClass<SelectedEditItemInfo_t>.From(nint handle) => new SelectedEditItemInfo_tImpl(handle);
  static int ISchemaClass<SelectedEditItemInfo_t>.Size => 24;

  
  public ref CUtlVector<SosEditItemInfo_t> EditItems { get; }


}