// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CNmOrientationWarpNode__AlignmentMode_t : byte
{
    MovementDirection = 0,
    AnimationEndFacing = 1,
}
