// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CustomCameraMode_t : byte
{
    CUSTOM_CAMERA_MODE_DISABLED = 0,
    CUSTOM_CAMERA_MODE_CONTROLLED = 1,
    CUSTOM_CAMERA_MODE_CONTROLLED_POSITION = 2,
    CUSTOM_CAMERA_MODE_FOLLOW_POSITION = 3,
}
