// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum INavObstacle__NavObstacleType_t : uint
{
    NAV_OBSTACLE_TYPE_INVALID = uint.MaxValue,
    NAV_OBSTACLE_TYPE_NONE = 0,
    NAV_OBSTACLE_TYPE_AVOID = 1,
    NAV_OBSTACLE_TYPE_CONN = 2,
    NAV_OBSTACLE_TYPE_BLOCK = 3,
    NAV_OBSTACLE_TYPE_PERMANENT_BLOCK = 4,
}
