// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum NmDocToolFlag_t : uint
{
    None = 0,
    StandaloneButton = 1,
    ShowInContextMenu = 2,
    RequiresSelection = 4,
    RestrictToSingleFileSelection = 8,
}
