// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum NoiseStreamType_t : uint
{
    NOISE_STREAM_TYPE_PERLIN = 0,
    NOISE_STREAM_TYPE_SIMPLEX = 1,
    NOISE_STREAM_TYPE_WORLEY = 2,
    NOISE_STREAM_TYPE_CURL = 3,
    NOISE_STREAM_TYPE_NONE = 4,
}
