// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ParticleEntityPos_t : uint
{
 PARTICLE_ABS_ORIGIN = 0,

 PARTICLE_WORLDSPACE_CENTER = 1,

 PARTICLE_EYES = 2,
}