// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum RadiusDmgOverride_t : uint
{
    RADIUS_DMG_OVERRIDE_NONE = 0,
    RADIUS_DMG_OVERRIDE_POSITION_ONLY = 1,
    RADIUS_DMG_OVERRIDE_POSITION_SKIP_TRACES = 2,
}
