// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SndBeatSyncStartType_t : uint
{
    eSndBeatSyncStartTypeInvalid = 0,
    eSndBeatSyncStartTypeImmediate = 1,
    eSndBeatSyncStartTypeQueue = 2,
}
