// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_DefaultNPC_DebugSnapshotData_t : DebugSnapshotBaseStructuredData_t, ISchemaClass<AI_DefaultNPC_DebugSnapshotData_t>
{
    static AI_DefaultNPC_DebugSnapshotData_t ISchemaClass<AI_DefaultNPC_DebugSnapshotData_t>.From(nint handle) => new AI_DefaultNPC_DebugSnapshotData_tImpl(handle);
    static int ISchemaClass<AI_DefaultNPC_DebugSnapshotData_t>.Size => 128;
    static string? ISchemaClass<AI_DefaultNPC_DebugSnapshotData_t>.ClassName => null;


    public ref CGlobalSymbol S_npc_current_ability { get; }

    public ref CGlobalSymbol S_npc_current_held_ability { get; }

    public ref CGlobalSymbol S_npc_tactic_current { get; }

    public ref CGlobalSymbol S_npc_tactic_phase { get; }

    public ref CUtlVector<CGlobalSymbol> Tactic_interrupt_conditions { get; }

    public AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t Path_query { get; }

    public ref CUtlVector<AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t> Path_queries_speculative { get; }


}