// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_AttributeContainer : CAttributeManager, ISchemaClass<C_AttributeContainer>
{
    static C_AttributeContainer ISchemaClass<C_AttributeContainer>.From(nint handle) => new C_AttributeContainerImpl(handle);
    static int ISchemaClass<C_AttributeContainer>.Size => 1552;
    static string? ISchemaClass<C_AttributeContainer>.ClassName => null;


    public C_EconItemView Item { get; }

    public ref int ExternalItemProviderRegisteredToken { get; }

    public ref ulong UllRegisteredAsItemID { get; }


}