// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_BaseModelEntity : C_BaseEntity, ISchemaClass<C_BaseModelEntity>
{
    static C_BaseModelEntity ISchemaClass<C_BaseModelEntity>.From(nint handle) => new C_BaseModelEntityImpl(handle);
    static int ISchemaClass<C_BaseModelEntity>.Size => 4248;
    static string? ISchemaClass<C_BaseModelEntity>.ClassName => null;


    public CRenderComponent? CRenderComponent { get; }

    public CHitboxComponent CHitboxComponent { get; }

    public CChoreoComponent? ChoreoComponent { get; }

    public ref HitGroup_t DestructiblePartInitialStateDestructed0 { get; }

    public ref HitGroup_t DestructiblePartInitialStateDestructed1 { get; }

    public ref HitGroup_t DestructiblePartInitialStateDestructed2 { get; }

    public ref HitGroup_t DestructiblePartInitialStateDestructed3 { get; }

    public ref HitGroup_t DestructiblePartInitialStateDestructed4 { get; }

    public ref int DestructiblePartInitialStateDestructed0_PartIndex { get; }

    public ref int DestructiblePartInitialStateDestructed1_PartIndex { get; }

    public ref int DestructiblePartInitialStateDestructed2_PartIndex { get; }

    public ref int DestructiblePartInitialStateDestructed3_PartIndex { get; }

    public ref int DestructiblePartInitialStateDestructed4_PartIndex { get; }

    public ref bool DestructiblePartInitialStateDestructed0_GenerateBreakpieces { get; }

    public ref bool DestructiblePartInitialStateDestructed1_GenerateBreakpieces { get; }

    public ref bool DestructiblePartInitialStateDestructed2_GenerateBreakpieces { get; }

    public ref bool DestructiblePartInitialStateDestructed3_GenerateBreakpieces { get; }

    public ref bool DestructiblePartInitialStateDestructed4_GenerateBreakpieces { get; }

    public CDestructiblePartsComponent? DestructiblePartsSystemComponent { get; }

    public ref bool InitModelEffects { get; }

    public ref bool DoingModelEffects { get; }

    public ref int OldHealth { get; }

    public ref RenderMode_t RenderMode { get; }

    public ref RenderFx_t RenderFX { get; }

    public ref bool AllowFadeInView { get; }

    public ref Color Render { get; }

    // C_UtlVectorEmbeddedNetworkVar< EntityRenderAttribute_t >
    public SchemaUntypedField RenderAttributes { get; }

    public ref bool RenderToCubemaps { get; }

    public ref bool ExpandRenderBoundsToIncludeCloth { get; }

    public ref bool NoInterpolate { get; }

    public CCollisionProperty Collision { get; }

    public CGlowProperty Glow { get; }

    public ref float GlowBackfaceMult { get; }

    public ref float FadeMinDist { get; }

    public ref float FadeMaxDist { get; }

    public ref float FadeScale { get; }

    public ref float ShadowStrength { get; }

    public ref byte ObjectCulling { get; }

    public ref DecalRtEncoding_t RequiredDecalRtEncoding { get; }

    public ref uint BodyGroupTotalRequestCount { get; }

    // CUtlVectorFixedGrowable< C_BaseModelEntity::BodyGroupRequest_t, 8 >
    public SchemaUntypedField BodyGroupRequests { get; }

    // CUtlOrderedMap< CGlobalSymbol, int32 >
    public SchemaUntypedField BodyGroupChoices { get; }

    public CNetworkViewOffsetVector ViewOffset { get; }

    public CClientAlphaProperty? ClientAlphaProperty { get; }

    public ref Color ClientOverrideTint { get; }

    public ref bool UseClientOverrideTint { get; }

    public ISchemaFixedArray<uint> DisabledHitGroups { get; }


}