// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_BaseCombatCharacter : CBaseAnimGraph, ISchemaClass<C_BaseCombatCharacter>
{
    static C_BaseCombatCharacter ISchemaClass<C_BaseCombatCharacter>.From(nint handle) => new C_BaseCombatCharacterImpl(handle);
    static int ISchemaClass<C_BaseCombatCharacter>.Size => 4848;
    static string? ISchemaClass<C_BaseCombatCharacter>.ClassName => null;


    // C_NetworkUtlVectorBase< CHandle< C_EconWearable > >
    public SchemaUntypedField MyWearables { get; }

    public AttachmentHandle_t LeftFootAttachment { get; }

    public AttachmentHandle_t RightFootAttachment { get; }

    public ref C_BaseCombatCharacter__WaterWakeMode_t WaterWakeMode { get; }

    public ref float WaterWorldZ { get; }

    public ref float WaterNextTraceTime { get; }


}