// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_BaseCSGrenadeProjectile : C_BaseGrenade, ISchemaClass<C_BaseCSGrenadeProjectile>
{
    static C_BaseCSGrenadeProjectile ISchemaClass<C_BaseCSGrenadeProjectile>.From(nint handle) => new C_BaseCSGrenadeProjectileImpl(handle);
    static int ISchemaClass<C_BaseCSGrenadeProjectile>.Size => 4936;
    static string? ISchemaClass<C_BaseCSGrenadeProjectile>.ClassName => null;


    public ref Vector InitialPosition { get; }

    public ref Vector InitialVelocity { get; }

    public ref int Bounces { get; }

    public ref CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> ExplodeEffectIndex { get; }

    public ref int ExplodeEffectTickBegin { get; }

    public ref Vector ExplodeEffectOrigin { get; }

    public GameTime_t SpawnTime { get; }

    public ref Vector LastTrailLinePos { get; }

    public GameTime_t NextTrailLineTime { get; }

    public ref bool ExplodeEffectBegan { get; }

    public ref bool CanCreateGrenadeTrail { get; }

    public ParticleIndex_t SnapshotTrajectoryEffectIndex { get; }

    public ref CStrongHandle<InfoForResourceTypeIParticleSnapshot> SnapshotTrajectoryParticleSnapshot { get; }

    public ref CUtlVector<Vector> TrajectoryTrailPoints { get; }

    public ref CUtlVector<float> TrajectoryTrailPointCreationTimes { get; }

    public ref float TrajectoryTrailEffectCreationTime { get; }


}