// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_C4 : C_CSWeaponBase, ISchemaClass<C_C4>
{
    static C_C4 ISchemaClass<C_C4>.From(nint handle) => new C_C4Impl(handle);
    static int ISchemaClass<C_C4>.Size => 8016;
    static string? ISchemaClass<C_C4>.ClassName => null;


    public ParticleIndex_t ActiveLightParticleIndex { get; }

    public ref C4LightEffect_t ActiveLightEffect { get; }

    public ref bool StartedArming { get; }

    public GameTime_t ArmedTime { get; }

    public ref bool BombPlacedAnimation { get; }

    public ref bool IsPlantingViaUse { get; }

    public EntitySpottedState_t EntitySpottedState { get; }

    public ref int SpotRules { get; }

    public ISchemaFixedArray<bool> PlayedArmingBeeps { get; }

    public ref bool BombPlanted { get; }


}