// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_ClientRagdoll : CBaseAnimGraph, ISchemaClass<C_ClientRagdoll>
{
    static C_ClientRagdoll ISchemaClass<C_ClientRagdoll>.From(nint handle) => new C_ClientRagdollImpl(handle);
    static int ISchemaClass<C_ClientRagdoll>.Size => 4864;
    static string? ISchemaClass<C_ClientRagdoll>.ClassName => null;


    public ref bool FadeOut { get; }

    public ref bool Important { get; }

    public GameTime_t EffectTime { get; }

    public GameTime_t GibDespawnTime { get; }

    public ref int CurrentFriction { get; }

    public ref int MinFriction { get; }

    public ref int MaxFriction { get; }

    public ref int FrictionAnimState { get; }

    public ref bool ReleaseRagdoll { get; }

    public AttachmentHandle_t EyeAttachment { get; }

    public ref bool FadingOut { get; }

    public ISchemaFixedArray<float> ScaleEnd { get; }

    public ISchemaClassFixedArray<GameTime_t> ScaleTimeStart { get; }

    public ISchemaClassFixedArray<GameTime_t> ScaleTimeEnd { get; }


}