// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_FireCrackerBlast : C_Inferno, ISchemaClass<C_FireCrackerBlast>
{
    static C_FireCrackerBlast ISchemaClass<C_FireCrackerBlast>.From(nint handle) => new C_FireCrackerBlastImpl(handle);
    static int ISchemaClass<C_FireCrackerBlast>.Size => 34464;
    static string? ISchemaClass<C_FireCrackerBlast>.ClassName => null;

}