// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_FuncMoveLinear : C_BaseToggle, ISchemaClass<C_FuncMoveLinear>
{
    static C_FuncMoveLinear ISchemaClass<C_FuncMoveLinear>.From(nint handle) => new C_FuncMoveLinearImpl(handle);
    static int ISchemaClass<C_FuncMoveLinear>.Size => 4248;
    static string? ISchemaClass<C_FuncMoveLinear>.ClassName => null;

}