// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_FuncElectrifiedVolume : C_FuncBrush, ISchemaClass<C_FuncElectrifiedVolume>
{
    static C_FuncElectrifiedVolume ISchemaClass<C_FuncElectrifiedVolume>.From(nint handle) => new C_FuncElectrifiedVolumeImpl(handle);
    static int ISchemaClass<C_FuncElectrifiedVolume>.Size => 4272;
    static string? ISchemaClass<C_FuncElectrifiedVolume>.ClassName => null;


    public ParticleIndex_t AmbientEffect { get; }

    public string EffectName { get; set; }

    public ref bool State { get; }


}