// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_Item : C_EconEntity, ISchemaClass<C_Item>
{
    static C_Item ISchemaClass<C_Item>.From(nint handle) => new C_ItemImpl(handle);
    static int ISchemaClass<C_Item>.Size => 6680;
    static string? ISchemaClass<C_Item>.ClassName => null;


    public string ReticleHintTextName { get; set; }


}