// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_LightEnvironmentEntity : C_LightDirectionalEntity, ISchemaClass<C_LightEnvironmentEntity>
{
    static C_LightEnvironmentEntity ISchemaClass<C_LightEnvironmentEntity>.From(nint handle) => new C_LightEnvironmentEntityImpl(handle);
    static int ISchemaClass<C_LightEnvironmentEntity>.Size => 4256;
    static string? ISchemaClass<C_LightEnvironmentEntity>.ClassName => null;

}