// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OmniLight : C_BarnLight, ISchemaClass<C_OmniLight>
{
    static C_OmniLight ISchemaClass<C_OmniLight>.From(nint handle) => new C_OmniLightImpl(handle);
    static int ISchemaClass<C_OmniLight>.Size => 5048;
    static string? ISchemaClass<C_OmniLight>.ClassName => null;


    public ref float InnerAngle { get; }

    public ref float OuterAngle { get; }

    public ref bool ShowLight { get; }


}