// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_MaxVelocity : CParticleFunctionOperator, ISchemaClass<C_OP_MaxVelocity>
{
    static C_OP_MaxVelocity ISchemaClass<C_OP_MaxVelocity>.From(nint handle) => new C_OP_MaxVelocityImpl(handle);
    static int ISchemaClass<C_OP_MaxVelocity>.Size => 1232;
    static string? ISchemaClass<C_OP_MaxVelocity>.ClassName => null;


    public CPerParticleFloatInput MaxVelocity { get; }

    public CPerParticleFloatInput MinVelocity { get; }


}