// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RenderLightBeam : CParticleFunctionRenderer, ISchemaClass<C_OP_RenderLightBeam>
{
    static C_OP_RenderLightBeam ISchemaClass<C_OP_RenderLightBeam>.From(nint handle) => new C_OP_RenderLightBeamImpl(handle);
    static int ISchemaClass<C_OP_RenderLightBeam>.Size => 8248;
    static string? ISchemaClass<C_OP_RenderLightBeam>.ClassName => null;


    public ref ushort MaxAllowed { get; }

    public CParticleCollectionVecInput ColorBlend { get; }

    public ref ParticleColorBlendType_t ColorBlendType { get; }

    public string StrLightStyle { get; set; }

    public CPerParticleFloatInput LightStyleTime { get; }

    public CParticleCollectionFloatInput BrightnessLumensPerMeter { get; }

    public CParticleCollectionFloatInput NumberOfLightsToCreate { get; }

    public ref bool CastShadows { get; }

    public ref bool DynamicBounce { get; }

    public CParticleCollectionFloatInput BounceScale { get; }

    public CParticleCollectionFloatInput Skirt { get; }

    public CParticleCollectionFloatInput Range { get; }

    public CParticleCollectionFloatInput Thickness { get; }

    public CParticleCollectionFloatInput InnerConeAngle { get; }

    public CParticleCollectionFloatInput OuterConeAngle { get; }

    public CParticleCollectionVecInput ConeRotationOffset { get; }

    public ref ParticleLightFogLightingMode_t FogLightingMode { get; }

    public CParticleCollectionRendererFloatInput FogContribution { get; }

    public CPerParticleFloatInput RenderFilter { get; }

    public ref bool DebugOrientation { get; }


}