// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_PhysMagnet : CBaseAnimGraph, ISchemaClass<C_PhysMagnet>
{
    static C_PhysMagnet ISchemaClass<C_PhysMagnet>.From(nint handle) => new C_PhysMagnetImpl(handle);
    static int ISchemaClass<C_PhysMagnet>.Size => 4760;
    static string? ISchemaClass<C_PhysMagnet>.ClassName => null;


    public ref CUtlVector<int> AttachedObjectsFromServer { get; }

    public ref CUtlVector<CHandle<C_BaseEntity>> AttachedObjects { get; }


}