// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_PointDeathcamBounds : C_BaseEntity, ISchemaClass<C_PointDeathcamBounds>
{
    static C_PointDeathcamBounds ISchemaClass<C_PointDeathcamBounds>.From(nint handle) => new C_PointDeathcamBoundsImpl(handle);
    static int ISchemaClass<C_PointDeathcamBounds>.Size => 1568;
    static string? ISchemaClass<C_PointDeathcamBounds>.ClassName => null;


    public ref Vector BoxMins { get; }

    public ref Vector BoxMaxs { get; }

    public ref float LerpDistance { get; }


}