// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_PointClientUIWorldPanel : C_BaseClientUIEntity, ISchemaClass<C_PointClientUIWorldPanel>
{
    static C_PointClientUIWorldPanel ISchemaClass<C_PointClientUIWorldPanel>.From(nint handle) => new C_PointClientUIWorldPanelImpl(handle);
    static int ISchemaClass<C_PointClientUIWorldPanel>.Size => 4864;
    static string? ISchemaClass<C_PointClientUIWorldPanel>.ClassName => null;


    public ref bool ForceRecreateNextUpdate { get; }

    public ref bool MoveViewToPlayerNextThink { get; }

    public ref bool CheckCSSClasses { get; }

    public ref CTransform AnchorDeltaTransform { get; }

    public CPointOffScreenIndicatorUi? OffScreenIndicator { get; }

    public ref bool IgnoreInput { get; }

    public ref bool Lit { get; }

    public ref bool FollowPlayerAcrossTeleport { get; }

    public ref float Width { get; }

    public ref float Height { get; }

    public ref float DPI { get; }

    public ref float WindowUIScale { get; }

    public ref float InteractDistance { get; }

    public ref float DepthOffset { get; }

    public ref uint OwnerContext { get; }

    public ref uint HorizontalAlign { get; }

    public ref uint VerticalAlign { get; }

    public ref uint Orientation { get; }

    public ref bool AllowInteractionFromAllSceneWorlds { get; }

    // C_NetworkUtlVectorBase< CUtlSymbolLarge >
    public SchemaUntypedField CSSClasses { get; }

    public ref bool Opaque { get; }

    public ref bool NoDepth { get; }

    public ref bool VisibleWhenParentNoDraw { get; }

    public ref bool RenderBackface { get; }

    public ref bool UseOffScreenIndicator { get; }

    public ref bool ExcludeFromSaveGames { get; }

    public ref bool Grabbable { get; }

    public ref bool OnlyRenderToTexture { get; }

    public ref bool DisableMipGen { get; }

    public ref int ExplicitImageLayout { get; }

    public ref bool IgnoreParentOrientation { get; }


}