// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_PointCommentaryNode : CBaseAnimGraph, ISchemaClass<C_PointCommentaryNode>
{
    static C_PointCommentaryNode ISchemaClass<C_PointCommentaryNode>.From(nint handle) => new C_PointCommentaryNodeImpl(handle);
    static int ISchemaClass<C_PointCommentaryNode>.Size => 4808;
    static string? ISchemaClass<C_PointCommentaryNode>.ClassName => null;


    public ref bool Active { get; }

    public ref bool WasActive { get; }

    public GameTime_t EndTime { get; }

    public GameTime_t StartTime { get; }

    public ref float StartTimeInCommentary { get; }

    public string CommentaryFile { get; set; }

    public string Title { get; set; }

    public string Speakers { get; set; }

    public ref int NodeNumber { get; }

    public ref int NodeNumberMax { get; }

    public ref bool ListenedTo { get; }

    public CSoundPatch? SndCommentary { get; }

    public ref CHandle<C_BaseEntity> ViewPosition { get; }

    public ref bool RestartAfterRestore { get; }


}