// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_SmokeGrenade : C_BaseCSGrenade, ISchemaClass<C_SmokeGrenade>
{
    static C_SmokeGrenade ISchemaClass<C_SmokeGrenade>.From(nint handle) => new C_SmokeGrenadeImpl(handle);
    static int ISchemaClass<C_SmokeGrenade>.Size => 8160;
    static string? ISchemaClass<C_SmokeGrenade>.ClassName => null;

}