// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_TriggerBuoyancy : C_BaseTrigger, ISchemaClass<C_TriggerBuoyancy>
{
    static C_TriggerBuoyancy ISchemaClass<C_TriggerBuoyancy>.From(nint handle) => new C_TriggerBuoyancyImpl(handle);
    static int ISchemaClass<C_TriggerBuoyancy>.Size => 4768;
    static string? ISchemaClass<C_TriggerBuoyancy>.ClassName => null;


    public CBuoyancyHelper BuoyancyHelper { get; }

    public ref float FluidDensity { get; }


}