// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_WeaponGlock : C_CSWeaponBaseGun, ISchemaClass<C_WeaponGlock>
{
    static C_WeaponGlock ISchemaClass<C_WeaponGlock>.From(nint handle) => new C_WeaponGlockImpl(handle);
    static int ISchemaClass<C_WeaponGlock>.Size => 8000;
    static string? ISchemaClass<C_WeaponGlock>.ClassName => null;

}