// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_WeaponMP5SD : C_CSWeaponBaseGun, ISchemaClass<C_WeaponMP5SD>
{
    static C_WeaponMP5SD ISchemaClass<C_WeaponMP5SD>.From(nint handle) => new C_WeaponMP5SDImpl(handle);
    static int ISchemaClass<C_WeaponMP5SD>.Size => 8000;
    static string? ISchemaClass<C_WeaponMP5SD>.ClassName => null;

}