// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_WeaponP90 : C_CSWeaponBaseGun, ISchemaClass<C_WeaponP90>
{
    static C_WeaponP90 ISchemaClass<C_WeaponP90>.From(nint handle) => new C_WeaponP90Impl(handle);
    static int ISchemaClass<C_WeaponP90>.Size => 8016;
    static string? ISchemaClass<C_WeaponP90>.ClassName => null;

}