// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSCustomHudLayoutState : ISchemaClass<CCSCustomHudLayoutState>
{
    static CCSCustomHudLayoutState ISchemaClass<CCSCustomHudLayoutState>.From(nint handle) => new CCSCustomHudLayoutStateImpl(handle);
    static int ISchemaClass<CCSCustomHudLayoutState>.Size => 408;
    static string? ISchemaClass<CCSCustomHudLayoutState>.ClassName => null;


    public ref uint PlayerSlot { get; }

    public ref bool InputCaptureEnabled { get; }

    public ref CUtlVector<HUDPanelHasClass_t> HasClasses { get; }

    public ref CUtlVector<HUDPanelDialogVariableString_t> DialogVariableStrings { get; }

    public void InputCaptureEnabledUpdated();
    public void HasClassesUpdated();
    public void DialogVariableStringsUpdated();
}