// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSGO_RushIntroCounterTerroristPosition : CCSGO_RushIntroCharacterPosition, ISchemaClass<CCSGO_RushIntroCounterTerroristPosition>
{
    static CCSGO_RushIntroCounterTerroristPosition ISchemaClass<CCSGO_RushIntroCounterTerroristPosition>.From(nint handle) => new CCSGO_RushIntroCounterTerroristPositionImpl(handle);
    static int ISchemaClass<CCSGO_RushIntroCounterTerroristPosition>.Size => 5224;
    static string? ISchemaClass<CCSGO_RushIntroCounterTerroristPosition>.ClassName => "rush_intro_counterterrorist";

}