// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSGO_RushIntroTerroristPosition : CCSGO_RushIntroCharacterPosition, ISchemaClass<CCSGO_RushIntroTerroristPosition>
{
    static CCSGO_RushIntroTerroristPosition ISchemaClass<CCSGO_RushIntroTerroristPosition>.From(nint handle) => new CCSGO_RushIntroTerroristPositionImpl(handle);
    static int ISchemaClass<CCSGO_RushIntroTerroristPosition>.Size => 5224;
    static string? ISchemaClass<CCSGO_RushIntroTerroristPosition>.ClassName => "rush_intro_terrorist";

}