// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSPlayerLegacyJump : ISchemaClass<CCSPlayerLegacyJump>
{
    static CCSPlayerLegacyJump ISchemaClass<CCSPlayerLegacyJump>.From(nint handle) => new CCSPlayerLegacyJumpImpl(handle);
    static int ISchemaClass<CCSPlayerLegacyJump>.Size => 24;
    static string? ISchemaClass<CCSPlayerLegacyJump>.ClassName => null;


    public ref bool OldJumpPressed { get; }

    public ref float JumpPressedTime { get; }

    public void OldJumpPressedUpdated();
}