// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSPlayerModernJump : ISchemaClass<CCSPlayerModernJump>
{
    static CCSPlayerModernJump ISchemaClass<CCSPlayerModernJump>.From(nint handle) => new CCSPlayerModernJumpImpl(handle);
    static int ISchemaClass<CCSPlayerModernJump>.Size => 48;
    static string? ISchemaClass<CCSPlayerModernJump>.ClassName => null;


    public GameTick_t LastActualJumpPressTick { get; }

    public ref float LastActualJumpPressFrac { get; }

    public GameTick_t LastUsableJumpPressTick { get; }

    public ref float LastUsableJumpPressFrac { get; }

    public GameTick_t LastLandedTick { get; }

    public ref float LastLandedFrac { get; }

    public ref float LastLandedVelocityX { get; }

    public ref float LastLandedVelocityY { get; }

    public void LastActualJumpPressTickUpdated();
    public void LastActualJumpPressFracUpdated();
    public void LastUsableJumpPressTickUpdated();
    public void LastUsableJumpPressFracUpdated();
    public void LastLandedTickUpdated();
    public void LastLandedFracUpdated();
    public void LastLandedVelocityXUpdated();
    public void LastLandedVelocityYUpdated();
}