// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFuncRotator : CBaseModelEntity, ISchemaClass<CFuncRotator>
{
    static CFuncRotator ISchemaClass<CFuncRotator>.From(nint handle) => new CFuncRotatorImpl(handle);
    static int ISchemaClass<CFuncRotator>.Size => 2288;
    static string? ISchemaClass<CFuncRotator>.ClassName => "func_rotator";


    public ref CFuncRotator__Rotate_t RotateType { get; }

    public ref bool IsRotating { get; }

    public ref SolidType_t SolidType { get; }

    public ref float Speed { get; }

    public ref float TimeToCompleteRotation { get; }

    public ref CHandle<CBaseEntity> RotatorTarget { get; }

    public string StrRotatorTarget { get; set; }

    public ref CUtlVector<Quaternion> LocalRotationHistory { get; }

    public ref CEntityIOOutput OnRotationStarted { get; }

    public ref CEntityIOOutput OnRotationCompleted { get; }

    public ref CEntityIOOutput OnOscillate { get; }

    public ref CEntityIOOutput OnOscillateStartArrive { get; }

    public ref CEntityIOOutput OnOscillateStartDepart { get; }

    public ref CEntityIOOutput OnOscillateEndArrive { get; }

    public ref CEntityIOOutput OnOscillateEndDepart { get; }

    public GameTick_t TickRotateRan { get; }

    public ref bool StartedRotating { get; }

    public FuncRotatorRotationSummary_t RotationSummary { get; }

    public ref float TimeToReachMaxSpeed { get; }

    public ref float TimeToReachZeroSpeed { get; }

    public GameTime_t TimeRotationStart { get; }

    public GameTime_t TimeRotationStop { get; }

    public ref float StartSpeed { get; }

    public ref Quaternion SpawnOrientation { get; }

    public ref bool RecordHistory { get; }

    public ref bool ReturningToPreviousRotation { get; }

    public ref bool ReturningToInitialRotation { get; }

    public ref float MinYawRotation { get; }

    public ref float MaxYawRotation { get; }

    public ref int OscillationCount { get; }

    public ref bool OscillationFromStart { get; }

    public ref CGameSoundEventName StartSound { get; }

    public ref CGameSoundEventName LoopSound { get; }

    public ref CGameSoundEventName StopSound { get; }

    public ref float TargetAngle { get; }

    public ref float CurrentAngle { get; }

    public ref CFuncRotator__RotationAxis_t RotationAxis { get; }

    public ref float SpeedDriftFromOverRotate { get; }


}