// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFuncTrackChange : CFuncPlatRot, ISchemaClass<CFuncTrackChange>
{
    static CFuncTrackChange ISchemaClass<CFuncTrackChange>.From(nint handle) => new CFuncTrackChangeImpl(handle);
    static int ISchemaClass<CFuncTrackChange>.Size => 2392;
    static string? ISchemaClass<CFuncTrackChange>.ClassName => "func_trackchange";


    public ref CHandle<CPathTrack> TrackTop { get; }

    public ref CHandle<CPathTrack> TrackBottom { get; }

    public ref CHandle<CFuncTrackTrain> Train { get; }

    public string TrackTopName { get; set; }

    public string TrackBottomName { get; set; }

    public string TrainName { get; set; }

    public ref TRAIN_CODE Code { get; }

    public ref int TargetState { get; }

    public ref int Use { get; }


}