// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CImageProcessor : ISchemaClass<CImageProcessor>
{
    static CImageProcessor ISchemaClass<CImageProcessor>.From(nint handle) => new CImageProcessorImpl(handle);
    static int ISchemaClass<CImageProcessor>.Size => 32;
    static string? ISchemaClass<CImageProcessor>.ClassName => null;


    public string Algorithm { get; set; }

    public string StringArg { get; set; }

    public ref Vector4D Float4Arg { get; }


}