// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixTrack : CMixPropertyBase, ISchemaClass<CMixTrack>
{
    static CMixTrack ISchemaClass<CMixTrack>.From(nint handle) => new CMixTrackImpl(handle);
    static int ISchemaClass<CMixTrack>.Size => 72;
    static string? ISchemaClass<CMixTrack>.ClassName => null;


    public ref int Channels { get; }

    public ref VMixMixDownRule_t MixDown { get; }

    public ref VMixSendOperator_t SendOperator { get; }

    public ISchemaUtlStringFixedArray SendNames { get; }


}