// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixPropertyBase : ISchemaClass<CMixPropertyBase>
{
    static CMixPropertyBase ISchemaClass<CMixPropertyBase>.From(nint handle) => new CMixPropertyBaseImpl(handle);
    static int ISchemaClass<CMixPropertyBase>.Size => 32;
    static string? ISchemaClass<CMixPropertyBase>.ClassName => null;


    public string Name { get; set; }

    public string Comment { get; set; }

    public ref bool Active { get; }

    public ref bool Solo { get; }

    public ref bool EditProperties { get; }

    public ref int GenerationId { get; }


}