// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNavPathCostForTests : CNavPathCost, ISchemaClass<CNavPathCostForTests>
{
    static CNavPathCostForTests ISchemaClass<CNavPathCostForTests>.From(nint handle) => new CNavPathCostForTestsImpl(handle);
    static int ISchemaClass<CNavPathCostForTests>.Size => 72;
    static string? ISchemaClass<CNavPathCostForTests>.ClassName => null;

}