// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmBodyGroupNode__CDefinition : CNmPassthroughNode__CDefinition, ISchemaClass<CNmBodyGroupNode__CDefinition>
{
    static CNmBodyGroupNode__CDefinition ISchemaClass<CNmBodyGroupNode__CDefinition>.From(nint handle) => new CNmBodyGroupNode__CDefinitionImpl(handle);
    static int ISchemaClass<CNmBodyGroupNode__CDefinition>.Size => 80;
    static string? ISchemaClass<CNmBodyGroupNode__CDefinition>.ClassName => null;


    public ref short EnabledNodeIdx { get; }

    public CNmBodyGroupEvent Event { get; }


}