// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmClipDocEvent_EntityAttribute : CNmClipDocEvent, ISchemaClass<CNmClipDocEvent_EntityAttribute>
{
    static CNmClipDocEvent_EntityAttribute ISchemaClass<CNmClipDocEvent_EntityAttribute>.From(nint handle) => new CNmClipDocEvent_EntityAttributeImpl(handle);
    static int ISchemaClass<CNmClipDocEvent_EntityAttribute>.Size => 112;
    static string? ISchemaClass<CNmClipDocEvent_EntityAttribute>.ClassName => null;


    public ref CNmEventTargetEntity_t Target { get; }

    public string AttributeName { get; set; }

    public ref CNmClipDocEvent_EntityAttribute_Type_t ValueType { get; }

    public ref int IntValue { get; }

    // CPiecewiseCurve
    public SchemaUntypedField FloatValue { get; }


}