// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmClipDocEvent_TargetWarp : CNmClipDocEvent, ISchemaClass<CNmClipDocEvent_TargetWarp>
{
    static CNmClipDocEvent_TargetWarp ISchemaClass<CNmClipDocEvent_TargetWarp>.From(nint handle) => new CNmClipDocEvent_TargetWarpImpl(handle);
    static int ISchemaClass<CNmClipDocEvent_TargetWarp>.Size => 32;
    static string? ISchemaClass<CNmClipDocEvent_TargetWarp>.ClassName => null;


    public ref NmTargetWarpRule_t Rule { get; }

    public ref NmTargetWarpAlgorithm_t Algorithm { get; }


}