// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmClipDocEvent_Particle : CNmClipDocEvent, ISchemaClass<CNmClipDocEvent_Particle>
{
    static CNmClipDocEvent_Particle ISchemaClass<CNmClipDocEvent_Particle>.From(nint handle) => new CNmClipDocEvent_ParticleImpl(handle);
    static int ISchemaClass<CNmClipDocEvent_Particle>.Size => 112;
    static string? ISchemaClass<CNmClipDocEvent_Particle>.ClassName => null;


    public ref CNmEventRelevance_t Relevance { get; }

    public ref CNmParticleEvent__Type_t Type { get; }

    public ref CNmEventTargetEntity_t Target { get; }

    public string ParticleSystem { get; set; }

    public ref bool DetachFromOwner { get; }

    public ref bool StopImmediately { get; }

    public ref bool PlayEndCap { get; }

    public string AttachmentPoint0 { get; set; }

    public ref ParticleAttachment_t AttachmentType0 { get; }

    public string AttachmentPoint1 { get; set; }

    public ref ParticleAttachment_t AttachmentType1 { get; }

    public string Config { get; set; }

    public string EffectForConfig { get; set; }

    public string Tags { get; set; }


}