// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmClipDocEvent_FrameSnap : CNmClipDocEvent, ISchemaClass<CNmClipDocEvent_FrameSnap>
{
    static CNmClipDocEvent_FrameSnap ISchemaClass<CNmClipDocEvent_FrameSnap>.From(nint handle) => new CNmClipDocEvent_FrameSnapImpl(handle);
    static int ISchemaClass<CNmClipDocEvent_FrameSnap>.Size => 32;
    static string? ISchemaClass<CNmClipDocEvent_FrameSnap>.ClassName => null;


    public ref NmFrameSnapEventMode_t FrameSnapMode { get; }


}