// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmClipDocEvent_CameraFOV : CNmClipDocEvent, ISchemaClass<CNmClipDocEvent_CameraFOV>
{
    static CNmClipDocEvent_CameraFOV ISchemaClass<CNmClipDocEvent_CameraFOV>.From(nint handle) => new CNmClipDocEvent_CameraFOVImpl(handle);
    static int ISchemaClass<CNmClipDocEvent_CameraFOV>.Size => 88;
    static string? ISchemaClass<CNmClipDocEvent_CameraFOV>.ClassName => null;


    // CPiecewiseCurve
    public SchemaUntypedField Curve { get; }


}