// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmClipDocEvent_CameraDOF : CNmClipDocEvent, ISchemaClass<CNmClipDocEvent_CameraDOF>
{
    static CNmClipDocEvent_CameraDOF ISchemaClass<CNmClipDocEvent_CameraDOF>.From(nint handle) => new CNmClipDocEvent_CameraDOFImpl(handle);
    static int ISchemaClass<CNmClipDocEvent_CameraDOF>.Size => 88;
    static string? ISchemaClass<CNmClipDocEvent_CameraDOF>.ClassName => null;


    // CPiecewiseCurve
    public SchemaUntypedField Curve { get; }


}