// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmEventConsumerCamera : CNmEventConsumer, ISchemaClass<CNmEventConsumerCamera>
{
    static CNmEventConsumerCamera ISchemaClass<CNmEventConsumerCamera>.From(nint handle) => new CNmEventConsumerCameraImpl(handle);
    static int ISchemaClass<CNmEventConsumerCamera>.Size => 176;
    static string? ISchemaClass<CNmEventConsumerCamera>.ClassName => null;

}