// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocTimeConditionNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocTimeConditionNode>
{
    static CNmGraphDocTimeConditionNode ISchemaClass<CNmGraphDocTimeConditionNode>.From(nint handle) => new CNmGraphDocTimeConditionNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocTimeConditionNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocTimeConditionNode>.ClassName => null;


    public ref float Comparand { get; }

    public ref CNmTimeConditionNode__ComparisonType_t Type { get; }

    public ref CNmTimeConditionNode__Operator_t Operator { get; }


}