// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocCommentNode : CNmGraphDocNode, ISchemaClass<CNmGraphDocCommentNode>
{
    static CNmGraphDocCommentNode ISchemaClass<CNmGraphDocCommentNode>.From(nint handle) => new CNmGraphDocCommentNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocCommentNode>.Size => 112;
    static string? ISchemaClass<CNmGraphDocCommentNode>.ClassName => null;


    public ref Vector2D Size { get; }

    public string Comment { get; set; }

    public ref Color NodeColor { get; }


}