// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocLayerBaseNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocLayerBaseNode>
{
    static CNmGraphDocLayerBaseNode ISchemaClass<CNmGraphDocLayerBaseNode>.From(nint handle) => new CNmGraphDocLayerBaseNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocLayerBaseNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocLayerBaseNode>.ClassName => null;


    public ref bool IsSynchronized { get; }

    public ref bool IgnoreEvents { get; }

    public ref NmPoseBlendMode_t BlendMode { get; }


}