// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocReferencePoseNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocReferencePoseNode>
{
    static CNmGraphDocReferencePoseNode ISchemaClass<CNmGraphDocReferencePoseNode>.From(nint handle) => new CNmGraphDocReferencePoseNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocReferencePoseNode>.Size => 264;
    static string? ISchemaClass<CNmGraphDocReferencePoseNode>.ClassName => null;

}