// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocIDBasedClipSelectorNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocIDBasedClipSelectorNode>
{
    static CNmGraphDocIDBasedClipSelectorNode ISchemaClass<CNmGraphDocIDBasedClipSelectorNode>.From(nint handle) => new CNmGraphDocIDBasedClipSelectorNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocIDBasedClipSelectorNode>.Size => 296;
    static string? ISchemaClass<CNmGraphDocIDBasedClipSelectorNode>.ClassName => null;


    public ref CUtlVector<CUtlString> OptionLabels { get; }

    public ref bool IgnoreInvalidOptions { get; }


}