// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocFloatMathNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocFloatMathNode>
{
    static CNmGraphDocFloatMathNode ISchemaClass<CNmGraphDocFloatMathNode>.From(nint handle) => new CNmGraphDocFloatMathNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocFloatMathNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocFloatMathNode>.ClassName => null;


    public ref bool ReturnAbsoluteResult { get; }

    public ref bool ReturnNegatedResult { get; }

    public ref CNmFloatMathNode__Operator_t Operator { get; }

    public ref float ValueB { get; }


}