// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocIDEventNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocIDEventNode>
{
    static CNmGraphDocIDEventNode ISchemaClass<CNmGraphDocIDEventNode>.From(nint handle) => new CNmGraphDocIDEventNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocIDEventNode>.Size => 280;
    static string? ISchemaClass<CNmGraphDocIDEventNode>.ClassName => null;


    public ref CGlobalSymbol DefaultValue { get; }

    public ref bool LimitSearchToSourceState { get; }

    public ref NmEventPriorityRule_t PriorityRule { get; }

    public ref bool IgnoreInactiveBranchEvents { get; }


}