// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocFlowNode : CNmGraphDocNode, ISchemaClass<CNmGraphDocFlowNode>
{
    static CNmGraphDocFlowNode ISchemaClass<CNmGraphDocFlowNode>.From(nint handle) => new CNmGraphDocFlowNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocFlowNode>.Size => 264;
    static string? ISchemaClass<CNmGraphDocFlowNode>.ClassName => null;


    // CUtlLeanVectorFixedGrowable< NmGraphDocPin_t, 4 >
    public SchemaUntypedField InputPins { get; }

    // CUtlLeanVectorFixedGrowable< NmGraphDocPin_t, 1 >
    public SchemaUntypedField OutputPins { get; }


}