// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocVectorResultNode : CNmGraphDocResultNode, ISchemaClass<CNmGraphDocVectorResultNode>
{
    static CNmGraphDocVectorResultNode ISchemaClass<CNmGraphDocVectorResultNode>.From(nint handle) => new CNmGraphDocVectorResultNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocVectorResultNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocVectorResultNode>.ClassName => null;

}