// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocParameterizedSelectorNode : CNmGraphDocVariationDataNode, ISchemaClass<CNmGraphDocParameterizedSelectorNode>
{
    static CNmGraphDocParameterizedSelectorNode ISchemaClass<CNmGraphDocParameterizedSelectorNode>.From(nint handle) => new CNmGraphDocParameterizedSelectorNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocParameterizedSelectorNode>.Size => 552;
    static string? ISchemaClass<CNmGraphDocParameterizedSelectorNode>.ClassName => null;


    public ref CUtlVector<CUtlString> OptionLabels { get; }

    public ref bool IgnoreInvalidOptions { get; }


}