// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocTargetResultNode : CNmGraphDocResultNode, ISchemaClass<CNmGraphDocTargetResultNode>
{
    static CNmGraphDocTargetResultNode ISchemaClass<CNmGraphDocTargetResultNode>.From(nint handle) => new CNmGraphDocTargetResultNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocTargetResultNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocTargetResultNode>.ClassName => null;

}