// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocFloatSelectorNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocFloatSelectorNode>
{
    static CNmGraphDocFloatSelectorNode ISchemaClass<CNmGraphDocFloatSelectorNode>.From(nint handle) => new CNmGraphDocFloatSelectorNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocFloatSelectorNode>.Size => 304;
    static string? ISchemaClass<CNmGraphDocFloatSelectorNode>.ClassName => null;


    public ref CUtlVector<CNmGraphDocFloatSelectorNode__Option_t> Options { get; }

    public ref float DefaultValue { get; }

    public ref NmEasingOperation_t Easing { get; }

    public ref float EaseTime { get; }


}