// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocBoneMaskBlendNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocBoneMaskBlendNode>
{
    static CNmGraphDocBoneMaskBlendNode ISchemaClass<CNmGraphDocBoneMaskBlendNode>.From(nint handle) => new CNmGraphDocBoneMaskBlendNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocBoneMaskBlendNode>.Size => 264;
    static string? ISchemaClass<CNmGraphDocBoneMaskBlendNode>.ClassName => null;

}