// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CnmGraphDocSnapWeaponNode : CNmGraphDocFlowNode, ISchemaClass<CnmGraphDocSnapWeaponNode>
{
    static CnmGraphDocSnapWeaponNode ISchemaClass<CnmGraphDocSnapWeaponNode>.From(nint handle) => new CnmGraphDocSnapWeaponNodeImpl(handle);
    static int ISchemaClass<CnmGraphDocSnapWeaponNode>.Size => 264;
    static string? ISchemaClass<CnmGraphDocSnapWeaponNode>.ClassName => null;

}