// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocEntryOverrideNode : CNmGraphDocResultNode, ISchemaClass<CNmGraphDocEntryOverrideNode>
{
    static CNmGraphDocEntryOverrideNode ISchemaClass<CNmGraphDocEntryOverrideNode>.From(nint handle) => new CNmGraphDocEntryOverrideNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocEntryOverrideNode>.Size => 288;
    static string? ISchemaClass<CNmGraphDocEntryOverrideNode>.ClassName => null;


    // V_uuid_t
    public SchemaUntypedField StateID { get; }


}