// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocIDVirtualParameterNode : CNmGraphDocVirtualParameterNode, ISchemaClass<CNmGraphDocIDVirtualParameterNode>
{
    static CNmGraphDocIDVirtualParameterNode ISchemaClass<CNmGraphDocIDVirtualParameterNode>.From(nint handle) => new CNmGraphDocIDVirtualParameterNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocIDVirtualParameterNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocIDVirtualParameterNode>.ClassName => null;

}