// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocIDResultNode : CNmGraphDocResultNode, ISchemaClass<CNmGraphDocIDResultNode>
{
    static CNmGraphDocIDResultNode ISchemaClass<CNmGraphDocIDResultNode>.From(nint handle) => new CNmGraphDocIDResultNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocIDResultNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocIDResultNode>.ClassName => null;

}