// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocAimCSNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocAimCSNode>
{
    static CNmGraphDocAimCSNode ISchemaClass<CNmGraphDocAimCSNode>.From(nint handle) => new CNmGraphDocAimCSNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocAimCSNode>.Size => 280;
    static string? ISchemaClass<CNmGraphDocAimCSNode>.ClassName => null;


    public ref float ActionBlendTimeSeconds { get; }

    public ref float HandIKBlendInTimeSeconds { get; }

    public ref float PlantingBlendTimeSeconds { get; }


}