// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocTransitionConduitNode : CNmGraphDocStateMachineGraphNode, ISchemaClass<CNmGraphDocTransitionConduitNode>
{
    static CNmGraphDocTransitionConduitNode ISchemaClass<CNmGraphDocTransitionConduitNode>.From(nint handle) => new CNmGraphDocTransitionConduitNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocTransitionConduitNode>.Size => 120;
    static string? ISchemaClass<CNmGraphDocTransitionConduitNode>.ClassName => null;


    // V_uuid_t
    public SchemaUntypedField StartStateID { get; }

    // V_uuid_t
    public SchemaUntypedField EndStateID { get; }


}