// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocTimeControlledClipNode : CNmGraphDocVariationDataNode, ISchemaClass<CNmGraphDocTimeControlledClipNode>
{
    static CNmGraphDocTimeControlledClipNode ISchemaClass<CNmGraphDocTimeControlledClipNode>.From(nint handle) => new CNmGraphDocTimeControlledClipNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocTimeControlledClipNode>.Size => 552;
    static string? ISchemaClass<CNmGraphDocTimeControlledClipNode>.ClassName => null;


    public ref bool SampleRootMotion { get; }

    public ref CUtlVector<CGlobalSymbol> GraphEvents { get; }


}