// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CnmGraphDocSpeedScaleNode : CNmGraphDocFlowNode, ISchemaClass<CnmGraphDocSpeedScaleNode>
{
    static CnmGraphDocSpeedScaleNode ISchemaClass<CnmGraphDocSpeedScaleNode>.From(nint handle) => new CnmGraphDocSpeedScaleNodeImpl(handle);
    static int ISchemaClass<CnmGraphDocSpeedScaleNode>.Size => 272;
    static string? ISchemaClass<CnmGraphDocSpeedScaleNode>.ClassName => null;


    public ref float Multiplier { get; }


}