// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocSyncEventIndexConditionNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocSyncEventIndexConditionNode>
{
    static CNmGraphDocSyncEventIndexConditionNode ISchemaClass<CNmGraphDocSyncEventIndexConditionNode>.From(nint handle) => new CNmGraphDocSyncEventIndexConditionNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocSyncEventIndexConditionNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocSyncEventIndexConditionNode>.ClassName => null;


    public ref CNmSyncEventIndexConditionNode__TriggerMode_t TriggerMode { get; }

    public ref int SyncEventIdx { get; }


}