// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocParameterReferenceNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocParameterReferenceNode>
{
    static CNmGraphDocParameterReferenceNode ISchemaClass<CNmGraphDocParameterReferenceNode>.From(nint handle) => new CNmGraphDocParameterReferenceNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocParameterReferenceNode>.Size => 312;
    static string? ISchemaClass<CNmGraphDocParameterReferenceNode>.ClassName => null;


    // V_uuid_t
    public SchemaUntypedField ParameterUUID { get; }

    public ref NmGraphValueType_t ParameterValueType { get; }

    public string ParameterName { get; set; }

    public string ParameterGroupName { get; set; }


}