// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocExternalPoseNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocExternalPoseNode>
{
    static CNmGraphDocExternalPoseNode ISchemaClass<CNmGraphDocExternalPoseNode>.From(nint handle) => new CNmGraphDocExternalPoseNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocExternalPoseNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocExternalPoseNode>.ClassName => null;


    public ref bool ShouldSampleRootMotion { get; }


}