// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocFloatResultNode : CNmGraphDocResultNode, ISchemaClass<CNmGraphDocFloatResultNode>
{
    static CNmGraphDocFloatResultNode ISchemaClass<CNmGraphDocFloatResultNode>.From(nint handle) => new CNmGraphDocFloatResultNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocFloatResultNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocFloatResultNode>.ClassName => null;

}