// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CnmGraphDocDurationScaleNode : CNmGraphDocFlowNode, ISchemaClass<CnmGraphDocDurationScaleNode>
{
    static CnmGraphDocDurationScaleNode ISchemaClass<CnmGraphDocDurationScaleNode>.From(nint handle) => new CnmGraphDocDurationScaleNodeImpl(handle);
    static int ISchemaClass<CnmGraphDocDurationScaleNode>.Size => 272;
    static string? ISchemaClass<CnmGraphDocDurationScaleNode>.ClassName => null;


    public ref float DesiredDuration { get; }


}