// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocSelectorConditionNode : CNmGraphDocResultNode, ISchemaClass<CNmGraphDocSelectorConditionNode>
{
    static CNmGraphDocSelectorConditionNode ISchemaClass<CNmGraphDocSelectorConditionNode>.From(nint handle) => new CNmGraphDocSelectorConditionNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocSelectorConditionNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocSelectorConditionNode>.ClassName => null;

}