// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocument : CNmAnimDocument, ISchemaClass<CNmGraphDocument>
{
    static CNmGraphDocument ISchemaClass<CNmGraphDocument>.From(nint handle) => new CNmGraphDocumentImpl(handle);
    static int ISchemaClass<CNmGraphDocument>.Size => 200;
    static string? ISchemaClass<CNmGraphDocument>.ClassName => null;


    public CNmGraphDocFlowGraph? RootGraph { get; }

    public CNmVariationHierarchy VariationHierarchy { get; }

    public ref CUtlLeanVector<CNmGraphDocument__DebugParameterSet_t, int> DebugParameterSets { get; }

    public ref CUtlLeanVector<CNmGraphDocument__DebugBoneFilterSet_t, int> DebugBoneFilterSets { get; }

    public ref CUtlVector<SchemaUntypedField> DictionaryIDSetIDs { get; }


}