// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CnmGraphDocFootIKNode : CNmGraphDocVariationDataNode, ISchemaClass<CnmGraphDocFootIKNode>
{
    static CnmGraphDocFootIKNode ISchemaClass<CnmGraphDocFootIKNode>.From(nint handle) => new CnmGraphDocFootIKNodeImpl(handle);
    static int ISchemaClass<CnmGraphDocFootIKNode>.Size => 528;
    static string? ISchemaClass<CnmGraphDocFootIKNode>.ClassName => null;


    public ref bool IsTargetInWorldSpace { get; }

    public ref NmIKBlendMode_t BlendMode { get; }


}