// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocVectorVirtualParameterNode : CNmGraphDocVirtualParameterNode, ISchemaClass<CNmGraphDocVectorVirtualParameterNode>
{
    static CNmGraphDocVectorVirtualParameterNode ISchemaClass<CNmGraphDocVectorVirtualParameterNode>.From(nint handle) => new CNmGraphDocVectorVirtualParameterNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocVectorVirtualParameterNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocVectorVirtualParameterNode>.ClassName => null;

}