// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocLocalLayerNode : CNmGraphDocLayerBaseNode, ISchemaClass<CNmGraphDocLocalLayerNode>
{
    static CNmGraphDocLocalLayerNode ISchemaClass<CNmGraphDocLocalLayerNode>.From(nint handle) => new CNmGraphDocLocalLayerNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocLocalLayerNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocLocalLayerNode>.ClassName => null;

}