// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocVectorControlParameterNode : CNmGraphDocControlParameterNode, ISchemaClass<CNmGraphDocVectorControlParameterNode>
{
    static CNmGraphDocVectorControlParameterNode ISchemaClass<CNmGraphDocVectorControlParameterNode>.From(nint handle) => new CNmGraphDocVectorControlParameterNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocVectorControlParameterNode>.Size => 304;
    static string? ISchemaClass<CNmGraphDocVectorControlParameterNode>.ClassName => null;


    public ref Vector PreviewStartValue { get; }


}