// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocFootEventConditionNode : CNmGraphDocFlowNode, ISchemaClass<CNmGraphDocFootEventConditionNode>
{
    static CNmGraphDocFootEventConditionNode ISchemaClass<CNmGraphDocFootEventConditionNode>.From(nint handle) => new CNmGraphDocFootEventConditionNodeImpl(handle);
    static int ISchemaClass<CNmGraphDocFootEventConditionNode>.Size => 272;
    static string? ISchemaClass<CNmGraphDocFootEventConditionNode>.ClassName => null;


    public ref NmFootPhaseCondition_t PhaseCondition { get; }

    public ref bool LimitSearchToSourceState { get; }

    public ref bool IgnoreInactiveBranchEvents { get; }


}