// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CodeGenAABB_t : ISchemaClass<CodeGenAABB_t>
{
    static CodeGenAABB_t ISchemaClass<CodeGenAABB_t>.From(nint handle) => new CodeGenAABB_tImpl(handle);
    static int ISchemaClass<CodeGenAABB_t>.Size => 24;
    static string? ISchemaClass<CodeGenAABB_t>.ClassName => null;


    public ref Vector MinBounds { get; }

    public ref Vector MaxBounds { get; }

    public void MinBoundsUpdated();
    public void MaxBoundsUpdated();
}