// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPathWithDynamicNodes : CPathSimple, ISchemaClass<CPathWithDynamicNodes>
{
    static CPathWithDynamicNodes ISchemaClass<CPathWithDynamicNodes>.From(nint handle) => new CPathWithDynamicNodesImpl(handle);
    static int ISchemaClass<CPathWithDynamicNodes>.Size => 1520;
    static string? ISchemaClass<CPathWithDynamicNodes>.ClassName => null;


    public ref CUtlVector<CHandle<CPathNode>> PathNodes { get; }

    public ref CTransform XInitialPathWorldToLocal { get; }

    public void PathNodesUpdated();
    public void XInitialPathWorldToLocalUpdated();
}