// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPathMoverEntitySpawner : CLogicalEntity, ISchemaClass<CPathMoverEntitySpawner>
{
    static CPathMoverEntitySpawner ISchemaClass<CPathMoverEntitySpawner>.From(nint handle) => new CPathMoverEntitySpawnerImpl(handle);
    static int ISchemaClass<CPathMoverEntitySpawner>.Size => 1288;
    static string? ISchemaClass<CPathMoverEntitySpawner>.ClassName => null;


    public ISchemaStringFixedArray SpawnTemplates { get; }

    public ref int SpawnIndex { get; }

    public ref CHandle<CPathMover> PathMover { get; }

    public ref float SpawnFrequencySeconds { get; }

    public ref float SpawnFrequencyDistToNearestMover { get; }

    // CUtlHashtable< CHandle< CFuncMover >, CPathMoverEntitySpawn >
    public SchemaUntypedField MapSpawnedMoverTemplates { get; }

    public ref int MaxActive { get; }

    public GameTime_t LastSpawnTime { get; }

    public ref bool Enabled { get; }


}