// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_ApplyEntityFlags : CPulseCell_BaseYieldingInflow, ISchemaClass<CPulseCell_ApplyEntityFlags>
{
    static CPulseCell_ApplyEntityFlags ISchemaClass<CPulseCell_ApplyEntityFlags>.From(nint handle) => new CPulseCell_ApplyEntityFlagsImpl(handle);
    static int ISchemaClass<CPulseCell_ApplyEntityFlags>.Size => 216;
    static string? ISchemaClass<CPulseCell_ApplyEntityFlags>.ClassName => null;

}