// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulse_TempVarBankDefinition : ISchemaClass<CPulse_TempVarBankDefinition>
{
    static CPulse_TempVarBankDefinition ISchemaClass<CPulse_TempVarBankDefinition>.From(nint handle) => new CPulse_TempVarBankDefinitionImpl(handle);
    static int ISchemaClass<CPulse_TempVarBankDefinition>.Size => 40;
    static string? ISchemaClass<CPulse_TempVarBankDefinition>.ClassName => null;


    public ref CUtlVector<CPulse_TempVarInfo> TempVars { get; }


}