// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_ApplyDynamicAttributeBase : CPulseCell_BaseYieldingInflow, ISchemaClass<CPulseCell_ApplyDynamicAttributeBase>
{
    static CPulseCell_ApplyDynamicAttributeBase ISchemaClass<CPulseCell_ApplyDynamicAttributeBase>.From(nint handle) => new CPulseCell_ApplyDynamicAttributeBaseImpl(handle);
    static int ISchemaClass<CPulseCell_ApplyDynamicAttributeBase>.Size => 216;
    static string? ISchemaClass<CPulseCell_ApplyDynamicAttributeBase>.ClassName => null;

}