// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_ApplyDynamicAttributeBase__CursorState_t : ISchemaClass<CPulseCell_ApplyDynamicAttributeBase__CursorState_t>
{
    static CPulseCell_ApplyDynamicAttributeBase__CursorState_t ISchemaClass<CPulseCell_ApplyDynamicAttributeBase__CursorState_t>.From(nint handle) => new CPulseCell_ApplyDynamicAttributeBase__CursorState_tImpl(handle);
    static int ISchemaClass<CPulseCell_ApplyDynamicAttributeBase__CursorState_t>.Size => 16;
    static string? ISchemaClass<CPulseCell_ApplyDynamicAttributeBase__CursorState_t>.ClassName => null;


    public ref CHandle<CBaseEntity> Entity { get; }

    public string AttributeKey { get; set; }


}