// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSimpleAssetTypeInfo : ISchemaClass<CSimpleAssetTypeInfo>
{
    static CSimpleAssetTypeInfo ISchemaClass<CSimpleAssetTypeInfo>.From(nint handle) => new CSimpleAssetTypeInfoImpl(handle);
    static int ISchemaClass<CSimpleAssetTypeInfo>.Size => 264;
    static string? ISchemaClass<CSimpleAssetTypeInfo>.ClassName => null;


    public string FriendlyName { get; set; }

    public string Ext { get; set; }

    public string IconLg { get; set; }

    public string IconSm { get; set; }

    public ref CUtlVector<CUtlString> SuppressSubstrings { get; }

    public ref CUtlVector<CUtlString> AdditionalExtensions { get; }

    public ref CUtlVector<AssetEngineCommand_t> EngineCommands { get; }

    public ref CUtlVector<CUtlString> LimitToMods { get; }

    public ref CUtlVector<CUtlString> ExcludeFromMods { get; }

    public ref CUtlVector<CUtlString> HideForRetailMods { get; }

    public string PreviewThumbnailOverlayIcon { get; set; }

    public ref bool ErrorOnUnrecognizedOutboundRefs { get; }

    public ref CUtlVector<CUtlString> UnrecognizedOutboundRefsErrorTypeExceptions { get; }

    public ref bool HideTypeByDefault { get; }

    public ref bool CannotBeShown { get; }

    public ref bool IsNontrivialChildAssetType { get; }

    public ref bool SuppressFullFingerprintCalculation { get; }

    public ref bool IgnoreCompiledState { get; }

    public ref bool ContentFileIsText { get; }

    public ref bool PrefersLivePreview { get; }

    public ref bool PresentInGameTree { get; }

    public ref bool ShouldCompileErrorFallbackToDisk { get; }

    public ref int AssetTypeVersion { get; }

    public ref int AssetThumbnailVersion { get; }

    public string Test_InjectSearchable { get; set; }


}