// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSkyCameraVolume : CBaseEntity, ISchemaClass<CSkyCameraVolume>
{
    static CSkyCameraVolume ISchemaClass<CSkyCameraVolume>.From(nint handle) => new CSkyCameraVolumeImpl(handle);
    static int ISchemaClass<CSkyCameraVolume>.Size => 1280;
    static string? ISchemaClass<CSkyCameraVolume>.ClassName => "sky_camera_volume";


    public ref Vector BoxMins { get; }

    public ref Vector BoxMaxs { get; }

    public ref CHandle<CSkyCameraVolumeTarget> Target { get; }

    public ref int Priority { get; }

    public ref bool IsEnabled { get; }

    public ref bool SkyboxBlurEffect { get; }

    public ref Vector BlurOrigin { get; }

    public ref bool SkyboxReceivesWorldCsm { get; }

    public ref bool WorldReceivesSkyboxCsm { get; }

    public ref bool StartDisabled { get; }

    public string TargetName { get; set; }

    public void BoxMinsUpdated();
    public void BoxMaxsUpdated();
    public void TargetUpdated();
    public void PriorityUpdated();
    public void IsEnabledUpdated();
    public void SkyboxBlurEffectUpdated();
    public void BlurOriginUpdated();
    public void SkyboxReceivesWorldCsmUpdated();
    public void WorldReceivesSkyboxCsmUpdated();
}