// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIO : CLogicalEntity, ISchemaClass<CTestPulseIO>
{
    static CTestPulseIO ISchemaClass<CTestPulseIO>.From(nint handle) => new CTestPulseIOImpl(handle);
    static int ISchemaClass<CTestPulseIO>.Size => 1424;
    static string? ISchemaClass<CTestPulseIO>.ClassName => "test_io_combinations";


    public ref CEntityIOOutput OnVariantVoid { get; }

    // CEntityOutputTemplate< bool, bool >
    public SchemaUntypedField OnVariantBool { get; }

    // CEntityOutputTemplate< int32, int32 >
    public SchemaUntypedField OnVariantInt { get; }

    // CEntityOutputTemplate< float32, float32 >
    public SchemaUntypedField OnVariantFloat { get; }

    // CEntityOutputTemplate< CUtlSymbolLarge, CUtlSymbolLarge >
    public SchemaUntypedField OnVariantString { get; }

    // CEntityOutputTemplate< Color, Color >
    public SchemaUntypedField OnVariantColor { get; }

    // CEntityOutputTemplate< Vector, Vector >
    public SchemaUntypedField OnVariantVector { get; }

    public ref bool AllowEmptyInputs { get; }


}