// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixPresetDSPProcessorDesc : CVMixBaseProcessorDesc, ISchemaClass<CVMixPresetDSPProcessorDesc>
{
    static CVMixPresetDSPProcessorDesc ISchemaClass<CVMixPresetDSPProcessorDesc>.From(nint handle) => new CVMixPresetDSPProcessorDescImpl(handle);
    static int ISchemaClass<CVMixPresetDSPProcessorDesc>.Size => 48;
    static string? ISchemaClass<CVMixPresetDSPProcessorDesc>.ClassName => null;


    public VMixPresetDSPDesc_t Desc { get; }


}