// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixSteamAudioHybridReverbProcessorDesc : CVMixBaseProcessorDesc, ISchemaClass<CVMixSteamAudioHybridReverbProcessorDesc>
{
    static CVMixSteamAudioHybridReverbProcessorDesc ISchemaClass<CVMixSteamAudioHybridReverbProcessorDesc>.From(nint handle) => new CVMixSteamAudioHybridReverbProcessorDescImpl(handle);
    static int ISchemaClass<CVMixSteamAudioHybridReverbProcessorDesc>.Size => 32;
    static string? ISchemaClass<CVMixSteamAudioHybridReverbProcessorDesc>.ClassName => null;




}