// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixShaperProcessorDesc : CVMixBaseProcessorDesc, ISchemaClass<CVMixShaperProcessorDesc>
{
    static CVMixShaperProcessorDesc ISchemaClass<CVMixShaperProcessorDesc>.From(nint handle) => new CVMixShaperProcessorDescImpl(handle);
    static int ISchemaClass<CVMixShaperProcessorDesc>.Size => 56;
    static string? ISchemaClass<CVMixShaperProcessorDesc>.ClassName => null;


    public VMixShaperDesc_t Desc { get; }


}