// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixGraphInput : CVMixInputBase, ISchemaClass<CVMixGraphInput>
{
    static CVMixGraphInput ISchemaClass<CVMixGraphInput>.From(nint handle) => new CVMixGraphInputImpl(handle);
    static int ISchemaClass<CVMixGraphInput>.Size => 24;
    static string? ISchemaClass<CVMixGraphInput>.ClassName => null;


    public CVMixDataOffset Offset { get; }


}