// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixVsndInput : ISchemaClass<CVMixVsndInput>
{
    static CVMixVsndInput ISchemaClass<CVMixVsndInput>.From(nint handle) => new CVMixVsndInputImpl(handle);
    static int ISchemaClass<CVMixVsndInput>.Size => 24;
    static string? ISchemaClass<CVMixVsndInput>.ClassName => null;


    public string DefaultValue { get; set; }


}