// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixControlInput : CVMixInputBase, ISchemaClass<CVMixControlInput>
{
    static CVMixControlInput ISchemaClass<CVMixControlInput>.From(nint handle) => new CVMixControlInputImpl(handle);
    static int ISchemaClass<CVMixControlInput>.Size => 24;
    static string? ISchemaClass<CVMixControlInput>.ClassName => null;


    public ref float DefaultValue { get; }


}