// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixCurveHeader : ISchemaClass<CVMixCurveHeader>
{
    static CVMixCurveHeader ISchemaClass<CVMixCurveHeader>.From(nint handle) => new CVMixCurveHeaderImpl(handle);
    static int ISchemaClass<CVMixCurveHeader>.Size => 8;
    static string? ISchemaClass<CVMixCurveHeader>.ClassName => null;


    public ref uint ControlPointCount { get; }

    public ref uint ControlPointStart { get; }


}