// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixDualCompressorProcessorDesc : CVMixBaseProcessorDesc, ISchemaClass<CVMixDualCompressorProcessorDesc>
{
    static CVMixDualCompressorProcessorDesc ISchemaClass<CVMixDualCompressorProcessorDesc>.From(nint handle) => new CVMixDualCompressorProcessorDescImpl(handle);
    static int ISchemaClass<CVMixDualCompressorProcessorDesc>.Size => 88;
    static string? ISchemaClass<CVMixDualCompressorProcessorDesc>.ClassName => null;


    public VMixDualCompressorDesc_t Desc { get; }


}