// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMMDAssetTypeInfo : CSimpleAssetTypeInfo, ISchemaClass<CVMMDAssetTypeInfo>
{
    static CVMMDAssetTypeInfo ISchemaClass<CVMMDAssetTypeInfo>.From(nint handle) => new CVMMDAssetTypeInfoImpl(handle);
    static int ISchemaClass<CVMMDAssetTypeInfo>.Size => 264;
    static string? ISchemaClass<CVMMDAssetTypeInfo>.ClassName => null;

}