// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerTapePlayer : CVoiceContainerAsyncGenerator, ISchemaClass<CVoiceContainerTapePlayer>
{
    static CVoiceContainerTapePlayer ISchemaClass<CVoiceContainerTapePlayer>.From(nint handle) => new CVoiceContainerTapePlayerImpl(handle);
    static int ISchemaClass<CVoiceContainerTapePlayer>.Size => 248;
    static string? ISchemaClass<CVoiceContainerTapePlayer>.ClassName => null;


    public ref bool ShouldWraparound { get; }

    public ref CStrongHandle<InfoForResourceTypeCVoiceContainerBase> SourceAudio { get; }

    public ref float TapeSpeedAttackTime { get; }

    public ref float TapeSpeedReleaseTime { get; }


}