// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerGenerator : CVoiceContainerBase, ISchemaClass<CVoiceContainerGenerator>
{
    static CVoiceContainerGenerator ISchemaClass<CVoiceContainerGenerator>.From(nint handle) => new CVoiceContainerGeneratorImpl(handle);
    static int ISchemaClass<CVoiceContainerGenerator>.Size => 168;
    static string? ISchemaClass<CVoiceContainerGenerator>.ClassName => null;




}