// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerVMixSnd : CVoiceContainerBase, ISchemaClass<CVoiceContainerVMixSnd>
{
    static CVoiceContainerVMixSnd ISchemaClass<CVoiceContainerVMixSnd>.From(nint handle) => new CVoiceContainerVMixSndImpl(handle);
    static int ISchemaClass<CVoiceContainerVMixSnd>.Size => 384;
    static string? ISchemaClass<CVoiceContainerVMixSnd>.ClassName => null;

}