// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface EventClientPreOutputParallelWithServer_t : EventClientPreOutput_t, ISchemaClass<EventClientPreOutputParallelWithServer_t>
{
    static EventClientPreOutputParallelWithServer_t ISchemaClass<EventClientPreOutputParallelWithServer_t>.From(nint handle) => new EventClientPreOutputParallelWithServer_tImpl(handle);
    static int ISchemaClass<EventClientPreOutputParallelWithServer_t>.Size => 72;
    static string? ISchemaClass<EventClientPreOutputParallelWithServer_t>.ClassName => null;




}