// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeSimdPrism_t : ISchemaClass<FeSimdPrism_t>
{
    static FeSimdPrism_t ISchemaClass<FeSimdPrism_t>.From(nint handle) => new FeSimdPrism_tImpl(handle);
    static int ISchemaClass<FeSimdPrism_t>.Size => 64;
    static string? ISchemaClass<FeSimdPrism_t>.ClassName => null;


    // uint16[4]
    public SchemaUntypedField Node { get; }

    public ref fltx4 Volume { get; }


}