// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface inv_image_camera_t : ISchemaClass<inv_image_camera_t>
{
    static inv_image_camera_t ISchemaClass<inv_image_camera_t>.From(nint handle) => new inv_image_camera_tImpl(handle);
    static int ISchemaClass<inv_image_camera_t>.Size => 56;
    static string? ISchemaClass<inv_image_camera_t>.ClassName => null;


    public ref QAngle Angle { get; }

    public ref float Fov_h { get; }

    public ref float Fov_v { get; }

    public ref float Znear { get; }

    public ref float Zfar { get; }

    public ref Vector Target { get; }

    public ref Vector Target_nudge { get; }

    public ref float Orbit_distance { get; }


}