// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface inv_image_data_t : ISchemaClass<inv_image_data_t>
{
    static inv_image_data_t ISchemaClass<inv_image_data_t>.From(nint handle) => new inv_image_data_tImpl(handle);
    static int ISchemaClass<inv_image_data_t>.Size => 240;
    static string? ISchemaClass<inv_image_data_t>.ClassName => null;


    public inv_image_map_t Map { get; }

    public inv_image_item_t Item { get; }

    public inv_image_camera_t Camera { get; }

    public inv_image_light_sun_t Lightsun { get; }

    public inv_image_light_fill_t Lightfill { get; }

    public inv_image_light_barn_t Light0 { get; }

    public inv_image_light_barn_t Light1 { get; }

    public inv_image_clearcolor_t Clearcolor { get; }


}