// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface NmContactAudioInfo_t : ISchemaClass<NmContactAudioInfo_t>
{
    static NmContactAudioInfo_t ISchemaClass<NmContactAudioInfo_t>.From(nint handle) => new NmContactAudioInfo_tImpl(handle);
    static int ISchemaClass<NmContactAudioInfo_t>.Size => 24;
    static string? ISchemaClass<NmContactAudioInfo_t>.ClassName => null;


    public ref CGlobalSymbol AudioActionID { get; }

    public ref CGlobalSymbol AudioTypeID { get; }

    public ref CGlobalSymbol SoundeventOverrideID { get; }


}