// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PulseRuntimeTempVarBankIndex_t : ISchemaClass<PulseRuntimeTempVarBankIndex_t>
{
    static PulseRuntimeTempVarBankIndex_t ISchemaClass<PulseRuntimeTempVarBankIndex_t>.From(nint handle) => new PulseRuntimeTempVarBankIndex_tImpl(handle);
    static int ISchemaClass<PulseRuntimeTempVarBankIndex_t>.Size => 2;
    static string? ISchemaClass<PulseRuntimeTempVarBankIndex_t>.ClassName => null;


    public ref short Value { get; }


}