// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface VMixFlangerDesc_t : ISchemaClass<VMixFlangerDesc_t>
{
    static VMixFlangerDesc_t ISchemaClass<VMixFlangerDesc_t>.From(nint handle) => new VMixFlangerDesc_tImpl(handle);
    static int ISchemaClass<VMixFlangerDesc_t>.Size => 36;
    static string? ISchemaClass<VMixFlangerDesc_t>.ClassName => null;


    public ref bool PhaseInvert { get; }

    public ref float GlideTime { get; }

    public ref float Delay { get; }

    public ref float OutputGain { get; }

    public ref float FeedbackGain { get; }

    public ref float FeedforwardGain { get; }

    public ref float ModRate { get; }

    public ref float ModDepth { get; }

    public ref bool ApplyAntialiasing { get; }


}