// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_CSGO_CounterTerroristRushIntroCameraImpl : C_CSGO_TeamPreviewCameraBoneImpl, C_CSGO_CounterTerroristRushIntroCamera
{
    public C_CSGO_CounterTerroristRushIntroCameraImpl(nint handle) : base(handle) { }

}