// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_ScaleVelocityImpl : CParticleFunctionInitializerImpl, C_INIT_ScaleVelocity
{
    public C_INIT_ScaleVelocityImpl(nint handle) : base(handle) { }

    private static nint? _ScaleOffset;
    private CParticleCollectionVecInputImpl? _ScaleInstance;

    public CParticleCollectionVecInput Scale
    {
        get
        {
            _ScaleOffset = _ScaleOffset ?? Schema.GetOffset(0xF226CCC35F596B51);
            var instance = _ScaleInstance ??= new CParticleCollectionVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _ScaleOffset!.Value);
            return instance;
        }
    }

}