// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_InitFromCPSnapshotImpl : CParticleFunctionInitializerImpl, C_INIT_InitFromCPSnapshot
{
    public C_INIT_InitFromCPSnapshotImpl(nint handle) : base(handle) { }

    private static nint? _ControlPointNumberOffset;

    public ref int ControlPointNumber
    {
        get
        {
            _ControlPointNumberOffset = _ControlPointNumberOffset ?? Schema.GetOffset(0x772EF71B3F31A6BD);
            return ref _Handle.AsRef<int>(_ControlPointNumberOffset!.Value);
        }
    }
    private static nint? _StrSnapshotSubsetOffset;

    public string StrSnapshotSubset
    {
        get
        {
            _StrSnapshotSubsetOffset = _StrSnapshotSubsetOffset ?? Schema.GetOffset(0x772EF71BBD8A8E5E);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrSnapshotSubsetOffset!.Value));
        }
        set
        {
            _StrSnapshotSubsetOffset = _StrSnapshotSubsetOffset ?? Schema.GetOffset(0x772EF71BBD8A8E5E);
            Schema.SetCUtlString(_Handle, _StrSnapshotSubsetOffset!.Value, value);
        }
    }
    private static nint? _AttributeToReadOffset;
    private ParticleAttributeIndex_tImpl? _AttributeToReadInstance;

    public ParticleAttributeIndex_t AttributeToRead
    {
        get
        {
            _AttributeToReadOffset = _AttributeToReadOffset ?? Schema.GetOffset(0x772EF71BE0F61F9E);
            var instance = _AttributeToReadInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _AttributeToReadOffset!.Value);
            return instance;
        }
    }
    private static nint? _AttributeToWriteOffset;
    private ParticleAttributeIndex_tImpl? _AttributeToWriteInstance;

    public ParticleAttributeIndex_t AttributeToWrite
    {
        get
        {
            _AttributeToWriteOffset = _AttributeToWriteOffset ?? Schema.GetOffset(0x772EF71B389A3CC1);
            var instance = _AttributeToWriteInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _AttributeToWriteOffset!.Value);
            return instance;
        }
    }
    private static nint? _LocalSpaceCPOffset;

    public ref int LocalSpaceCP
    {
        get
        {
            _LocalSpaceCPOffset = _LocalSpaceCPOffset ?? Schema.GetOffset(0x772EF71BC8E9CB31);
            return ref _Handle.AsRef<int>(_LocalSpaceCPOffset!.Value);
        }
    }
    private static nint? _RandomOffset;

    public ref bool Random
    {
        get
        {
            _RandomOffset = _RandomOffset ?? Schema.GetOffset(0x772EF71BD13B9DC2);
            return ref _Handle.AsRef<bool>(_RandomOffset!.Value);
        }
    }
    private static nint? _ReverseOffset;

    public ref bool Reverse
    {
        get
        {
            _ReverseOffset = _ReverseOffset ?? Schema.GetOffset(0x772EF71BEA4E22E5);
            return ref _Handle.AsRef<bool>(_ReverseOffset!.Value);
        }
    }
    private static nint? _SnapShotIncrementOffset;
    private CParticleCollectionFloatInputImpl? _SnapShotIncrementInstance;

    public CParticleCollectionFloatInput SnapShotIncrement
    {
        get
        {
            _SnapShotIncrementOffset = _SnapShotIncrementOffset ?? Schema.GetOffset(0x772EF71BC1AED602);
            var instance = _SnapShotIncrementInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _SnapShotIncrementOffset!.Value);
            return instance;
        }
    }
    private static nint? _ManualSnapshotIndexOffset;
    private CPerParticleFloatInputImpl? _ManualSnapshotIndexInstance;

    public CPerParticleFloatInput ManualSnapshotIndex
    {
        get
        {
            _ManualSnapshotIndexOffset = _ManualSnapshotIndexOffset ?? Schema.GetOffset(0x772EF71BA02E904D);
            var instance = _ManualSnapshotIndexInstance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _ManualSnapshotIndexOffset!.Value);
            return instance;
        }
    }
    private static nint? _RandomSeedOffset;

    public ref int RandomSeed
    {
        get
        {
            _RandomSeedOffset = _RandomSeedOffset ?? Schema.GetOffset(0x772EF71B6388F067);
            return ref _Handle.AsRef<int>(_RandomSeedOffset!.Value);
        }
    }
    private static nint? _LocalSpaceAnglesOffset;

    public ref bool LocalSpaceAngles
    {
        get
        {
            _LocalSpaceAnglesOffset = _LocalSpaceAnglesOffset ?? Schema.GetOffset(0x772EF71BF571F352);
            return ref _Handle.AsRef<bool>(_LocalSpaceAnglesOffset!.Value);
        }
    }

}