// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_CreateInEpitrochoidImpl : CParticleFunctionInitializerImpl, C_INIT_CreateInEpitrochoid
{
    public C_INIT_CreateInEpitrochoidImpl(nint handle) : base(handle) { }

    private static nint? _Component1Offset;

    public ref int Component1
    {
        get
        {
            _Component1Offset = _Component1Offset ?? Schema.GetOffset(0x3B16C41F125ABCA7);
            return ref _Handle.AsRef<int>(_Component1Offset!.Value);
        }
    }
    private static nint? _Component2Offset;

    public ref int Component2
    {
        get
        {
            _Component2Offset = _Component2Offset ?? Schema.GetOffset(0x3B16C41F135ABE3A);
            return ref _Handle.AsRef<int>(_Component2Offset!.Value);
        }
    }
    private static nint? _TransformInputOffset;
    private CParticleTransformInputImpl? _TransformInputInstance;

    public CParticleTransformInput TransformInput
    {
        get
        {
            _TransformInputOffset = _TransformInputOffset ?? Schema.GetOffset(0x3B16C41FB3FDC289);
            var instance = _TransformInputInstance ??= new CParticleTransformInputImpl(0);
            instance.DangerousSetHandle(_Handle + _TransformInputOffset!.Value);
            return instance;
        }
    }
    private static nint? _ParticleDensityOffset;
    private CPerParticleFloatInputImpl? _ParticleDensityInstance;

    public CPerParticleFloatInput ParticleDensity
    {
        get
        {
            _ParticleDensityOffset = _ParticleDensityOffset ?? Schema.GetOffset(0x3B16C41FF720B9EF);
            var instance = _ParticleDensityInstance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _ParticleDensityOffset!.Value);
            return instance;
        }
    }
    private static nint? _OffsetOffset;
    private CPerParticleFloatInputImpl? _OffsetInstance;

    public CPerParticleFloatInput Offset
    {
        get
        {
            _OffsetOffset = _OffsetOffset ?? Schema.GetOffset(0x3B16C41F7F14BA34);
            var instance = _OffsetInstance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _OffsetOffset!.Value);
            return instance;
        }
    }
    private static nint? _Radius1Offset;
    private CPerParticleFloatInputImpl? _Radius1Instance;

    public CPerParticleFloatInput Radius1
    {
        get
        {
            _Radius1Offset = _Radius1Offset ?? Schema.GetOffset(0x3B16C41FB10C67F4);
            var instance = _Radius1Instance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _Radius1Offset!.Value);
            return instance;
        }
    }
    private static nint? _Radius2Offset;
    private CPerParticleFloatInputImpl? _Radius2Instance;

    public CPerParticleFloatInput Radius2
    {
        get
        {
            _Radius2Offset = _Radius2Offset ?? Schema.GetOffset(0x3B16C41FB40C6CAD);
            var instance = _Radius2Instance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _Radius2Offset!.Value);
            return instance;
        }
    }
    private static nint? _UseCountOffset;

    public ref bool UseCount
    {
        get
        {
            _UseCountOffset = _UseCountOffset ?? Schema.GetOffset(0x3B16C41F8836B9AB);
            return ref _Handle.AsRef<bool>(_UseCountOffset!.Value);
        }
    }
    private static nint? _UseLocalCoordsOffset;

    public ref bool UseLocalCoords
    {
        get
        {
            _UseLocalCoordsOffset = _UseLocalCoordsOffset ?? Schema.GetOffset(0x3B16C41F8AB11575);
            return ref _Handle.AsRef<bool>(_UseLocalCoordsOffset!.Value);
        }
    }
    private static nint? _OffsetExistingPosOffset;

    public ref bool OffsetExistingPos
    {
        get
        {
            _OffsetExistingPosOffset = _OffsetExistingPosOffset ?? Schema.GetOffset(0x3B16C41F79DD329B);
            return ref _Handle.AsRef<bool>(_OffsetExistingPosOffset!.Value);
        }
    }

}