// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_SetVectorAttributeToVectorExpressionImpl : CParticleFunctionInitializerImpl, C_INIT_SetVectorAttributeToVectorExpression
{
    public C_INIT_SetVectorAttributeToVectorExpressionImpl(nint handle) : base(handle) { }

    private static nint? _ExpressionOffset;

    public ref VectorExpressionType_t Expression
    {
        get
        {
            _ExpressionOffset = _ExpressionOffset ?? Schema.GetOffset(0x71A0FB13160B2427);
            return ref _Handle.AsRef<VectorExpressionType_t>(_ExpressionOffset!.Value);
        }
    }
    private static nint? _Input1Offset;
    private CPerParticleVecInputImpl? _Input1Instance;

    public CPerParticleVecInput Input1
    {
        get
        {
            _Input1Offset = _Input1Offset ?? Schema.GetOffset(0x71A0FB13E17F27DA);
            var instance = _Input1Instance ??= new CPerParticleVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _Input1Offset!.Value);
            return instance;
        }
    }
    private static nint? _Input2Offset;
    private CPerParticleVecInputImpl? _Input2Instance;

    public CPerParticleVecInput Input2
    {
        get
        {
            _Input2Offset = _Input2Offset ?? Schema.GetOffset(0x71A0FB13E07F2647);
            var instance = _Input2Instance ??= new CPerParticleVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _Input2Offset!.Value);
            return instance;
        }
    }
    private static nint? _LerpOffset;
    private CPerParticleFloatInputImpl? _LerpInstance;

    public CPerParticleFloatInput Lerp
    {
        get
        {
            _LerpOffset = _LerpOffset ?? Schema.GetOffset(0x71A0FB13622FAB06);
            var instance = _LerpInstance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _LerpOffset!.Value);
            return instance;
        }
    }
    private static nint? _OutputFieldOffset;
    private ParticleAttributeIndex_tImpl? _OutputFieldInstance;

    public ParticleAttributeIndex_t OutputField
    {
        get
        {
            _OutputFieldOffset = _OutputFieldOffset ?? Schema.GetOffset(0x71A0FB13324F6F74);
            var instance = _OutputFieldInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _OutputFieldOffset!.Value);
            return instance;
        }
    }
    private static nint? _SetMethodOffset;

    public ref ParticleSetMethod_t SetMethod
    {
        get
        {
            _SetMethodOffset = _SetMethodOffset ?? Schema.GetOffset(0x71A0FB13FB53C31E);
            return ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset!.Value);
        }
    }
    private static nint? _NormalizedOutputOffset;

    public ref bool NormalizedOutput
    {
        get
        {
            _NormalizedOutputOffset = _NormalizedOutputOffset ?? Schema.GetOffset(0x71A0FB130AA98C55);
            return ref _Handle.AsRef<bool>(_NormalizedOutputOffset!.Value);
        }
    }

}