// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_CreateOnModelAtHeightImpl : CParticleFunctionInitializerImpl, C_INIT_CreateOnModelAtHeight
{
    public C_INIT_CreateOnModelAtHeightImpl(nint handle) : base(handle) { }

    private static nint? _UseBonesOffset;

    public ref bool UseBones
    {
        get
        {
            _UseBonesOffset = _UseBonesOffset ?? Schema.GetOffset(0xBB8B79F610D1938B);
            return ref _Handle.AsRef<bool>(_UseBonesOffset!.Value);
        }
    }
    private static nint? _ForceZOffset;

    public ref bool ForceZ
    {
        get
        {
            _ForceZOffset = _ForceZOffset ?? Schema.GetOffset(0xBB8B79F6A3DF359A);
            return ref _Handle.AsRef<bool>(_ForceZOffset!.Value);
        }
    }
    private static nint? _ControlPointNumberOffset;

    public ref int ControlPointNumber
    {
        get
        {
            _ControlPointNumberOffset = _ControlPointNumberOffset ?? Schema.GetOffset(0xBB8B79F63F31A6BD);
            return ref _Handle.AsRef<int>(_ControlPointNumberOffset!.Value);
        }
    }
    private static nint? _HeightCPOffset;

    public ref int HeightCP
    {
        get
        {
            _HeightCPOffset = _HeightCPOffset ?? Schema.GetOffset(0xBB8B79F6943E048D);
            return ref _Handle.AsRef<int>(_HeightCPOffset!.Value);
        }
    }
    private static nint? _UseWaterHeightOffset;

    public ref bool UseWaterHeight
    {
        get
        {
            _UseWaterHeightOffset = _UseWaterHeightOffset ?? Schema.GetOffset(0xBB8B79F616CA1A0C);
            return ref _Handle.AsRef<bool>(_UseWaterHeightOffset!.Value);
        }
    }
    private static nint? _DesiredHeightOffset;
    private CParticleCollectionFloatInputImpl? _DesiredHeightInstance;

    public CParticleCollectionFloatInput DesiredHeight
    {
        get
        {
            _DesiredHeightOffset = _DesiredHeightOffset ?? Schema.GetOffset(0xBB8B79F6D72286F4);
            var instance = _DesiredHeightInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _DesiredHeightOffset!.Value);
            return instance;
        }
    }
    private static nint? _HitBoxScaleOffset;
    private CParticleCollectionVecInputImpl? _HitBoxScaleInstance;

    public CParticleCollectionVecInput HitBoxScale
    {
        get
        {
            _HitBoxScaleOffset = _HitBoxScaleOffset ?? Schema.GetOffset(0xBB8B79F658EE3FB7);
            var instance = _HitBoxScaleInstance ??= new CParticleCollectionVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _HitBoxScaleOffset!.Value);
            return instance;
        }
    }
    private static nint? _DirectionBiasOffset;
    private CParticleCollectionVecInputImpl? _DirectionBiasInstance;

    public CParticleCollectionVecInput DirectionBias
    {
        get
        {
            _DirectionBiasOffset = _DirectionBiasOffset ?? Schema.GetOffset(0xBB8B79F65A1697CF);
            var instance = _DirectionBiasInstance ??= new CParticleCollectionVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _DirectionBiasOffset!.Value);
            return instance;
        }
    }
    private static nint? _BiasTypeOffset;

    public ref ParticleHitboxBiasType_t BiasType
    {
        get
        {
            _BiasTypeOffset = _BiasTypeOffset ?? Schema.GetOffset(0xBB8B79F65FAB0448);
            return ref _Handle.AsRef<ParticleHitboxBiasType_t>(_BiasTypeOffset!.Value);
        }
    }
    private static nint? _LocalCoordsOffset;

    public ref bool LocalCoords
    {
        get
        {
            _LocalCoordsOffset = _LocalCoordsOffset ?? Schema.GetOffset(0xBB8B79F630E716DE);
            return ref _Handle.AsRef<bool>(_LocalCoordsOffset!.Value);
        }
    }
    private static nint? _PreferMovingBoxesOffset;

    public ref bool PreferMovingBoxes
    {
        get
        {
            _PreferMovingBoxesOffset = _PreferMovingBoxesOffset ?? Schema.GetOffset(0xBB8B79F68F1573EE);
            return ref _Handle.AsRef<bool>(_PreferMovingBoxesOffset!.Value);
        }
    }
    private static nint? _HitboxSetNameOffset;

    public string HitboxSetName
    {
        get
        {
            _HitboxSetNameOffset = _HitboxSetNameOffset ?? Schema.GetOffset(0xBB8B79F66A21BB0E);
            return Schema.GetString(_Handle + _HitboxSetNameOffset!.Value);
        }
        set
        {
            _HitboxSetNameOffset = _HitboxSetNameOffset ?? Schema.GetOffset(0xBB8B79F66A21BB0E);
            Schema.SetFixedString(_Handle, _HitboxSetNameOffset!.Value, value, 128);
        }
    }
    private static nint? _HitboxVelocityScaleOffset;
    private CParticleCollectionFloatInputImpl? _HitboxVelocityScaleInstance;

    public CParticleCollectionFloatInput HitboxVelocityScale
    {
        get
        {
            _HitboxVelocityScaleOffset = _HitboxVelocityScaleOffset ?? Schema.GetOffset(0xBB8B79F65BE2EDCC);
            var instance = _HitboxVelocityScaleInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _HitboxVelocityScaleOffset!.Value);
            return instance;
        }
    }
    private static nint? _MaxBoneVelocityOffset;
    private CParticleCollectionFloatInputImpl? _MaxBoneVelocityInstance;

    public CParticleCollectionFloatInput MaxBoneVelocity
    {
        get
        {
            _MaxBoneVelocityOffset = _MaxBoneVelocityOffset ?? Schema.GetOffset(0xBB8B79F660C6A35A);
            var instance = _MaxBoneVelocityInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _MaxBoneVelocityOffset!.Value);
            return instance;
        }
    }

}