// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_CylindricalDistanceToTransformImpl : CParticleFunctionOperatorImpl, C_OP_CylindricalDistanceToTransform
{
    public C_OP_CylindricalDistanceToTransformImpl(nint handle) : base(handle) { }

    private static nint? _FieldOutputOffset;
    private ParticleAttributeIndex_tImpl? _FieldOutputInstance;

    public ParticleAttributeIndex_t FieldOutput
    {
        get
        {
            _FieldOutputOffset = _FieldOutputOffset ?? Schema.GetOffset(0x3B99017E5729606);
            var instance = _FieldOutputInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _FieldOutputOffset!.Value);
            return instance;
        }
    }
    private static nint? _InputMinOffset;
    private CPerParticleFloatInputImpl? _InputMinInstance;

    public CPerParticleFloatInput InputMin
    {
        get
        {
            _InputMinOffset = _InputMinOffset ?? Schema.GetOffset(0x3B99017E88A0D0F);
            var instance = _InputMinInstance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _InputMinOffset!.Value);
            return instance;
        }
    }
    private static nint? _InputMaxOffset;
    private CPerParticleFloatInputImpl? _InputMaxInstance;

    public CPerParticleFloatInput InputMax
    {
        get
        {
            _InputMaxOffset = _InputMaxOffset ?? Schema.GetOffset(0x3B99017D6766901);
            var instance = _InputMaxInstance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _InputMaxOffset!.Value);
            return instance;
        }
    }
    private static nint? _OutputMinOffset;
    private CPerParticleFloatInputImpl? _OutputMinInstance;

    public CPerParticleFloatInput OutputMin
    {
        get
        {
            _OutputMinOffset = _OutputMinOffset ?? Schema.GetOffset(0x3B990175F8D7716);
            var instance = _OutputMinInstance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _OutputMinOffset!.Value);
            return instance;
        }
    }
    private static nint? _OutputMaxOffset;
    private CPerParticleFloatInputImpl? _OutputMaxInstance;

    public CPerParticleFloatInput OutputMax
    {
        get
        {
            _OutputMaxOffset = _OutputMaxOffset ?? Schema.GetOffset(0x3B9901751A0E8C4);
            var instance = _OutputMaxInstance ??= new CPerParticleFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _OutputMaxOffset!.Value);
            return instance;
        }
    }
    private static nint? _TransformStartOffset;
    private CParticleTransformInputImpl? _TransformStartInstance;

    public CParticleTransformInput TransformStart
    {
        get
        {
            _TransformStartOffset = _TransformStartOffset ?? Schema.GetOffset(0x3B99017D94FA7F9);
            var instance = _TransformStartInstance ??= new CParticleTransformInputImpl(0);
            instance.DangerousSetHandle(_Handle + _TransformStartOffset!.Value);
            return instance;
        }
    }
    private static nint? _TransformEndOffset;
    private CParticleTransformInputImpl? _TransformEndInstance;

    public CParticleTransformInput TransformEnd
    {
        get
        {
            _TransformEndOffset = _TransformEndOffset ?? Schema.GetOffset(0x3B990170C3277C8);
            var instance = _TransformEndInstance ??= new CParticleTransformInputImpl(0);
            instance.DangerousSetHandle(_Handle + _TransformEndOffset!.Value);
            return instance;
        }
    }
    private static nint? _SetMethodOffset;

    public ref ParticleSetMethod_t SetMethod
    {
        get
        {
            _SetMethodOffset = _SetMethodOffset ?? Schema.GetOffset(0x3B99017FB53C31E);
            return ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset!.Value);
        }
    }
    private static nint? _ActiveRangeOffset;

    public ref bool ActiveRange
    {
        get
        {
            _ActiveRangeOffset = _ActiveRangeOffset ?? Schema.GetOffset(0x3B990173FA53B84);
            return ref _Handle.AsRef<bool>(_ActiveRangeOffset!.Value);
        }
    }
    private static nint? _AdditiveOffset;

    public ref bool Additive
    {
        get
        {
            _AdditiveOffset = _AdditiveOffset ?? Schema.GetOffset(0x3B990170FA86105);
            return ref _Handle.AsRef<bool>(_AdditiveOffset!.Value);
        }
    }
    private static nint? _CapsuleOffset;

    public ref bool Capsule
    {
        get
        {
            _CapsuleOffset = _CapsuleOffset ?? Schema.GetOffset(0x3B99017F8D8D1AC);
            return ref _Handle.AsRef<bool>(_CapsuleOffset!.Value);
        }
    }

}