// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_MovementLoopInsideSphereImpl : CParticleFunctionOperatorImpl, C_OP_MovementLoopInsideSphere
{
    public C_OP_MovementLoopInsideSphereImpl(nint handle) : base(handle) { }

    private static nint? _CPOffset;

    public ref int CP
    {
        get
        {
            _CPOffset = _CPOffset ?? Schema.GetOffset(0x7C19959FEB661472);
            return ref _Handle.AsRef<int>(_CPOffset!.Value);
        }
    }
    private static nint? _DistanceOffset;
    private CParticleCollectionFloatInputImpl? _DistanceInstance;

    public CParticleCollectionFloatInput Distance
    {
        get
        {
            _DistanceOffset = _DistanceOffset ?? Schema.GetOffset(0x7C19959F00DC4A68);
            var instance = _DistanceInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _DistanceOffset!.Value);
            return instance;
        }
    }
    private static nint? _ScaleOffset;
    private CParticleCollectionVecInputImpl? _ScaleInstance;

    public CParticleCollectionVecInput Scale
    {
        get
        {
            _ScaleOffset = _ScaleOffset ?? Schema.GetOffset(0x7C19959F5F596B51);
            var instance = _ScaleInstance ??= new CParticleCollectionVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _ScaleOffset!.Value);
            return instance;
        }
    }
    private static nint? _DistSqrAttrOffset;
    private ParticleAttributeIndex_tImpl? _DistSqrAttrInstance;

    public ParticleAttributeIndex_t DistSqrAttr
    {
        get
        {
            _DistSqrAttrOffset = _DistSqrAttrOffset ?? Schema.GetOffset(0x7C19959F767818FE);
            var instance = _DistSqrAttrInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _DistSqrAttrOffset!.Value);
            return instance;
        }
    }

}