// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapTransformOrientationToYawImpl : CParticleFunctionOperatorImpl, C_OP_RemapTransformOrientationToYaw
{
    public C_OP_RemapTransformOrientationToYawImpl(nint handle) : base(handle) { }

    private static nint? _TransformInputOffset;
    private CParticleTransformInputImpl? _TransformInputInstance;

    public CParticleTransformInput TransformInput
    {
        get
        {
            _TransformInputOffset = _TransformInputOffset ?? Schema.GetOffset(0xA0DF014CB3FDC289);
            var instance = _TransformInputInstance ??= new CParticleTransformInputImpl(0);
            instance.DangerousSetHandle(_Handle + _TransformInputOffset!.Value);
            return instance;
        }
    }
    private static nint? _FieldOutputOffset;
    private ParticleAttributeIndex_tImpl? _FieldOutputInstance;

    public ParticleAttributeIndex_t FieldOutput
    {
        get
        {
            _FieldOutputOffset = _FieldOutputOffset ?? Schema.GetOffset(0xA0DF014CE5729606);
            var instance = _FieldOutputInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _FieldOutputOffset!.Value);
            return instance;
        }
    }
    private static nint? _RotOffsetOffset;

    public ref float RotOffset
    {
        get
        {
            _RotOffsetOffset = _RotOffsetOffset ?? Schema.GetOffset(0xA0DF014CD1EA9CDF);
            return ref _Handle.AsRef<float>(_RotOffsetOffset!.Value);
        }
    }
    private static nint? _SpinStrengthOffset;

    public ref float SpinStrength
    {
        get
        {
            _SpinStrengthOffset = _SpinStrengthOffset ?? Schema.GetOffset(0xA0DF014C12520F26);
            return ref _Handle.AsRef<float>(_SpinStrengthOffset!.Value);
        }
    }

}