// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapScalarOnceTimedImpl : CParticleFunctionOperatorImpl, C_OP_RemapScalarOnceTimed
{
    public C_OP_RemapScalarOnceTimedImpl(nint handle) : base(handle) { }

    private static nint? _ProportionalOffset;

    public ref bool Proportional
    {
        get
        {
            _ProportionalOffset = _ProportionalOffset ?? Schema.GetOffset(0xF5150932891F328A);
            return ref _Handle.AsRef<bool>(_ProportionalOffset!.Value);
        }
    }
    private static nint? _FieldInputOffset;
    private ParticleAttributeIndex_tImpl? _FieldInputInstance;

    public ParticleAttributeIndex_t FieldInput
    {
        get
        {
            _FieldInputOffset = _FieldInputOffset ?? Schema.GetOffset(0xF5150932AE775669);
            var instance = _FieldInputInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _FieldInputOffset!.Value);
            return instance;
        }
    }
    private static nint? _FieldOutputOffset;
    private ParticleAttributeIndex_tImpl? _FieldOutputInstance;

    public ParticleAttributeIndex_t FieldOutput
    {
        get
        {
            _FieldOutputOffset = _FieldOutputOffset ?? Schema.GetOffset(0xF5150932E5729606);
            var instance = _FieldOutputInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _FieldOutputOffset!.Value);
            return instance;
        }
    }
    private static nint? _InputMinOffset;

    public ref float InputMin
    {
        get
        {
            _InputMinOffset = _InputMinOffset ?? Schema.GetOffset(0xF5150932E88A0D0F);
            return ref _Handle.AsRef<float>(_InputMinOffset!.Value);
        }
    }
    private static nint? _InputMaxOffset;

    public ref float InputMax
    {
        get
        {
            _InputMaxOffset = _InputMaxOffset ?? Schema.GetOffset(0xF5150932D6766901);
            return ref _Handle.AsRef<float>(_InputMaxOffset!.Value);
        }
    }
    private static nint? _OutputMinOffset;

    public ref float OutputMin
    {
        get
        {
            _OutputMinOffset = _OutputMinOffset ?? Schema.GetOffset(0xF51509325F8D7716);
            return ref _Handle.AsRef<float>(_OutputMinOffset!.Value);
        }
    }
    private static nint? _OutputMaxOffset;

    public ref float OutputMax
    {
        get
        {
            _OutputMaxOffset = _OutputMaxOffset ?? Schema.GetOffset(0xF515093251A0E8C4);
            return ref _Handle.AsRef<float>(_OutputMaxOffset!.Value);
        }
    }
    private static nint? _RemapTimeOffset;

    public ref float RemapTime
    {
        get
        {
            _RemapTimeOffset = _RemapTimeOffset ?? Schema.GetOffset(0xF5150932F436AC39);
            return ref _Handle.AsRef<float>(_RemapTimeOffset!.Value);
        }
    }

}