// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_OrientTo2dDirectionImpl : CParticleFunctionOperatorImpl, C_OP_OrientTo2dDirection
{
    public C_OP_OrientTo2dDirectionImpl(nint handle) : base(handle) { }

    private static nint? _InputOffset;
    private CPerParticleVecInputImpl? _InputInstance;

    public CPerParticleVecInput Input
    {
        get
        {
            _InputOffset = _InputOffset ?? Schema.GetOffset(0x2AC61F041EA0ED5B);
            var instance = _InputInstance ??= new CPerParticleVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _InputOffset!.Value);
            return instance;
        }
    }
    private static nint? _RotOffsetOffset;

    public ref float RotOffset
    {
        get
        {
            _RotOffsetOffset = _RotOffsetOffset ?? Schema.GetOffset(0x2AC61F04D1EA9CDF);
            return ref _Handle.AsRef<float>(_RotOffsetOffset!.Value);
        }
    }
    private static nint? _SpinStrengthOffset;

    public ref float SpinStrength
    {
        get
        {
            _SpinStrengthOffset = _SpinStrengthOffset ?? Schema.GetOffset(0x2AC61F0412520F26);
            return ref _Handle.AsRef<float>(_SpinStrengthOffset!.Value);
        }
    }
    private static nint? _FieldOutputOffset;
    private ParticleAttributeIndex_tImpl? _FieldOutputInstance;

    public ParticleAttributeIndex_t FieldOutput
    {
        get
        {
            _FieldOutputOffset = _FieldOutputOffset ?? Schema.GetOffset(0x2AC61F04E5729606);
            var instance = _FieldOutputInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _FieldOutputOffset!.Value);
            return instance;
        }
    }

}