// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_GameLiquidSpillImpl : CParticleFunctionRendererImpl, C_OP_GameLiquidSpill
{
    public C_OP_GameLiquidSpillImpl(nint handle) : base(handle) { }

    private static nint? _LiquidContentsFieldOffset;
    private CParticleCollectionFloatInputImpl? _LiquidContentsFieldInstance;

    public CParticleCollectionFloatInput LiquidContentsField
    {
        get
        {
            _LiquidContentsFieldOffset = _LiquidContentsFieldOffset ?? Schema.GetOffset(0xB07185274F9A10CB);
            var instance = _LiquidContentsFieldInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _LiquidContentsFieldOffset!.Value);
            return instance;
        }
    }
    private static nint? _ExpirationTimeOffset;
    private CParticleCollectionFloatInputImpl? _ExpirationTimeInstance;

    public CParticleCollectionFloatInput ExpirationTime
    {
        get
        {
            _ExpirationTimeOffset = _ExpirationTimeOffset ?? Schema.GetOffset(0xB07185272A34213F);
            var instance = _ExpirationTimeInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _ExpirationTimeOffset!.Value);
            return instance;
        }
    }
    private static nint? _RadiusOffset;
    private CParticleCollectionFloatInputImpl? _RadiusInstance;

    public CParticleCollectionFloatInput Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0xB07185275ACFC08D);
            var instance = _RadiusInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _RadiusOffset!.Value);
            return instance;
        }
    }
    private static nint? _CheckExposedToSkyOffset;

    public ref bool CheckExposedToSky
    {
        get
        {
            _CheckExposedToSkyOffset = _CheckExposedToSkyOffset ?? Schema.GetOffset(0xB07185270385F99D);
            return ref _Handle.AsRef<bool>(_CheckExposedToSkyOffset!.Value);
        }
    }
    private static nint? _AmountAttributeOffset;
    private ParticleAttributeIndex_tImpl? _AmountAttributeInstance;

    public ParticleAttributeIndex_t AmountAttribute
    {
        get
        {
            _AmountAttributeOffset = _AmountAttributeOffset ?? Schema.GetOffset(0xB071852755424147);
            var instance = _AmountAttributeInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _AmountAttributeOffset!.Value);
            return instance;
        }
    }

}