// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapScalarImpl : CParticleFunctionOperatorImpl, C_OP_RemapScalar
{
    public C_OP_RemapScalarImpl(nint handle) : base(handle) { }

    private static nint? _FieldInputOffset;
    private ParticleAttributeIndex_tImpl? _FieldInputInstance;

    public ParticleAttributeIndex_t FieldInput
    {
        get
        {
            _FieldInputOffset = _FieldInputOffset ?? Schema.GetOffset(0x580A448EAE775669);
            var instance = _FieldInputInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _FieldInputOffset!.Value);
            return instance;
        }
    }
    private static nint? _FieldOutputOffset;
    private ParticleAttributeIndex_tImpl? _FieldOutputInstance;

    public ParticleAttributeIndex_t FieldOutput
    {
        get
        {
            _FieldOutputOffset = _FieldOutputOffset ?? Schema.GetOffset(0x580A448EE5729606);
            var instance = _FieldOutputInstance ??= new ParticleAttributeIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _FieldOutputOffset!.Value);
            return instance;
        }
    }
    private static nint? _InputMinOffset;

    public ref float InputMin
    {
        get
        {
            _InputMinOffset = _InputMinOffset ?? Schema.GetOffset(0x580A448EE88A0D0F);
            return ref _Handle.AsRef<float>(_InputMinOffset!.Value);
        }
    }
    private static nint? _InputMaxOffset;

    public ref float InputMax
    {
        get
        {
            _InputMaxOffset = _InputMaxOffset ?? Schema.GetOffset(0x580A448ED6766901);
            return ref _Handle.AsRef<float>(_InputMaxOffset!.Value);
        }
    }
    private static nint? _OutputMinOffset;

    public ref float OutputMin
    {
        get
        {
            _OutputMinOffset = _OutputMinOffset ?? Schema.GetOffset(0x580A448E5F8D7716);
            return ref _Handle.AsRef<float>(_OutputMinOffset!.Value);
        }
    }
    private static nint? _OutputMaxOffset;

    public ref float OutputMax
    {
        get
        {
            _OutputMaxOffset = _OutputMaxOffset ?? Schema.GetOffset(0x580A448E51A0E8C4);
            return ref _Handle.AsRef<float>(_OutputMaxOffset!.Value);
        }
    }
    private static nint? _OldCodeOffset;

    public ref bool OldCode
    {
        get
        {
            _OldCodeOffset = _OldCodeOffset ?? Schema.GetOffset(0x580A448EFB4CA66B);
            return ref _Handle.AsRef<bool>(_OldCodeOffset!.Value);
        }
    }

}