// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimationGraphVisualizerPrimitiveBaseImpl : SchemaClass, CAnimationGraphVisualizerPrimitiveBase
{
    public CAnimationGraphVisualizerPrimitiveBaseImpl(nint handle) : base(handle) { }

    private static nint? _TypeOffset;

    public ref CAnimationGraphVisualizerPrimitiveType Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0x5204B0848ED6D5CD);
            return ref _Handle.AsRef<CAnimationGraphVisualizerPrimitiveType>(_TypeOffset!.Value);
        }
    }
    private static nint? _OwningAnimNodePathsOffset;
    private SchemaClassFixedArray<AnimNodeID>? _OwningAnimNodePathsInstance;

    public ISchemaClassFixedArray<AnimNodeID> OwningAnimNodePaths
    {
        get
        {
            _OwningAnimNodePathsOffset = _OwningAnimNodePathsOffset ?? Schema.GetOffset(0x5204B08461A2E55C);
            var instance = _OwningAnimNodePathsInstance ??= new SchemaClassFixedArray<AnimNodeID>(0, 0x5204B08461A2E55C, 11, 4, 4);
            instance.DangerousSetHandle(_Handle + _OwningAnimNodePathsOffset!.Value);
            return instance;
        }
    }
    private static nint? _OwningAnimNodePathCountOffset;

    public ref int OwningAnimNodePathCount
    {
        get
        {
            _OwningAnimNodePathCountOffset = _OwningAnimNodePathCountOffset ?? Schema.GetOffset(0x5204B0844241A972);
            return ref _Handle.AsRef<int>(_OwningAnimNodePathCountOffset!.Value);
        }
    }

}