// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphControllerManagerImpl : SchemaClass, CAnimGraphControllerManager
{
    public CAnimGraphControllerManagerImpl(nint handle) : base(handle) { }

    private static nint? _ControllersOffset;

    public ref CUtlVector<PointerTo<CAnimGraphControllerBase>> Controllers {
        get {
            _ControllersOffset = _ControllersOffset ?? Schema.GetOffset(0x991B1F440CF2DE16);
            return ref _Handle.AsRef<CUtlVector<PointerTo<CAnimGraphControllerBase>>>(_ControllersOffset!.Value);
        }
    }
    private static nint? _GraphBindingsCreatedOffset;

    public ref bool GraphBindingsCreated {
        get {
            _GraphBindingsCreatedOffset = _GraphBindingsCreatedOffset ?? Schema.GetOffset(0x991B1F443C33156F);
            return ref _Handle.AsRef<bool>(_GraphBindingsCreatedOffset!.Value);
        }
    }


}