// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimUpdateSharedDataImpl : SchemaClass, CAnimUpdateSharedData
{
    public CAnimUpdateSharedDataImpl(nint handle) : base(handle) { }

    private static nint? _NodesOffset;

    public ref CUtlVector<SchemaUntypedField> Nodes
    {
        get
        {
            _NodesOffset = _NodesOffset ?? Schema.GetOffset(0xA294DB47780F027A);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_NodesOffset!.Value);
        }
    }
    private static nint? _NodeIndexMapOffset;
    private SchemaUntypedField? _NodeIndexMapInstance;

    public SchemaUntypedField NodeIndexMap
    {
        get
        {
            _NodeIndexMapOffset = _NodeIndexMapOffset ?? Schema.GetOffset(0xA294DB47D3B3E7A3);
            var instance = _NodeIndexMapInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _NodeIndexMapOffset!.Value);
            return instance;
        }
    }
    private static nint? _ComponentsOffset;

    public ref CUtlVector<SchemaUntypedField> Components
    {
        get
        {
            _ComponentsOffset = _ComponentsOffset ?? Schema.GetOffset(0xA294DB47F87FC409);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_ComponentsOffset!.Value);
        }
    }
    private static nint? _ParamListUpdaterOffset;
    private SchemaUntypedField? _ParamListUpdaterInstance;

    public SchemaUntypedField ParamListUpdater
    {
        get
        {
            _ParamListUpdaterOffset = _ParamListUpdaterOffset ?? Schema.GetOffset(0xA294DB4784AA7F15);
            var instance = _ParamListUpdaterInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _ParamListUpdaterOffset!.Value);
            return instance;
        }
    }
    private static nint? _TagManagerUpdaterOffset;
    private SchemaUntypedField? _TagManagerUpdaterInstance;

    public SchemaUntypedField TagManagerUpdater
    {
        get
        {
            _TagManagerUpdaterOffset = _TagManagerUpdaterOffset ?? Schema.GetOffset(0xA294DB47432E460D);
            var instance = _TagManagerUpdaterInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _TagManagerUpdaterOffset!.Value);
            return instance;
        }
    }
    private static nint? _ScriptManagerOffset;
    private SchemaUntypedField? _ScriptManagerInstance;

    public SchemaUntypedField ScriptManager
    {
        get
        {
            _ScriptManagerOffset = _ScriptManagerOffset ?? Schema.GetOffset(0xA294DB47F4257D31);
            var instance = _ScriptManagerInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _ScriptManagerOffset!.Value);
            return instance;
        }
    }
    private static nint? _SettingsOffset;
    private CAnimGraphSettingsManagerImpl? _SettingsInstance;

    public CAnimGraphSettingsManager Settings
    {
        get
        {
            _SettingsOffset = _SettingsOffset ?? Schema.GetOffset(0xA294DB47B3DE33A8);
            var instance = _SettingsInstance ??= new CAnimGraphSettingsManagerImpl(0);
            instance.DangerousSetHandle(_Handle + _SettingsOffset!.Value);
            return instance;
        }
    }
    private static nint? _StaticPoseCacheOffset;
    private SchemaUntypedField? _StaticPoseCacheInstance;

    public SchemaUntypedField StaticPoseCache
    {
        get
        {
            _StaticPoseCacheOffset = _StaticPoseCacheOffset ?? Schema.GetOffset(0xA294DB475BFC0C1E);
            var instance = _StaticPoseCacheInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _StaticPoseCacheOffset!.Value);
            return instance;
        }
    }
    private static nint? _SkeletonOffset;
    private SchemaUntypedField? _SkeletonInstance;

    public SchemaUntypedField Skeleton
    {
        get
        {
            _SkeletonOffset = _SkeletonOffset ?? Schema.GetOffset(0xA294DB4744BBF688);
            var instance = _SkeletonInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _SkeletonOffset!.Value);
            return instance;
        }
    }
    private static nint? _RootNodePathOffset;
    private CAnimNodePathImpl? _RootNodePathInstance;

    public CAnimNodePath RootNodePath
    {
        get
        {
            _RootNodePathOffset = _RootNodePathOffset ?? Schema.GetOffset(0xA294DB476893B9EE);
            var instance = _RootNodePathInstance ??= new CAnimNodePathImpl(0);
            instance.DangerousSetHandle(_Handle + _RootNodePathOffset!.Value);
            return instance;
        }
    }

}