// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseClientUIEntityImpl : CBaseModelEntityImpl, CBaseClientUIEntity
{
    public CBaseClientUIEntityImpl(nint handle) : base(handle) { }

    private static nint? _EnabledOffset;

    public ref bool Enabled {
        get {
            _EnabledOffset = _EnabledOffset ?? Schema.GetOffset(0x51A22D116154EB7E);
            return ref _Handle.AsRef<bool>(_EnabledOffset!.Value);
        }
    }
    private static nint? _DialogXMLNameOffset;

    public string DialogXMLName {
        get {
            _DialogXMLNameOffset = _DialogXMLNameOffset ?? Schema.GetOffset(0x51A22D11D13858C9);
            return Schema.GetString(_Handle.Read<nint>(_DialogXMLNameOffset!.Value));
        }
        set {
            _DialogXMLNameOffset = _DialogXMLNameOffset ?? Schema.GetOffset(0x51A22D11D13858C9);
            Schema.SetString(_Handle, _DialogXMLNameOffset!.Value, value);
        }
    } 
    private static nint? _PanelClassNameOffset;

    public string PanelClassName {
        get {
            _PanelClassNameOffset = _PanelClassNameOffset ?? Schema.GetOffset(0x51A22D115C958CBC);
            return Schema.GetString(_Handle.Read<nint>(_PanelClassNameOffset!.Value));
        }
        set {
            _PanelClassNameOffset = _PanelClassNameOffset ?? Schema.GetOffset(0x51A22D115C958CBC);
            Schema.SetString(_Handle, _PanelClassNameOffset!.Value, value);
        }
    } 
    private static nint? _PanelIDOffset;

    public string PanelID {
        get {
            _PanelIDOffset = _PanelIDOffset ?? Schema.GetOffset(0x51A22D1107A4EF60);
            return Schema.GetString(_Handle.Read<nint>(_PanelIDOffset!.Value));
        }
        set {
            _PanelIDOffset = _PanelIDOffset ?? Schema.GetOffset(0x51A22D1107A4EF60);
            Schema.SetString(_Handle, _PanelIDOffset!.Value, value);
        }
    } 
    private static nint? _CustomOutput0Offset;

    public SchemaUntypedField CustomOutput0 {
        get {
            _CustomOutput0Offset = _CustomOutput0Offset ?? Schema.GetOffset(0x51A22D119AA5C775);
            return new SchemaUntypedField(_Handle + _CustomOutput0Offset!.Value);
        }
    }
    private static nint? _CustomOutput1Offset;

    public SchemaUntypedField CustomOutput1 {
        get {
            _CustomOutput1Offset = _CustomOutput1Offset ?? Schema.GetOffset(0x51A22D1199A5C5E2);
            return new SchemaUntypedField(_Handle + _CustomOutput1Offset!.Value);
        }
    }
    private static nint? _CustomOutput2Offset;

    public SchemaUntypedField CustomOutput2 {
        get {
            _CustomOutput2Offset = _CustomOutput2Offset ?? Schema.GetOffset(0x51A22D1198A5C44F);
            return new SchemaUntypedField(_Handle + _CustomOutput2Offset!.Value);
        }
    }
    private static nint? _CustomOutput3Offset;

    public SchemaUntypedField CustomOutput3 {
        get {
            _CustomOutput3Offset = _CustomOutput3Offset ?? Schema.GetOffset(0x51A22D1197A5C2BC);
            return new SchemaUntypedField(_Handle + _CustomOutput3Offset!.Value);
        }
    }
    private static nint? _CustomOutput4Offset;

    public SchemaUntypedField CustomOutput4 {
        get {
            _CustomOutput4Offset = _CustomOutput4Offset ?? Schema.GetOffset(0x51A22D1196A5C129);
            return new SchemaUntypedField(_Handle + _CustomOutput4Offset!.Value);
        }
    }
    private static nint? _CustomOutput5Offset;

    public SchemaUntypedField CustomOutput5 {
        get {
            _CustomOutput5Offset = _CustomOutput5Offset ?? Schema.GetOffset(0x51A22D1195A5BF96);
            return new SchemaUntypedField(_Handle + _CustomOutput5Offset!.Value);
        }
    }
    private static nint? _CustomOutput6Offset;

    public SchemaUntypedField CustomOutput6 {
        get {
            _CustomOutput6Offset = _CustomOutput6Offset ?? Schema.GetOffset(0x51A22D1194A5BE03);
            return new SchemaUntypedField(_Handle + _CustomOutput6Offset!.Value);
        }
    }
    private static nint? _CustomOutput7Offset;

    public SchemaUntypedField CustomOutput7 {
        get {
            _CustomOutput7Offset = _CustomOutput7Offset ?? Schema.GetOffset(0x51A22D1193A5BC70);
            return new SchemaUntypedField(_Handle + _CustomOutput7Offset!.Value);
        }
    }
    private static nint? _CustomOutput8Offset;

    public SchemaUntypedField CustomOutput8 {
        get {
            _CustomOutput8Offset = _CustomOutput8Offset ?? Schema.GetOffset(0x51A22D11A2A5D40D);
            return new SchemaUntypedField(_Handle + _CustomOutput8Offset!.Value);
        }
    }
    private static nint? _CustomOutput9Offset;

    public SchemaUntypedField CustomOutput9 {
        get {
            _CustomOutput9Offset = _CustomOutput9Offset ?? Schema.GetOffset(0x51A22D11A1A5D27A);
            return new SchemaUntypedField(_Handle + _CustomOutput9Offset!.Value);
        }
    }

    public void EnabledUpdated() => Schema.Update(_Handle, 0x51A22D116154EB7E);
    public void DialogXMLNameUpdated() => Schema.Update(_Handle, 0x51A22D11D13858C9);
    public void PanelClassNameUpdated() => Schema.Update(_Handle, 0x51A22D115C958CBC);
    public void PanelIDUpdated() => Schema.Update(_Handle, 0x51A22D1107A4EF60);
}