// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBodyComponentImpl : CEntityComponentImpl, CBodyComponent
{
    public CBodyComponentImpl(nint handle) : base(handle) { }

    private static nint? _SceneNodeOffset;
    private CGameSceneNodeImpl? _SceneNodeInstance;

    public CGameSceneNode? SceneNode
    {
        get
        {
            _SceneNodeOffset = _SceneNodeOffset ?? Schema.GetOffset(0x4EF2C865D7D13495);
            var ptr = _Handle.Read<nint>(_SceneNodeOffset!.Value);
            if (!ptr.IsValidPtr()) return null;
            var instance = _SceneNodeInstance ??= new CGameSceneNodeImpl(0);
            instance.DangerousSetHandle(ptr);
            return instance;
        }
    }
    private static nint? ___m_pChainEntityOffset;

    public ref CNetworkVarChainer __m_pChainEntity
    {
        get
        {
            ___m_pChainEntityOffset = ___m_pChainEntityOffset ?? Schema.GetOffset(0x4EF2C865F63F0E7D);
            return ref _Handle.AsRef<CNetworkVarChainer>(___m_pChainEntityOffset!.Value);
        }
    }

}