// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CConstantForceControllerImpl : SchemaClass, CConstantForceController
{
    public CConstantForceControllerImpl(nint handle) : base(handle) { }

    private static nint? _LinearOffset;

    public ref Vector Linear
    {
        get
        {
            _LinearOffset = _LinearOffset ?? Schema.GetOffset(0x37030A8D6B6D1260);
            return ref _Handle.AsRef<Vector>(_LinearOffset!.Value);
        }
    }
    private static nint? _AngularOffset;
    private SchemaUntypedField? _AngularInstance;

    public SchemaUntypedField Angular
    {
        get
        {
            _AngularOffset = _AngularOffset ?? Schema.GetOffset(0x37030A8D74E0EB09);
            var instance = _AngularInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _AngularOffset!.Value);
            return instance;
        }
    }
    private static nint? _LinearSaveOffset;

    public ref Vector LinearSave
    {
        get
        {
            _LinearSaveOffset = _LinearSaveOffset ?? Schema.GetOffset(0x37030A8D96B9953D);
            return ref _Handle.AsRef<Vector>(_LinearSaveOffset!.Value);
        }
    }
    private static nint? _AngularSaveOffset;
    private SchemaUntypedField? _AngularSaveInstance;

    public SchemaUntypedField AngularSave
    {
        get
        {
            _AngularSaveOffset = _AngularSaveOffset ?? Schema.GetOffset(0x37030A8D8294323C);
            var instance = _AngularSaveInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _AngularSaveOffset!.Value);
            return instance;
        }
    }

}