// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCS2ChickenGraphControllerImpl : CAnimGraphControllerBaseImpl, CCS2ChickenGraphController
{
    public CCS2ChickenGraphControllerImpl(nint handle) : base(handle) { }

    private static nint? _ActionOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol Action
    {
        get
        {
            _ActionOffset = _ActionOffset ?? Schema.GetOffset(0xC887F1577918619F);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_ActionOffset!.Value);
        }
    }
    private static nint? _ActionResetOffset;
    private SchemaUntypedField? _ActionResetInstance;

    public SchemaUntypedField ActionReset
    {
        get
        {
            _ActionResetOffset = _ActionResetOffset ?? Schema.GetOffset(0xC887F157580F422E);
            var instance = _ActionResetInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _ActionResetOffset!.Value);
            return instance;
        }
    }
    private static nint? _ActionVariationOffset;

    public ref CAnimGraph2ParamOptionalRefFloat ActionVariation
    {
        get
        {
            _ActionVariationOffset = _ActionVariationOffset ?? Schema.GetOffset(0xC887F15766ADE45C);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_ActionVariationOffset!.Value);
        }
    }
    private static nint? _InWaterOffset;

    public ref CAnimGraph2ParamOptionalRefBool InWater
    {
        get
        {
            _InWaterOffset = _InWaterOffset ?? Schema.GetOffset(0xC887F157E47F9BA9);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefBool>(_InWaterOffset!.Value);
        }
    }
    private static nint? _ModeOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol Mode
    {
        get
        {
            _ModeOffset = _ModeOffset ?? Schema.GetOffset(0xC887F15790FD5BB2);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_ModeOffset!.Value);
        }
    }
    private static nint? _LifeStageOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol LifeStage
    {
        get
        {
            _LifeStageOffset = _LifeStageOffset ?? Schema.GetOffset(0xC887F1570C64458B);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_LifeStageOffset!.Value);
        }
    }
    private static nint? _IdlePhaseOffset;

    public ref CAnimGraph2ParamOptionalRefFloat IdlePhase
    {
        get
        {
            _IdlePhaseOffset = _IdlePhaseOffset ?? Schema.GetOffset(0xC887F157DC9A63DE);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_IdlePhaseOffset!.Value);
        }
    }
    private static nint? _TurnAngleOffset;

    public ref CAnimGraph2ParamOptionalRefFloat TurnAngle
    {
        get
        {
            _TurnAngleOffset = _TurnAngleOffset ?? Schema.GetOffset(0xC887F157A2008A79);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_TurnAngleOffset!.Value);
        }
    }
    private static nint? _HasLookatTargetOffset;

    public ref CAnimGraph2ParamOptionalRefBool HasLookatTarget
    {
        get
        {
            _HasLookatTargetOffset = _HasLookatTargetOffset ?? Schema.GetOffset(0xC887F157636503F8);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefBool>(_HasLookatTargetOffset!.Value);
        }
    }
    private static nint? _LookatTargetOffset;
    private SchemaUntypedField? _LookatTargetInstance;

    public SchemaUntypedField LookatTarget
    {
        get
        {
            _LookatTargetOffset = _LookatTargetOffset ?? Schema.GetOffset(0xC887F157BD59D4D6);
            var instance = _LookatTargetInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _LookatTargetOffset!.Value);
            return instance;
        }
    }
    private static nint? _FlinchOffset;

    public ref CAnimGraph2ParamOptionalRefBool Flinch
    {
        get
        {
            _FlinchOffset = _FlinchOffset ?? Schema.GetOffset(0xC887F157E8E04CA7);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefBool>(_FlinchOffset!.Value);
        }
    }
    private static nint? _FlinchVariationOffset;

    public ref CAnimGraph2ParamOptionalRefFloat FlinchVariation
    {
        get
        {
            _FlinchVariationOffset = _FlinchVariationOffset ?? Schema.GetOffset(0xC887F1577DB92C14);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_FlinchVariationOffset!.Value);
        }
    }
    private static nint? _HasActionCompletedEventOffset;

    public ref bool HasActionCompletedEvent
    {
        get
        {
            _HasActionCompletedEventOffset = _HasActionCompletedEventOffset ?? Schema.GetOffset(0xC887F157CD4A37EA);
            return ref _Handle.AsRef<bool>(_HasActionCompletedEventOffset!.Value);
        }
    }

}