// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSObservableElementImpl : CBaseEntityImpl, CCSObservableElement
{
    public CCSObservableElementImpl(nint handle) : base(handle) { }

    private static nint? _ObservableModelEntityOffset;

    public string ObservableModelEntity
    {
        get
        {
            _ObservableModelEntityOffset = _ObservableModelEntityOffset ?? Schema.GetOffset(0xE7DAA353E2DEBFF2);
            return Schema.GetString(_Handle.Read<nint>(_ObservableModelEntityOffset!.Value));
        }
        set
        {
            _ObservableModelEntityOffset = _ObservableModelEntityOffset ?? Schema.GetOffset(0xE7DAA353E2DEBFF2);
            Schema.SetString(_Handle, _ObservableModelEntityOffset!.Value, value);
        }
    }
    private static nint? _ObservableModelEntity1Offset;

    public ref CHandle<CBaseEntity> ObservableModelEntity1
    {
        get
        {
            _ObservableModelEntity1Offset = _ObservableModelEntity1Offset ?? Schema.GetOffset(0xE7DAA3531BC96308);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_ObservableModelEntity1Offset!.Value);
        }
    }
    private static nint? _ObservableModelEntity2Offset;

    public ref CHandle<CBaseEntity> ObservableModelEntity2
    {
        get
        {
            _ObservableModelEntity2Offset = _ObservableModelEntity2Offset ?? Schema.GetOffset(0xE7DAA353F807344E);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_ObservableModelEntity2Offset!.Value);
        }
    }
    private static nint? _TeamFilterOffset;

    public ref uint TeamFilter
    {
        get
        {
            _TeamFilterOffset = _TeamFilterOffset ?? Schema.GetOffset(0xE7DAA353919CFBA2);
            return ref _Handle.AsRef<uint>(_TeamFilterOffset!.Value);
        }
    }

    public void ObservableModelEntity1Updated() => Schema.Update(_Handle, 0xE7DAA3531BC96308);
    public void ObservableModelEntity2Updated() => Schema.Update(_Handle, 0xE7DAA353F807344E);
    public void TeamFilterUpdated() => Schema.Update(_Handle, 0xE7DAA353919CFBA2);
}