// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSRadarElementImpl : CBaseEntityImpl, CCSRadarElement
{
    public CCSRadarElementImpl(nint handle) : base(handle) { }

    private static nint? _ElementTypeOffset;

    public ref uint ElementType
    {
        get
        {
            _ElementTypeOffset = _ElementTypeOffset ?? Schema.GetOffset(0x6619A9743991D36B);
            return ref _Handle.AsRef<uint>(_ElementTypeOffset!.Value);
        }
    }
    private static nint? _ElementColorOffset;

    public ref uint ElementColor
    {
        get
        {
            _ElementColorOffset = _ElementColorOffset ?? Schema.GetOffset(0x6619A97489C5AFF2);
            return ref _Handle.AsRef<uint>(_ElementColorOffset!.Value);
        }
    }
    private static nint? _TeamFilterOffset;

    public ref uint TeamFilter
    {
        get
        {
            _TeamFilterOffset = _TeamFilterOffset ?? Schema.GetOffset(0x6619A974919CFBA2);
            return ref _Handle.AsRef<uint>(_TeamFilterOffset!.Value);
        }
    }

    public void ElementTypeUpdated() => Schema.Update(_Handle, 0x6619A9743991D36B);
    public void ElementColorUpdated() => Schema.Update(_Handle, 0x6619A97489C5AFF2);
    public void TeamFilterUpdated() => Schema.Update(_Handle, 0x6619A974919CFBA2);
}