// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFilterMultipleImpl : CBaseFilterImpl, CFilterMultiple
{
    public CFilterMultipleImpl(nint handle) : base(handle) { }

    private static nint? _FilterTypeOffset;

    public ref filter_t FilterType {
        get {
            _FilterTypeOffset = _FilterTypeOffset ?? Schema.GetOffset(0x6EA0578071861EDB);
            return ref _Handle.AsRef<filter_t>(_FilterTypeOffset!.Value);
        }
    }
    public ISchemaStringFixedArray FilterName {
        get => new SchemaStringFixedArray(_Handle, 0x6EA0578009C86445, 10, 8, 8);
    }
    public ISchemaFixedArray<CHandle<CBaseEntity>> Filter {
        get => new SchemaFixedArray<CHandle<CBaseEntity>>(_Handle, 0x6EA0578045D9E0B1, 10, 4, 4);
    }


}