// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFilterStageImpl : SchemaClass, CFilterStage
{
    public CFilterStageImpl(nint handle) : base(handle) { }

    private static nint? _FilterTypeOffset;

    public string FilterType
    {
        get
        {
            _FilterTypeOffset = _FilterTypeOffset ?? Schema.GetOffset(0x38F1B4EA7E582F6F);
            return Schema.GetCUtlString(_Handle.Read<nint>(_FilterTypeOffset!.Value));
        }
        set
        {
            _FilterTypeOffset = _FilterTypeOffset ?? Schema.GetOffset(0x38F1B4EA7E582F6F);
            Schema.SetCUtlString(_Handle, _FilterTypeOffset!.Value, value);
        }
    }
    private static nint? _FrequencyOffset;

    public ref float Frequency
    {
        get
        {
            _FrequencyOffset = _FrequencyOffset ?? Schema.GetOffset(0x38F1B4EAD2C16DD7);
            return ref _Handle.AsRef<float>(_FrequencyOffset!.Value);
        }
    }
    private static nint? _QOffset;

    public ref float Q
    {
        get
        {
            _QOffset = _QOffset ?? Schema.GetOffset(0x38F1B4EA96122E3A);
            return ref _Handle.AsRef<float>(_QOffset!.Value);
        }
    }
    private static nint? _FldbGainOffset;

    public ref float FldbGain
    {
        get
        {
            _FldbGainOffset = _FldbGainOffset ?? Schema.GetOffset(0x38F1B4EA31BF2DF2);
            return ref _Handle.AsRef<float>(_FldbGainOffset!.Value);
        }
    }
    private static nint? _FilterSlopeOffset;

    public ref VMixFilterSlope_t FilterSlope
    {
        get
        {
            _FilterSlopeOffset = _FilterSlopeOffset ?? Schema.GetOffset(0x38F1B4EA6387D992);
            return ref _Handle.AsRef<VMixFilterSlope_t>(_FilterSlopeOffset!.Value);
        }
    }
    private static nint? _ChannelSetOffset;

    public ref VMixFilterChannelSet_t ChannelSet
    {
        get
        {
            _ChannelSetOffset = _ChannelSetOffset ?? Schema.GetOffset(0x38F1B4EA9B251258);
            return ref _Handle.AsRef<VMixFilterChannelSet_t>(_ChannelSetOffset!.Value);
        }
    }
    private static nint? _EnableOffset;

    public ref bool Enable
    {
        get
        {
            _EnableOffset = _EnableOffset ?? Schema.GetOffset(0x38F1B4EA13C00D2E);
            return ref _Handle.AsRef<bool>(_EnableOffset!.Value);
        }
    }

}