// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFuncMoverImpl : CBaseModelEntityImpl, CFuncMover
{
    public CFuncMoverImpl(nint handle) : base(handle) { }

    private static nint? _PathNameOffset;

    public string PathName
    {
        get
        {
            _PathNameOffset = _PathNameOffset ?? Schema.GetOffset(0x320E8B6981A419FD);
            return Schema.GetString(_Handle.Read<nint>(_PathNameOffset!.Value));
        }
        set
        {
            _PathNameOffset = _PathNameOffset ?? Schema.GetOffset(0x320E8B6981A419FD);
            Schema.SetString(_Handle, _PathNameOffset!.Value, value);
        }
    }
    private static nint? _PathMoverOffset;

    public ref CHandle<CPathMover> PathMover
    {
        get
        {
            _PathMoverOffset = _PathMoverOffset ?? Schema.GetOffset(0x320E8B69AFA877CD);
            return ref _Handle.AsRef<CHandle<CPathMover>>(_PathMoverOffset!.Value);
        }
    }
    private static nint? _PrevPathMoverOffset;

    public ref CHandle<CPathMover> PrevPathMover
    {
        get
        {
            _PrevPathMoverOffset = _PrevPathMoverOffset ?? Schema.GetOffset(0x320E8B69FB9DE3C6);
            return ref _Handle.AsRef<CHandle<CPathMover>>(_PrevPathMoverOffset!.Value);
        }
    }
    private static nint? _PathNodeStartOffset;

    public string PathNodeStart
    {
        get
        {
            _PathNodeStartOffset = _PathNodeStartOffset ?? Schema.GetOffset(0x320E8B691B0A1252);
            return Schema.GetString(_Handle.Read<nint>(_PathNodeStartOffset!.Value));
        }
        set
        {
            _PathNodeStartOffset = _PathNodeStartOffset ?? Schema.GetOffset(0x320E8B691B0A1252);
            Schema.SetString(_Handle, _PathNodeStartOffset!.Value, value);
        }
    }
    private static nint? _PathNodeEndOffset;

    public string PathNodeEnd
    {
        get
        {
            _PathNodeEndOffset = _PathNodeEndOffset ?? Schema.GetOffset(0x320E8B69F1D1AED7);
            return Schema.GetString(_Handle.Read<nint>(_PathNodeEndOffset!.Value));
        }
        set
        {
            _PathNodeEndOffset = _PathNodeEndOffset ?? Schema.GetOffset(0x320E8B69F1D1AED7);
            Schema.SetString(_Handle, _PathNodeEndOffset!.Value, value);
        }
    }
    private static nint? _IgnoreEndNodeOffset;

    public ref bool IgnoreEndNode
    {
        get
        {
            _IgnoreEndNodeOffset = _IgnoreEndNodeOffset ?? Schema.GetOffset(0x320E8B69D7345D9C);
            return ref _Handle.AsRef<bool>(_IgnoreEndNodeOffset!.Value);
        }
    }
    private static nint? _MoveTypeOffset;

    public ref CFuncMover__Move_t MoveType
    {
        get
        {
            _MoveTypeOffset = _MoveTypeOffset ?? Schema.GetOffset(0x320E8B69E635C185);
            return ref _Handle.AsRef<CFuncMover__Move_t>(_MoveTypeOffset!.Value);
        }
    }
    private static nint? _IsReversingOffset;

    public ref bool IsReversing
    {
        get
        {
            _IsReversingOffset = _IsReversingOffset ?? Schema.GetOffset(0x320E8B69899E5BEE);
            return ref _Handle.AsRef<bool>(_IsReversingOffset!.Value);
        }
    }
    private static nint? _StartSpeedOffset;

    public ref float StartSpeed
    {
        get
        {
            _StartSpeedOffset = _StartSpeedOffset ?? Schema.GetOffset(0x320E8B695EAB0EE0);
            return ref _Handle.AsRef<float>(_StartSpeedOffset!.Value);
        }
    }
    private static nint? _PathLocationOffset;

    public ref float PathLocation
    {
        get
        {
            _PathLocationOffset = _PathLocationOffset ?? Schema.GetOffset(0x320E8B694232CFBF);
            return ref _Handle.AsRef<float>(_PathLocationOffset!.Value);
        }
    }
    private static nint? _TOffset;

    public ref float T
    {
        get
        {
            _TOffset = _TOffset ?? Schema.GetOffset(0x320E8B6993122981);
            return ref _Handle.AsRef<float>(_TOffset!.Value);
        }
    }
    private static nint? _CurrentNodeIndexOffset;

    public ref int CurrentNodeIndex
    {
        get
        {
            _CurrentNodeIndexOffset = _CurrentNodeIndexOffset ?? Schema.GetOffset(0x320E8B6948C15E6E);
            return ref _Handle.AsRef<int>(_CurrentNodeIndexOffset!.Value);
        }
    }
    private static nint? _PreviousNodeIndexOffset;

    public ref int PreviousNodeIndex
    {
        get
        {
            _PreviousNodeIndexOffset = _PreviousNodeIndexOffset ?? Schema.GetOffset(0x320E8B690BA7740C);
            return ref _Handle.AsRef<int>(_PreviousNodeIndexOffset!.Value);
        }
    }
    private static nint? _SolidTypeOffset;

    public ref SolidType_t SolidType
    {
        get
        {
            _SolidTypeOffset = _SolidTypeOffset ?? Schema.GetOffset(0x320E8B695B4C380F);
            return ref _Handle.AsRef<SolidType_t>(_SolidTypeOffset!.Value);
        }
    }
    private static nint? _IsMovingOffset;

    public ref bool IsMoving
    {
        get
        {
            _IsMovingOffset = _IsMovingOffset ?? Schema.GetOffset(0x320E8B69874D1717);
            return ref _Handle.AsRef<bool>(_IsMovingOffset!.Value);
        }
    }
    private static nint? _TimeToReachMaxSpeedOffset;

    public ref float TimeToReachMaxSpeed
    {
        get
        {
            _TimeToReachMaxSpeedOffset = _TimeToReachMaxSpeedOffset ?? Schema.GetOffset(0x320E8B699452902F);
            return ref _Handle.AsRef<float>(_TimeToReachMaxSpeedOffset!.Value);
        }
    }
    private static nint? _DistanceToReachMaxSpeedOffset;

    public ref float DistanceToReachMaxSpeed
    {
        get
        {
            _DistanceToReachMaxSpeedOffset = _DistanceToReachMaxSpeedOffset ?? Schema.GetOffset(0x320E8B6907733475);
            return ref _Handle.AsRef<float>(_DistanceToReachMaxSpeedOffset!.Value);
        }
    }
    private static nint? _TimeToReachZeroSpeedOffset;

    public ref float TimeToReachZeroSpeed
    {
        get
        {
            _TimeToReachZeroSpeedOffset = _TimeToReachZeroSpeedOffset ?? Schema.GetOffset(0x320E8B69816228FB);
            return ref _Handle.AsRef<float>(_TimeToReachZeroSpeedOffset!.Value);
        }
    }
    private static nint? _ComputedDistanceToReachMaxSpeedOffset;

    public ref float ComputedDistanceToReachMaxSpeed
    {
        get
        {
            _ComputedDistanceToReachMaxSpeedOffset = _ComputedDistanceToReachMaxSpeedOffset ?? Schema.GetOffset(0x320E8B69359FD260);
            return ref _Handle.AsRef<float>(_ComputedDistanceToReachMaxSpeedOffset!.Value);
        }
    }
    private static nint? _ComputedDistanceToReachZeroSpeedOffset;

    public ref float ComputedDistanceToReachZeroSpeed
    {
        get
        {
            _ComputedDistanceToReachZeroSpeedOffset = _ComputedDistanceToReachZeroSpeedOffset ?? Schema.GetOffset(0x320E8B694037DD4A);
            return ref _Handle.AsRef<float>(_ComputedDistanceToReachZeroSpeedOffset!.Value);
        }
    }
    private static nint? _StartCurveScaleOffset;

    public ref float StartCurveScale
    {
        get
        {
            _StartCurveScaleOffset = _StartCurveScaleOffset ?? Schema.GetOffset(0x320E8B6933788D4E);
            return ref _Handle.AsRef<float>(_StartCurveScaleOffset!.Value);
        }
    }
    private static nint? _StopCurveScaleOffset;

    public ref float StopCurveScale
    {
        get
        {
            _StopCurveScaleOffset = _StopCurveScaleOffset ?? Schema.GetOffset(0x320E8B69507BDED4);
            return ref _Handle.AsRef<float>(_StopCurveScaleOffset!.Value);
        }
    }
    private static nint? _DistanceToReachZeroSpeedOffset;

    public ref float DistanceToReachZeroSpeed
    {
        get
        {
            _DistanceToReachZeroSpeedOffset = _DistanceToReachZeroSpeedOffset ?? Schema.GetOffset(0x320E8B69354237E9);
            return ref _Handle.AsRef<float>(_DistanceToReachZeroSpeedOffset!.Value);
        }
    }
    private static nint? _TimeMovementStartOffset;
    private GameTime_tImpl? _TimeMovementStartInstance;

    public GameTime_t TimeMovementStart
    {
        get
        {
            _TimeMovementStartOffset = _TimeMovementStartOffset ?? Schema.GetOffset(0x320E8B69CD2B8B85);
            var instance = _TimeMovementStartInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _TimeMovementStartOffset!.Value);
            return instance;
        }
    }
    private static nint? _TimeMovementStopOffset;
    private GameTime_tImpl? _TimeMovementStopInstance;

    public GameTime_t TimeMovementStop
    {
        get
        {
            _TimeMovementStopOffset = _TimeMovementStopOffset ?? Schema.GetOffset(0x320E8B696E9B82D7);
            var instance = _TimeMovementStopInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _TimeMovementStopOffset!.Value);
            return instance;
        }
    }
    private static nint? _StopAtNodeOffset;

    public ref CHandle<CMoverPathNode> StopAtNode
    {
        get
        {
            _StopAtNodeOffset = _StopAtNodeOffset ?? Schema.GetOffset(0x320E8B6907744C56);
            return ref _Handle.AsRef<CHandle<CMoverPathNode>>(_StopAtNodeOffset!.Value);
        }
    }
    private static nint? _PathLocationToBeginStopOffset;

    public ref float PathLocationToBeginStop
    {
        get
        {
            _PathLocationToBeginStopOffset = _PathLocationToBeginStopOffset ?? Schema.GetOffset(0x320E8B69976C5777);
            return ref _Handle.AsRef<float>(_PathLocationToBeginStopOffset!.Value);
        }
    }
    private static nint? _PathLocationStartOffset;

    public ref float PathLocationStart
    {
        get
        {
            _PathLocationStartOffset = _PathLocationStartOffset ?? Schema.GetOffset(0x320E8B692C806F55);
            return ref _Handle.AsRef<float>(_PathLocationStartOffset!.Value);
        }
    }
    private static nint? _BeginStopTOffset;

    public ref float BeginStopT
    {
        get
        {
            _BeginStopTOffset = _BeginStopTOffset ?? Schema.GetOffset(0x320E8B69BCC3AE54);
            return ref _Handle.AsRef<float>(_BeginStopTOffset!.Value);
        }
    }
    private static nint? _StartForwardSoundOffset;

    public ref CGameSoundEventName StartForwardSound
    {
        get
        {
            _StartForwardSoundOffset = _StartForwardSoundOffset ?? Schema.GetOffset(0x320E8B69CBDFD56B);
            return ref _Handle.AsRef<CGameSoundEventName>(_StartForwardSoundOffset!.Value);
        }
    }
    private static nint? _LoopForwardSoundOffset;

    public ref CGameSoundEventName LoopForwardSound
    {
        get
        {
            _LoopForwardSoundOffset = _LoopForwardSoundOffset ?? Schema.GetOffset(0x320E8B69C875F2F7);
            return ref _Handle.AsRef<CGameSoundEventName>(_LoopForwardSoundOffset!.Value);
        }
    }
    private static nint? _StopForwardSoundOffset;

    public ref CGameSoundEventName StopForwardSound
    {
        get
        {
            _StopForwardSoundOffset = _StopForwardSoundOffset ?? Schema.GetOffset(0x320E8B69B72A6EC9);
            return ref _Handle.AsRef<CGameSoundEventName>(_StopForwardSoundOffset!.Value);
        }
    }
    private static nint? _StartReverseSoundOffset;

    public ref CGameSoundEventName StartReverseSound
    {
        get
        {
            _StartReverseSoundOffset = _StartReverseSoundOffset ?? Schema.GetOffset(0x320E8B6927D9C282);
            return ref _Handle.AsRef<CGameSoundEventName>(_StartReverseSoundOffset!.Value);
        }
    }
    private static nint? _LoopReverseSoundOffset;

    public ref CGameSoundEventName LoopReverseSound
    {
        get
        {
            _LoopReverseSoundOffset = _LoopReverseSoundOffset ?? Schema.GetOffset(0x320E8B69FC2C15CE);
            return ref _Handle.AsRef<CGameSoundEventName>(_LoopReverseSoundOffset!.Value);
        }
    }
    private static nint? _StopReverseSoundOffset;

    public ref CGameSoundEventName StopReverseSound
    {
        get
        {
            _StopReverseSoundOffset = _StopReverseSoundOffset ?? Schema.GetOffset(0x320E8B69B0EFF4BC);
            return ref _Handle.AsRef<CGameSoundEventName>(_StopReverseSoundOffset!.Value);
        }
    }
    private static nint? _ArriveAtDestinationSoundOffset;

    public ref CGameSoundEventName ArriveAtDestinationSound
    {
        get
        {
            _ArriveAtDestinationSoundOffset = _ArriveAtDestinationSoundOffset ?? Schema.GetOffset(0x320E8B696350F6A0);
            return ref _Handle.AsRef<CGameSoundEventName>(_ArriveAtDestinationSoundOffset!.Value);
        }
    }
    private static nint? _OnMovementEndOffset;

    public ref CEntityIOOutput OnMovementEnd
    {
        get
        {
            _OnMovementEndOffset = _OnMovementEndOffset ?? Schema.GetOffset(0x320E8B699BD1966A);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnMovementEndOffset!.Value);
        }
    }
    private static nint? _StartAtClosestPointOffset;

    public ref bool StartAtClosestPoint
    {
        get
        {
            _StartAtClosestPointOffset = _StartAtClosestPointOffset ?? Schema.GetOffset(0x320E8B69FBBC7ACD);
            return ref _Handle.AsRef<bool>(_StartAtClosestPointOffset!.Value);
        }
    }
    private static nint? _StartAtEndOffset;

    public ref bool StartAtEnd
    {
        get
        {
            _StartAtEndOffset = _StartAtEndOffset ?? Schema.GetOffset(0x320E8B694B214AF7);
            return ref _Handle.AsRef<bool>(_StartAtEndOffset!.Value);
        }
    }
    private static nint? _StartFollowingClosestMoverOffset;

    public ref bool StartFollowingClosestMover
    {
        get
        {
            _StartFollowingClosestMoverOffset = _StartFollowingClosestMoverOffset ?? Schema.GetOffset(0x320E8B69AAD3ACDA);
            return ref _Handle.AsRef<bool>(_StartFollowingClosestMoverOffset!.Value);
        }
    }
    private static nint? _OrientationUpdateOffset;

    public ref CFuncMover__OrientationUpdate_t OrientationUpdate
    {
        get
        {
            _OrientationUpdateOffset = _OrientationUpdateOffset ?? Schema.GetOffset(0x320E8B69D0D215E3);
            return ref _Handle.AsRef<CFuncMover__OrientationUpdate_t>(_OrientationUpdateOffset!.Value);
        }
    }
    private static nint? _TimeStartOrientationChangeOffset;
    private GameTime_tImpl? _TimeStartOrientationChangeInstance;

    public GameTime_t TimeStartOrientationChange
    {
        get
        {
            _TimeStartOrientationChangeOffset = _TimeStartOrientationChangeOffset ?? Schema.GetOffset(0x320E8B698090B2A8);
            var instance = _TimeStartOrientationChangeInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _TimeStartOrientationChangeOffset!.Value);
            return instance;
        }
    }
    private static nint? _TimeToBlendToNewOrientationOffset;

    public ref float TimeToBlendToNewOrientation
    {
        get
        {
            _TimeToBlendToNewOrientationOffset = _TimeToBlendToNewOrientationOffset ?? Schema.GetOffset(0x320E8B69F64E85BB);
            return ref _Handle.AsRef<float>(_TimeToBlendToNewOrientationOffset!.Value);
        }
    }
    private static nint? _DurationBlendToNewOrientationRanOffset;

    public ref float DurationBlendToNewOrientationRan
    {
        get
        {
            _DurationBlendToNewOrientationRanOffset = _DurationBlendToNewOrientationRanOffset ?? Schema.GetOffset(0x320E8B693B19BF08);
            return ref _Handle.AsRef<float>(_DurationBlendToNewOrientationRanOffset!.Value);
        }
    }
    private static nint? _CreateMovableNavMeshOffset;

    public ref bool CreateMovableNavMesh
    {
        get
        {
            _CreateMovableNavMeshOffset = _CreateMovableNavMeshOffset ?? Schema.GetOffset(0x320E8B6985442AAF);
            return ref _Handle.AsRef<bool>(_CreateMovableNavMeshOffset!.Value);
        }
    }
    private static nint? _CreateMovableSurfaceGraphOffset;

    public ref bool CreateMovableSurfaceGraph
    {
        get
        {
            _CreateMovableSurfaceGraphOffset = _CreateMovableSurfaceGraphOffset ?? Schema.GetOffset(0x320E8B690BC6AA1C);
            return ref _Handle.AsRef<bool>(_CreateMovableSurfaceGraphOffset!.Value);
        }
    }
    private static nint? _AllowMovableNavMeshDockingOnEntireEntityOffset;

    public ref bool AllowMovableNavMeshDockingOnEntireEntity
    {
        get
        {
            _AllowMovableNavMeshDockingOnEntireEntityOffset = _AllowMovableNavMeshDockingOnEntireEntityOffset ?? Schema.GetOffset(0x320E8B690CC0563A);
            return ref _Handle.AsRef<bool>(_AllowMovableNavMeshDockingOnEntireEntityOffset!.Value);
        }
    }
    private static nint? _OnNodePassedOffset;
    private SchemaUntypedField? _OnNodePassedInstance;

    public SchemaUntypedField OnNodePassed
    {
        get
        {
            _OnNodePassedOffset = _OnNodePassedOffset ?? Schema.GetOffset(0x320E8B69709328FC);
            var instance = _OnNodePassedInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _OnNodePassedOffset!.Value);
            return instance;
        }
    }
    private static nint? _OrientationMatchEntityNameOffset;

    public string OrientationMatchEntityName
    {
        get
        {
            _OrientationMatchEntityNameOffset = _OrientationMatchEntityNameOffset ?? Schema.GetOffset(0x320E8B69384CF18A);
            return Schema.GetString(_Handle.Read<nint>(_OrientationMatchEntityNameOffset!.Value));
        }
        set
        {
            _OrientationMatchEntityNameOffset = _OrientationMatchEntityNameOffset ?? Schema.GetOffset(0x320E8B69384CF18A);
            Schema.SetString(_Handle, _OrientationMatchEntityNameOffset!.Value, value);
        }
    }
    private static nint? _OrientationMatchEntityOffset;

    public ref CHandle<CBaseEntity> OrientationMatchEntity
    {
        get
        {
            _OrientationMatchEntityOffset = _OrientationMatchEntityOffset ?? Schema.GetOffset(0x320E8B6924A0D317);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_OrientationMatchEntityOffset!.Value);
        }
    }
    private static nint? _TimeToTraverseToNextNodeOffset;

    public ref float TimeToTraverseToNextNode
    {
        get
        {
            _TimeToTraverseToNextNodeOffset = _TimeToTraverseToNextNodeOffset ?? Schema.GetOffset(0x320E8B6942129DF9);
            return ref _Handle.AsRef<float>(_TimeToTraverseToNextNodeOffset!.Value);
        }
    }
    private static nint? _LerpToNewPosStartInPathEntitySpaceOffset;

    public ref Vector LerpToNewPosStartInPathEntitySpace
    {
        get
        {
            _LerpToNewPosStartInPathEntitySpaceOffset = _LerpToNewPosStartInPathEntitySpaceOffset ?? Schema.GetOffset(0x320E8B6958D80CD2);
            return ref _Handle.AsRef<Vector>(_LerpToNewPosStartInPathEntitySpaceOffset!.Value);
        }
    }
    private static nint? _LerpToNewPosEndInPathEntitySpaceOffset;

    public ref Vector LerpToNewPosEndInPathEntitySpace
    {
        get
        {
            _LerpToNewPosEndInPathEntitySpaceOffset = _LerpToNewPosEndInPathEntitySpaceOffset ?? Schema.GetOffset(0x320E8B698269BEB5);
            return ref _Handle.AsRef<Vector>(_LerpToNewPosEndInPathEntitySpaceOffset!.Value);
        }
    }
    private static nint? _LerpToPositionTOffset;

    public ref float LerpToPositionT
    {
        get
        {
            _LerpToPositionTOffset = _LerpToPositionTOffset ?? Schema.GetOffset(0x320E8B69C191D824);
            return ref _Handle.AsRef<float>(_LerpToPositionTOffset!.Value);
        }
    }
    private static nint? _LerpToPositionDeltaTOffset;

    public ref float LerpToPositionDeltaT
    {
        get
        {
            _LerpToPositionDeltaTOffset = _LerpToPositionDeltaTOffset ?? Schema.GetOffset(0x320E8B69A0AFA3BE);
            return ref _Handle.AsRef<float>(_LerpToPositionDeltaTOffset!.Value);
        }
    }
    private static nint? _OnLerpToPositionCompleteOffset;

    public ref CEntityIOOutput OnLerpToPositionComplete
    {
        get
        {
            _OnLerpToPositionCompleteOffset = _OnLerpToPositionCompleteOffset ?? Schema.GetOffset(0x320E8B693D72E078);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnLerpToPositionCompleteOffset!.Value);
        }
    }
    private static nint? _IsPausedOffset;

    public ref bool IsPaused
    {
        get
        {
            _IsPausedOffset = _IsPausedOffset ?? Schema.GetOffset(0x320E8B690BA146BB);
            return ref _Handle.AsRef<bool>(_IsPausedOffset!.Value);
        }
    }
    private static nint? _TransitionedToPathNodeActionOffset;

    public ref CFuncMover__TransitionToPathNodeAction_t TransitionedToPathNodeAction
    {
        get
        {
            _TransitionedToPathNodeActionOffset = _TransitionedToPathNodeActionOffset ?? Schema.GetOffset(0x320E8B696FEE6BBE);
            return ref _Handle.AsRef<CFuncMover__TransitionToPathNodeAction_t>(_TransitionedToPathNodeActionOffset!.Value);
        }
    }
    private static nint? _TransitionSourceOrientationOffset;

    public ref Quaternion TransitionSourceOrientation
    {
        get
        {
            _TransitionSourceOrientationOffset = _TransitionSourceOrientationOffset ?? Schema.GetOffset(0x320E8B695AA3CF34);
            return ref _Handle.AsRef<Quaternion>(_TransitionSourceOrientationOffset!.Value);
        }
    }
    private static nint? _DelayedTeleportToNodeOffset;

    public ref int DelayedTeleportToNode
    {
        get
        {
            _DelayedTeleportToNodeOffset = _DelayedTeleportToNodeOffset ?? Schema.GetOffset(0x320E8B69A71F8CA3);
            return ref _Handle.AsRef<int>(_DelayedTeleportToNodeOffset!.Value);
        }
    }
    private static nint? _IsImGuiLoggingOffset;

    public ref bool IsImGuiLogging
    {
        get
        {
            _IsImGuiLoggingOffset = _IsImGuiLoggingOffset ?? Schema.GetOffset(0x320E8B690BF8C787);
            return ref _Handle.AsRef<bool>(_IsImGuiLoggingOffset!.Value);
        }
    }
    private static nint? _IsImGuiEntTextLoggingOffset;

    public ref bool IsImGuiEntTextLogging
    {
        get
        {
            _IsImGuiEntTextLoggingOffset = _IsImGuiEntTextLoggingOffset ?? Schema.GetOffset(0x320E8B6922F2184D);
            return ref _Handle.AsRef<bool>(_IsImGuiEntTextLoggingOffset!.Value);
        }
    }
    private static nint? _SpeedOffset;

    public ref float Speed
    {
        get
        {
            _SpeedOffset = _SpeedOffset ?? Schema.GetOffset(0x320E8B69C631B7EA);
            return ref _Handle.AsRef<float>(_SpeedOffset!.Value);
        }
    }
    private static nint? _FollowEntityOffset;

    public ref CHandle<CBaseEntity> FollowEntity
    {
        get
        {
            _FollowEntityOffset = _FollowEntityOffset ?? Schema.GetOffset(0x320E8B6969846129);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_FollowEntityOffset!.Value);
        }
    }
    private static nint? _FollowDistanceOffset;

    public ref float FollowDistance
    {
        get
        {
            _FollowDistanceOffset = _FollowDistanceOffset ?? Schema.GetOffset(0x320E8B69CF6A55D9);
            return ref _Handle.AsRef<float>(_FollowDistanceOffset!.Value);
        }
    }
    private static nint? _FollowMinimumSpeedOffset;

    public ref float FollowMinimumSpeed
    {
        get
        {
            _FollowMinimumSpeedOffset = _FollowMinimumSpeedOffset ?? Schema.GetOffset(0x320E8B69929585C9);
            return ref _Handle.AsRef<float>(_FollowMinimumSpeedOffset!.Value);
        }
    }
    private static nint? _CurFollowEntityTOffset;

    public ref float CurFollowEntityT
    {
        get
        {
            _CurFollowEntityTOffset = _CurFollowEntityTOffset ?? Schema.GetOffset(0x320E8B6977610EE3);
            return ref _Handle.AsRef<float>(_CurFollowEntityTOffset!.Value);
        }
    }
    private static nint? _CurFollowSpeedOffset;

    public ref float CurFollowSpeed
    {
        get
        {
            _CurFollowSpeedOffset = _CurFollowSpeedOffset ?? Schema.GetOffset(0x320E8B6958BEEE69);
            return ref _Handle.AsRef<float>(_CurFollowSpeedOffset!.Value);
        }
    }
    private static nint? _StrOrientationFaceEntityNameOffset;

    public string StrOrientationFaceEntityName
    {
        get
        {
            _StrOrientationFaceEntityNameOffset = _StrOrientationFaceEntityNameOffset ?? Schema.GetOffset(0x320E8B694B008CC7);
            return Schema.GetString(_Handle.Read<nint>(_StrOrientationFaceEntityNameOffset!.Value));
        }
        set
        {
            _StrOrientationFaceEntityNameOffset = _StrOrientationFaceEntityNameOffset ?? Schema.GetOffset(0x320E8B694B008CC7);
            Schema.SetString(_Handle, _StrOrientationFaceEntityNameOffset!.Value, value);
        }
    }
    private static nint? _OrientationFaceEntityOffset;

    public ref CHandle<CBaseEntity> OrientationFaceEntity
    {
        get
        {
            _OrientationFaceEntityOffset = _OrientationFaceEntityOffset ?? Schema.GetOffset(0x320E8B696BA187E1);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_OrientationFaceEntityOffset!.Value);
        }
    }
    private static nint? _OnStartOffset;

    public ref CEntityIOOutput OnStart
    {
        get
        {
            _OnStartOffset = _OnStartOffset ?? Schema.GetOffset(0x320E8B69C3FE848C);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnStartOffset!.Value);
        }
    }
    private static nint? _OnStartForwardOffset;

    public ref CEntityIOOutput OnStartForward
    {
        get
        {
            _OnStartForwardOffset = _OnStartForwardOffset ?? Schema.GetOffset(0x320E8B69FC63B371);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnStartForwardOffset!.Value);
        }
    }
    private static nint? _OnStartReverseOffset;

    public ref CEntityIOOutput OnStartReverse
    {
        get
        {
            _OnStartReverseOffset = _OnStartReverseOffset ?? Schema.GetOffset(0x320E8B693AC2BDEA);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnStartReverseOffset!.Value);
        }
    }
    private static nint? _OnStopOffset;

    public ref CEntityIOOutput OnStop
    {
        get
        {
            _OnStopOffset = _OnStopOffset ?? Schema.GetOffset(0x320E8B6915A596E8);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnStopOffset!.Value);
        }
    }
    private static nint? _OnStoppedOffset;

    public ref CEntityIOOutput OnStopped
    {
        get
        {
            _OnStoppedOffset = _OnStoppedOffset ?? Schema.GetOffset(0x320E8B69161C44C9);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnStoppedOffset!.Value);
        }
    }
    private static nint? _NextNodeReturnsCurrentOffset;

    public ref bool NextNodeReturnsCurrent
    {
        get
        {
            _NextNodeReturnsCurrentOffset = _NextNodeReturnsCurrentOffset ?? Schema.GetOffset(0x320E8B69097A17E4);
            return ref _Handle.AsRef<bool>(_NextNodeReturnsCurrentOffset!.Value);
        }
    }
    private static nint? _StartedMovingOffset;

    public ref bool StartedMoving
    {
        get
        {
            _StartedMovingOffset = _StartedMovingOffset ?? Schema.GetOffset(0x320E8B6939B1504C);
            return ref _Handle.AsRef<bool>(_StartedMovingOffset!.Value);
        }
    }
    private static nint? _FollowEntityDirectionOffset;

    public ref CFuncMover__FollowEntityDirection_t FollowEntityDirection
    {
        get
        {
            _FollowEntityDirectionOffset = _FollowEntityDirectionOffset ?? Schema.GetOffset(0x320E8B69E14C9BB7);
            return ref _Handle.AsRef<CFuncMover__FollowEntityDirection_t>(_FollowEntityDirectionOffset!.Value);
        }
    }
    private static nint? _FollowMoverOffset;

    public ref CHandle<CFuncMover> FollowMover
    {
        get
        {
            _FollowMoverOffset = _FollowMoverOffset ?? Schema.GetOffset(0x320E8B69F740ACBF);
            return ref _Handle.AsRef<CHandle<CFuncMover>>(_FollowMoverOffset!.Value);
        }
    }
    private static nint? _FollowEntityNameOffset;

    public string FollowEntityName
    {
        get
        {
            _FollowEntityNameOffset = _FollowEntityNameOffset ?? Schema.GetOffset(0x320E8B69D56EA0F8);
            return Schema.GetString(_Handle.Read<nint>(_FollowEntityNameOffset!.Value));
        }
        set
        {
            _FollowEntityNameOffset = _FollowEntityNameOffset ?? Schema.GetOffset(0x320E8B69D56EA0F8);
            Schema.SetString(_Handle, _FollowEntityNameOffset!.Value, value);
        }
    }
    private static nint? _FollowMoverEntityNameOffset;

    public string FollowMoverEntityName
    {
        get
        {
            _FollowMoverEntityNameOffset = _FollowMoverEntityNameOffset ?? Schema.GetOffset(0x320E8B69C148B6E1);
            return Schema.GetString(_Handle.Read<nint>(_FollowMoverEntityNameOffset!.Value));
        }
        set
        {
            _FollowMoverEntityNameOffset = _FollowMoverEntityNameOffset ?? Schema.GetOffset(0x320E8B69C148B6E1);
            Schema.SetString(_Handle, _FollowMoverEntityNameOffset!.Value, value);
        }
    }
    private static nint? _FollowMoverDistanceOffset;

    public ref float FollowMoverDistance
    {
        get
        {
            _FollowMoverDistanceOffset = _FollowMoverDistanceOffset ?? Schema.GetOffset(0x320E8B6997F8FE00);
            return ref _Handle.AsRef<float>(_FollowMoverDistanceOffset!.Value);
        }
    }
    private static nint? _FollowMoverRatioOffset;

    public ref float FollowMoverRatio
    {
        get
        {
            _FollowMoverRatioOffset = _FollowMoverRatioOffset ?? Schema.GetOffset(0x320E8B698AD69AD2);
            return ref _Handle.AsRef<float>(_FollowMoverRatioOffset!.Value);
        }
    }
    private static nint? _FollowMoverCalculatedDistanceOffset;

    public ref float FollowMoverCalculatedDistance
    {
        get
        {
            _FollowMoverCalculatedDistanceOffset = _FollowMoverCalculatedDistanceOffset ?? Schema.GetOffset(0x320E8B6956A2C074);
            return ref _Handle.AsRef<float>(_FollowMoverCalculatedDistanceOffset!.Value);
        }
    }
    private static nint? _FollowMoverSpringStrengthOffset;

    public ref float FollowMoverSpringStrength
    {
        get
        {
            _FollowMoverSpringStrengthOffset = _FollowMoverSpringStrengthOffset ?? Schema.GetOffset(0x320E8B695CE8CC87);
            return ref _Handle.AsRef<float>(_FollowMoverSpringStrengthOffset!.Value);
        }
    }
    private static nint? _FollowMoverConstraintPriorityOffset;

    public ref int FollowMoverConstraintPriority
    {
        get
        {
            _FollowMoverConstraintPriorityOffset = _FollowMoverConstraintPriorityOffset ?? Schema.GetOffset(0x320E8B69E4EFD3C2);
            return ref _Handle.AsRef<int>(_FollowMoverConstraintPriorityOffset!.Value);
        }
    }
    private static nint? _FollowMoverCouplerRangeOffset;

    public ref Vector2D FollowMoverCouplerRange
    {
        get
        {
            _FollowMoverCouplerRangeOffset = _FollowMoverCouplerRangeOffset ?? Schema.GetOffset(0x320E8B69D982E782);
            return ref _Handle.AsRef<Vector2D>(_FollowMoverCouplerRangeOffset!.Value);
        }
    }
    private static nint? _FollowConstraintsInitializedOffset;

    public ref bool FollowConstraintsInitialized
    {
        get
        {
            _FollowConstraintsInitializedOffset = _FollowConstraintsInitializedOffset ?? Schema.GetOffset(0x320E8B692E4782E2);
            return ref _Handle.AsRef<bool>(_FollowConstraintsInitializedOffset!.Value);
        }
    }
    private static nint? _FollowConstraintOffset;

    public ref CFuncMover__FollowConstraint_t FollowConstraint
    {
        get
        {
            _FollowConstraintOffset = _FollowConstraintOffset ?? Schema.GetOffset(0x320E8B6997B1D7F2);
            return ref _Handle.AsRef<CFuncMover__FollowConstraint_t>(_FollowConstraintOffset!.Value);
        }
    }
    private static nint? _FollowMoverSpeedOffset;

    public ref float FollowMoverSpeed
    {
        get
        {
            _FollowMoverSpeedOffset = _FollowMoverSpeedOffset ?? Schema.GetOffset(0x320E8B69C50E41B2);
            return ref _Handle.AsRef<float>(_FollowMoverSpeedOffset!.Value);
        }
    }
    private static nint? _FollowMoverVelocityOffset;

    public ref float FollowMoverVelocity
    {
        get
        {
            _FollowMoverVelocityOffset = _FollowMoverVelocityOffset ?? Schema.GetOffset(0x320E8B69141496E0);
            return ref _Handle.AsRef<float>(_FollowMoverVelocityOffset!.Value);
        }
    }
    private static nint? _TickMovementRanOffset;
    private GameTick_tImpl? _TickMovementRanInstance;

    public GameTick_t TickMovementRan
    {
        get
        {
            _TickMovementRanOffset = _TickMovementRanOffset ?? Schema.GetOffset(0x320E8B694A0C4C8E);
            var instance = _TickMovementRanInstance ??= new GameTick_tImpl(0);
            instance.DangerousSetHandle(_Handle + _TickMovementRanOffset!.Value);
            return instance;
        }
    }
    private static nint? _MovementSummaryOffset;
    private FuncMoverMovementSummary_tImpl? _MovementSummaryInstance;

    public FuncMoverMovementSummary_t MovementSummary
    {
        get
        {
            _MovementSummaryOffset = _MovementSummaryOffset ?? Schema.GetOffset(0x320E8B69C49463D0);
            var instance = _MovementSummaryInstance ??= new FuncMoverMovementSummary_tImpl(0);
            instance.DangerousSetHandle(_Handle + _MovementSummaryOffset!.Value);
            return instance;
        }
    }
    private static nint? _StopFromBeginStopTargetOffset;

    public ref bool StopFromBeginStopTarget
    {
        get
        {
            _StopFromBeginStopTargetOffset = _StopFromBeginStopTargetOffset ?? Schema.GetOffset(0x320E8B69162F1CD7);
            return ref _Handle.AsRef<bool>(_StopFromBeginStopTargetOffset!.Value);
        }
    }
    private static nint? _QueueStopOffset;

    public ref bool QueueStop
    {
        get
        {
            _QueueStopOffset = _QueueStopOffset ?? Schema.GetOffset(0x320E8B69109D47C0);
            return ref _Handle.AsRef<bool>(_QueueStopOffset!.Value);
        }
    }
    private static nint? _QueueStopMovingOffset;

    public ref bool QueueStopMoving
    {
        get
        {
            _QueueStopMovingOffset = _QueueStopMovingOffset ?? Schema.GetOffset(0x320E8B690D240066);
            return ref _Handle.AsRef<bool>(_QueueStopMovingOffset!.Value);
        }
    }
    private static nint? _QueueSetupPathMoverOffset;

    public ref bool QueueSetupPathMover
    {
        get
        {
            _QueueSetupPathMoverOffset = _QueueSetupPathMoverOffset ?? Schema.GetOffset(0x320E8B69E851D603);
            return ref _Handle.AsRef<bool>(_QueueSetupPathMoverOffset!.Value);
        }
    }
    private static nint? _PathRebuildStrategyOffset;

    public ref CFuncMover__PathRebuildStrategy_t PathRebuildStrategy
    {
        get
        {
            _PathRebuildStrategyOffset = _PathRebuildStrategyOffset ?? Schema.GetOffset(0x320E8B6989C0A69F);
            return ref _Handle.AsRef<CFuncMover__PathRebuildStrategy_t>(_PathRebuildStrategyOffset!.Value);
        }
    }

}