// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmBoneMaskSwitchNode__CDefinitionImpl : CNmBoneMaskValueNode__CDefinitionImpl, CNmBoneMaskSwitchNode__CDefinition
{
    public CNmBoneMaskSwitchNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _SwitchValueNodeIdxOffset;

    public ref short SwitchValueNodeIdx {
        get {
            _SwitchValueNodeIdxOffset = _SwitchValueNodeIdxOffset ?? Schema.GetOffset(0xD21604677FBD7561);
            return ref _Handle.AsRef<short>(_SwitchValueNodeIdxOffset!.Value);
        }
    }
    private static nint? _TrueValueNodeIdxOffset;

    public ref short TrueValueNodeIdx {
        get {
            _TrueValueNodeIdxOffset = _TrueValueNodeIdxOffset ?? Schema.GetOffset(0xD2160467FDE74365);
            return ref _Handle.AsRef<short>(_TrueValueNodeIdxOffset!.Value);
        }
    }
    private static nint? _FalseValueNodeIdxOffset;

    public ref short FalseValueNodeIdx {
        get {
            _FalseValueNodeIdxOffset = _FalseValueNodeIdxOffset ?? Schema.GetOffset(0xD21604678DBA2C78);
            return ref _Handle.AsRef<short>(_FalseValueNodeIdxOffset!.Value);
        }
    }
    private static nint? _BlendTimeSecondsOffset;

    public ref float BlendTimeSeconds {
        get {
            _BlendTimeSecondsOffset = _BlendTimeSecondsOffset ?? Schema.GetOffset(0xD21604676D3A08FC);
            return ref _Handle.AsRef<float>(_BlendTimeSecondsOffset!.Value);
        }
    }
    private static nint? _SwitchDynamicallyOffset;

    public ref bool SwitchDynamically {
        get {
            _SwitchDynamicallyOffset = _SwitchDynamicallyOffset ?? Schema.GetOffset(0xD216046746047CB8);
            return ref _Handle.AsRef<bool>(_SwitchDynamicallyOffset!.Value);
        }
    }


}