// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmClipDocEvent_BodyGroupImpl : CNmClipDocEventImpl, CNmClipDocEvent_BodyGroup
{
    public CNmClipDocEvent_BodyGroupImpl(nint handle) : base(handle) { }

    private static nint? _TargetOffset;

    public ref CNmEventTargetEntity_t Target
    {
        get
        {
            _TargetOffset = _TargetOffset ?? Schema.GetOffset(0xB1AC0287FA08A9E8);
            return ref _Handle.AsRef<CNmEventTargetEntity_t>(_TargetOffset!.Value);
        }
    }
    private static nint? _BodygroupOffset;

    public string Bodygroup
    {
        get
        {
            _BodygroupOffset = _BodygroupOffset ?? Schema.GetOffset(0xB1AC0287BCFB279C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_BodygroupOffset!.Value));
        }
        set
        {
            _BodygroupOffset = _BodygroupOffset ?? Schema.GetOffset(0xB1AC0287BCFB279C);
            Schema.SetCUtlString(_Handle, _BodygroupOffset!.Value, value);
        }
    }
    private static nint? _ChoiceOffset;

    public string Choice
    {
        get
        {
            _ChoiceOffset = _ChoiceOffset ?? Schema.GetOffset(0xB1AC02872D56D3F6);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ChoiceOffset!.Value));
        }
        set
        {
            _ChoiceOffset = _ChoiceOffset ?? Schema.GetOffset(0xB1AC02872D56D3F6);
            Schema.SetCUtlString(_Handle, _ChoiceOffset!.Value, value);
        }
    }

}