// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmClipDocEvent_CameraFOVImpl : CNmClipDocEventImpl, CNmClipDocEvent_CameraFOV
{
    public CNmClipDocEvent_CameraFOVImpl(nint handle) : base(handle) { }

    private static nint? _CurveOffset;
    private SchemaUntypedField? _CurveInstance;

    public SchemaUntypedField Curve
    {
        get
        {
            _CurveOffset = _CurveOffset ?? Schema.GetOffset(0x2347E866BFFA0B34);
            var instance = _CurveInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _CurveOffset!.Value);
            return instance;
        }
    }

}