// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocTargetSelectorNodeImpl : CNmGraphDocVariationDataNodeImpl, CNmGraphDocTargetSelectorNode
{
    public CNmGraphDocTargetSelectorNodeImpl(nint handle) : base(handle) { }

    private static nint? _OptionLabelsOffset;

    public ref CUtlVector<CUtlString> OptionLabels
    {
        get
        {
            _OptionLabelsOffset = _OptionLabelsOffset ?? Schema.GetOffset(0xF34A1909D071C433);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_OptionLabelsOffset!.Value);
        }
    }
    private static nint? _OrientationScoreWeightOffset;

    public ref float OrientationScoreWeight
    {
        get
        {
            _OrientationScoreWeightOffset = _OrientationScoreWeightOffset ?? Schema.GetOffset(0xF34A190984AD2F6B);
            return ref _Handle.AsRef<float>(_OrientationScoreWeightOffset!.Value);
        }
    }
    private static nint? _PositionScoreWeightOffset;

    public ref float PositionScoreWeight
    {
        get
        {
            _PositionScoreWeightOffset = _PositionScoreWeightOffset ?? Schema.GetOffset(0xF34A1909DD432F1E);
            return ref _Handle.AsRef<float>(_PositionScoreWeightOffset!.Value);
        }
    }
    private static nint? _IsWorldSpaceTargetOffset;

    public ref bool IsWorldSpaceTarget
    {
        get
        {
            _IsWorldSpaceTargetOffset = _IsWorldSpaceTargetOffset ?? Schema.GetOffset(0xF34A1909B81D53F2);
            return ref _Handle.AsRef<bool>(_IsWorldSpaceTargetOffset!.Value);
        }
    }
    private static nint? _IgnoreInvalidOptionsOffset;

    public ref bool IgnoreInvalidOptions
    {
        get
        {
            _IgnoreInvalidOptionsOffset = _IgnoreInvalidOptionsOffset ?? Schema.GetOffset(0xF34A1909507C679C);
            return ref _Handle.AsRef<bool>(_IgnoreInvalidOptionsOffset!.Value);
        }
    }

}