// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocTargetSelectorNode__CDataImpl : CNmGraphDocVariationDataNode__CDataImpl, CNmGraphDocTargetSelectorNode__CData
{
    public CNmGraphDocTargetSelectorNode__CDataImpl(nint handle) : base(handle) { }

    private static nint? _StrAlignmentBoneNameOffset;

    public ref CGlobalSymbol StrAlignmentBoneName
    {
        get
        {
            _StrAlignmentBoneNameOffset = _StrAlignmentBoneNameOffset ?? Schema.GetOffset(0x376832FE788CAA2C);
            return ref _Handle.AsRef<CGlobalSymbol>(_StrAlignmentBoneNameOffset!.Value);
        }
    }

}