// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphEventConditionNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmGraphEventConditionNode__CDefinition
{
    public CNmGraphEventConditionNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _SourceStateNodeIdxOffset;

    public ref short SourceStateNodeIdx
    {
        get
        {
            _SourceStateNodeIdxOffset = _SourceStateNodeIdxOffset ?? Schema.GetOffset(0x8806734863F0228C);
            return ref _Handle.AsRef<short>(_SourceStateNodeIdxOffset!.Value);
        }
    }
    private static nint? _EventConditionRulesOffset;
    private CNmBitFlagsImpl? _EventConditionRulesInstance;

    public CNmBitFlags EventConditionRules
    {
        get
        {
            _EventConditionRulesOffset = _EventConditionRulesOffset ?? Schema.GetOffset(0x88067348A904315F);
            var instance = _EventConditionRulesInstance ??= new CNmBitFlagsImpl(0);
            instance.DangerousSetHandle(_Handle + _EventConditionRulesOffset!.Value);
            return instance;
        }
    }
    private static nint? _ConditionsOffset;
    private SchemaUntypedField? _ConditionsInstance;

    public SchemaUntypedField Conditions
    {
        get
        {
            _ConditionsOffset = _ConditionsOffset ?? Schema.GetOffset(0x88067348EDDF6757);
            var instance = _ConditionsInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _ConditionsOffset!.Value);
            return instance;
        }
    }

}