// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmIsExternalGraphSlotFilledNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmIsExternalGraphSlotFilledNode__CDefinition
{
    public CNmIsExternalGraphSlotFilledNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _ExternalGraphNodeIdxOffset;

    public ref short ExternalGraphNodeIdx {
        get {
            _ExternalGraphNodeIdxOffset = _ExternalGraphNodeIdxOffset ?? Schema.GetOffset(0x973486C85D32D8E5);
            return ref _Handle.AsRef<short>(_ExternalGraphNodeIdxOffset!.Value);
        }
    }


}