// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmIDBasedSelectorNode__CDefinitionImpl : CNmPoseNode__CDefinitionImpl, CNmIDBasedSelectorNode__CDefinition
{
    public CNmIDBasedSelectorNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _OptionNodeIndicesOffset;
    private SchemaUntypedField? _OptionNodeIndicesInstance;

    public SchemaUntypedField OptionNodeIndices
    {
        get
        {
            _OptionNodeIndicesOffset = _OptionNodeIndicesOffset ?? Schema.GetOffset(0x28793D28DA97B15D);
            var instance = _OptionNodeIndicesInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _OptionNodeIndicesOffset!.Value);
            return instance;
        }
    }
    private static nint? _OptionIDsOffset;
    private SchemaUntypedField? _OptionIDsInstance;

    public SchemaUntypedField OptionIDs
    {
        get
        {
            _OptionIDsOffset = _OptionIDsOffset ?? Schema.GetOffset(0x28793D288B69497E);
            var instance = _OptionIDsInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _OptionIDsOffset!.Value);
            return instance;
        }
    }
    private static nint? _ParameterNodeIdxOffset;

    public ref short ParameterNodeIdx
    {
        get
        {
            _ParameterNodeIdxOffset = _ParameterNodeIdxOffset ?? Schema.GetOffset(0x28793D28FE88B1EF);
            return ref _Handle.AsRef<short>(_ParameterNodeIdxOffset!.Value);
        }
    }
    private static nint? _FallbackNodeIdxOffset;

    public ref short FallbackNodeIdx
    {
        get
        {
            _FallbackNodeIdxOffset = _FallbackNodeIdxOffset ?? Schema.GetOffset(0x28793D28AFA8F89E);
            return ref _Handle.AsRef<short>(_FallbackNodeIdxOffset!.Value);
        }
    }
    private static nint? _IgnoreInvalidOptionsOffset;

    public ref bool IgnoreInvalidOptions
    {
        get
        {
            _IgnoreInvalidOptionsOffset = _IgnoreInvalidOptionsOffset ?? Schema.GetOffset(0x28793D28507C679C);
            return ref _Handle.AsRef<bool>(_IgnoreInvalidOptionsOffset!.Value);
        }
    }

}