// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmSyncTrack__Event_tImpl : SchemaClass, CNmSyncTrack__Event_t
{
    public CNmSyncTrack__Event_tImpl(nint handle) : base(handle) { }

    private static nint? _IDOffset;

    public ref CGlobalSymbol ID
    {
        get
        {
            _IDOffset = _IDOffset ?? Schema.GetOffset(0x8B8C5B0A95066900);
            return ref _Handle.AsRef<CGlobalSymbol>(_IDOffset!.Value);
        }
    }
    private static nint? _StartTimeOffset;
    private NmPercent_tImpl? _StartTimeInstance;

    public NmPercent_t StartTime
    {
        get
        {
            _StartTimeOffset = _StartTimeOffset ?? Schema.GetOffset(0x8B8C5B0A6330E7EE);
            var instance = _StartTimeInstance ??= new NmPercent_tImpl(0);
            instance.DangerousSetHandle(_Handle + _StartTimeOffset!.Value);
            return instance;
        }
    }
    private static nint? _DurationOffset;
    private NmPercent_tImpl? _DurationInstance;

    public NmPercent_t Duration
    {
        get
        {
            _DurationOffset = _DurationOffset ?? Schema.GetOffset(0x8B8C5B0A3D9FF5AD);
            var instance = _DurationInstance ??= new NmPercent_tImpl(0);
            instance.DangerousSetHandle(_Handle + _DurationOffset!.Value);
            return instance;
        }
    }

}