// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmTwoBoneIKTaskImpl : CNmPoseTaskImpl, CNmTwoBoneIKTask
{
    public CNmTwoBoneIKTaskImpl(nint handle) : base(handle) { }

    private static nint? _EffectorBoneIdxOffset;

    public ref int EffectorBoneIdx {
        get {
            _EffectorBoneIdxOffset = _EffectorBoneIdxOffset ?? Schema.GetOffset(0xE29DE6F8A9C233BE);
            return ref _Handle.AsRef<int>(_EffectorBoneIdxOffset!.Value);
        }
    }
    private static nint? _EffectorTargetBoneIdxOffset;

    public ref int EffectorTargetBoneIdx {
        get {
            _EffectorTargetBoneIdxOffset = _EffectorTargetBoneIdxOffset ?? Schema.GetOffset(0xE29DE6F83A19E0D9);
            return ref _Handle.AsRef<int>(_EffectorTargetBoneIdxOffset!.Value);
        }
    }
    private static nint? _TargetTransformOffset;

    public ref CTransform TargetTransform {
        get {
            _TargetTransformOffset = _TargetTransformOffset ?? Schema.GetOffset(0xE29DE6F8B1497974);
            return ref _Handle.AsRef<CTransform>(_TargetTransformOffset!.Value);
        }
    }
    private static nint? _EffectorTargetOffset;

    public CNmTarget EffectorTarget {
        get {
            _EffectorTargetOffset = _EffectorTargetOffset ?? Schema.GetOffset(0xE29DE6F88D86AF5C);
            return new CNmTargetImpl(_Handle + _EffectorTargetOffset!.Value);
        }
    }
    private static nint? _BlendModeOffset;

    public ref NmIKBlendMode_t BlendMode {
        get {
            _BlendModeOffset = _BlendModeOffset ?? Schema.GetOffset(0xE29DE6F88D5006AB);
            return ref _Handle.AsRef<NmIKBlendMode_t>(_BlendModeOffset!.Value);
        }
    }
    private static nint? _BlendWeightOffset;

    public ref float BlendWeight {
        get {
            _BlendWeightOffset = _BlendWeightOffset ?? Schema.GetOffset(0xE29DE6F8E5D6B9CE);
            return ref _Handle.AsRef<float>(_BlendWeightOffset!.Value);
        }
    }
    private static nint? _IsTargetInWorldSpaceOffset;

    public ref bool IsTargetInWorldSpace {
        get {
            _IsTargetInWorldSpaceOffset = _IsTargetInWorldSpaceOffset ?? Schema.GetOffset(0xE29DE6F85F56E0C5);
            return ref _Handle.AsRef<bool>(_IsTargetInWorldSpaceOffset!.Value);
        }
    }
    private static nint? _IsRunningFromDeserializedDataOffset;

    public ref bool IsRunningFromDeserializedData {
        get {
            _IsRunningFromDeserializedDataOffset = _IsRunningFromDeserializedDataOffset ?? Schema.GetOffset(0xE29DE6F84791111D);
            return ref _Handle.AsRef<bool>(_IsRunningFromDeserializedDataOffset!.Value);
        }
    }
    private static nint? _ReferencePoseTwistWeightOffset;

    public ref float ReferencePoseTwistWeight {
        get {
            _ReferencePoseTwistWeightOffset = _ReferencePoseTwistWeightOffset ?? Schema.GetOffset(0xE29DE6F807335404);
            return ref _Handle.AsRef<float>(_ReferencePoseTwistWeightOffset!.Value);
        }
    }
    private static nint? _DebugEffectorBoneIDOffset;

    public ref CGlobalSymbol DebugEffectorBoneID {
        get {
            _DebugEffectorBoneIDOffset = _DebugEffectorBoneIDOffset ?? Schema.GetOffset(0xE29DE6F8A9F0F1F3);
            return ref _Handle.AsRef<CGlobalSymbol>(_DebugEffectorBoneIDOffset!.Value);
        }
    }


}