// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmTwoBoneIKTaskImpl : CNmPoseTaskImpl, CNmTwoBoneIKTask
{
    public CNmTwoBoneIKTaskImpl(nint handle) : base(handle) { }

    private static nint? _EffectorBoneIdxOffset;

    public ref int EffectorBoneIdx
    {
        get
        {
            _EffectorBoneIdxOffset = _EffectorBoneIdxOffset ?? Schema.GetOffset(0xE29DE6F8A9C233BE);
            return ref _Handle.AsRef<int>(_EffectorBoneIdxOffset!.Value);
        }
    }
    private static nint? _EffectorTargetBoneIdxOffset;

    public ref int EffectorTargetBoneIdx
    {
        get
        {
            _EffectorTargetBoneIdxOffset = _EffectorTargetBoneIdxOffset ?? Schema.GetOffset(0xE29DE6F83A19E0D9);
            return ref _Handle.AsRef<int>(_EffectorTargetBoneIdxOffset!.Value);
        }
    }
    private static nint? _TargetTransformOffset;

    public ref CTransform TargetTransform
    {
        get
        {
            _TargetTransformOffset = _TargetTransformOffset ?? Schema.GetOffset(0xE29DE6F8B1497974);
            return ref _Handle.AsRef<CTransform>(_TargetTransformOffset!.Value);
        }
    }

}