// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CodeGenAABB_tImpl : SchemaClass, CodeGenAABB_t
{
    public CodeGenAABB_tImpl(nint handle) : base(handle) { }

    private static nint? _MinBoundsOffset;

    public ref Vector MinBounds {
        get {
            _MinBoundsOffset = _MinBoundsOffset ?? Schema.GetOffset(0xB0F2ACCB114799FE);
            return ref _Handle.AsRef<Vector>(_MinBoundsOffset!.Value);
        }
    }
    private static nint? _MaxBoundsOffset;

    public ref Vector MaxBounds {
        get {
            _MaxBoundsOffset = _MaxBoundsOffset ?? Schema.GetOffset(0xB0F2ACCBC0B4CE60);
            return ref _Handle.AsRef<Vector>(_MaxBoundsOffset!.Value);
        }
    }

    public void MinBoundsUpdated() => Schema.Update(_Handle, 0xB0F2ACCB114799FE);
    public void MaxBoundsUpdated() => Schema.Update(_Handle, 0xB0F2ACCBC0B4CE60);
}