// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class constraint_hingeparams_tImpl : SchemaClass, constraint_hingeparams_t
{
    public constraint_hingeparams_tImpl(nint handle) : base(handle) { }

    private static nint? _WorldPositionOffset;

    public ref Vector WorldPosition
    {
        get
        {
            _WorldPositionOffset = _WorldPositionOffset ?? Schema.GetOffset(0x790804C3F16C2360);
            return ref _Handle.AsRef<Vector>(_WorldPositionOffset!.Value);
        }
    }
    private static nint? _WorldAxisDirectionOffset;

    public ref Vector WorldAxisDirection
    {
        get
        {
            _WorldAxisDirectionOffset = _WorldAxisDirectionOffset ?? Schema.GetOffset(0x790804C3637CEB43);
            return ref _Handle.AsRef<Vector>(_WorldAxisDirectionOffset!.Value);
        }
    }
    private static nint? _HingeAxisOffset;
    private constraint_axislimit_tImpl? _HingeAxisInstance;

    public constraint_axislimit_t HingeAxis
    {
        get
        {
            _HingeAxisOffset = _HingeAxisOffset ?? Schema.GetOffset(0x790804C33BD096FD);
            var instance = _HingeAxisInstance ??= new constraint_axislimit_tImpl(0);
            instance.DangerousSetHandle(_Handle + _HingeAxisOffset!.Value);
            return instance;
        }
    }
    private static nint? _ConstraintOffset;
    private constraint_breakableparams_tImpl? _ConstraintInstance;

    public constraint_breakableparams_t Constraint
    {
        get
        {
            _ConstraintOffset = _ConstraintOffset ?? Schema.GetOffset(0x790804C3B822E25A);
            var instance = _ConstraintInstance ??= new constraint_breakableparams_tImpl(0);
            instance.DangerousSetHandle(_Handle + _ConstraintOffset!.Value);
            return instance;
        }
    }

}