// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPhysSurfacePropertiesImpl : SchemaClass, CPhysSurfaceProperties
{
    public CPhysSurfacePropertiesImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x682A31344D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x682A31344D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _NameHashOffset;

    public ref uint NameHash
    {
        get
        {
            _NameHashOffset = _NameHashOffset ?? Schema.GetOffset(0x682A313474C2670A);
            return ref _Handle.AsRef<uint>(_NameHashOffset!.Value);
        }
    }
    private static nint? _BaseNameHashOffset;

    public ref uint BaseNameHash
    {
        get
        {
            _BaseNameHashOffset = _BaseNameHashOffset ?? Schema.GetOffset(0x682A31347BCDC37B);
            return ref _Handle.AsRef<uint>(_BaseNameHashOffset!.Value);
        }
    }
    private static nint? _HiddenOffset;

    public ref bool Hidden
    {
        get
        {
            _HiddenOffset = _HiddenOffset ?? Schema.GetOffset(0x682A313457D2DC99);
            return ref _Handle.AsRef<bool>(_HiddenOffset!.Value);
        }
    }
    private static nint? _DescriptionOffset;

    public string Description
    {
        get
        {
            _DescriptionOffset = _DescriptionOffset ?? Schema.GetOffset(0x682A313499F68389);
            return Schema.GetCUtlString(_Handle.Read<nint>(_DescriptionOffset!.Value));
        }
        set
        {
            _DescriptionOffset = _DescriptionOffset ?? Schema.GetOffset(0x682A313499F68389);
            Schema.SetCUtlString(_Handle, _DescriptionOffset!.Value, value);
        }
    }
    private static nint? _PhysicsOffset;
    private CPhysSurfacePropertiesPhysicsImpl? _PhysicsInstance;

    public CPhysSurfacePropertiesPhysics Physics
    {
        get
        {
            _PhysicsOffset = _PhysicsOffset ?? Schema.GetOffset(0x682A3134B4C7F5C2);
            var instance = _PhysicsInstance ??= new CPhysSurfacePropertiesPhysicsImpl(0);
            instance.DangerousSetHandle(_Handle + _PhysicsOffset!.Value);
            return instance;
        }
    }
    private static nint? _VehicleParamsOffset;
    private CPhysSurfacePropertiesVehicleImpl? _VehicleParamsInstance;

    public CPhysSurfacePropertiesVehicle VehicleParams
    {
        get
        {
            _VehicleParamsOffset = _VehicleParamsOffset ?? Schema.GetOffset(0x682A3134FF85787D);
            var instance = _VehicleParamsInstance ??= new CPhysSurfacePropertiesVehicleImpl(0);
            instance.DangerousSetHandle(_Handle + _VehicleParamsOffset!.Value);
            return instance;
        }
    }
    private static nint? _AudioSoundsOffset;
    private CPhysSurfacePropertiesSoundNamesImpl? _AudioSoundsInstance;

    public CPhysSurfacePropertiesSoundNames AudioSounds
    {
        get
        {
            _AudioSoundsOffset = _AudioSoundsOffset ?? Schema.GetOffset(0x682A3134F7E0C689);
            var instance = _AudioSoundsInstance ??= new CPhysSurfacePropertiesSoundNamesImpl(0);
            instance.DangerousSetHandle(_Handle + _AudioSoundsOffset!.Value);
            return instance;
        }
    }
    private static nint? _AudioParamsOffset;
    private CPhysSurfacePropertiesAudioImpl? _AudioParamsInstance;

    public CPhysSurfacePropertiesAudio AudioParams
    {
        get
        {
            _AudioParamsOffset = _AudioParamsOffset ?? Schema.GetOffset(0x682A3134BCDFAD3F);
            var instance = _AudioParamsInstance ??= new CPhysSurfacePropertiesAudioImpl(0);
            instance.DangerousSetHandle(_Handle + _AudioParamsOffset!.Value);
            return instance;
        }
    }

}