// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPhysicsBodyGameMarkupDataImpl : SchemaClass, CPhysicsBodyGameMarkupData
{
    public CPhysicsBodyGameMarkupDataImpl(nint handle) : base(handle) { }

    private static nint? _PhysicsBodyMarkupByBoneNameOffset;
    private SchemaUntypedField? _PhysicsBodyMarkupByBoneNameInstance;

    public SchemaUntypedField PhysicsBodyMarkupByBoneName
    {
        get
        {
            _PhysicsBodyMarkupByBoneNameOffset = _PhysicsBodyMarkupByBoneNameOffset ?? Schema.GetOffset(0x29262AE188A1FE22);
            var instance = _PhysicsBodyMarkupByBoneNameInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _PhysicsBodyMarkupByBoneNameOffset!.Value);
            return instance;
        }
    }

}