// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_ApplyDynamicAttributeIntImpl : CPulseCell_ApplyDynamicAttributeBaseImpl, CPulseCell_ApplyDynamicAttributeInt
{
    public CPulseCell_ApplyDynamicAttributeIntImpl(nint handle) : base(handle) { }

}