// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_RaceCursorsImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_RaceCursors
{
    public CPulseCell_RaceCursorsImpl(nint handle) : base(handle) { }

    private static nint? _OutflowsOffset;

    public ref CUtlVector<CPulse_OutflowConnection> Outflows
    {
        get
        {
            _OutflowsOffset = _OutflowsOffset ?? Schema.GetOffset(0x63FBF7A48F0AFDF8);
            return ref _Handle.AsRef<CUtlVector<CPulse_OutflowConnection>>(_OutflowsOffset!.Value);
        }
    }
    private static nint? _OnFinishedOffset;
    private CPulse_ResumePointImpl? _OnFinishedInstance;

    public CPulse_ResumePoint OnFinished
    {
        get
        {
            _OnFinishedOffset = _OnFinishedOffset ?? Schema.GetOffset(0x63FBF7A48D903E5E);
            var instance = _OnFinishedInstance ??= new CPulse_ResumePointImpl(0);
            instance.DangerousSetHandle(_Handle + _OnFinishedOffset!.Value);
            return instance;
        }
    }

}