// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_BaseLerpImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_BaseLerp
{
    public CPulseCell_BaseLerpImpl(nint handle) : base(handle) { }

    private static nint? _WakeResumeOffset;
    private CPulse_ResumePointImpl? _WakeResumeInstance;

    public CPulse_ResumePoint WakeResume
    {
        get
        {
            _WakeResumeOffset = _WakeResumeOffset ?? Schema.GetOffset(0x8AF2C31831F86DC2);
            var instance = _WakeResumeInstance ??= new CPulse_ResumePointImpl(0);
            instance.DangerousSetHandle(_Handle + _WakeResumeOffset!.Value);
            return instance;
        }
    }

}