// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulse_TempVarInfoImpl : SchemaClass, CPulse_TempVarInfo
{
    public CPulse_TempVarInfoImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;
    private SchemaUntypedField? _NameInstance;

    public SchemaUntypedField Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xE24B177BCAE8A266);
            var instance = _NameInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _NameOffset!.Value);
            return instance;
        }
    }
    private static nint? _TypeOffset;
    private SchemaUntypedField? _TypeInstance;

    public SchemaUntypedField Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0xE24B177B8ED6D5CD);
            var instance = _TypeInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _TypeOffset!.Value);
            return instance;
        }
    }
    private static nint? _EditorNodeIDOffset;
    private PulseDocNodeID_tImpl? _EditorNodeIDInstance;

    public PulseDocNodeID_t EditorNodeID
    {
        get
        {
            _EditorNodeIDOffset = _EditorNodeIDOffset ?? Schema.GetOffset(0xE24B177B8D964CBD);
            var instance = _EditorNodeIDInstance ??= new PulseDocNodeID_tImpl(0);
            instance.DangerousSetHandle(_Handle + _EditorNodeIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _IsObservableOffset;

    public ref bool IsObservable
    {
        get
        {
            _IsObservableOffset = _IsObservableOffset ?? Schema.GetOffset(0xE24B177B60684D58);
            return ref _Handle.AsRef<bool>(_IsObservableOffset!.Value);
        }
    }

}