// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Outflow_TestExplicitYesNoImpl : CPulseCell_BaseFlowImpl, CPulseCell_Outflow_TestExplicitYesNo
{
    public CPulseCell_Outflow_TestExplicitYesNoImpl(nint handle) : base(handle) { }

    private static nint? _YesOffset;
    private CPulse_OutflowConnectionImpl? _YesInstance;

    public CPulse_OutflowConnection Yes
    {
        get
        {
            _YesOffset = _YesOffset ?? Schema.GetOffset(0xA1B4A577DA358F10);
            var instance = _YesInstance ??= new CPulse_OutflowConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _YesOffset!.Value);
            return instance;
        }
    }
    private static nint? _NoOffset;
    private CPulse_OutflowConnectionImpl? _NoInstance;

    public CPulse_OutflowConnection No
    {
        get
        {
            _NoOffset = _NoOffset ?? Schema.GetOffset(0xA1B4A577E004A07A);
            var instance = _NoInstance ??= new CPulse_OutflowConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _NoOffset!.Value);
            return instance;
        }
    }

}