// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_BaseLerp__CursorState_tImpl : SchemaClass, CPulseCell_BaseLerp__CursorState_t
{
    public CPulseCell_BaseLerp__CursorState_tImpl(nint handle) : base(handle) { }

    private static nint? _StartTimeOffset;
    private GameTime_tImpl? _StartTimeInstance;

    public GameTime_t StartTime
    {
        get
        {
            _StartTimeOffset = _StartTimeOffset ?? Schema.GetOffset(0x1FAAE76897B5FA8E);
            var instance = _StartTimeInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _StartTimeOffset!.Value);
            return instance;
        }
    }
    private static nint? _EndTimeOffset;
    private GameTime_tImpl? _EndTimeInstance;

    public GameTime_t EndTime
    {
        get
        {
            _EndTimeOffset = _EndTimeOffset ?? Schema.GetOffset(0x1FAAE7687AA8F56B);
            var instance = _EndTimeInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _EndTimeOffset!.Value);
            return instance;
        }
    }

}