// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Inflow_GraphHookImpl : CPulseCell_Inflow_BaseEntrypointImpl, CPulseCell_Inflow_GraphHook
{
    public CPulseCell_Inflow_GraphHookImpl(nint handle) : base(handle) { }

    private static nint? _HookNameOffset;
    private SchemaUntypedField? _HookNameInstance;

    public SchemaUntypedField HookName
    {
        get
        {
            _HookNameOffset = _HookNameOffset ?? Schema.GetOffset(0xEA4B2E6FA19F4D11);
            var instance = _HookNameInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _HookNameOffset!.Value);
            return instance;
        }
    }

}