// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Outflow_PlayVOLineImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_Outflow_PlayVOLine
{
    public CPulseCell_Outflow_PlayVOLineImpl(nint handle) : base(handle) { }

    private static nint? _OnFinishedOffset;
    private CPulse_ResumePointImpl? _OnFinishedInstance;

    public CPulse_ResumePoint OnFinished
    {
        get
        {
            _OnFinishedOffset = _OnFinishedOffset ?? Schema.GetOffset(0x54A0846E8D903E5E);
            var instance = _OnFinishedInstance ??= new CPulse_ResumePointImpl(0);
            instance.DangerousSetHandle(_Handle + _OnFinishedOffset!.Value);
            return instance;
        }
    }

}