// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Outflow_ListenForEntityOutputImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_Outflow_ListenForEntityOutput
{
    public CPulseCell_Outflow_ListenForEntityOutputImpl(nint handle) : base(handle) { }

    private static nint? _OnFiredOffset;
    private SignatureOutflow_ResumeImpl? _OnFiredInstance;

    public SignatureOutflow_Resume OnFired
    {
        get
        {
            _OnFiredOffset = _OnFiredOffset ?? Schema.GetOffset(0xCB35163784825730);
            var instance = _OnFiredInstance ??= new SignatureOutflow_ResumeImpl(0);
            instance.DangerousSetHandle(_Handle + _OnFiredOffset!.Value);
            return instance;
        }
    }
    private static nint? _StrEntityOutputOffset;

    public ref CGlobalSymbol StrEntityOutput
    {
        get
        {
            _StrEntityOutputOffset = _StrEntityOutputOffset ?? Schema.GetOffset(0xCB351637C8E70456);
            return ref _Handle.AsRef<CGlobalSymbol>(_StrEntityOutputOffset!.Value);
        }
    }
    private static nint? _StrEntityOutputParamOffset;

    public string StrEntityOutputParam
    {
        get
        {
            _StrEntityOutputParamOffset = _StrEntityOutputParamOffset ?? Schema.GetOffset(0xCB351637BB356637);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrEntityOutputParamOffset!.Value));
        }
        set
        {
            _StrEntityOutputParamOffset = _StrEntityOutputParamOffset ?? Schema.GetOffset(0xCB351637BB356637);
            Schema.SetCUtlString(_Handle, _StrEntityOutputParamOffset!.Value, value);
        }
    }
    private static nint? _ListenUntilCanceledOffset;

    public ref bool ListenUntilCanceled
    {
        get
        {
            _ListenUntilCanceledOffset = _ListenUntilCanceledOffset ?? Schema.GetOffset(0xCB351637C798285D);
            return ref _Handle.AsRef<bool>(_ListenUntilCanceledOffset!.Value);
        }
    }

}