// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulse_InvokeBindingImpl : SchemaClass, CPulse_InvokeBinding
{
    public CPulse_InvokeBindingImpl(nint handle) : base(handle) { }

    private static nint? _RegisterMapOffset;
    private PulseRegisterMap_tImpl? _RegisterMapInstance;

    public PulseRegisterMap_t RegisterMap
    {
        get
        {
            _RegisterMapOffset = _RegisterMapOffset ?? Schema.GetOffset(0x3632DF0D7BD4CE96);
            var instance = _RegisterMapInstance ??= new PulseRegisterMap_tImpl(0);
            instance.DangerousSetHandle(_Handle + _RegisterMapOffset!.Value);
            return instance;
        }
    }
    private static nint? _FuncNameOffset;
    private SchemaUntypedField? _FuncNameInstance;

    public SchemaUntypedField FuncName
    {
        get
        {
            _FuncNameOffset = _FuncNameOffset ?? Schema.GetOffset(0x3632DF0D1B5BC2A4);
            var instance = _FuncNameInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _FuncNameOffset!.Value);
            return instance;
        }
    }
    private static nint? _CellIndexOffset;
    private PulseRuntimeCellIndex_tImpl? _CellIndexInstance;

    public PulseRuntimeCellIndex_t CellIndex
    {
        get
        {
            _CellIndexOffset = _CellIndexOffset ?? Schema.GetOffset(0x3632DF0DACE41A7F);
            var instance = _CellIndexInstance ??= new PulseRuntimeCellIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _CellIndexOffset!.Value);
            return instance;
        }
    }
    private static nint? _SrcChunkOffset;
    private PulseRuntimeChunkIndex_tImpl? _SrcChunkInstance;

    public PulseRuntimeChunkIndex_t SrcChunk
    {
        get
        {
            _SrcChunkOffset = _SrcChunkOffset ?? Schema.GetOffset(0x3632DF0D313F814A);
            var instance = _SrcChunkInstance ??= new PulseRuntimeChunkIndex_tImpl(0);
            instance.DangerousSetHandle(_Handle + _SrcChunkOffset!.Value);
            return instance;
        }
    }
    private static nint? _SrcInstructionOffset;

    public ref int SrcInstruction
    {
        get
        {
            _SrcInstructionOffset = _SrcInstructionOffset ?? Schema.GetOffset(0x3632DF0D99E09AE7);
            return ref _Handle.AsRef<int>(_SrcInstructionOffset!.Value);
        }
    }

}