// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulse_BlackboardReferenceImpl : SchemaClass, CPulse_BlackboardReference
{
    public CPulse_BlackboardReferenceImpl(nint handle) : base(handle) { }

    private static nint? _BlackboardResourceOffset;

    public ref CStrongHandle<InfoForResourceTypeIPulseGraphDef> BlackboardResource
    {
        get
        {
            _BlackboardResourceOffset = _BlackboardResourceOffset ?? Schema.GetOffset(0xEF83970A45E704DE);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIPulseGraphDef>>(_BlackboardResourceOffset!.Value);
        }
    }
    private static nint? _BlackboardResource1Offset;
    private SchemaUntypedField? _BlackboardResource1Instance;

    public SchemaUntypedField BlackboardResource1
    {
        get
        {
            _BlackboardResource1Offset = _BlackboardResource1Offset ?? Schema.GetOffset(0xEF83970A83127470);
            var instance = _BlackboardResource1Instance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _BlackboardResource1Offset!.Value);
            return instance;
        }
    }
    private static nint? _NodeIDOffset;
    private PulseDocNodeID_tImpl? _NodeIDInstance;

    public PulseDocNodeID_t NodeID
    {
        get
        {
            _NodeIDOffset = _NodeIDOffset ?? Schema.GetOffset(0xEF83970A0FD6755C);
            var instance = _NodeIDInstance ??= new PulseDocNodeID_tImpl(0);
            instance.DangerousSetHandle(_Handle + _NodeIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _NodeNameOffset;

    public ref CGlobalSymbol NodeName
    {
        get
        {
            _NodeNameOffset = _NodeNameOffset ?? Schema.GetOffset(0xEF83970A3FB4DAAE);
            return ref _Handle.AsRef<CGlobalSymbol>(_NodeNameOffset!.Value);
        }
    }

}