// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulse_PublicOutputImpl : SchemaClass, CPulse_PublicOutput
{
    public CPulse_PublicOutputImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;
    private SchemaUntypedField? _NameInstance;

    public SchemaUntypedField Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x74B3BCA4CAE8A266);
            var instance = _NameInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _NameOffset!.Value);
            return instance;
        }
    }
    private static nint? _DescriptionOffset;

    public string Description
    {
        get
        {
            _DescriptionOffset = _DescriptionOffset ?? Schema.GetOffset(0x74B3BCA4678744E9);
            return Schema.GetCUtlString(_Handle.Read<nint>(_DescriptionOffset!.Value));
        }
        set
        {
            _DescriptionOffset = _DescriptionOffset ?? Schema.GetOffset(0x74B3BCA4678744E9);
            Schema.SetCUtlString(_Handle, _DescriptionOffset!.Value, value);
        }
    }
    private static nint? _ArgsOffset;

    public ref CUtlLeanVector<CPulseRuntimeMethodArg, int> Args
    {
        get
        {
            _ArgsOffset = _ArgsOffset ?? Schema.GetOffset(0x74B3BCA4DAB98BBC);
            return ref _Handle.AsRef<CUtlLeanVector<CPulseRuntimeMethodArg, int>>(_ArgsOffset!.Value);
        }
    }

}