// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CReplicationParametersImpl : SchemaClass, CReplicationParameters
{
    public CReplicationParametersImpl(nint handle) : base(handle) { }

    private static nint? _ReplicationModeOffset;

    public ref ParticleReplicationMode_t ReplicationMode
    {
        get
        {
            _ReplicationModeOffset = _ReplicationModeOffset ?? Schema.GetOffset(0xFA909F20C8967832);
            return ref _Handle.AsRef<ParticleReplicationMode_t>(_ReplicationModeOffset!.Value);
        }
    }
    private static nint? _ScaleChildParticleRadiiOffset;

    public ref bool ScaleChildParticleRadii
    {
        get
        {
            _ScaleChildParticleRadiiOffset = _ScaleChildParticleRadiiOffset ?? Schema.GetOffset(0xFA909F207842F3CC);
            return ref _Handle.AsRef<bool>(_ScaleChildParticleRadiiOffset!.Value);
        }
    }
    private static nint? _MinRandomRadiusScaleOffset;
    private CParticleCollectionFloatInputImpl? _MinRandomRadiusScaleInstance;

    public CParticleCollectionFloatInput MinRandomRadiusScale
    {
        get
        {
            _MinRandomRadiusScaleOffset = _MinRandomRadiusScaleOffset ?? Schema.GetOffset(0xFA909F208CBF88EE);
            var instance = _MinRandomRadiusScaleInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _MinRandomRadiusScaleOffset!.Value);
            return instance;
        }
    }
    private static nint? _MaxRandomRadiusScaleOffset;
    private CParticleCollectionFloatInputImpl? _MaxRandomRadiusScaleInstance;

    public CParticleCollectionFloatInput MaxRandomRadiusScale
    {
        get
        {
            _MaxRandomRadiusScaleOffset = _MaxRandomRadiusScaleOffset ?? Schema.GetOffset(0xFA909F2022697B5C);
            var instance = _MaxRandomRadiusScaleInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _MaxRandomRadiusScaleOffset!.Value);
            return instance;
        }
    }
    private static nint? _MinRandomDisplacementOffset;
    private CParticleCollectionVecInputImpl? _MinRandomDisplacementInstance;

    public CParticleCollectionVecInput MinRandomDisplacement
    {
        get
        {
            _MinRandomDisplacementOffset = _MinRandomDisplacementOffset ?? Schema.GetOffset(0xFA909F20808FB77F);
            var instance = _MinRandomDisplacementInstance ??= new CParticleCollectionVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _MinRandomDisplacementOffset!.Value);
            return instance;
        }
    }
    private static nint? _MaxRandomDisplacementOffset;
    private CParticleCollectionVecInputImpl? _MaxRandomDisplacementInstance;

    public CParticleCollectionVecInput MaxRandomDisplacement
    {
        get
        {
            _MaxRandomDisplacementOffset = _MaxRandomDisplacementOffset ?? Schema.GetOffset(0xFA909F20FF279F49);
            var instance = _MaxRandomDisplacementInstance ??= new CParticleCollectionVecInputImpl(0);
            instance.DangerousSetHandle(_Handle + _MaxRandomDisplacementOffset!.Value);
            return instance;
        }
    }
    private static nint? _ModellingScaleOffset;
    private CParticleCollectionFloatInputImpl? _ModellingScaleInstance;

    public CParticleCollectionFloatInput ModellingScale
    {
        get
        {
            _ModellingScaleOffset = _ModellingScaleOffset ?? Schema.GetOffset(0xFA909F20BE93B72A);
            var instance = _ModellingScaleInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _ModellingScaleOffset!.Value);
            return instance;
        }
    }

}