// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRootMotionImpl : SchemaClass, CRootMotion
{
    public CRootMotionImpl(nint handle) : base(handle) { }

    private static nint? _DeltaTransformOffset;
    private SchemaUntypedField? _DeltaTransformInstance;

    public SchemaUntypedField DeltaTransform
    {
        get
        {
            _DeltaTransformOffset = _DeltaTransformOffset ?? Schema.GetOffset(0xC7D44244B5B7D687);
            var instance = _DeltaTransformInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _DeltaTransformOffset!.Value);
            return instance;
        }
    }
    private static nint? _VelocityMSOffset;

    public ref Vector VelocityMS
    {
        get
        {
            _VelocityMSOffset = _VelocityMSOffset ?? Schema.GetOffset(0xC7D442445D4CE9AE);
            return ref _Handle.AsRef<Vector>(_VelocityMSOffset!.Value);
        }
    }
    private static nint? _UpOverrideOffset;

    public ref Vector UpOverride
    {
        get
        {
            _UpOverrideOffset = _UpOverrideOffset ?? Schema.GetOffset(0xC7D4424428D9D8F4);
            return ref _Handle.AsRef<Vector>(_UpOverrideOffset!.Value);
        }
    }

}