// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundEventBoxEntityImpl : CSoundEventMultiPointEntityImpl, CSoundEventBoxEntity
{
    public CSoundEventBoxEntityImpl(nint handle) : base(handle) { }

    private static nint? _BoxEntitiesOffset;
    private SchemaStringFixedArray? _BoxEntitiesInstance;

    public ISchemaStringFixedArray BoxEntities
    {
        get
        {
            _BoxEntitiesOffset = _BoxEntitiesOffset ?? Schema.GetOffset(0x4082DF6F27B5A8E5);
            var instance = _BoxEntitiesInstance ??= new SchemaStringFixedArray(0, 0x4082DF6F27B5A8E5, 16, 8, 8);
            instance.DangerousSetHandle(_Handle + _BoxEntitiesOffset!.Value);
            return instance;
        }
    }
    private static nint? _BoxHelpersNetworkedOffset;

    public ref CUtlVector<SoundeventBoxHelperNetworked_t> BoxHelpersNetworked
    {
        get
        {
            _BoxHelpersNetworkedOffset = _BoxHelpersNetworkedOffset ?? Schema.GetOffset(0x4082DF6F0010FE06);
            return ref _Handle.AsRef<CUtlVector<SoundeventBoxHelperNetworked_t>>(_BoxHelpersNetworkedOffset!.Value);
        }
    }

    public void BoxHelpersNetworkedUpdated() => Schema.Update(_Handle, 0x4082DF6F0010FE06);
}