// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundOpvarSetDomeEntityImpl : CSoundOpvarSetPointEntityImpl, CSoundOpvarSetDomeEntity
{
    public CSoundOpvarSetDomeEntityImpl(nint handle) : base(handle) { }

    private static nint? _ArDirectionsOffset;

    public ref CUtlVector<Vector> ArDirections
    {
        get
        {
            _ArDirectionsOffset = _ArDirectionsOffset ?? Schema.GetOffset(0xBFBF1D05990FF4A4);
            return ref _Handle.AsRef<CUtlVector<Vector>>(_ArDirectionsOffset!.Value);
        }
    }
    private static nint? _ArOpennessOffset;

    public ref CUtlVector<float> ArOpenness
    {
        get
        {
            _ArOpennessOffset = _ArOpennessOffset ?? Schema.GetOffset(0xBFBF1D05F8239549);
            return ref _Handle.AsRef<CUtlVector<float>>(_ArOpennessOffset!.Value);
        }
    }
    private static nint? _ArNeighborsOffset;

    public ref CUtlVector<int> ArNeighbors
    {
        get
        {
            _ArNeighborsOffset = _ArNeighborsOffset ?? Schema.GetOffset(0xBFBF1D05F3E3EDC9);
            return ref _Handle.AsRef<CUtlVector<int>>(_ArNeighborsOffset!.Value);
        }
    }
    private static nint? _CurrentIndexOffset;

    public ref int CurrentIndex
    {
        get
        {
            _CurrentIndexOffset = _CurrentIndexOffset ?? Schema.GetOffset(0xBFBF1D05AB513352);
            return ref _Handle.AsRef<int>(_CurrentIndexOffset!.Value);
        }
    }
    private static nint? _ArClusterParentOffset;

    public ref CUtlVector<int> ArClusterParent
    {
        get
        {
            _ArClusterParentOffset = _ArClusterParentOffset ?? Schema.GetOffset(0xBFBF1D05E40A2D94);
            return ref _Handle.AsRef<CUtlVector<int>>(_ArClusterParentOffset!.Value);
        }
    }
    private static nint? _ArClusterSizeOffset;

    public ref CUtlVector<int> ArClusterSize
    {
        get
        {
            _ArClusterSizeOffset = _ArClusterSizeOffset ?? Schema.GetOffset(0xBFBF1D050C93B5B5);
            return ref _Handle.AsRef<CUtlVector<int>>(_ArClusterSizeOffset!.Value);
        }
    }
    private static nint? _ArClusterWeightOffset;

    public ref CUtlVector<float> ArClusterWeight
    {
        get
        {
            _ArClusterWeightOffset = _ArClusterWeightOffset ?? Schema.GetOffset(0xBFBF1D05BB4D328C);
            return ref _Handle.AsRef<CUtlVector<float>>(_ArClusterWeightOffset!.Value);
        }
    }
    private static nint? _ArClusterDirSumOffset;

    public ref CUtlVector<Vector> ArClusterDirSum
    {
        get
        {
            _ArClusterDirSumOffset = _ArClusterDirSumOffset ?? Schema.GetOffset(0xBFBF1D0509CCF2C6);
            return ref _Handle.AsRef<CUtlVector<Vector>>(_ArClusterDirSumOffset!.Value);
        }
    }
    private static nint? _ClusterIndexOffset;

    public ref int ClusterIndex
    {
        get
        {
            _ClusterIndexOffset = _ClusterIndexOffset ?? Schema.GetOffset(0xBFBF1D053006D287);
            return ref _Handle.AsRef<int>(_ClusterIndexOffset!.Value);
        }
    }
    private static nint? _ClusteredOpennessOffset;

    public ref float ClusteredOpenness
    {
        get
        {
            _ClusteredOpennessOffset = _ClusteredOpennessOffset ?? Schema.GetOffset(0xBFBF1D05924AEE85);
            return ref _Handle.AsRef<float>(_ClusteredOpennessOffset!.Value);
        }
    }
    private static nint? _ClusterDirectionOffset;

    public ref Vector ClusterDirection
    {
        get
        {
            _ClusterDirectionOffset = _ClusterDirectionOffset ?? Schema.GetOffset(0xBFBF1D05D6479E8E);
            return ref _Handle.AsRef<Vector>(_ClusterDirectionOffset!.Value);
        }
    }
    private static nint? _SmoothedOpenDirOffset;

    public ref Vector SmoothedOpenDir
    {
        get
        {
            _SmoothedOpenDirOffset = _SmoothedOpenDirOffset ?? Schema.GetOffset(0xBFBF1D05D35C2D11);
            return ref _Handle.AsRef<Vector>(_SmoothedOpenDirOffset!.Value);
        }
    }
    private static nint? _DirWarmupThinksRemainingOffset;

    public ref int DirWarmupThinksRemaining
    {
        get
        {
            _DirWarmupThinksRemainingOffset = _DirWarmupThinksRemainingOffset ?? Schema.GetOffset(0xBFBF1D0537CF55DF);
            return ref _Handle.AsRef<int>(_DirWarmupThinksRemainingOffset!.Value);
        }
    }
    private static nint? _LastTraceOriginOffset;

    public ref Vector LastTraceOrigin
    {
        get
        {
            _LastTraceOriginOffset = _LastTraceOriginOffset ?? Schema.GetOffset(0xBFBF1D05681BD610);
            return ref _Handle.AsRef<Vector>(_LastTraceOriginOffset!.Value);
        }
    }
    private static nint? _TraceOriginValidOffset;

    public ref bool TraceOriginValid
    {
        get
        {
            _TraceOriginValidOffset = _TraceOriginValidOffset ?? Schema.GetOffset(0xBFBF1D05305464AA);
            return ref _Handle.AsRef<bool>(_TraceOriginValidOffset!.Value);
        }
    }
    private static nint? _CatchUpThinksRemainingOffset;

    public ref int CatchUpThinksRemaining
    {
        get
        {
            _CatchUpThinksRemainingOffset = _CatchUpThinksRemainingOffset ?? Schema.GetOffset(0xBFBF1D056E618564);
            return ref _Handle.AsRef<int>(_CatchUpThinksRemainingOffset!.Value);
        }
    }
    private static nint? _DiscontinuityPendingOffset;

    public ref bool DiscontinuityPending
    {
        get
        {
            _DiscontinuityPendingOffset = _DiscontinuityPendingOffset ?? Schema.GetOffset(0xBFBF1D05518D8A08);
            return ref _Handle.AsRef<bool>(_DiscontinuityPendingOffset!.Value);
        }
    }
    private static nint? _SmoothedOpennessOffset;

    public ref float SmoothedOpenness
    {
        get
        {
            _SmoothedOpennessOffset = _SmoothedOpennessOffset ?? Schema.GetOffset(0xBFBF1D050A48DDFF);
            return ref _Handle.AsRef<float>(_SmoothedOpennessOffset!.Value);
        }
    }
    private static nint? _LastSmoothTimeOffset;
    private GameTime_tImpl? _LastSmoothTimeInstance;

    public GameTime_t LastSmoothTime
    {
        get
        {
            _LastSmoothTimeOffset = _LastSmoothTimeOffset ?? Schema.GetOffset(0xBFBF1D05C7238E5C);
            var instance = _LastSmoothTimeInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _LastSmoothTimeOffset!.Value);
            return instance;
        }
    }
    private static nint? _SizeOffset;

    public ref float Size
    {
        get
        {
            _SizeOffset = _SizeOffset ?? Schema.GetOffset(0xBFBF1D054CF0EBC6);
            return ref _Handle.AsRef<float>(_SizeOffset!.Value);
        }
    }
    private static nint? _TotalDirectionsOffset;

    public ref int TotalDirections
    {
        get
        {
            _TotalDirectionsOffset = _TotalDirectionsOffset ?? Schema.GetOffset(0xBFBF1D052CDE169F);
            return ref _Handle.AsRef<int>(_TotalDirectionsOffset!.Value);
        }
    }
    private static nint? _TracesPerFrameOffset;

    public ref int TracesPerFrame
    {
        get
        {
            _TracesPerFrameOffset = _TracesPerFrameOffset ?? Schema.GetOffset(0xBFBF1D0578339D73);
            return ref _Handle.AsRef<int>(_TracesPerFrameOffset!.Value);
        }
    }
    private static nint? _DomeModeOffset;

    public ref bool DomeMode
    {
        get
        {
            _DomeModeOffset = _DomeModeOffset ?? Schema.GetOffset(0xBFBF1D05C494A741);
            return ref _Handle.AsRef<bool>(_DomeModeOffset!.Value);
        }
    }
    private static nint? _MultiWallOffset;

    public ref bool MultiWall
    {
        get
        {
            _MultiWallOffset = _MultiWallOffset ?? Schema.GetOffset(0xBFBF1D053640EB2A);
            return ref _Handle.AsRef<bool>(_MultiWallOffset!.Value);
        }
    }
    private static nint? _WallTransmissionOffset;

    public ref float WallTransmission
    {
        get
        {
            _WallTransmissionOffset = _WallTransmissionOffset ?? Schema.GetOffset(0xBFBF1D051D7206B7);
            return ref _Handle.AsRef<float>(_WallTransmissionOffset!.Value);
        }
    }
    private static nint? _ClusterKOffset;

    public ref int ClusterK
    {
        get
        {
            _ClusterKOffset = _ClusterKOffset ?? Schema.GetOffset(0xBFBF1D059494FE0E);
            return ref _Handle.AsRef<int>(_ClusterKOffset!.Value);
        }
    }
    private static nint? _ClusterPOffset;

    public ref float ClusterP
    {
        get
        {
            _ClusterPOffset = _ClusterPOffset ?? Schema.GetOffset(0xBFBF1D0549B2C43D);
            return ref _Handle.AsRef<float>(_ClusterPOffset!.Value);
        }
    }
    private static nint? _ClusterBlendOffset;

    public ref float ClusterBlend
    {
        get
        {
            _ClusterBlendOffset = _ClusterBlendOffset ?? Schema.GetOffset(0xBFBF1D05FFB6AAF6);
            return ref _Handle.AsRef<float>(_ClusterBlendOffset!.Value);
        }
    }
    private static nint? _OpennessExponentOffset;

    public ref float OpennessExponent
    {
        get
        {
            _OpennessExponentOffset = _OpennessExponentOffset ?? Schema.GetOffset(0xBFBF1D0554EC838B);
            return ref _Handle.AsRef<float>(_OpennessExponentOffset!.Value);
        }
    }
    private static nint? _ShoulderExponentOffset;

    public ref float ShoulderExponent
    {
        get
        {
            _ShoulderExponentOffset = _ShoulderExponentOffset ?? Schema.GetOffset(0xBFBF1D05C96D29E8);
            return ref _Handle.AsRef<float>(_ShoulderExponentOffset!.Value);
        }
    }
    private static nint? _SmoothHalfLifeOffset;

    public ref float SmoothHalfLife
    {
        get
        {
            _SmoothHalfLifeOffset = _SmoothHalfLifeOffset ?? Schema.GetOffset(0xBFBF1D05641636A6);
            return ref _Handle.AsRef<float>(_SmoothHalfLifeOffset!.Value);
        }
    }

}