// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSSDSMsg_ViewRenderImpl : SchemaClass, CSSDSMsg_ViewRender
{
    public CSSDSMsg_ViewRenderImpl(nint handle) : base(handle) { }

    private static nint? _ViewIdOffset;
    private SceneViewId_tImpl? _ViewIdInstance;

    public SceneViewId_t ViewId
    {
        get
        {
            _ViewIdOffset = _ViewIdOffset ?? Schema.GetOffset(0x2CD48EEEE976CB25);
            var instance = _ViewIdInstance ??= new SceneViewId_tImpl(0);
            instance.DangerousSetHandle(_Handle + _ViewIdOffset!.Value);
            return instance;
        }
    }
    private static nint? _ViewNameOffset;

    public string ViewName
    {
        get
        {
            _ViewNameOffset = _ViewNameOffset ?? Schema.GetOffset(0x2CD48EEEBA5BBDBB);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ViewNameOffset!.Value));
        }
        set
        {
            _ViewNameOffset = _ViewNameOffset ?? Schema.GetOffset(0x2CD48EEEBA5BBDBB);
            Schema.SetCUtlString(_Handle, _ViewNameOffset!.Value, value);
        }
    }

}