// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CStateUpdateDataImpl : SchemaClass, CStateUpdateData
{
    public CStateUpdateDataImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xD984C8C64D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xD984C8C64D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _ScriptOffset;
    private AnimScriptHandleImpl? _ScriptInstance;

    public AnimScriptHandle Script
    {
        get
        {
            _ScriptOffset = _ScriptOffset ?? Schema.GetOffset(0xD984C8C629D70FB0);
            var instance = _ScriptInstance ??= new AnimScriptHandleImpl(0);
            instance.DangerousSetHandle(_Handle + _ScriptOffset!.Value);
            return instance;
        }
    }
    private static nint? _TransitionIndicesOffset;

    public ref CUtlVector<int> TransitionIndices
    {
        get
        {
            _TransitionIndicesOffset = _TransitionIndicesOffset ?? Schema.GetOffset(0xD984C8C689E40507);
            return ref _Handle.AsRef<CUtlVector<int>>(_TransitionIndicesOffset!.Value);
        }
    }
    private static nint? _ActionsOffset;

    public ref CUtlVector<CStateActionUpdater> Actions
    {
        get
        {
            _ActionsOffset = _ActionsOffset ?? Schema.GetOffset(0xD984C8C68D622684);
            return ref _Handle.AsRef<CUtlVector<CStateActionUpdater>>(_ActionsOffset!.Value);
        }
    }
    private static nint? _StateIDOffset;
    private AnimStateIDImpl? _StateIDInstance;

    public AnimStateID StateID
    {
        get
        {
            _StateIDOffset = _StateIDOffset ?? Schema.GetOffset(0xD984C8C65362B56B);
            var instance = _StateIDInstance ??= new AnimStateIDImpl(0);
            instance.DangerousSetHandle(_Handle + _StateIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _IsStartStateOffset;
    private SchemaUntypedField? _IsStartStateInstance;

    public SchemaUntypedField IsStartState
    {
        get
        {
            _IsStartStateOffset = _IsStartStateOffset ?? Schema.GetOffset(0xD984C8C6B4CEE040);
            var instance = _IsStartStateInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _IsStartStateOffset!.Value);
            return instance;
        }
    }
    private static nint? _IsEndStateOffset;
    private SchemaUntypedField? _IsEndStateInstance;

    public SchemaUntypedField IsEndState
    {
        get
        {
            _IsEndStateOffset = _IsEndStateOffset ?? Schema.GetOffset(0xD984C8C65C2338AF);
            var instance = _IsEndStateInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _IsEndStateOffset!.Value);
            return instance;
        }
    }
    private static nint? _IsPassthroughOffset;
    private SchemaUntypedField? _IsPassthroughInstance;

    public SchemaUntypedField IsPassthrough
    {
        get
        {
            _IsPassthroughOffset = _IsPassthroughOffset ?? Schema.GetOffset(0xD984C8C6F0AD9431);
            var instance = _IsPassthroughInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _IsPassthroughOffset!.Value);
            return instance;
        }
    }
    private static nint? _IsPassthroughRootMotionOffset;
    private SchemaUntypedField? _IsPassthroughRootMotionInstance;

    public SchemaUntypedField IsPassthroughRootMotion
    {
        get
        {
            _IsPassthroughRootMotionOffset = _IsPassthroughRootMotionOffset ?? Schema.GetOffset(0xD984C8C64B319C83);
            var instance = _IsPassthroughRootMotionInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _IsPassthroughRootMotionOffset!.Value);
            return instance;
        }
    }
    private static nint? _PreEvaluatePassthroughTransitionPathOffset;
    private SchemaUntypedField? _PreEvaluatePassthroughTransitionPathInstance;

    public SchemaUntypedField PreEvaluatePassthroughTransitionPath
    {
        get
        {
            _PreEvaluatePassthroughTransitionPathOffset = _PreEvaluatePassthroughTransitionPathOffset ?? Schema.GetOffset(0xD984C8C60DFCB92D);
            var instance = _PreEvaluatePassthroughTransitionPathInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _PreEvaluatePassthroughTransitionPathOffset!.Value);
            return instance;
        }
    }

}