// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTestPulseIO__EntityNameStringArgs_tImpl : SchemaClass, CTestPulseIO__EntityNameStringArgs_t
{
    public CTestPulseIO__EntityNameStringArgs_tImpl(nint handle) : base(handle) { }

    private static nint? _NameAOffset;
    private SchemaUntypedField? _NameAInstance;

    public SchemaUntypedField NameA
    {
        get
        {
            _NameAOffset = _NameAOffset ?? Schema.GetOffset(0xD922F2E0F8E58DE5);
            var instance = _NameAInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _NameAOffset!.Value);
            return instance;
        }
    }
    private static nint? _StrValueBOffset;

    public string StrValueB
    {
        get
        {
            _StrValueBOffset = _StrValueBOffset ?? Schema.GetOffset(0xD922F2E08F89A299);
            return Schema.GetString(_Handle.Read<nint>(_StrValueBOffset!.Value));
        }
        set
        {
            _StrValueBOffset = _StrValueBOffset ?? Schema.GetOffset(0xD922F2E08F89A299);
            Schema.SetString(_Handle, _StrValueBOffset!.Value, value);
        }
    }

}