// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTestPulseIOComponentImpl : SchemaClass, CTestPulseIOComponent
{
    public CTestPulseIOComponentImpl(nint handle) : base(handle) { }

    private static nint? _ComponentDataOffset;

    public string ComponentData
    {
        get
        {
            _ComponentDataOffset = _ComponentDataOffset ?? Schema.GetOffset(0x38B7AE6EF07BDB48);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ComponentDataOffset!.Value));
        }
        set
        {
            _ComponentDataOffset = _ComponentDataOffset ?? Schema.GetOffset(0x38B7AE6EF07BDB48);
            Schema.SetCUtlString(_Handle, _ComponentDataOffset!.Value, value);
        }
    }
    private static nint? _OnComponentTestFuncOffset;
    private SchemaUntypedField? _OnComponentTestFuncInstance;

    public SchemaUntypedField OnComponentTestFunc
    {
        get
        {
            _OnComponentTestFuncOffset = _OnComponentTestFuncOffset ?? Schema.GetOffset(0x38B7AE6E61B44981);
            var instance = _OnComponentTestFuncInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _OnComponentTestFuncOffset!.Value);
            return instance;
        }
    }

}