// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVMixCurveHeaderImpl : SchemaClass, CVMixCurveHeader
{
    public CVMixCurveHeaderImpl(nint handle) : base(handle) { }

    private static nint? _ControlPointCountOffset;

    public ref uint ControlPointCount {
        get {
            _ControlPointCountOffset = _ControlPointCountOffset ?? Schema.GetOffset(0xAE0FC3E09E029D53);
            return ref _Handle.AsRef<uint>(_ControlPointCountOffset!.Value);
        }
    }
    private static nint? _ControlPointStartOffset;

    public ref uint ControlPointStart {
        get {
            _ControlPointStartOffset = _ControlPointStartOffset ?? Schema.GetOffset(0xAE0FC3E0EB974DA0);
            return ref _Handle.AsRef<uint>(_ControlPointStartOffset!.Value);
        }
    }


}