// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVMixAutoFilterProcessorDescImpl : CVMixBaseProcessorDescImpl, CVMixAutoFilterProcessorDesc
{
    public CVMixAutoFilterProcessorDescImpl(nint handle) : base(handle) { }

    private static nint? _DescOffset;

    public VMixAutoFilterDesc_t Desc {
        get {
            _DescOffset = _DescOffset ?? Schema.GetOffset(0xB83D09DC27917BC0);
            return new VMixAutoFilterDesc_tImpl(_Handle + _DescOffset!.Value);
        }
    }


}