// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVMixToolEffectsListImpl : SchemaClass, CVMixToolEffectsList
{
    public CVMixToolEffectsListImpl(nint handle) : base(handle) { }

    private static nint? _IsAutomaticDSPOffset;

    public ref bool IsAutomaticDSP
    {
        get
        {
            _IsAutomaticDSPOffset = _IsAutomaticDSPOffset ?? Schema.GetOffset(0xE053AACE97360A4B);
            return ref _Handle.AsRef<bool>(_IsAutomaticDSPOffset!.Value);
        }
    }
    private static nint? _ListOffset;

    public ref CUtlVector<SchemaUntypedField> List
    {
        get
        {
            _ListOffset = _ListOffset ?? Schema.GetOffset(0xE053AACECAD81C21);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_ListOffset!.Value);
        }
    }

}