// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVMixDelayProcessorDescImpl : CVMixBaseProcessorDescImpl, CVMixDelayProcessorDesc
{
    public CVMixDelayProcessorDescImpl(nint handle) : base(handle) { }

    private static nint? _DescOffset;
    private VMixDelayDesc_tImpl? _DescInstance;

    public VMixDelayDesc_t Desc
    {
        get
        {
            _DescOffset = _DescOffset ?? Schema.GetOffset(0xDFF6E06227917BC0);
            var instance = _DescInstance ??= new VMixDelayDesc_tImpl(0);
            instance.DangerousSetHandle(_Handle + _DescOffset!.Value);
            return instance;
        }
    }
    private static nint? _ParamCutoffFrequencyOffset;
    private CVMixParameterFloatImpl? _ParamCutoffFrequencyInstance;

    public CVMixParameterFloat ParamCutoffFrequency
    {
        get
        {
            _ParamCutoffFrequencyOffset = _ParamCutoffFrequencyOffset ?? Schema.GetOffset(0xDFF6E06212AFDCC7);
            var instance = _ParamCutoffFrequencyInstance ??= new CVMixParameterFloatImpl(0);
            instance.DangerousSetHandle(_Handle + _ParamCutoffFrequencyOffset!.Value);
            return instance;
        }
    }
    private static nint? _ParamDelayOffset;
    private CVMixParameterFloatImpl? _ParamDelayInstance;

    public CVMixParameterFloat ParamDelay
    {
        get
        {
            _ParamDelayOffset = _ParamDelayOffset ?? Schema.GetOffset(0xDFF6E062CA358765);
            var instance = _ParamDelayInstance ??= new CVMixParameterFloatImpl(0);
            instance.DangerousSetHandle(_Handle + _ParamDelayOffset!.Value);
            return instance;
        }
    }

}