// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVMixPresetDSPProcessorDescImpl : CVMixBaseProcessorDescImpl, CVMixPresetDSPProcessorDesc
{
    public CVMixPresetDSPProcessorDescImpl(nint handle) : base(handle) { }

    private static nint? _DescOffset;
    private VMixPresetDSPDesc_tImpl? _DescInstance;

    public VMixPresetDSPDesc_t Desc
    {
        get
        {
            _DescOffset = _DescOffset ?? Schema.GetOffset(0x9FACEE2127917BC0);
            var instance = _DescInstance ??= new VMixPresetDSPDesc_tImpl(0);
            instance.DangerousSetHandle(_Handle + _DescOffset!.Value);
            return instance;
        }
    }
    private static nint? _ParamEffectNameOffset;
    private CVMixParameterEffectNameImpl? _ParamEffectNameInstance;

    public CVMixParameterEffectName ParamEffectName
    {
        get
        {
            _ParamEffectNameOffset = _ParamEffectNameOffset ?? Schema.GetOffset(0x9FACEE21CC86B95C);
            var instance = _ParamEffectNameInstance ??= new CVMixParameterEffectNameImpl(0);
            instance.DangerousSetHandle(_Handle + _ParamEffectNameOffset!.Value);
            return instance;
        }
    }

}