// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVMixOscProcessorDescImpl : CVMixBaseProcessorDescImpl, CVMixOscProcessorDesc
{
    public CVMixOscProcessorDescImpl(nint handle) : base(handle) { }

    private static nint? _DescOffset;

    public VMixOscDesc_t Desc {
        get {
            _DescOffset = _DescOffset ?? Schema.GetOffset(0x18D0F65A27917BC0);
            return new VMixOscDesc_tImpl(_Handle + _DescOffset!.Value);
        }
    }


}