// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVoiceContainerBaseImpl : SchemaClass, CVoiceContainerBase
{
    public CVoiceContainerBaseImpl(nint handle) : base(handle) { }

    private static nint? _SoundOffset;
    private CVSoundImpl? _SoundInstance;

    public CVSound Sound
    {
        get
        {
            _SoundOffset = _SoundOffset ?? Schema.GetOffset(0x9D65DC3663C1A950);
            var instance = _SoundInstance ??= new CVSoundImpl(0);
            instance.DangerousSetHandle(_Handle + _SoundOffset!.Value);
            return instance;
        }
    }
    private static nint? _EnvelopeAnalyzerOffset;
    private CVoiceContainerAnalysisBaseImpl? _EnvelopeAnalyzerInstance;

    public CVoiceContainerAnalysisBase? EnvelopeAnalyzer
    {
        get
        {
            _EnvelopeAnalyzerOffset = _EnvelopeAnalyzerOffset ?? Schema.GetOffset(0x9D65DC362102947D);
            var ptr = _Handle.Read<nint>(_EnvelopeAnalyzerOffset!.Value);
            if (!ptr.IsValidPtr()) return null;
            var instance = _EnvelopeAnalyzerInstance ??= new CVoiceContainerAnalysisBaseImpl(0);
            instance.DangerousSetHandle(ptr);
            return instance;
        }
    }

}