// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVoiceContainerLoopXFadeImpl : CVoiceContainerBaseImpl, CVoiceContainerLoopXFade
{
    public CVoiceContainerLoopXFadeImpl(nint handle) : base(handle) { }

    private static nint? _SoundOffset;

    public CSoundContainerReference Sound {
        get {
            _SoundOffset = _SoundOffset ?? Schema.GetOffset(0x5815536D4E1C4FB4);
            return new CSoundContainerReferenceImpl(_Handle + _SoundOffset!.Value);
        }
    }
    private static nint? _LoopEndOffset;

    public ref float LoopEnd {
        get {
            _LoopEndOffset = _LoopEndOffset ?? Schema.GetOffset(0x5815536DF25EF00A);
            return ref _Handle.AsRef<float>(_LoopEndOffset!.Value);
        }
    }
    private static nint? _LoopStartOffset;

    public ref float LoopStart {
        get {
            _LoopStartOffset = _LoopStartOffset ?? Schema.GetOffset(0x5815536D2157C63F);
            return ref _Handle.AsRef<float>(_LoopStartOffset!.Value);
        }
    }
    private static nint? _FadeOutOffset;

    public ref float FadeOut {
        get {
            _FadeOutOffset = _FadeOutOffset ?? Schema.GetOffset(0x5815536DFEBCE80B);
            return ref _Handle.AsRef<float>(_FadeOutOffset!.Value);
        }
    }
    private static nint? _FadeInOffset;

    public ref float FadeIn {
        get {
            _FadeInOffset = _FadeInOffset ?? Schema.GetOffset(0x5815536DFCA835D2);
            return ref _Handle.AsRef<float>(_FadeInOffset!.Value);
        }
    }
    private static nint? _PlayHeadOffset;

    public ref bool PlayHead {
        get {
            _PlayHeadOffset = _PlayHeadOffset ?? Schema.GetOffset(0x5815536D2F1158D9);
            return ref _Handle.AsRef<bool>(_PlayHeadOffset!.Value);
        }
    }
    private static nint? _PlayTailOffset;

    public ref bool PlayTail {
        get {
            _PlayTailOffset = _PlayTailOffset ?? Schema.GetOffset(0x5815536D77C04419);
            return ref _Handle.AsRef<bool>(_PlayTailOffset!.Value);
        }
    }
    private static nint? _EqualPowOffset;

    public ref bool EqualPow {
        get {
            _EqualPowOffset = _EqualPowOffset ?? Schema.GetOffset(0x5815536DCA06F463);
            return ref _Handle.AsRef<bool>(_EqualPowOffset!.Value);
        }
    }


}