// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVoiceContainerLoopTriggerWithRandomPannerImpl : CVoiceContainerLoopTriggerImpl, CVoiceContainerLoopTriggerWithRandomPanner
{
    public CVoiceContainerLoopTriggerWithRandomPannerImpl(nint handle) : base(handle) { }

    private static nint? _RandomPannerControlsOffset;
    private CRandomPannerControlsImpl? _RandomPannerControlsInstance;

    public CRandomPannerControls RandomPannerControls
    {
        get
        {
            _RandomPannerControlsOffset = _RandomPannerControlsOffset ?? Schema.GetOffset(0x20EAB9B0788B5490);
            var instance = _RandomPannerControlsInstance ??= new CRandomPannerControlsImpl(0);
            instance.DangerousSetHandle(_Handle + _RandomPannerControlsOffset!.Value);
            return instance;
        }
    }

}