// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVsndRadioButtonSlotImpl : SchemaClass, CVsndRadioButtonSlot
{
    public CVsndRadioButtonSlotImpl(nint handle) : base(handle) { }

    private static nint? _EnableVsndOffset;

    public ref bool EnableVsnd
    {
        get
        {
            _EnableVsndOffset = _EnableVsndOffset ?? Schema.GetOffset(0xB3DE3CEEE95E449B);
            return ref _Handle.AsRef<bool>(_EnableVsndOffset!.Value);
        }
    }
    private static nint? _VsndOffset;
    private CSoundContainerReferenceImpl? _VsndInstance;

    public CSoundContainerReference Vsnd
    {
        get
        {
            _VsndOffset = _VsndOffset ?? Schema.GetOffset(0xB3DE3CEE865F386C);
            var instance = _VsndInstance ??= new CSoundContainerReferenceImpl(0);
            instance.DangerousSetHandle(_Handle + _VsndOffset!.Value);
            return instance;
        }
    }
    private static nint? _EnableEndcapOffset;

    public ref bool EnableEndcap
    {
        get
        {
            _EnableEndcapOffset = _EnableEndcapOffset ?? Schema.GetOffset(0xB3DE3CEE7399D6F1);
            return ref _Handle.AsRef<bool>(_EnableEndcapOffset!.Value);
        }
    }
    private static nint? _EndcapVsndOffset;
    private CSoundContainerReferenceImpl? _EndcapVsndInstance;

    public CSoundContainerReference EndcapVsnd
    {
        get
        {
            _EndcapVsndOffset = _EndcapVsndOffset ?? Schema.GetOffset(0xB3DE3CEEAD14708F);
            var instance = _EndcapVsndInstance ??= new CSoundContainerReferenceImpl(0);
            instance.DangerousSetHandle(_Handle + _EndcapVsndOffset!.Value);
            return instance;
        }
    }
    private static nint? _EnableLoopcapOffset;

    public ref bool EnableLoopcap
    {
        get
        {
            _EnableLoopcapOffset = _EnableLoopcapOffset ?? Schema.GetOffset(0xB3DE3CEEE522C044);
            return ref _Handle.AsRef<bool>(_EnableLoopcapOffset!.Value);
        }
    }
    private static nint? _LoopcapVsndOffset;
    private CSoundContainerReferenceImpl? _LoopcapVsndInstance;

    public CSoundContainerReference LoopcapVsnd
    {
        get
        {
            _LoopcapVsndOffset = _LoopcapVsndOffset ?? Schema.GetOffset(0xB3DE3CEE99377240);
            var instance = _LoopcapVsndInstance ??= new CSoundContainerReferenceImpl(0);
            instance.DangerousSetHandle(_Handle + _LoopcapVsndOffset!.Value);
            return instance;
        }
    }
    private static nint? _GroupOffset;

    public ref int Group
    {
        get
        {
            _GroupOffset = _GroupOffset ?? Schema.GetOffset(0xB3DE3CEE9FC645AC);
            return ref _Handle.AsRef<int>(_GroupOffset!.Value);
        }
    }
    private static nint? _VolumeOffset;

    public ref float Volume
    {
        get
        {
            _VolumeOffset = _VolumeOffset ?? Schema.GetOffset(0xB3DE3CEEE3962F2F);
            return ref _Handle.AsRef<float>(_VolumeOffset!.Value);
        }
    }
    private static nint? _FadeOutOffset;

    public ref float FadeOut
    {
        get
        {
            _FadeOutOffset = _FadeOutOffset ?? Schema.GetOffset(0xB3DE3CEE68E7FFE5);
            return ref _Handle.AsRef<float>(_FadeOutOffset!.Value);
        }
    }
    private static nint? _ModeOffset;

    public ref EVsndPlaybackMode Mode
    {
        get
        {
            _ModeOffset = _ModeOffset ?? Schema.GetOffset(0xB3DE3CEE90FD5BB2);
            return ref _Handle.AsRef<EVsndPlaybackMode>(_ModeOffset!.Value);
        }
    }

}