// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class EventServerBeginAsyncPostTickWork_tImpl : SchemaClass, EventServerBeginAsyncPostTickWork_t
{
    public EventServerBeginAsyncPostTickWork_tImpl(nint handle) : base(handle) { }

    private static nint? _IsOncePerFrameAsyncWorkPhaseOffset;

    public ref bool IsOncePerFrameAsyncWorkPhase {
        get {
            _IsOncePerFrameAsyncWorkPhaseOffset = _IsOncePerFrameAsyncWorkPhaseOffset ?? Schema.GetOffset(0x2113CA2A1908E5C4);
            return ref _Handle.AsRef<bool>(_IsOncePerFrameAsyncWorkPhaseOffset!.Value);
        }
    }


}