// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeNodeStrayBox_tImpl : SchemaClass, FeNodeStrayBox_t
{
    public FeNodeStrayBox_tImpl(nint handle) : base(handle) { }

    private static nint? _MinOffset;

    public ref Vector Min {
        get {
            _MinOffset = _MinOffset ?? Schema.GetOffset(0x6809134DFBEAA903);
            return ref _Handle.AsRef<Vector>(_MinOffset!.Value);
        }
    }
    private static nint? _FlagsOffset;

    public ref uint Flags {
        get {
            _FlagsOffset = _FlagsOffset ?? Schema.GetOffset(0x6809134DB8D52E48);
            return ref _Handle.AsRef<uint>(_FlagsOffset!.Value);
        }
    }
    private static nint? _MaxOffset;

    public ref Vector Max {
        get {
            _MaxOffset = _MaxOffset ?? Schema.GetOffset(0x6809134DF1FE20FD);
            return ref _Handle.AsRef<Vector>(_MaxOffset!.Value);
        }
    }
    public ISchemaFixedArray<ushort> Node {
        get => new SchemaFixedArray<ushort>(_Handle, 0x6809134DCD6694B9, 2, 2, 2);
    }


}