// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FloatInputMaterialVariable_tImpl : SchemaClass, FloatInputMaterialVariable_t
{
    public FloatInputMaterialVariable_tImpl(nint handle) : base(handle) { }

    private static nint? _StrVariableOffset;

    public string StrVariable
    {
        get
        {
            _StrVariableOffset = _StrVariableOffset ?? Schema.GetOffset(0xEFEA50FDA52C3390);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrVariableOffset!.Value));
        }
        set
        {
            _StrVariableOffset = _StrVariableOffset ?? Schema.GetOffset(0xEFEA50FDA52C3390);
            Schema.SetCUtlString(_Handle, _StrVariableOffset!.Value, value);
        }
    }
    private static nint? _InputOffset;
    private CParticleCollectionFloatInputImpl? _InputInstance;

    public CParticleCollectionFloatInput Input
    {
        get
        {
            _InputOffset = _InputOffset ?? Schema.GetOffset(0xEFEA50FD1D4B7FFD);
            var instance = _InputInstance ??= new CParticleCollectionFloatInputImpl(0);
            instance.DangerousSetHandle(_Handle + _InputOffset!.Value);
            return instance;
        }
    }

}