// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ImportExportOptionsEditableData_tImpl : SchemaClass, ImportExportOptionsEditableData_t
{
    public ImportExportOptionsEditableData_tImpl(nint handle) : base(handle) { }

    private static nint? _ExportPropsOffset;

    public ref bool ExportProps
    {
        get
        {
            _ExportPropsOffset = _ExportPropsOffset ?? Schema.GetOffset(0xAF39C5039EE3AEB7);
            return ref _Handle.AsRef<bool>(_ExportPropsOffset!.Value);
        }
    }
    private static nint? _ExportHiddenOffset;

    public ref bool ExportHidden
    {
        get
        {
            _ExportHiddenOffset = _ExportHiddenOffset ?? Schema.GetOffset(0xAF39C503216EC573);
            return ref _Handle.AsRef<bool>(_ExportHiddenOffset!.Value);
        }
    }
    private static nint? _ExportBonesOffset;

    public ref bool ExportBones
    {
        get
        {
            _ExportBonesOffset = _ExportBonesOffset ?? Schema.GetOffset(0xAF39C5034AA831B6);
            return ref _Handle.AsRef<bool>(_ExportBonesOffset!.Value);
        }
    }
    private static nint? _ExportSkinningOffset;

    public ref bool ExportSkinning
    {
        get
        {
            _ExportSkinningOffset = _ExportSkinningOffset ?? Schema.GetOffset(0xAF39C50344525E04);
            return ref _Handle.AsRef<bool>(_ExportSkinningOffset!.Value);
        }
    }
    private static nint? _ExportFbxEmbedTexturesOffset;

    public ref bool ExportFbxEmbedTextures
    {
        get
        {
            _ExportFbxEmbedTexturesOffset = _ExportFbxEmbedTexturesOffset ?? Schema.GetOffset(0xAF39C503B57F044E);
            return ref _Handle.AsRef<bool>(_ExportFbxEmbedTexturesOffset!.Value);
        }
    }
    private static nint? _ExportFbxUnitOffset;

    public ref ImportExportOptionsEditableData_t__ExportFbxUnit_t ExportFbxUnit
    {
        get
        {
            _ExportFbxUnitOffset = _ExportFbxUnitOffset ?? Schema.GetOffset(0xAF39C5031E002FFB);
            return ref _Handle.AsRef<ImportExportOptionsEditableData_t__ExportFbxUnit_t>(_ExportFbxUnitOffset!.Value);
        }
    }
    private static nint? _ExportDefaultFormatOffset;

    public ref ImportExportOptionsEditableData_t__ExportDefaultFormat_t ExportDefaultFormat
    {
        get
        {
            _ExportDefaultFormatOffset = _ExportDefaultFormatOffset ?? Schema.GetOffset(0xAF39C503141E75F3);
            return ref _Handle.AsRef<ImportExportOptionsEditableData_t__ExportDefaultFormat_t>(_ExportDefaultFormatOffset!.Value);
        }
    }
    private static nint? _ExportEncodingOffset;

    public ref ImportExportOptionsEditableData_t__ExportEncoding_t ExportEncoding
    {
        get
        {
            _ExportEncodingOffset = _ExportEncodingOffset ?? Schema.GetOffset(0xAF39C5039DB400F6);
            return ref _Handle.AsRef<ImportExportOptionsEditableData_t__ExportEncoding_t>(_ExportEncodingOffset!.Value);
        }
    }

}