// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ModelAnimGraph2Ref_tImpl : SchemaClass, ModelAnimGraph2Ref_t
{
    public ModelAnimGraph2Ref_tImpl(nint handle) : base(handle) { }

    private static nint? _IdentifierOffset;

    public string Identifier {
        get {
            _IdentifierOffset = _IdentifierOffset ?? Schema.GetOffset(0xB068395EF7D0521);
            return Schema.GetCUtlString(_Handle.Read<nint>(_IdentifierOffset!.Value));
        }
        set {
            _IdentifierOffset = _IdentifierOffset ?? Schema.GetOffset(0xB068395EF7D0521);
            Schema.SetCUtlString(_Handle, _IdentifierOffset!.Value, value);
        }
    } 
    private static nint? _GraphOffset;

    public ref CStrongHandle<InfoForResourceTypeCNmGraphDefinition> Graph {
        get {
            _GraphOffset = _GraphOffset ?? Schema.GetOffset(0xB068395AA5BE1A5);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCNmGraphDefinition>>(_GraphOffset!.Value);
        }
    }


}