// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class OutflowWithRequirements_tImpl : SchemaClass, OutflowWithRequirements_t
{
    public OutflowWithRequirements_tImpl(nint handle) : base(handle) { }

    private static nint? _ConnectionOffset;
    private CPulse_OutflowConnectionImpl? _ConnectionInstance;

    public CPulse_OutflowConnection Connection
    {
        get
        {
            _ConnectionOffset = _ConnectionOffset ?? Schema.GetOffset(0x5BFC4DD4D4CD5F59);
            var instance = _ConnectionInstance ??= new CPulse_OutflowConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _ConnectionOffset!.Value);
            return instance;
        }
    }
    private static nint? _DestinationFlowNodeIDOffset;
    private PulseDocNodeID_tImpl? _DestinationFlowNodeIDInstance;

    public PulseDocNodeID_t DestinationFlowNodeID
    {
        get
        {
            _DestinationFlowNodeIDOffset = _DestinationFlowNodeIDOffset ?? Schema.GetOffset(0x5BFC4DD4C986A186);
            var instance = _DestinationFlowNodeIDInstance ??= new PulseDocNodeID_tImpl(0);
            instance.DangerousSetHandle(_Handle + _DestinationFlowNodeIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _RequirementNodeIDsOffset;

    public ref CUtlVector<PulseDocNodeID_t> RequirementNodeIDs
    {
        get
        {
            _RequirementNodeIDsOffset = _RequirementNodeIDsOffset ?? Schema.GetOffset(0x5BFC4DD47DAC9EFE);
            return ref _Handle.AsRef<CUtlVector<PulseDocNodeID_t>>(_RequirementNodeIDsOffset!.Value);
        }
    }
    private static nint? _CursorStateBlockIndexOffset;

    public ref CUtlVector<int> CursorStateBlockIndex
    {
        get
        {
            _CursorStateBlockIndexOffset = _CursorStateBlockIndexOffset ?? Schema.GetOffset(0x5BFC4DD46CECC07B);
            return ref _Handle.AsRef<CUtlVector<int>>(_CursorStateBlockIndexOffset!.Value);
        }
    }

}