// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PulseGraphExecutionHistoryEntry_tImpl : SchemaClass, PulseGraphExecutionHistoryEntry_t
{
    public PulseGraphExecutionHistoryEntry_tImpl(nint handle) : base(handle) { }

    private static nint? _CursorIDOffset;
    private PulseCursorID_tImpl? _CursorIDInstance;

    public PulseCursorID_t CursorID
    {
        get
        {
            _CursorIDOffset = _CursorIDOffset ?? Schema.GetOffset(0x9346B0AB0B44CBF6);
            var instance = _CursorIDInstance ??= new PulseCursorID_tImpl(0);
            instance.DangerousSetHandle(_Handle + _CursorIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _EditorIDOffset;
    private PulseDocNodeID_tImpl? _EditorIDInstance;

    public PulseDocNodeID_t EditorID
    {
        get
        {
            _EditorIDOffset = _EditorIDOffset ?? Schema.GetOffset(0x9346B0AB74188E69);
            var instance = _EditorIDInstance ??= new PulseDocNodeID_tImpl(0);
            instance.DangerousSetHandle(_Handle + _EditorIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _ExecTimeOffset;

    public ref float ExecTime
    {
        get
        {
            _ExecTimeOffset = _ExecTimeOffset ?? Schema.GetOffset(0x9346B0ABFAE08483);
            return ref _Handle.AsRef<float>(_ExecTimeOffset!.Value);
        }
    }
    private static nint? _FlagsOffset;

    public ref uint Flags
    {
        get
        {
            _FlagsOffset = _FlagsOffset ?? Schema.GetOffset(0x9346B0AB5E9538F5);
            return ref _Handle.AsRef<uint>(_FlagsOffset!.Value);
        }
    }
    private static nint? _TagNameOffset;
    private SchemaUntypedField? _TagNameInstance;

    public SchemaUntypedField TagName
    {
        get
        {
            _TagNameOffset = _TagNameOffset ?? Schema.GetOffset(0x9346B0ABBD7B50F8);
            var instance = _TagNameInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _TagNameOffset!.Value);
            return instance;
        }
    }

}