// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PulseNodeDynamicOutflows_t__DynamicOutflow_tImpl : SchemaClass, PulseNodeDynamicOutflows_t__DynamicOutflow_t
{
    public PulseNodeDynamicOutflows_t__DynamicOutflow_tImpl(nint handle) : base(handle) { }

    private static nint? _OutflowIDOffset;

    public ref CGlobalSymbol OutflowID
    {
        get
        {
            _OutflowIDOffset = _OutflowIDOffset ?? Schema.GetOffset(0x4ACC8D59E16DD56);
            return ref _Handle.AsRef<CGlobalSymbol>(_OutflowIDOffset!.Value);
        }
    }
    private static nint? _ConnectionOffset;
    private CPulse_OutflowConnectionImpl? _ConnectionInstance;

    public CPulse_OutflowConnection Connection
    {
        get
        {
            _ConnectionOffset = _ConnectionOffset ?? Schema.GetOffset(0x4ACC8D5D4CD5F59);
            var instance = _ConnectionInstance ??= new CPulse_OutflowConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _ConnectionOffset!.Value);
            return instance;
        }
    }

}