// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class RnCompound_tImpl : SchemaClass, RnCompound_t
{
    public RnCompound_tImpl(nint handle) : base(handle) { }

    private static nint? _TreeOffset;
    private RnCompoundTree_tImpl? _TreeInstance;

    public RnCompoundTree_t Tree
    {
        get
        {
            _TreeOffset = _TreeOffset ?? Schema.GetOffset(0xAFF8C613AB3A1955);
            var instance = _TreeInstance ??= new RnCompoundTree_tImpl(0);
            instance.DangerousSetHandle(_Handle + _TreeOffset!.Value);
            return instance;
        }
    }
    private static nint? _HullBaseIndexOffset;

    public ref int HullBaseIndex
    {
        get
        {
            _HullBaseIndexOffset = _HullBaseIndexOffset ?? Schema.GetOffset(0xAFF8C61328B4E0FD);
            return ref _Handle.AsRef<int>(_HullBaseIndexOffset!.Value);
        }
    }
    private static nint? _MeshBaseIndexOffset;

    public ref int MeshBaseIndex
    {
        get
        {
            _MeshBaseIndexOffset = _MeshBaseIndexOffset ?? Schema.GetOffset(0xAFF8C61364293A13);
            return ref _Handle.AsRef<int>(_MeshBaseIndexOffset!.Value);
        }
    }
    private static nint? _ShapeCountOffset;

    public ref int ShapeCount
    {
        get
        {
            _ShapeCountOffset = _ShapeCountOffset ?? Schema.GetOffset(0xAFF8C6136BF2B149);
            return ref _Handle.AsRef<int>(_ShapeCountOffset!.Value);
        }
    }
    private static nint? _MeshesOffset;
    private SchemaUntypedField? _MeshesInstance;

    public SchemaUntypedField Meshes
    {
        get
        {
            _MeshesOffset = _MeshesOffset ?? Schema.GetOffset(0xAFF8C613D394E2B8);
            var instance = _MeshesInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _MeshesOffset!.Value);
            return instance;
        }
    }
    private static nint? _HullsOffset;

    public ref CUtlLeanVector<RnHull_t, int> Hulls
    {
        get
        {
            _HullsOffset = _HullsOffset ?? Schema.GetOffset(0xAFF8C6138C3BD39F);
            return ref _Handle.AsRef<CUtlLeanVector<RnHull_t, int>>(_HullsOffset!.Value);
        }
    }
    private static nint? _CapsulesOffset;

    public ref CUtlLeanVector<RnCapsule_t, int> Capsules
    {
        get
        {
            _CapsulesOffset = _CapsulesOffset ?? Schema.GetOffset(0xAFF8C613FC27BB2D);
            return ref _Handle.AsRef<CUtlLeanVector<RnCapsule_t, int>>(_CapsulesOffset!.Value);
        }
    }
    private static nint? _SpheresOffset;

    public ref CUtlLeanVector<RnSphere_t, int> Spheres
    {
        get
        {
            _SpheresOffset = _SpheresOffset ?? Schema.GetOffset(0xAFF8C613E56F78F1);
            return ref _Handle.AsRef<CUtlLeanVector<RnSphere_t, int>>(_SpheresOffset!.Value);
        }
    }
    private static nint? _CompoundMaterialIndicesOffset;

    public ref CUtlLeanVector<byte, int> CompoundMaterialIndices
    {
        get
        {
            _CompoundMaterialIndicesOffset = _CompoundMaterialIndicesOffset ?? Schema.GetOffset(0xAFF8C61356D76BA2);
            return ref _Handle.AsRef<CUtlLeanVector<byte, int>>(_CompoundMaterialIndicesOffset!.Value);
        }
    }
    private static nint? _BoundsOffset;
    private AABB_tImpl? _BoundsInstance;

    public AABB_t Bounds
    {
        get
        {
            _BoundsOffset = _BoundsOffset ?? Schema.GetOffset(0xAFF8C613ABF76288);
            var instance = _BoundsInstance ??= new AABB_tImpl(0);
            instance.DangerousSetHandle(_Handle + _BoundsOffset!.Value);
            return instance;
        }
    }
    private static nint? _OrthographicAreasOffset;

    public ref Vector OrthographicAreas
    {
        get
        {
            _OrthographicAreasOffset = _OrthographicAreasOffset ?? Schema.GetOffset(0xAFF8C613B74855D3);
            return ref _Handle.AsRef<Vector>(_OrthographicAreasOffset!.Value);
        }
    }
    private static nint? _SurfaceAreaOffset;

    public ref float SurfaceArea
    {
        get
        {
            _SurfaceAreaOffset = _SurfaceAreaOffset ?? Schema.GetOffset(0xAFF8C613E4AE7C2F);
            return ref _Handle.AsRef<float>(_SurfaceAreaOffset!.Value);
        }
    }
    private static nint? _VolumeOffset;

    public ref float Volume
    {
        get
        {
            _VolumeOffset = _VolumeOffset ?? Schema.GetOffset(0xAFF8C6137647E0C9);
            return ref _Handle.AsRef<float>(_VolumeOffset!.Value);
        }
    }

}