// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class RnSoftbodyCapsule_tImpl : SchemaClass, RnSoftbodyCapsule_t
{
    public RnSoftbodyCapsule_tImpl(nint handle) : base(handle) { }

    private static nint? _CenterOffset;
    private SchemaFixedArray<Vector>? _CenterInstance;

    public ISchemaFixedArray<Vector> Center
    {
        get
        {
            _CenterOffset = _CenterOffset ?? Schema.GetOffset(0x896978BC82A5908);
            var instance = _CenterInstance ??= new SchemaFixedArray<Vector>(0, 0x896978BC82A5908, 2, 12, 4);
            instance.DangerousSetHandle(_Handle + _CenterOffset!.Value);
            return instance;
        }
    }
    private static nint? _RadiusOffset;

    public ref float Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0x896978B5ACFC08D);
            return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
        }
    }
    private static nint? _ParticleOffset;
    private SchemaFixedArray<ushort>? _ParticleInstance;

    public ISchemaFixedArray<ushort> Particle
    {
        get
        {
            _ParticleOffset = _ParticleOffset ?? Schema.GetOffset(0x896978B863A8E83);
            var instance = _ParticleInstance ??= new SchemaFixedArray<ushort>(0, 0x896978B863A8E83, 2, 2, 2);
            instance.DangerousSetHandle(_Handle + _ParticleOffset!.Value);
            return instance;
        }
    }

}