// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class TargetSelectorInstanceData_tImpl : SchemaClass, TargetSelectorInstanceData_t
{
    public TargetSelectorInstanceData_tImpl(nint handle) : base(handle) { }

    private static nint? _CurrentIndexOffset;
    private SchemaUntypedField? _CurrentIndexInstance;

    public SchemaUntypedField CurrentIndex
    {
        get
        {
            _CurrentIndexOffset = _CurrentIndexOffset ?? Schema.GetOffset(0xE96408C1883AA9CE);
            var instance = _CurrentIndexInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _CurrentIndexOffset!.Value);
            return instance;
        }
    }
    private static nint? _MSRootMotionAnlyzerTargetOffset;
    private SchemaUntypedField? _MSRootMotionAnlyzerTargetInstance;

    public SchemaUntypedField MSRootMotionAnlyzerTarget
    {
        get
        {
            _MSRootMotionAnlyzerTargetOffset = _MSRootMotionAnlyzerTargetOffset ?? Schema.GetOffset(0xE96408C1FB915109);
            var instance = _MSRootMotionAnlyzerTargetInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _MSRootMotionAnlyzerTargetOffset!.Value);
            return instance;
        }
    }

}