name: Synchronize master to beta

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Synchronize
      run: |
        git fetch origin master:refs/remotes/origin/master beta:refs/remotes/origin/beta
        git checkout -B beta origin/beta
        git reset --hard origin/master
        git push --force-with-lease=refs/heads/beta origin beta
